"""Mémo du parcours Linux : une fiche par commande (ou notion du shell), débloquée par un exercice."""


def C(id, name, category, desc, syntax, examples, unlock):
    return {"id": id, "name": name, "category": category, "desc": desc, "syntax": syntax,
            "examples": examples, "unlock": unlock}


NAV, FILES, TEXT, SHELL, USERS, PROC, SYS, NET, ARCH, SCRIPT, SEC = (
    "Se repérer", "Fichiers et dossiers", "Texte et recherche", "Syntaxe du shell", "Utilisateurs et droits",
    "Processus", "Système et paquets", "Réseau et SSH", "Archives", "Scripts et automatisation", "Sécurité et dépannage",
)

CARDS = [
    # ── Se repérer ─────────────────────────────────────────────────────
    C("pwd", "pwd", NAV, "Affiche le dossier dans lequel on se trouve (chemin absolu).",
      ["pwd"], [("pwd", "→ /home/etudiant")], ["1.1"]),
    C("cd", "cd", NAV, "Change de dossier courant.",
      ["cd <dossier>", "cd ..", "cd ~", "cd -"],
      [("cd /etc", "chemin absolu"), ("cd ..", "remonte d'un niveau"), ("cd", "retour au dossier personnel"),
       ("cd -", "revient au dossier précédent")], ["1.1"]),
    C("ls", "ls", NAV, "Liste le contenu d'un dossier.",
      ["ls [options] [chemin]"],
      [("ls -l", "format détaillé : droits, propriétaire, taille, date"), ("ls -a", "affiche aussi les fichiers cachés (.nom)"),
       ("ls -la /etc", "les deux, sur un autre dossier"), ("ls -lS", "trié par taille")], ["1.1"]),
    C("cat", "cat", NAV, "Affiche le contenu d'un ou plusieurs fichiers.",
      ["cat <fichier>...", "cat -A <fichier>"],
      [("cat notes.txt", ""), ("cat -A deploy.sh", "révèle les caractères invisibles (^M des fins de ligne Windows)")], ["1.1"]),
    C("echo", "echo", NAV, "Affiche un texte ; combiné à > ou >>, l'écrit dans un fichier.",
      ['echo "texte"'], [('echo "Bonjour" > f.txt', "crée ou remplace f.txt"), ("echo $HOME", "affiche une variable")], ["1.1"]),
    C("man", "man", NAV, "Ouvre le manuel d'une commande. RTFM !",
      ["man <commande>", "<commande> --help"],
      [("man ls", "/mot pour chercher, n pour le suivant, q pour quitter"), ("mkdir --help", "aide courte")], ["2.2"]),
    C("chemins", ". .. ~ et chemins", NAV, "Chemin absolu (commence par /) ou relatif (part du dossier courant).",
      ["/chemin/absolu", "chemin/relatif", ". (ici)   .. (parent)   ~ (dossier personnel)"],
      [("cat ../../tarifs.txt", "deux niveaux au-dessus"), ("cp ~/notes.txt .", "copie dans le dossier courant")], ["2.3"]),

    # ── Fichiers et dossiers ──────────────────────────────────────────
    C("mkdir", "mkdir", FILES, "Crée un ou plusieurs dossiers.",
      ["mkdir <dossier>...", "mkdir -p <a/b/c>"],
      [("mkdir documents projets", "deux dossiers"), ("mkdir -p projets/boutique/src", "crée aussi les parents manquants")], ["1.3"]),
    C("touch", "touch", FILES, "Crée un fichier vide (ou met à jour sa date de modification).",
      ["touch <fichier>..."], [("touch journal.txt", "")], ["1.4"]),
    C("cp", "cp", FILES, "Copie des fichiers ou des dossiers.",
      ["cp <source> <destination>", "cp -r <dossier> <destination>"],
      [("cp notes.txt sauvegarde/", "garde le même nom"), ("cp notes.txt copie.txt", "copie sous un autre nom"),
       ("cp -r site/ site-bak/", "copie récursive d'un dossier")], ["3.4"]),
    C("mv", "mv", FILES, "Déplace ou renomme (il n'y a pas de commande « rename »).",
      ["mv <source> <destination>"], [("mv brouillon.txt final.txt", "renomme"), ("mv *.log archives/", "déplace")], ["3.4"]),
    C("rm", "rm", FILES, "Supprime des fichiers ou des dossiers. Pas de corbeille !",
      ["rm <fichier>...", "rm -r <dossier>", "rm -i <fichier>"],
      [("rm *.tmp", "testez d'abord le motif avec ls *.tmp"), ("rm -r vieux-projets", "supprime un dossier et son contenu")], ["3.5"]),
    C("jokers", "Jokers * ?", FILES, "Le shell remplace les motifs par la liste des fichiers correspondants.",
      ["*  (n'importe quelle suite)", "?  (un caractère)", "[abc]  (un caractère parmi)"],
      [("ls *.txt", ""), ("rm brouillon?.md", ""), ("cp rapport-[0-9].pdf archives/", "")], ["3.5"]),
    C("ln", "ln", FILES, "Crée un lien dur (même inode) ou symbolique (raccourci vers un chemin).",
      ["ln <cible> <lien>", "ln -s <cible> <lien>", "ln -sfn <nouvelle-cible> <lien>"],
      [("ln tarifs.csv tarifs-courant.csv", "lien dur"), ("ln -s /etc ~/conf-systeme", "lien symbolique"),
       ("ln -sfn annuaire.txt compta", "remplace la cible d'un lien existant")], ["4.1"]),
    C("stat", "stat", FILES, "Informations détaillées sur un fichier : inode, droits, nombre de liens, dates.",
      ["stat <fichier>", "stat -c <format> <fichier>"],
      [("stat -c %h base.db", "nombre de liens durs"), ("stat -c '%a %U:%G' secret.txt", "droits octaux et propriétaire")], ["4.2"]),
    C("readlink", "readlink", FILES, "Affiche la cible d'un lien symbolique.",
      ["readlink <lien>", "readlink -f <lien>"], [("readlink -f ~/conf-systeme", "chemin final, liens résolus")], ["4.5"]),

    # ── Texte et recherche ─────────────────────────────────────────────
    C("find", "find", TEXT, "Recherche des fichiers selon des critères (nom, type, taille, droits, date…).",
      ["find <où> <critères> [action]"],
      [('find /etc -name "*.conf"', "par nom (-iname : sans la casse)"), ("find /var -type d", "dossiers seulement"),
       ("find / -size +5M", "plus de 5 Mo"), ("find ~/liens -xtype l", "liens symboliques cassés"),
       ("find / -perm -4000 -type f 2>/dev/null", "fichiers SUID")], ["5.1"]),
    C("grep", "grep", TEXT, "Cherche les lignes qui contiennent un motif.",
      ["grep [options] <motif> <fichier>..."],
      [('grep -i erreur rapport.txt', "sans tenir compte de la casse"), ('grep -c ERROR app.log', "compte les lignes"),
       ('grep -rl "TOKEN-" /srv', "récursif, noms de fichiers seulement"), ("grep -v '^#' f", "inverse : lignes sans #"),
       ("grep -n motif f", "avec les numéros de ligne")], ["5.2"]),
    C("wc", "wc", TEXT, "Compte les lignes, mots ou octets.",
      ["wc -l | -w | -c <fichier>"], [("wc -l /etc/passwd", "nombre de lignes"), ("ls /etc | wc -l", "nombre d'entrées")], ["5.3"]),
    C("sort", "sort", TEXT, "Trie les lignes.",
      ["sort [options] [fichier]"],
      [("sort -u noms.txt", "trie et supprime les doublons"), ("sort -n", "tri numérique"), ("sort -rn", "numérique décroissant")], ["6.5"]),
    C("cut", "cut", TEXT, "Extrait des champs ou des colonnes de chaque ligne.",
      ["cut -d <séparateur> -f <champs>"], [("cut -d: -f1 /etc/passwd", "1er champ séparé par :"), ("cut -d: -f1,7 /etc/passwd", "champs 1 et 7")], ["6.5"]),
    C("tee", "tee", TEXT, "Écrit ce qu'il reçoit dans un fichier ET l'affiche.",
      ["commande | tee <fichier>", "commande | tee -a <fichier>"], [("ls /usr/bin | tee programmes.txt", ""), ("echo ligne | sudo tee -a /etc/hosts", "écrire dans un fichier protégé")], ["6.4"]),
    C("nano", "nano", TEXT, "Éditeur de texte simple dans le terminal.",
      ["nano <fichier>"], [("Ctrl+O", "enregistrer"), ("Ctrl+X", "quitter"), ("Ctrl+W", "rechercher"), ("Ctrl+K", "couper la ligne")], ["7.1"]),
    C("vim", "vim", TEXT, "Éditeur modal puissant : mode normal, insertion (i), commande (:).",
      ["vim <fichier>"],
      [("i / Echap", "passer en insertion / revenir en mode normal"), ("dd", "supprimer la ligne"), ("G puis o", "nouvelle ligne à la fin"),
       (":wq  /  :q!", "enregistrer et quitter / quitter sans enregistrer")], ["7.2"]),
    C("sed", "sed", TEXT, "Éditeur de flux : remplacements et suppressions ligne à ligne.",
      ["sed 's/ancien/nouveau/[g]' <fichier>", "sed -i ... (modifie le fichier)"],
      [("sed -i 's/debug=false/debug=true/' config.txt", ""), ("sed 's/[0-9]/X/g' f", "tous les chiffres"),
       ("sed '/INTRUS/d' f", "supprime les lignes qui contiennent INTRUS"), ("sed -i 's/\\r$//' f", "fins de ligne Windows → Unix")], ["7.3"]),
    C("regex", "Expressions régulières", TEXT, "Décrire précisément un motif de texte (avec grep -E, sed…).",
      ["^ début   $ fin   . un caractère   * + ? répétitions", "[a-z] classe   (a|b) alternative   {2,} au moins 2   \\. un vrai point"],
      [("grep '^[rs]' /etc/passwd", "lignes commençant par r ou s"), ("grep -oE '[a-z0-9._-]+@[a-z0-9.-]+\\.[a-z]{2,}' f", "extrait des e-mails"),
       ("grep -vE '^\\s*(#|$)' f", "ni commentaire ni ligne blanche")], ["8.2"]),
    C("head-tail", "head / tail", TEXT, "Affiche le début ou la fin d'un fichier ; tail -f suit un journal en direct.",
      ["head -n <N>", "tail -n <N>", "tail -f <fichier>"],
      [("head -3", "3 premières lignes"), ("tail -n 20 /var/log/syslog", ""), ("tail -f /var/log/syslog", "Ctrl+C pour arrêter")], ["9.2"]),
    C("uniq", "uniq", TEXT, "Regroupe les lignes identiques consécutives (triez d'abord !).",
      ["sort | uniq [-c]"], [("cut -d: -f7 /etc/passwd | sort | uniq -c | sort -rn", "compter les occurrences, les plus fréquentes d'abord")], ["9.1"]),
    C("awk", "awk", TEXT, "Découpe chaque ligne en champs ($1, $2…) et agit selon des conditions.",
      ["awk [-F séparateur] 'condition { action }' <fichier>"],
      [("awk '{print $1}' access.log", "1re colonne"), ("awk '$9 == 404' access.log", "filtre sur un champ précis"),
       ("awk -F: '$3 >= 1000 {print $1, $3}' /etc/passwd", "séparateur :")], ["9.3"]),
    C("tr", "tr", TEXT, "Remplace ou supprime des caractères (lit l'entrée standard).",
      ["tr <ensemble1> <ensemble2>", "tr -d <ensemble>"], [("tr 'a-z' 'A-Z' < f.txt", "majuscules"), ("tr -d '\\r' < win.txt > unix.txt", "")], ["9.5"]),

    # ── Syntaxe du shell ───────────────────────────────────────────────
    C("redirection", "> et >>", SHELL, "Redirige la sortie d'une commande vers un fichier.",
      ["commande > fichier   (remplace)", "commande >> fichier  (ajoute à la fin)"],
      [('echo "Titre" > notes.txt', ""), ('echo "Suite" >> notes.txt', "")], ["3.3"]),
    C("pipe", "Le pipe |", SHELL, "Branche la sortie d'une commande sur l'entrée de la suivante.",
      ["commande1 | commande2 | commande3"], [("ls /etc | wc -l", ""), ("cat access.log | grep 404 | head", "")], ["6.1"]),
    C("stderr", "2> et /dev/null", SHELL, "Les erreurs passent par un flux séparé (stderr, n°2).",
      ["commande 2> erreurs.txt", "commande 2>/dev/null", "commande > tout.txt 2>&1"],
      [("find /root > ok.txt 2> erreurs.txt", "sorties séparées"), ("find /etc -type f 2>/dev/null", "jeter les erreurs")], ["6.2"]),
    C("variables", "Variables et export", SHELL, "Une variable exportée est transmise aux programmes lancés depuis le shell.",
      ["NOM=valeur", "export NOM=valeur", "echo $NOM", "env"],
      [("export PROJET=linux-lab", ""), ("echo 'export PROJET=linux-lab' >> ~/.bashrc", "permanent"), ("source ~/.bashrc", "recharger")], ["15.1"]),
    C("path", "PATH", SHELL, "Liste des dossiers où le shell cherche les commandes.",
      ['export PATH="$PATH:$HOME/outils"', "command -v <commande>"],
      [("echo $PATH", ""), ("command -v bonjour", "où la commande est-elle trouvée ?")], ["15.2"]),
    C("alias", "alias", SHELL, "Raccourci pour une commande.",
      ["alias nom='commande'", "unalias nom"], [("alias ll='ls -la'", "à mettre dans ~/.bashrc pour le garder")], ["15.3"]),

    # ── Utilisateurs et droits ─────────────────────────────────────────
    C("sudo", "sudo", USERS, "Exécute une commande avec les droits d'administrateur (ou d'un autre utilisateur).",
      ["sudo <commande>", "sudo -u <utilisateur> <commande>"],
      [("sudo apt update", ""), ("sudo -u bob touch /home/partage/test", "tester les droits de bob")], ["10.1"]),
    C("useradd", "useradd / userdel", USERS, "Crée ou supprime un compte utilisateur.",
      ["useradd -m -s /bin/bash <nom>", "userdel -r <nom>"],
      [("sudo useradd -m -s /bin/bash alice", "-m crée le dossier personnel"), ("id alice", "vérifier : UID et groupes")], ["10.1"]),
    C("groupes", "groupadd / usermod -aG", USERS, "Crée un groupe et y ajoute des utilisateurs.",
      ["groupadd <groupe>", "usermod -aG <groupe> <utilisateur>"],
      [("sudo groupadd equipe", ""), ("sudo usermod -aG equipe alice", "-a : sans retirer ses autres groupes !"), ("id -nG alice", "")], ["10.2"]),
    C("chown", "chown / chgrp", USERS, "Change le propriétaire et/ou le groupe d'un fichier.",
      ["chown <user>[:<groupe>] <fichier>", "chgrp <groupe> <fichier>"],
      [("sudo chgrp equipe /home/partage", ""), ("sudo chown alice:equipe secret.txt", ""), ("sudo chown -R ops:ops /home/ops/.ssh", "récursif")], ["10.3"]),
    C("chmod", "chmod", USERS, "Modifie les droits : u (propriétaire), g (groupe), o (autres) ; r=4 w=2 x=1.",
      ["chmod <octal> <fichier>", "chmod u+x,g-w,o-rwx <fichier>"],
      [("chmod 640 secret.txt", "rw- r-- ---"), ("chmod u+x deploy.sh", "exécutable par le propriétaire"),
       ("chmod g+s /home/partage", "setgid : les fichiers héritent du groupe"), ("chmod u-s fichier", "retire le bit SUID")], ["10.4"]),
    C("su", "su", USERS, "Ouvre un shell sous l'identité d'un autre utilisateur.",
      ["su - <utilisateur>"], [("sudo su - papa", "devenir papa pour tester ses droits"), ("exit", "revenir")], ["12.1"]),

    # ── Processus ──────────────────────────────────────────────────────
    C("ps", "ps / pgrep / top", PROC, "Liste les processus en cours.",
      ["ps aux", "ps -o pid,user,ni,cmd -C <nom>", "pgrep -a <nom>", "top"],
      [("ps aux | grep rogue", ""), ("ps aux --sort=-%mem | head", "les plus gourmands en mémoire"),
       ("pgrep -x lab-service", "PID d'un processus"), ("top", "M : trier par mémoire, P : par CPU, q : quitter")], ["11.2"]),
    C("kill", "kill", PROC, "Envoie un signal à un processus.",
      ["kill <PID>", "kill -9 <PID>", "kill -HUP <PID>"],
      [("sudo kill 1234", "arrêt propre (TERM)"), ("kill -9 1234", "arrêt forcé, en dernier recours"),
       ("sudo kill -HUP $(pgrep -x lab-service)", "demande de recharger la configuration")], ["11.3"]),
    C("jobs", "& nice jobs", PROC, "Lancer en arrière-plan, avec une priorité plus basse.",
      ["commande &", "nice -n <10> commande", "jobs  fg  bg", "renice"],
      [("nice -n 10 sleep 1000 &", ""), ("jobs", "tâches du terminal"), ("fg %1", "ramener au premier plan")], ["11.4"]),

    # ── Système et paquets ─────────────────────────────────────────────
    C("apt", "apt", SYS, "Gestionnaire de paquets Debian / Ubuntu.",
      ["sudo apt update", "sudo apt install <paquet>", "sudo apt remove <paquet>", "apt search <mot>"],
      [("sudo apt update && sudo apt install tree", "toujours mettre à jour la liste d'abord")], ["13.1"]),
    C("dpkg", "dpkg", SYS, "Base des paquets installés.",
      ["dpkg -l", "dpkg -L <paquet>", "dpkg -S <fichier>"], [("dpkg -S /usr/bin/pgrep", "quel paquet a installé ce fichier ?")], ["13.2"]),
    C("wget", "wget / curl", SYS, "Télécharge depuis le web.",
      ["wget -O <fichier> <url>", "curl -o <fichier> <url>"], [("wget -O page.html https://example.com", ""), ("curl -s https://example.com | head", "")], ["13.3"]),
    C("df", "df", SYS, "Espace disque par système de fichiers.",
      ["df -h", "df -T <chemin>"], [("df -h", "tailles lisibles"), ("df -T /", "type du système de fichiers")], ["14.1"]),
    C("du", "du", SYS, "Espace occupé par des fichiers et dossiers.",
      ["du -sh <dossier>", "du -s <dossier>/* | sort -n"],
      [("du -sh /var/log", ""), ("du -s /srv/data/* | sort -n", "qui prend le plus de place ?"), ("du -sm /srv/data", "en Mo")], ["14.2"]),
    C("fstab", "mount et /etc/fstab", SYS, "Monter un système de fichiers, à la main ou au démarrage.",
      ["mount <périphérique> <point>", "umount <point>", "/etc/fstab : périph. point type options dump pass"],
      [("sudo mount /dev/sdb1 /mnt/usb", ""), ("/dev/sdb1  /mnt/usb  ext4  defaults  0  2", "ligne fstab")], ["14.4"]),
    C("free", "free / uptime", SYS, "Mémoire utilisée, et charge du système.",
      ["free -h", "uptime"], [("free -h", ""), ("uptime", "load average sur 1, 5 et 15 min")], ["19.1"]),
    C("logger", "logger / journaux", SYS, "Écrire dans le journal système ; les journaux sont dans /var/log.",
      ["logger <message>", "tail /var/log/syslog"], [('logger "Mon premier log"', ""), ("sudo tail -f /var/log/syslog", "")], ["20.1"]),
    C("logrotate", "logrotate", SYS, "Fait tourner les journaux pour qu'ils ne remplissent pas le disque.",
      ["/etc/logrotate.d/<appli>", "logrotate -d <config>"],
      [("/var/log/app/*.log { daily  rotate 7  compress }", ""), ("sudo logrotate -d /etc/logrotate.d/app-lab", "test à blanc")], ["20.5"]),

    # ── Archives ───────────────────────────────────────────────────────
    C("tar", "tar", ARCH, "Archive un dossier, compressé ou non. c=créer, x=extraire, t=lister, z=gzip, f=fichier.",
      ["tar -czf <archive.tar.gz> <dossier>", "tar -tzf <archive>", "tar -xzf <archive> -C <dest>"],
      [("tar -czf site.tar.gz site/", ""), ("tar -tzf paquet.tar.gz", "voir le contenu"), ("tar -xzf paquet.tar.gz -C /tmp/x", "")], ["16.1"]),
    C("gzip", "gzip / zcat", ARCH, "Compresse un fichier (remplace l'original, sauf avec -k).",
      ["gzip [-k] <fichier>", "gunzip <fichier.gz>", "zcat <fichier.gz>"], [("gzip -k rapport.txt", "garde l'original")], ["16.4"]),
    C("zip", "zip / unzip", ARCH, "Archive compatible Windows.",
      ["zip -r <archive.zip> <dossier>", "unzip -l <archive.zip>", "unzip <archive.zip>"], [("zip -r backup.zip archive-test", "")], ["16.5"]),

    # ── Scripts et automatisation ──────────────────────────────────────
    C("script", "Script bash", SCRIPT, "Un fichier de commandes : shebang en 1re ligne, puis chmod +x.",
      ["#!/bin/bash", "chmod +x script.sh", "./script.sh"],
      [("#!/bin/bash\necho \"Bonjour\"", "contenu minimal"), ("bash -x script.sh", "exécution pas à pas, pour déboguer")], ["17.1"]),
    C("if", "if / test / arguments", SCRIPT, "Conditions, et arguments reçus par le script.",
      ['if [ -e "$1" ]; then ... else ... fi', "$1 $2 … arguments   $# nombre   $0 nom du script   exit 1"],
      [('[ $# -eq 0 ] && { echo "Usage : $0 chemin"; exit 1; }', ""), ("-e existe  -f fichier  -d dossier  -z vide", "tests utiles")], ["17.3"]),
    C("for", "for", SCRIPT, "Répète des commandes pour chaque élément d'une liste.",
      ["for x in <liste>; do ...; done"],
      [("for i in $(seq 1 5); do touch user$i.txt; done", ""), ("for f in *.log; do gzip \"$f\"; done", "")], ["17.4"]),
    C("crontab", "crontab", SCRIPT, "Tâches planifiées d'un utilisateur.",
      ["crontab -l", "crontab -e"], [("* * * * * date >> ~/tick.log", "chaque minute")], ["18.1"]),
    C("cron", "Syntaxe cron et /etc/cron.d", SCRIPT, "minute heure jour-du-mois mois jour-semaine [utilisateur] commande",
      ["m h dom mon dow commande", "/etc/cron.d : 6e champ = utilisateur", "run-parts --test /etc/cron.daily"],
      [("30 8 * * 1", "tous les lundis à 8h30"), ("*/15 * * * *", "toutes les 15 min"),
       ("0 2 * * * root /home/etudiant/hello.sh", "dans /etc/cron.d, chemin absolu"), ("nettoyage-tmp", "pas de point dans le nom (run-parts !)")], ["18.2"]),
    C("date", "date", SCRIPT, "Date et heure, dans le format voulu.",
      ["date +<format>"], [("date +%F", "2026-09-28"), ("date +%Y%m%d-%H%M%S", "pour nommer des sauvegardes")], ["25.3"]),
    C("xargs", "xargs", SCRIPT, "Transforme des lignes en arguments pour une commande.",
      ["... | xargs [-r] <commande>"], [("ls -1t site-*.tar.gz | tail -n +8 | xargs -r rm -f", "garder les 7 plus récents")], ["25.5"]),

    # ── Réseau et SSH ──────────────────────────────────────────────────
    C("ip", "ip / hostname", NET, "Adresses et interfaces réseau, nom de la machine.",
      ["ip a", "hostname", "hostname -I"], [("ip a show eth0", ""), ("hostname -I", "adresses IP")], ["21.1"]),
    C("ss", "ss", NET, "Ports en écoute et connexions.",
      ["ss -tuln", "sudo ss -tulnp"], [("ss -tln", "ports TCP en écoute"), ("sudo ss -tlnp", "avec le programme")], ["21.3"]),
    C("hosts", "/etc/hosts et DNS", NET, "Résolution de noms : /etc/hosts (local, prioritaire) puis DNS (/etc/resolv.conf).",
      ["getent hosts <nom>", "/etc/hosts : <IP> <nom>"],
      [("echo '192.168.1.100 serveur-local' | sudo tee -a /etc/hosts", ""), ("getent ahostsv4 serveur-local", "tester la résolution")], ["21.4"]),
    C("ssh-keygen", "ssh-keygen / ssh-copy-id", NET, "Crée une paire de clés, et installe la clé publique sur un serveur.",
      ["ssh-keygen -t ed25519", "ssh-copy-id <user>@<hôte>"],
      [("ssh-keygen -t ed25519", "~/.ssh/id_ed25519 (privée) et .pub"), ("ssh-copy-id deploy@localhost", "")], ["22.2"]),
    C("ssh", "ssh et ~/.ssh/config", NET, "Connexion à distance ; alias dans ~/.ssh/config.",
      ["ssh <user>@<hôte>", "Host <alias> / HostName / User"],
      [("ssh deploy@localhost", ""), ("Host prod\n    HostName localhost\n    User deploy", "puis : ssh prod"), ("ssh -v prod", "verbeux, pour diagnostiquer")], ["22.3"]),
    C("scp", "scp", NET, "Copie de fichiers via SSH.",
      ["scp <fichier> <user>@<hôte>:<chemin>", "scp -r <dossier> <hôte>:"], [("scp livrable.txt prod:", "dans le dossier personnel distant")], ["22.4"]),
    C("sshd", "sshd_config", NET, "Configuration du serveur SSH.",
      ["/etc/ssh/sshd_config", "sudo sshd -t", "sudo service ssh reload"],
      [("PasswordAuthentication no", "clés uniquement"), ("PermitRootLogin no", ""), ("sudo sshd -t && sudo service ssh reload", "")], ["22.5"]),

    # ── Sécurité et dépannage ──────────────────────────────────────────
    C("passwd", "passwd / chage", SEC, "Verrouiller un compte, gérer l'expiration des mots de passe.",
      ["passwd -l|-u <user>", "passwd -S <user>", "chage -l|-M <jours> <user>"],
      [("sudo passwd -l toor", "verrouille"), ("sudo usermod -s /usr/sbin/nologin toor", "interdit le shell"), ("sudo chage -M 90 securise", "")], ["23.4"]),
    C("audit", "Audit rapide", SEC, "Repérer ce qui est dangereux sur une machine.",
      ["find / -perm -4000 -type f", "find /etc -type f -perm -o+w", "awk -F: '$3 == 0' /etc/passwd"],
      [("find / -perm -4000 -type f 2>/dev/null", "exécutables SUID"), ("find /etc -type f -perm -o+w", "modifiables par tous"),
       ("awk -F: '$3 == 0 {print $1}' /etc/passwd", "comptes d'UID 0")], ["23.1"]),
    C("crlf", "Fins de ligne Windows", SEC, "Un script écrit sous Windows contient des \\r : « bad interpreter ».",
      ["cat -A <fichier>", "file <fichier>", "sed -i 's/\\r$//' <fichier>"], [("cat -A deploy.sh", "^M en fin de ligne = CRLF")], ["24.1"]),
    C("truncate", "truncate", SEC, "Vide un fichier sans le supprimer (le programme qui l'a ouvert continue d'écrire).",
      ["truncate -s 0 <fichier>", ": > <fichier>"], [("sudo truncate -s 0 /var/log/app-debug/trace.log", "")], ["24.2"]),
    C("namei", "namei", SEC, "Affiche les droits de chaque dossier d'un chemin.",
      ["namei -l <chemin>"], [("namei -l /home/ops/.ssh/authorized_keys", "trouver le dossier trop ouvert")], ["24.3"]),
]
