"""Mémo du parcours Linux : une fiche par commande (ou notion du shell), débloquée par un exercice."""


def C(id, name, category, desc, syntax, examples, unlock):
    return {"id": id, "name": name, "category": category, "desc": desc, "syntax": syntax,
            "examples": examples, "unlock": unlock}


NAV, FILES, TEXT, SHELL, USERS, PROC, SYS, NET, ARCH, SCRIPT, SEC = (
    "Se repérer", "Fichiers et dossiers", "Texte et recherche", "Syntaxe du shell", "Utilisateurs et droits",
    "Processus", "Système et paquets", "Réseau et SSH", "Archives", "Scripts et automatisation", "Sécurité et dépannage",
)

CARDS = [
    # ── Se repérer ─────────────────────────────────────────────────────
    C("pwd", "pwd", NAV, "Affiche le dossier dans lequel on se trouve (chemin absolu).",
      ["pwd"], [("pwd", "→ /home/etudiant")], ["1.1"]),
    C("cd", "cd", NAV, "Change de dossier courant.",
      ["cd <dossier>", "cd ..", "cd ~", "cd -"],
      [("cd /var/log", "chemin absolu"), ("cd ..", "remonte d'un niveau"), ("cd", "retour au dossier personnel"),
       ("cd -", "revient au dossier précédent")], ["1.1"]),
    C("ls", "ls", NAV, "Liste le contenu d'un dossier.",
      ["ls [options] [chemin]"],
      [("ls -l", "format détaillé : droits, propriétaire, taille, date"), ("ls -a", "affiche aussi les fichiers cachés (.nom)"),
       ("ls -la /var/log", "les deux, sur un autre dossier"), ("ls -lh", "tailles lisibles (K, M, G)")], ["1.1"]),
    C("cat", "cat", NAV, "Affiche le contenu d'un ou plusieurs fichiers.",
      ["cat <fichier>...", "cat -A <fichier>"],
      [("cat /etc/hostname", ""), ("cat -A deploy.sh", "révèle les caractères invisibles (^M des fins de ligne Windows)")], ["1.1"]),
    C("echo", "echo", NAV, "Affiche un texte ; combiné à > ou >>, l'écrit dans un fichier.",
      ['echo "texte"'], [('echo "Bonjour" > f.txt', "crée ou remplace f.txt"), ("echo $HOME", "affiche une variable")], ["1.1", "3.2"]),
    C("caches", "Fichiers cachés", NAV, "Un nom qui commence par un point est caché : ls ne l'affiche pas sans option.",
      ["ls -a [dossier]", "ls -d <dossier>/.*"],
      [("ls -a ~", "tout, y compris . et .."), ("ls -d ~/.*", "seulement les entrées cachées")], ["1.2", "3.9"]),
    C("noms-speciaux", "Espaces et tirets dans les noms", NAV, "Le shell coupe la ligne aux espaces ; un argument qui commence par - est pris pour une option.",
      ['"nom avec espaces"', "nom\\ avec\\ espaces", "./-nom   ou   -- -nom"],
      [('cat "compte rendu.txt"', "guillemets : un seul argument"), ("rm -- -brouillon.txt", "-- : fin des options"),
       ("cat ./-brouillon.txt", "un chemin qui ne commence pas par -")], ["1.5"]),
    C("man", "man", NAV, "Ouvre le manuel d'une commande. RTFM !",
      ["man <commande>", "man <section> <page>", "man -k <mot>", "<commande> --help"],
      [("man ls", "/mot pour chercher, n pour le suivant, q pour quitter"), ("man 5 crontab", "la page de la section 5 (format de fichier)"),
       ("man -k compress", "chercher une commande par mot-clé"), ("mkdir --help", "aide courte")], ["2.2"]),
    C("help", "Commandes internes : type et help", NAV, "Certaines commandes font partie du shell lui-même : pas de page de manuel à leur nom.",
      ["type <commande>", "help <commande>"], [("type pwd", "pwd is a shell builtin"), ("help pwd", "documentation d'une commande interne")], ["2.5"]),
    C("less", "less", NAV, "Lit un long fichier page par page, avec les mêmes touches que man.",
      ["less <fichier>"], [("/mot puis n", "chercher, puis occurrence suivante"), ("G  /  g", "fin / début du fichier"), ("q", "quitter")], ["2.7"]),
    C("ls-tri", "Trier avec ls", NAV, "ls trie par nom par défaut ; d'autres critères existent (voir man ls).",
      ["ls -lt", "ls -ltr"], [("ls -lt /var/log | head", "les plus récemment modifiés en premier"), ("ls -ltr", "ordre inversé : le plus récent en bas")], ["2.6"]),
    C("chemins", ". .. ~ et chemins", NAV, "Chemin absolu (commence par /) ou relatif (part du dossier courant).",
      ["/chemin/absolu", "chemin/relatif", ". (ici)   .. (parent)   ~ (dossier personnel)"],
      [("cat ../notes.txt", "un niveau au-dessus"), ("ls ../../lib", "depuis /var/log/apt : /var/lib"), ("cp ~/notes.txt .", "copie dans le dossier courant")],
      ["2.3", "2.4", "2.8"]),

    # ── Fichiers et dossiers ──────────────────────────────────────────
    C("mkdir", "mkdir", FILES, "Crée un ou plusieurs dossiers.",
      ["mkdir <dossier>..."],
      [("mkdir photos musique", "deux dossiers"), ("mkdir ~/photos/2026", "le dossier photos doit déjà exister")], ["1.3"]),
    C("arborescence", "mkdir -p et accolades", FILES, "Créer d'un coup toute une chaîne de dossiers, ou plusieurs variantes d'un nom.",
      ["mkdir -p <a/b/c>", "{x,y,z}   (développé par le shell)"],
      [("mkdir -p site/assets/css", "crée aussi site et assets s'ils manquent"), ("mkdir -p photos/{2025,2026}", "photos/2025 et photos/2026")], ["2.1", "3.1"]),
    C("touch", "touch", FILES, "Crée un fichier vide (ou met à jour sa date de modification).",
      ["touch <fichier>..."], [("touch liste.txt", ""), ("touch a.txt b.txt", "plusieurs d'un coup")], ["1.4", "1.7"]),
    C("cp", "cp", FILES, "Copie des fichiers ou des dossiers.",
      ["cp <source> <destination>", "cp -r <dossier> <destination>"],
      [("cp notes.txt sauvegarde/", "garde le même nom"), ("cp notes.txt copie.txt", "copie sous un autre nom"),
       ("cp -r site/ site-bak/", "copie récursive d'un dossier")], ["3.4"]),
    C("mv", "mv", FILES, "Déplace ou renomme (renommer, c'est déplacer). Écrase la destination sans prévenir !",
      ["mv <source> <destination>", "mv -n …   (n'écrase jamais)", "mv -i …   (demande avant d'écraser)"],
      [("mv brouillon.txt final.txt", "renomme ; écrase final.txt s'il existe"), ("mv -n notes.txt archives/", "refuse d'écraser"),
       ("mv *.log archives/", "déplace plusieurs fichiers")], ["3.6"]),
    C("rm", "rm", FILES, "Supprime des fichiers ou des dossiers. Pas de corbeille !",
      ["rm <fichier>...", "rm -r <dossier>", "rm -i <fichier>"],
      [("rm *.bak", "testez d'abord le motif avec ls *.bak"), ("rm -r ancien-site", "supprime un dossier et son contenu")], ["3.5"]),
    C("jokers", "Jokers * ? [ ]", FILES, "Le shell remplace les motifs par la liste des fichiers correspondants.",
      ["*  (n'importe quelle suite)", "?  (un caractère)", "[abc] [0-9]  (un caractère parmi)"],
      [("ls *.txt", ""), ("rm brouillon?.md", "un seul caractère"), ("cp scan-[a-c].pdf archives/", "un caractère parmi une plage")], ["3.5", "3.7", "3.8"]),
    C("ln", "ln", FILES, "Crée un lien dur (même inode) ou symbolique (raccourci vers un chemin).",
      ["ln <cible> <lien>", "ln -s <cible> <lien>"],
      [("ln rapport.txt rapport-bis.txt", "lien dur"), ("ln -s /var/log ~/journaux", "lien symbolique")], ["4.1", "4.3"]),
    C("stat", "stat", FILES, "Informations détaillées sur un fichier : inode, droits, nombre de liens, dates.",
      ["stat <fichier>", "stat -c <format> <fichier>"],
      [("stat -c %h base.db", "nombre de liens durs"), ("stat -c '%a %U:%G' secret.txt", "droits octaux et propriétaire")], ["4.2"]),
    C("liens-casses", "Liens cassés et remplacement", FILES, "Un lien symbolique dont la cible a disparu est cassé ; ln -f remplace un lien existant.",
      ["find <où> -xtype l", "ln -sf <nouvelle-cible> <lien>"],
      [("find ~/liens -xtype l", "liens cassés"), ("ln -sf ../doc/guide.pdf guide", "remplace le lien guide")], ["4.4", "4.5"]),
    C("lien-relatif", "Liens relatifs", FILES, "Un chemin relatif dans un lien est lu depuis le dossier du lien : il reste valable si l'ensemble est déplacé.",
      ["ln -s <chemin relatif au dossier du lien> <lien>", "readlink <lien>"],
      [("cd ~/site && ln -s docs/v2 doc-actuelle", "valable même si ~/site change de place"), ("readlink doc-actuelle", "affiche docs/v2")], ["4.6"]),
    C("ln-n", "Remplacer un lien vers un dossier", FILES, "Sans -n, ln suit un lien vers un dossier et crée le nouveau lien à l'intérieur.",
      ["ln -sfn <nouvelle-cible> <lien>"], [("ln -sfn versions/v3 actuelle", "actuelle pointe désormais vers versions/v3")], ["4.7"]),
    C("inode", "Retrouver un fichier par son inode", FILES, "Chaque nom renvoie à un inode ; find sait retrouver tous les noms d'un même inode.",
      ["ls -i <fichier>", "find <où> -inum <numéro>", "find <où> -samefile <fichier>"],
      [("ls -li ~/doc", "inodes des fichiers"), ("find / -xdev -inum 131074 2>/dev/null", "tous les noms de l'inode 131074")], ["4.8"]),
    C("readlink", "readlink / realpath", FILES, "Affiche la cible d'un lien symbolique, ou le chemin final après tous les liens.",
      ["readlink <lien>", "readlink -f <lien>", "realpath <chemin>"],
      [("readlink ~/journaux", "la cible immédiate"), ("readlink -f ~/journaux", "chemin final, tous les liens résolus")], ["4.9"]),

    # ── Texte et recherche ─────────────────────────────────────────────
    C("find", "find", TEXT, "Recherche des fichiers selon des critères (nom, type, taille, droits, date…).",
      ["find <où> <critères> [action]"],
      [('find /var -name "*.log"', "par nom (-iname : sans la casse)"), ("find /usr -type d", "dossiers seulement"),
       ("find /home -size +100k", "plus de 100 Kio"), ("find /tmp -mtime -7", "modifiés il y a moins de 7 jours"),
       ("find /var -type f -name '*.gz'", "plusieurs critères : tous doivent être vrais")], ["5.1", "5.3", "5.4", "5.6"]),
    C("find-plus", "find : chemin, dates, unités", TEXT, "Critères plus fins, et le piège de l'arrondi des tailles.",
      ["-path '<motif>'", "-newer <fichier>", "-size -<N>k   (taille arrondie à l'unité avant la comparaison)"],
      [("find /var -path '*/cache/*' -name '*.bin'", "motif sur le chemin complet"), ("find /etc -newer /etc/hostname", "modifiés après ce fichier"),
       ("find . -size -2048k", "moins de 2 Mio (avec -2M : moins de 1 Mio arrondi, donc les fichiers vides)")], ["5.8"]),
    C("grep", "grep", TEXT, "Cherche les lignes qui contiennent un motif.",
      ["grep [options] <motif> <fichier>..."],
      [("grep -r TODO ~/projets", "récursif"), ('grep -rl "motif" /srv', "noms de fichiers seulement"),
       ("grep -v '^#' f", "inverse : lignes sans #"), ("grep -n motif f", "avec les numéros de ligne")], ["5.2", "5.5", "5.7"]),
    C("grep-plus", "grep : casse, comptage, mots, contexte", TEXT, "Options courantes de grep.",
      ["-i  -c  -w", "-A <n>  -B <n>  -C <n>"],
      [("grep -ic warning app.log", "compte, sans tenir compte de la casse"), ("grep -w chat f", "le mot chat, pas chaton"),
       ("grep -A2 Exception app.log", "la ligne trouvée et les 2 suivantes")], ["5.9"]),
    C("wc", "wc", TEXT, "Compte les lignes, mots ou octets.",
      ["wc -l | -w | -c <fichier>"], [("wc -l /etc/passwd", "nombre de lignes"), ("wc -w rapport.txt", "nombre de mots")], ["5.3"]),
    C("sort", "sort", TEXT, "Trie les lignes.",
      ["sort [options] [fichier]"],
      [("sort -u noms.txt", "trie et supprime les doublons"), ("sort -n", "tri numérique"), ("sort -rn", "numérique décroissant"),
       ("sort -t';' -k3 -n f", "sur le 3e champ, séparateur ;")], ["6.8"]),
    C("cut", "cut", TEXT, "Extrait des champs ou des colonnes de chaque ligne.",
      ["cut -d <séparateur> -f <champs>"], [("cut -d: -f1 /etc/group", "1er champ séparé par :"), ("cut -d' ' -f2,3 f", "champs 2 et 3, séparés par une espace")], ["6.5"]),
    C("tee", "tee", TEXT, "Écrit ce qu'il reçoit dans un fichier ET le transmet à la suite (écran ou commande suivante).",
      ["commande | tee <fichier>", "commande | tee -a <fichier>"], [("df -h | tee disque.txt", "affiche et enregistre"), ("ps aux | tee -a suivi.txt", "ajoute à la fin du fichier")], ["6.4"]),
    C("nano", "nano", TEXT, "Éditeur de texte simple dans le terminal.",
      ["nano <fichier>"], [("Ctrl+O", "enregistrer"), ("Ctrl+X", "quitter"), ("Ctrl+W", "rechercher"), ("Ctrl+K", "couper la ligne")], ["7.1"]),
    C("vim", "vim", TEXT, "Éditeur modal puissant : mode normal, insertion (i), commande (:).",
      ["vim <fichier>"],
      [("i / Echap", "passer en insertion / revenir en mode normal"), ("dd", "supprimer la ligne"), ("G puis o", "nouvelle ligne à la fin"),
       (":wq  /  :q!", "enregistrer et quitter / quitter sans enregistrer")], ["7.2"]),
    C("sed", "sed", TEXT, "Éditeur de flux : remplacements ligne à ligne.",
      ["sed 's/ancien/nouveau/[g]' <fichier>", "sed -i ... (modifie le fichier)"],
      [("sed -i 's/mode=test/mode=prod/' app.ini", ""), ("sed 's/[0-9]/#/g' f", "tous les chiffres"),
       ("sed -i 's/\\r$//' f", "fins de ligne Windows → Unix")], ["7.3", "7.4", "7.5", "7.6", "7.7", "8.4", "8.6", "8.8"]),
    C("sed-plus", "sed : lignes ciblées, séparateurs, sauvegarde", TEXT, "Aller plus loin avec sed.",
      ["sed '<n>s/…/…/'", "sed '/<début>/,/<fin>/ s/…/…/'", "sed '/<motif>/d'", "sed 's|a/b|c/d|'", "sed -i.<suffixe> …"],
      [("sed -i.orig 's/on/off/' app.ini", "garde une copie app.ini.orig"), ("sed 's#/opt/app#/srv/app#g' f", "séparateur # : pas besoin d'échapper les /"),
       ("sed '/^\\[db\\]/,/^\\[/ s/host=a/host=b/' f", "seulement dans la section [db]"), ("sed '/^#/d' f", "supprime les lignes de commentaire")], ["7.8"]),
    C("regex", "Expressions régulières", TEXT, "Décrire précisément un motif de texte (avec grep -E, sed -E…).",
      ["^ début   $ fin   . un caractère   * + ? répétitions", "[a-z] classe   (a|b) alternative   {2,} au moins 2   \\. un vrai point"],
      [("grep '^[ab]' noms.txt", "lignes commençant par a ou b"), ("grep -E '^[0-9]{5}$' f", "lignes qui ne sont qu'un code postal"),
       ("grep -oE '[0-9]+' f", "extrait les nombres"), ("grep -vE '^[[:space:]]*$' f", "sans les lignes blanches")], ["8.1", "8.2", "8.3", "8.5", "8.7"]),
    C("regex-plus", "Regex : lignes entières, mots, captures", TEXT, "Valider une ligne entière, isoler un mot, réutiliser un morceau capturé.",
      ["grep -x <motif>", "grep -w <motif>", "\\b   (frontière de mot, GNU)", "sed -E 's/(…)(…)/\\2\\1/'"],
      [("grep -xE '[A-Z]{2}[0-9]{3}' codes.txt", "lignes qui sont exactement un code"), ("sed -E 's/([0-9]+)h([0-9]+)/\\1:\\2/' f", "14h30 → 14:30")], ["8.8"]),
    C("head-tail", "head / tail", TEXT, "Affiche le début ou la fin d'un fichier ; tail -f suit un journal en direct.",
      ["head -n <N>", "tail -n <N>", "tail -n +<N>", "tail -f <fichier>"],
      [("head -3", "3 premières lignes"), ("tail -n +2 f", "tout sauf la 1re ligne"), ("tail -f /var/log/syslog", "Ctrl+C pour arrêter")], ["9.2", "9.9"]),
    C("uniq", "uniq", TEXT, "Regroupe les lignes identiques consécutives (triez d'abord !).",
      ["sort | uniq [-c] [-d]"], [("sort noms.txt | uniq -c", "compte chaque ligne"), ("sort noms.txt | uniq -d", "seulement les lignes répétées")], ["6.9", "9.1"]),
    C("awk", "awk", TEXT, "Découpe chaque ligne en champs ($1, $2…) et agit selon des conditions.",
      ["awk [-F séparateur] 'condition { action }' <fichier>"],
      [("awk '{print $1}' access.log", "1re colonne"), ("awk -F';' '$3 > 100 {print $1}' ventes.csv", "séparateur ; et condition"),
       ("awk '$1 ~ /^srv/' f", "le 1er champ correspond à une regex")], ["9.3", "9.4", "9.6"]),
    C("awk-calcul", "awk : sommes et tableaux", TEXT, "Accumuler ligne après ligne, puis afficher le résultat dans le bloc END.",
      ["awk '{ s += $2 } END { print s }'", "awk '{ t[$1] += $2 } END { for (k in t) print k, t[k] }'"],
      [("awk '{ s += $5 } END { print s }' liste.txt", "somme d'une colonne"), ("awk '{ n[$1]++ } END { for (ip in n) print n[ip], ip }' access.log", "requêtes par IP")], ["9.7"]),
    C("tr", "tr", TEXT, "Remplace ou supprime des caractères (lit l'entrée standard).",
      ["tr <ensemble1> <ensemble2>", "tr -d <ensemble>"], [("tr 'A-Z' 'a-z' < f.txt", "minuscules"), ("tr -d '\\r' < win.txt > unix.txt", "")], ["9.5"]),
    C("majuscules", "Majuscules et accents", TEXT, "tr ne traite que des octets : pour les caractères accentués, passez par sed ou awk.",
      ["sed 's/.*/\\U&/'", "awk '{ print toupper($0) }'"], [("echo 'été' | sed 's/.*/\\U&/'", "ÉTÉ"), ("awk '{ print tolower($0) }' f", "minuscules")], ["9.8"]),

    # ── Syntaxe du shell ───────────────────────────────────────────────
    C("redirection", "> et >>", SHELL, "Redirige la sortie d'une commande vers un fichier.",
      ["commande > fichier   (remplace)", "commande >> fichier  (ajoute à la fin)"],
      [('echo "Titre" > notes.txt', ""), ('echo "Suite" >> notes.txt', "")], ["3.3"]),
    C("pipe", "Le pipe |", SHELL, "Branche la sortie d'une commande sur l'entrée de la suivante.",
      ["commande1 | commande2 | commande3"], [("cat /etc/group | wc -l", ""), ("grep bash /etc/passwd | cut -d: -f1", "")], ["6.1"]),
    C("stderr", "2> et /dev/null", SHELL, "Les erreurs passent par un flux séparé (stderr, n°2), qui ne va pas dans le pipe.",
      ["commande 2> erreurs.txt", "commande 2>> erreurs.txt", "commande 2>/dev/null"],
      [("ls /inexistant 2> err.txt", "les erreurs dans un fichier"), ("du -sh /var/* 2>/dev/null", "jeter les erreurs")], ["6.2", "6.3", "6.6"]),
    C("fusion", "Fusionner les flux : 2>&1", SHELL, "2>&1 envoie les erreurs là où va la sortie standard à cet instant : l'ordre des redirections compte.",
      ["commande > fichier 2>&1", "commande 2>&1 | …", "commande 2>&1 >/dev/null | …   (seulement les erreurs dans le pipe)"],
      [("make > build.log 2>&1", "tout dans le fichier, dans l'ordre"), ("make 2>&1 > build.log", "les erreurs restent à l'écran !")], ["6.7"]),
    C("variables", "Variables et export", SHELL, "Une variable exportée est transmise aux programmes lancés depuis le shell.",
      ["NOM=valeur", "export NOM=valeur", "echo $NOM", "env", "unset NOM"],
      [("export VILLE=Grenoble", ""), ("bash -c 'echo $VILLE'", "vide si la variable n'est pas exportée"),
       ("echo 'export VILLE=Grenoble' >> ~/.bashrc", "permanent"), ("source ~/.bashrc", "recharger")], ["15.1", "15.4"]),
    C("path", "PATH", SHELL, "Liste des dossiers où le shell cherche les commandes, dans l'ordre : le premier trouvé gagne.",
      ['export PATH="$PATH:/opt/scripts"', "command -v <commande>"],
      [("echo $PATH", ""), ("command -v python3", "où la commande est-elle trouvée ?"),
       ('export PATH="$PATH:$HOME/bin"', "$HOME plutôt que ~ entre guillemets")], ["15.2"]),
    C("alias", "alias", SHELL, "Raccourci pour une commande, propre au shell interactif.",
      ["alias nom='commande'", "unalias nom", "alias   (liste les alias)"],
      [("alias la='ls -A'", "à mettre dans ~/.bashrc pour le garder"), ("grep -n alias ~/.bashrc", "la dernière définition l'emporte")], ["15.3"]),
    C("type", "type / command -v", SHELL, "Ce que le shell lancera vraiment : alias, fonction, commande interne ou fichier du PATH.",
      ["type -a <nom>", "type -t <nom>", "command -v <nom>"],
      [("type -a ls", "toutes les définitions, dans l'ordre de recherche"), ("type -t cd", "builtin : commande interne"),
       ("sudo -iu alice", "shell de connexion d'alice, pour examiner son environnement")], ["15.5"]),
    C("demarrage", "Fichiers de démarrage du shell", SHELL, "Où rendre un réglage permanent, et pour qui.",
      ["~/.bashrc  (shells interactifs)", "~/.profile  (shell de connexion)", "/etc/profile.d/*.sh  (tous les utilisateurs)", "/etc/environment  (NOM=valeur)"],
      [("grep -n VILLE ~/.bashrc ~/.profile", "où la variable est-elle définie ?"), ("sudo -iu bob", "tester la session d'un autre compte")], ["15.3", "15.4"]),
    C("sudo-env", "L'environnement de sudo", USERS, "sudo repart d'un environnement propre, avec son propre PATH (secure_path).",
      ["sudo -l", "sudo grep -r secure_path /etc/sudoers*", "sudo install -m 755 <source> <destination>"],
      [("sudo install -m 755 -o root -g root outil.sh /usr/local/bin/outil", "copie appartenant à root, non modifiable par les autres"),
       ("sudo env | grep PATH", "le PATH vu par sudo")], ["15.6"]),
    C("redir-sudo", "sudo et redirections", SHELL, "La redirection est faite par le shell qui lance la commande, pas par sudo.",
      ["sudo -u <user> bash -c '<commande> > fichier'", "<commande> | sudo -u <user> tee fichier"],
      [("sudo -u alice bash -c 'echo test > /home/partage/a.txt'", "c'est alice qui ouvre le fichier"),
       ("echo test | sudo tee /etc/exemple.conf", "écrire un fichier protégé")], ["25.2"]),

    # ── Utilisateurs et droits ─────────────────────────────────────────
    C("sudo", "sudo", USERS, "Exécute une commande avec les droits d'administrateur (ou d'un autre utilisateur).",
      ["sudo <commande>", "sudo -u <utilisateur> <commande>"],
      [("sudo apt update", ""), ("sudo -u carla touch /srv/compta/test", "tester les droits de carla"), ("sudo -l -U carla", "ce que carla a le droit de lancer")], ["10.1", "11.1"]),
    C("useradd", "useradd / userdel / passwd", USERS, "Crée ou supprime un compte utilisateur, lui donne un mot de passe.",
      ["useradd -m -s /bin/bash <nom>", "userdel -r <nom>", "passwd <nom>"],
      [("sudo useradd -m -s /bin/bash carla", "-m crée le dossier personnel"), ("id carla", "vérifier : UID et groupes"),
       ("sudo passwd carla", "définir son mot de passe")], ["10.1"]),
    C("groupes", "groupadd / usermod -aG", USERS, "Crée un groupe et y ajoute des utilisateurs.",
      ["groupadd <groupe>", "usermod -aG <groupe> <utilisateur>"],
      [("sudo groupadd compta", ""), ("sudo usermod -aG compta carla", "-a : sans retirer ses autres groupes !"), ("id -nG carla", "")], ["10.2", "10.7", "12.2"]),
    C("chown", "chown / chgrp", USERS, "Change le propriétaire et/ou le groupe d'un fichier.",
      ["chown <user>[:<groupe>] <fichier>", "chgrp <groupe> <fichier>"],
      [("sudo chgrp compta /srv/compta", ""), ("sudo chown carla:compta bilan.txt", ""), ("sudo chown -R carla:carla /home/carla/projets", "récursif")],
      ["10.3", "10.4", "12.3", "12.4", "12.6"]),
    C("chmod", "chmod", USERS, "Modifie les droits : u (propriétaire), g (groupe), o (autres) ; r=4 w=2 x=1.",
      ["chmod <octal> <fichier>", "chmod u+x,g-w,o-rwx <fichier>"],
      [("chmod 640 bilan.txt", "rw- r-- ---"), ("chmod g+w,o-rwx notes.txt", "symbolique : ajoute et retire sans toucher au reste"),
       ("chmod u-s fichier", "retire le bit SUID")], ["10.4", "10.5", "10.9"]),
    C("setgid", "Dossier partagé : setgid", USERS, "Sur un dossier, le bit setgid fait hériter aux nouveaux fichiers le groupe du dossier.",
      ["chmod g+s <dossier>", "chmod 2770 <dossier>"],
      [("sudo chmod g+s /srv/compta", ""), ("ls -ld /srv/compta", "drwxrws--- : un s à la place du x du groupe")], ["10.6"]),
    C("sudo-tee", "Écrire dans un fichier de root", USERS, "Dans « sudo commande > f », c'est votre shell qui ouvre f : il faut que la commande lancée avec sudo écrive elle-même.",
      ["<commande> | sudo tee <fichier>", "<commande> | sudo tee -a <fichier>"],
      [("echo '10.0.0.8 nas' | sudo tee -a /etc/hosts > /dev/null", "ajoute une ligne à un fichier de root"),
       ("sudo sh -c 'date > /etc/derniere-maj'", "autre solution : tout le shell en root")], ["10.8"]),
    C("sudoers", "Déléguer avec sudoers", USERS, "Une règle par ligne : qui, depuis quelle machine, sous quelle identité, quelles commandes.",
      ["sudo visudo -f /etc/sudoers.d/<nom>", "<user> ALL=(root) [NOPASSWD:] /chemin/commande", "sudo -l -U <user>"],
      [("%compta ALL=(root) /usr/bin/lpq", "le groupe compta peut lancer lpq en root"), ("sudo visudo -c", "vérifier toute la configuration")], ["11.8"]),
    C("su", "su", USERS, "Ouvre un shell sous l'identité d'un autre utilisateur.",
      ["su - <utilisateur>"], [("sudo su - papa", "devenir papa pour tester ses droits"), ("exit", "revenir")], ["12.1"]),
    C("login-defs", "Réglages des nouveaux comptes", USERS, "/etc/login.defs fixe notamment les droits des dossiers personnels créés par useradd.",
      ["HOME_MODE <octal>", "UMASK <octal>   (utilisé si HOME_MODE est absent)"],
      [("grep -E '^(HOME_MODE|UMASK)' /etc/login.defs", "réglages actuels"), ("ls -ld /home/*", "les dossiers déjà créés ne changent pas")], ["12.5"]),
    C("find-perm", "Chercher par droits : find -perm", USERS, "-perm N : droits exactement égaux à N ; -perm -N : au moins ces bits-là.",
      ["find <où> -perm <octal>", "find <où> -perm -<octal>", "find <où> -perm -o=w"],
      [("find /srv -type f -perm -002", "modifiables par les autres"), ("find ~ -type f -perm 600", "exactement rw-------")], ["12.7"]),
    C("bits", "Bits spéciaux : SUID, SGID, sticky", USERS, "4000 : s'exécute avec les droits du propriétaire ; 2000 : groupe hérité (dossier) ; 1000 : sticky.",
      ["chmod u-s <fichier>", "chmod g+s <dossier>", "chmod +t <dossier>", "chmod 1777 <dossier>"],
      [("ls -ld /tmp", "drwxrwxrwt : le t final est le bit sticky"), ("find /usr -perm -2000 -type f", "fichiers SETGID"),
       ("chmod +t /srv/partage", "chacun ne supprime que ses propres fichiers")], ["23.2", "23.6"]),
    C("umask", "umask", USERS, "Droits retirés aux fichiers et dossiers au moment de leur création.",
      ["umask", "umask 027", "666 - umask = droits d'un fichier ; 777 - umask = ceux d'un dossier"],
      [("umask 022", "fichiers en 644, dossiers en 755"), ("umask 077", "rien pour le groupe ni les autres"),
       ("grep -rn umask /etc/profile /etc/profile.d", "qui la règle à l'ouverture de session ?")], ["23.7", "25.9"]),
    C("equipe", "Dossier d'équipe", USERS, "Un groupe propriétaire, l'écriture pour ce groupe et l'héritage du groupe (setgid).",
      ["chgrp -R <groupe> <dossier>", "chmod -R 2775 <dossier>"],
      [("sudo chgrp -R compta /srv/compta", ""), ("sudo chmod -R 2770 /srv/compta", "équipe en écriture, rien pour les autres"),
       ("sudo -u bob touch /srv/compta/test", "vérifier avec un membre")], ["25.1"]),
    C("traverser", "Traverser un dossier", USERS, "Pour atteindre un fichier, il faut le droit x sur chaque dossier du chemin ; r sert seulement à lister.",
      ["namei -l <chemin>", "chmod o+x <dossier>   (traverser sans lister)"],
      [("namei -l /var/www/site/index.html", "droits de chaque élément du chemin"), ("chmod 711 /srv/docs", "traversable, mais pas listable par les autres")], ["24.6"]),

    # ── Processus ──────────────────────────────────────────────────────
    C("ps", "ps / pgrep / top", PROC, "Liste les processus en cours.",
      ["ps aux", "ps -o pid,user,ni,cmd -C <nom>", "pgrep -a <nom>", "top"],
      [("ps aux | grep cron", ""), ("ps -eo pid,user,etime,cmd", "colonnes choisies (etime : depuis quand)"),
       ("pgrep -x cron", "PID d'un processus"), ("top", "M : trier par mémoire, P : par CPU, q : quitter")], ["11.2"]),
    C("kill", "kill", PROC, "Envoie un signal à un processus.",
      ["kill <PID>", "kill -9 <PID>", "kill -HUP <PID>"],
      [("sudo kill 1234", "demande d'arrêt (TERM) : le programme peut faire le ménage"), ("kill -9 1234", "arrêt forcé, en dernier recours"),
       ("sudo kill -HUP $(pgrep -x nginx)", "par convention, les services relisent leur configuration")], ["11.3", "11.5"]),
    C("jobs", "& nice jobs", PROC, "Lancer en arrière-plan, avec une priorité plus basse.",
      ["commande &", "nice -n <gentillesse> commande", "jobs  fg  bg", "renice"],
      [("nice -n 15 tar -czf /tmp/s.tgz /srv &", ""), ("jobs", "tâches du terminal"), ("fg %1", "ramener au premier plan")], ["11.4"]),
    C("ppid", "Parents et enfants", PROC, "Chaque processus a un parent (PPID) : c'est lui qui peut le relancer.",
      ["ps -o pid,ppid,user,cmd -p <PID>", "pstree -p", "pstree -p <PID>"],
      [("ps -o pid,ppid,cmd -C cron", "le PID du parent de cron"), ("pstree -p $(pgrep -x sshd | head -n1)", "l'arbre des processus sous sshd")], ["11.6"]),
    C("signaux", "Pause et reprise", PROC, "STOP gèle un processus sans le terminer ; CONT le fait repartir.",
      ["kill -l", "kill -STOP <PID>", "kill -CONT <PID>"],
      [("kill -STOP 4321", "la colonne STAT de ps passe à T"), ("kill -CONT 4321", "le processus reprend là où il en était")], ["11.7"]),
    C("tri-ps", "Trier les processus", PROC, "ps trie sur n'importe quelle colonne ; RSS = mémoire réellement occupée (Kio).",
      ["ps aux --sort=-<colonne>", "ps -eo pid,rss,cmd --sort=-rss"],
      [("ps aux --sort=-%cpu | head", "les plus gourmands en processeur"), ("ps -eo pid,rss,comm --sort=-rss | head -3", "les plus gourmands en mémoire")], ["19.2"]),
    C("renice", "renice", PROC, "Change la gentillesse d'un processus déjà lancé (de -20, prioritaire, à 19).",
      ["renice -n <valeur> -p <PID>"], [("sudo renice -n 10 -p 4321", ""), ("ps -o pid,ni,comm -p 4321", "vérifier la colonne NI")], ["19.5"]),
    C("lsof", "lsof", PROC, "Fichiers ouverts par les processus (et qui a ouvert quoi).",
      ["lsof -p <PID>", "lsof <fichier>", "lsof +L1", "lsof -i :<port>"],
      [("sudo lsof /var/log/syslog", "qui garde ce fichier ouvert ?"), ("sudo lsof +L1", "fichiers supprimés mais encore ouverts"),
       ("ls -l /proc/4321/fd", "les descripteurs d'un processus")], ["19.6", "24.2"]),
    C("etats", "États des processus", PROC, "R : en cours, S : endormi, D : entrée-sortie, T : arrêté, Z : zombie (fin non récupérée par le parent).",
      ["ps -eo pid,ppid,stat,cmd"], [("ps -eo pid,ppid,stat,cmd | grep -w Z", "les zombies et leur parent (PPID)")], ["19.7"]),

    # ── Système et paquets ─────────────────────────────────────────────
    C("apt", "apt", SYS, "Gestionnaire de paquets Debian / Ubuntu.",
      ["sudo apt update", "sudo apt install <paquet>", "sudo apt remove <paquet>", "apt search <mot>"],
      [("sudo apt update && sudo apt install htop", "toujours mettre à jour la liste d'abord")], ["13.1", "13.4", "13.5"]),
    C("dpkg", "dpkg", SYS, "Base des paquets installés.",
      ["dpkg -l", "dpkg -s <paquet>", "dpkg -L <paquet>", "dpkg -S <fichier>"],
      [("dpkg -S /usr/bin/who", "quel paquet a installé ce fichier ?"), ("dpkg -L less | grep man", "les pages de manuel d'un paquet")], ["13.2", "13.8"]),
    C("dpkg-deb", "Paquets .deb locaux", SYS, "Inspecter un .deb avant de l'installer ; dpkg n'installe pas les dépendances à votre place.",
      ["dpkg -c <fichier.deb>", "dpkg -I <fichier.deb>", "sudo dpkg -i <fichier.deb>...", "sudo dpkg --configure -a"],
      [("dpkg -I outil_2.1_all.deb | grep Depends", "dépendances déclarées"), ("sudo dpkg -i dep_1.4_all.deb outil_2.1_all.deb", "installer plusieurs paquets ensemble")], ["13.6"]),
    C("purge", "remove, purge et état rc", SYS, "remove retire le programme mais garde sa configuration (état rc) ; purge efface tout.",
      ["sudo apt purge <paquet>", "sudo dpkg -P <paquet>", "dpkg -l | grep '^rc'"],
      [("dpkg -l | grep '^rc'", "paquets retirés dont la configuration traîne encore")], ["13.7"]),
    C("dpkg-verify", "Vérifier les fichiers d'un paquet", SYS, "dpkg compare les fichiers installés aux empreintes enregistrées lors de l'installation.",
      ["dpkg -V <paquet>", "sudo dpkg -i <le même .deb>   (réinstaller)"],
      [("dpkg -V openssh-server", "rien : aucun fichier modifié ; ??5?????? : contenu changé")], ["13.9"]),
    C("wget", "wget / curl", SYS, "Télécharge depuis le web.",
      ["wget -O <fichier> <url>", "curl -o <fichier> <url>"], [("wget -O accueil.html https://www.debian.org", ""), ("curl -s https://www.debian.org | head", "")], ["13.3"]),
    C("df", "df / findmnt", SYS, "Espace disque et types des systèmes de fichiers montés.",
      ["df -h", "df -T <chemin>", "df -i", "findmnt"],
      [("df -h /home", "tailles lisibles"), ("df -i", "inodes : nombre de fichiers possibles"), ("findmnt -o TARGET,FSTYPE,OPTIONS", "montages et options")], ["14.1", "14.7"]),
    C("du", "du", SYS, "Espace occupé par des fichiers et dossiers.",
      ["du -sh <dossier>", "du -h -d 1 <dossier> | sort -h", "du --apparent-size"],
      [("du -sh /var/log", ""), ("du -s /home/* | sort -n", "qui prend le plus de place ?"), ("du -sm /var/cache", "total en Mio"),
       ("du -h -d 1 ~ | sort -h", "inclut les dossiers cachés, contrairement à *")], ["14.2", "14.3", "14.5"]),
    C("creux", "Taille apparente et taille réelle", SYS, "ls montre la taille annoncée, du les blocs occupés : un fichier creux annonce plus qu'il n'occupe.",
      ["ls -ls <fichier>", "du -h <fichier>", "du -h --apparent-size <fichier>"],
      [("truncate -s 10G test.img", "crée un fichier creux de 10 Gio"), ("du -h --apparent-size test.img; du -h test.img", "10G contre 0")], ["14.6"]),
    C("fstab", "mount, blkid et /etc/fstab", SYS, "Monter un système de fichiers, à la main ou au démarrage.",
      ["mount <source> <point>", "umount <point>", "blkid <périphérique ou image>", "/etc/fstab : source point type options dump pass"],
      [("sudo blkid /dev/sdc1", "UUID et type"), ("UUID=3f1c…  /srv/web  xfs  defaults,noatime  0  2", "ligne fstab"),
       ("sudo findmnt --verify", "vérifier fstab avant de redémarrer")], ["14.4"]),
    C("free", "free / uptime", SYS, "Mémoire utilisée, et charge du système (celles de l'hôte dans un conteneur).",
      ["free -h", "uptime", "nproc"], [("free -h", ""), ("uptime", "load average sur 1, 5 et 15 min")], ["19.1"]),
    C("cgroups", "Limites d'un conteneur (cgroups)", SYS, "Les limites de mémoire et de processeur d'un conteneur sont fixées par le noyau.",
      ["/sys/fs/cgroup/memory.max  (cgroup v2)", "/sys/fs/cgroup/memory/memory.limit_in_bytes  (cgroup v1)"],
      [("cat /sys/fs/cgroup/cpu.max", "quota de processeur (v2)"), ("echo $(( 536870912 / 1048576 ))", "octets → Mio")], ["19.4"]),
    C("gros-fichiers", "Trouver les gros fichiers", SYS, "find sélectionne par taille ; du -a liste aussi les fichiers.",
      ["find <où> -type f -size +<N>M", "du -ah <où> | sort -h | tail"],
      [("sudo find /home -xdev -type f -size +100M", ""), ("sudo find /opt -type f -printf '%s %p\\n' | sort -n | tail -3", "les 3 plus gros")], ["19.3"]),
    C("logger", "logger / journaux", SYS, "Écrire dans le journal système ; les journaux sont dans /var/log.",
      ["logger <message>", "logger -t <étiquette> -p <facility.niveau> <message>"],
      [('logger -t sauvegarde "Sauvegarde terminée"', "avec une étiquette"), ("sudo tail -f /var/log/syslog", "")], ["20.1"]),
    C("grep-f", "Chercher des caractères spéciaux", TEXT, "[ ] . * ont un sens dans un motif : échappez-les, ou cherchez littéralement.",
      ["grep '\\[CRIT\\]' f", "grep -F '[CRIT]' f", "grep -c <motif> f"],
      [("grep -c '^2026-01-10 .*\\[WARN\\]' app.log", "date en début de ligne et niveau"), ("grep -F 'a.b' f", "le point pris à la lettre")], ["20.2", "20.3", "20.4"]),
    C("zgrep", "zgrep / zcat", TEXT, "Lire ou filtrer des journaux compressés sans les décompresser sur le disque.",
      ["zcat <f.gz>", "zgrep <motif> <fichiers>", "zcat -f <fichiers>   (compressés ou non)"],
      [("zgrep -h 'timeout' /var/log/nginx/error.log*", "toutes les versions tournées d'un coup")], ["20.7"]),
    C("authlog", "Analyser auth.log", SEC, "Une tentative de connexion laisse plusieurs lignes : ne comptez qu'un seul type de ligne.",
      ["grep 'Failed password' <journal>", "grep -oE 'from [0-9.]+'", "sort | uniq -c | sort -rn"],
      [("sudo grep 'Accepted' /var/log/auth.log | grep -oE 'for [a-z]+' | sort | uniq -c", "qui s'est connecté, combien de fois")], ["20.6"]),
    C("logrotate", "logrotate", SYS, "Fait tourner les journaux pour qu'ils ne remplissent pas le disque.",
      ["/etc/logrotate.d/<appli>", "logrotate -d <config>   (test à blanc)", "logrotate -f <config>   (rotation forcée)"],
      [("/var/log/exemple/*.log { weekly  rotate 4  missingok }", ""), ("sudo logrotate -d /etc/logrotate.d/exemple", "test à blanc")], ["20.5"]),
    C("logrotate-ouvert", "Rotation d'un journal ouvert", SYS, "Un programme qui garde son journal ouvert écrit toujours dans le fichier renommé.",
      ["copytruncate", "postrotate … endscript", "create <droits> <user> <groupe>"],
      [("postrotate\n    systemctl reload nginx\nendscript", "sur un vrai serveur : demander au service de rouvrir ses journaux")], ["20.8"]),
    C("rsyslog", "rsyslog", SYS, "Ranger les messages selon leur facility et leur niveau, dans des fichiers dédiés.",
      ["/etc/rsyslog.d/<nom>.conf : facility.niveau  destination", "logger -p <facility.niveau> <message>"],
      [("mail.err    /var/log/mail-erreurs.log", "une règle"), ("sudo pkill -x rsyslogd; sudo rsyslogd", "redémarrer rsyslog dans ce conteneur")], ["20.9"]),

    # ── Archives ───────────────────────────────────────────────────────
    C("tar", "tar", ARCH, "Archive un dossier, compressé ou non. c=créer, x=extraire, t=lister, z=gzip, f=fichier.",
      ["tar -czf <archive.tar.gz> <dossier>", "tar -tzf <archive>", "tar -xzf <archive> -C <dest>"],
      [("tar -czf site.tar.gz site/", ""), ("tar -tzvf livraison.tar.gz", "voir le contenu, en détail"),
       ("tar -xzf livraison.tar.gz -C /tmp/verif", "extraire ailleurs")], ["16.1", "16.2", "16.3"]),
    C("tar-plus", "tar : extraire une partie, exclure", ARCH, "Extraire un seul membre (par son chemin exact dans l'archive) ou ignorer des fichiers.",
      ["tar -xzf <archive> <chemin/exact> -C <dest>", "tar -xzOf <archive> <chemin>   (vers la sortie)", "tar -czf <archive> --exclude=<motif> <dossier>"],
      [("tar -tzf photos.tar.gz | grep vacances", "trouver le chemin exact"), ("tar -czf site.tar.gz --exclude='*.tmp' site", "")], ["16.6", "16.9"]),
    C("gzip", "gzip / zcat", ARCH, "Compresse un fichier (remplace l'original, sauf avec -k).",
      ["gzip [-k] <fichier>", "gunzip <fichier.gz>", "zcat <fichier.gz>", "gzip -t <fichier.gz>"], [("gzip -k rapport.txt", "garde l'original")], ["16.4"]),
    C("zip", "zip / unzip", ARCH, "Archive compatible Windows.",
      ["zip -r <archive.zip> <dossier>", "unzip -l <archive.zip>", "unzip <archive.zip> -d <dest>"], [("zip -r cartes.zip cartes", "")], ["16.5"]),
    C("sha256sum", "sha256sum", ARCH, "Empreinte d'un fichier : la moindre modification la change complètement.",
      ["sha256sum <fichier>", "sha256sum -c <liste>"], [("sha256sum image.iso", ""), ("sha256sum -c SHA256SUMS", "vérifier une liste d'empreintes fournie")], ["16.7"]),
    C("file", "file", ARCH, "Identifie le vrai type d'un fichier d'après son contenu, pas son extension.",
      ["file <fichier>..."], [("file /usr/bin/ls photo.jpg", ""), ("file -z archive.gz", "regarde aussi à l'intérieur de la compression")], ["1.6", "16.8"]),

    # ── Scripts et automatisation ──────────────────────────────────────
    C("script", "Script bash", SCRIPT, "Un fichier de commandes : shebang en 1re ligne, puis chmod +x.",
      ["#!/bin/bash", "chmod +x script.sh", "./script.sh"],
      [("#!/bin/bash\necho \"Bonjour\"", "contenu minimal"), ("bash -x script.sh", "exécution pas à pas, pour déboguer")], ["17.1"]),
    C("date", "date", SCRIPT, "Date et heure, dans le format voulu.",
      ["date +<format>"], [("date '+%F %T'", "2026-09-28 14:05:00"), ("date +%d/%m/%Y", "28/09/2026"), ("date +%A", "jour de la semaine")], ["17.2", "25.3"]),
    C("if", "if / test / arguments", SCRIPT, "Conditions, et arguments reçus par le script.",
      ['if [ -e "$1" ]; then ... else ... fi', "$1 $2 … arguments   $# nombre   $0 nom du script   exit 1"],
      [('[ -d "$1" ] || { echo "Usage : $0 dossier" >&2; exit 1; }', "message d'erreur sur la sortie d'erreur"),
       ("-e existe  -f fichier  -d dossier  -z vide", "tests utiles")], ["17.3"]),
    C("guillemets", "Guillemets et espaces", SCRIPT, "Sans guillemets, une variable contenant une espace devient plusieurs arguments.",
      ['"$var"   "$1"   "$@"', 'for f in "$dossier"/*; do …; done'],
      [('cp -- "$f" "$dest/"', "-- : la suite n'est pas une option"), ('touch "mon fichier.txt"', "un seul fichier")], ["17.3", "17.5", "24.8"]),
    C("for", "for", SCRIPT, "Répète des commandes pour chaque élément d'une liste.",
      ["for x in <liste>; do ...; done"],
      [("for i in $(seq 1 3); do echo \"essai $i\"; done", ""), ("for f in *.log; do gzip \"$f\"; done", "")], ["17.4"]),
    C("calcul", "Calculs et printf", SCRIPT, "Calcul entier avec $(( )), mise en forme avec printf.",
      ["n=$(( n + 1 ))", "printf '<format>' <valeurs>", "printf -v <var> '<format>' <valeurs>"],
      [("printf 'lot-%03d\\n' 7", "lot-007"), ("basename /a/b/c.txt", "c.txt")], ["17.6"]),
    C("while-read", "Lire un fichier ligne par ligne", SCRIPT, "while read découpe chaque ligne selon IFS ; awk est souvent plus simple pour additionner.",
      ["while IFS=';' read -r a b; do …; done < fichier", "awk -F';' '{ t[$1] += $2 } END { … }'"],
      [("awk -F: '{ n[$7]++ } END { for (s in n) print s, n[s] }' /etc/passwd", "compter par valeur"), ("sort -k2,2nr", "trier sur la 2e colonne, numérique décroissant")], ["17.7"]),
    C("bash-x", "Déboguer un script", SCRIPT, "bash -x affiche chaque commande, variables remplacées, avant de l'exécuter.",
      ["bash -x script.sh <arguments>", "set -x … set +x   (dans le script)"],
      [("bash -x ./sauvegarde.sh /tmp/test", "les lignes préfixées par + sont celles réellement exécutées")], ["17.8"]),
    C("crontab", "crontab", SCRIPT, "Tâches planifiées d'un utilisateur.",
      ["crontab -l", "crontab -e"], [("*/5 * * * * /usr/local/bin/sonde >> /tmp/sonde.log 2>&1", "toutes les 5 minutes, sortie conservée")], ["18.1"]),
    C("cron", "Syntaxe cron et /etc/cron.d", SCRIPT, "minute heure jour-du-mois mois jour-semaine [utilisateur] commande",
      ["m h dom mon dow commande", "/etc/cron.d : 6e champ = utilisateur", "run-parts --test /etc/cron.daily"],
      [("15 7 * * 1-5", "7h15 en semaine"), ("0 0,12 * * *", "à minuit et à midi"),
       ("30 23 * * * root /usr/local/sbin/purge", "dans /etc/cron.d, chemin absolu"), ("nettoyage-cache", "pas de point dans le nom (run-parts !)")],
      ["18.2", "18.3", "18.4", "25.4"]),
    C("cron-pieges", "Pièges de cron", SCRIPT, "Environnement minimal, sortie perdue, % spécial : ce qui marche dans le terminal peut échouer sous cron.",
      ["grep CRON /var/log/syslog", "… >> /var/log/tache.log 2>&1", "\\%  (dans une ligne de crontab)", "PATH=…  (en tête de crontab)"],
      [("0 6 * * * tar -czf /tmp/sav-$(date +\\%F).tar.gz /srv/site", "% échappé"), ("* * * * * env > /tmp/env-cron.txt", "voir l'environnement de cron")],
      ["18.5", "18.6", "18.7", "24.4"]),
    C("flock", "flock", SCRIPT, "Verrou sur un fichier : empêche deux exécutions simultanées.",
      ["flock -n <verrou> <commande>"], [("flock -n /run/lock/import.lock /usr/local/sbin/import", "abandonne si une instance tourne déjà")], ["18.8"]),
    C("xargs", "xargs", SCRIPT, "Transforme des lignes en arguments pour une commande.",
      ["... | xargs [-r] <commande>"], [("find /tmp -name '*.old' | xargs -r rm -f", "-r : rien si la liste est vide")], ["25.5"]),
    C("nombres", "Comparer des nombres", SCRIPT, "Dans [ ], les nombres se comparent avec -eq -ne -gt -ge -lt -le.",
      ['[ "$a" -gt "$b" ]', "df -P <chemin> | awk 'NR==2 {print $5}'"],
      [('[ "$(nproc)" -ge 4 ] && echo "au moins 4 cœurs"', ""), ("tr -d %", "retirer le signe %")], ["25.6"]),

    # ── Réseau et SSH ──────────────────────────────────────────────────
    C("ip", "ip / hostname", NET, "Adresses et interfaces réseau, nom de la machine.",
      ["ip a", "ip -4 addr show <interface>", "hostname", "hostname -I"], [("ip -4 a", "adresses IPv4 et longueur du préfixe"), ("hostname -I", "adresses IP")], ["21.1"]),
    C("route", "Réseau, préfixe et passerelle", NET, "Préfixe /n : les n premiers bits désignent le réseau ; la route par défaut désigne la passerelle.",
      ["ip route", "adresse du réseau = adresse IP avec les bits machine à 0"],
      [("192.168.50.130/24 → 192.168.50.0/24", ""), ("10.8.3.25/16 → 10.8.0.0/16", "")], ["21.1", "21.2"]),
    C("ss", "ss", NET, "Ports en écoute et connexions.",
      ["ss -tuln", "sudo ss -tulnp", "ss -tn"], [("ss -tln", "ports TCP en écoute"), ("sudo ss -tlnp", "avec le programme"), ("ss -tn", "connexions établies")], ["21.3"]),
    C("ss-p", "Qui utilise ce port ?", NET, "ss et lsof indiquent le programme propriétaire d'un port ou d'une connexion (avec root).",
      ["sudo ss -tlnp 'sport = :<port>'", "sudo ss -tnp", "sudo lsof -i :<port>"],
      [("sudo ss -tnp 'dport = :443'", "connexions sortantes vers le port 443"), ("ps -o user=,comm= -p 4321", "propriétaire et nom d'un PID")], ["21.6", "21.9"]),
    C("ecoute", "Adresse d'écoute", NET, "127.0.0.1 : la machine seule ; 0.0.0.0 : toutes les interfaces.",
      ["ss -tln", "curl http://<adresse>:<port>/"], [("curl -s http://10.0.0.5:8080/", "tester depuis l'adresse réelle, pas seulement localhost")], ["21.7"]),
    C("nc", "nc (netcat)", NET, "Ouvrir une connexion TCP, ou attendre une connexion.",
      ["nc -zv <hôte> <port>", "nc -l <adresse> <port>"], [("nc -zv -w1 intranet 443", "le port répond-il ?"), ("nc -l 127.0.0.1 9000", "attendre une connexion")], ["21.8", "25.8"]),
    C("hosts", "/etc/hosts et DNS", NET, "Résolution de noms : /etc/hosts (local) puis DNS (/etc/resolv.conf).",
      ["getent hosts <nom>", "/etc/hosts : <IP> <nom>"],
      [("echo '10.0.0.12 intranet' | sudo tee -a /etc/hosts", ""), ("getent ahostsv4 intranet", "toutes les adresses obtenues")], ["21.4"]),
    C("resolv", "Serveurs DNS", NET, "/etc/resolv.conf : serveurs interrogés dans l'ordre ; le premier doit répondre.",
      ["/etc/resolv.conf : nameserver <IP>", "time getent hosts <nom>"],
      [("resolvectl status", "sur un vrai Ubuntu (systemd-resolved)"), ("sudo nano /etc/resolv.conf", "dans ce conteneur (sed -i échoue)")], ["21.5"]),
    C("ssh-keygen", "ssh-keygen / ssh-copy-id", NET, "Crée une paire de clés, et installe la clé publique sur un serveur.",
      ["ssh-keygen -t ed25519", "ssh-copy-id <user>@<hôte>", "ssh-keygen -lf <clé.pub>", "ssh-keygen -R <hôte>"],
      [("ssh-keygen -t ed25519 -f ~/.ssh/cle_projet", "une clé dédiée"), ("ssh-copy-id -i ~/.ssh/cle_projet.pub alice@10.0.0.5", "")], ["22.1", "22.2"]),
    C("ssh", "ssh et ~/.ssh/config", NET, "Connexion à distance ; alias dans ~/.ssh/config.",
      ["ssh <user>@<hôte>", "Host <alias> / HostName / User / Port / IdentityFile", "ssh -G <alias>"],
      [("ssh -p 2200 backup@10.0.0.42", ""), ("Host sauvegarde\n    HostName 10.0.0.42\n    User backup\n    Port 2200", "puis : ssh sauvegarde"),
       ("ssh -v sauvegarde", "bavard, pour diagnostiquer")], ["22.3"]),
    C("scp", "scp", NET, "Copie de fichiers via SSH.",
      ["scp <fichier> <user>@<hôte>:<chemin>", "scp -r <dossier> <hôte>:"], [("scp rapport.pdf sauvegarde:", "dans le dossier personnel distant")], ["22.4"]),
    C("sshd", "sshd_config", NET, "Configuration du serveur SSH.",
      ["/etc/ssh/sshd_config", "sudo sshd -t", "sudo sshd -T", "sudo service ssh reload"],
      [("MaxAuthTries 3", ""), ("sudo sshd -t && sudo service ssh reload", "vérifier puis recharger")], ["22.5"]),
    C("sshd-T", "Configuration effective de sshd", NET, "Les fichiers de sshd_config.d sont lus en premier : la première valeur lue l'emporte.",
      ["sudo sshd -T | grep -i <option>", "grep -n Include /etc/ssh/sshd_config", "ls /etc/ssh/sshd_config.d/"],
      [("sudo sshd -T | grep -i x11forwarding", "la valeur réellement appliquée")], ["24.7"]),
    C("authorized-keys", "authorized_keys et ses options", NET, "Une ligne par clé autorisée ; des options peuvent la restreindre.",
      ["[options] <type> <clé> <commentaire>", 'from="…"   command="…"   no-pty   no-port-forwarding'],
      [('from="10.0.0.0/8" ssh-ed25519 AAAA… admin@poste', "clé utilisable seulement depuis ce réseau"), ("man sshd", "section AUTHORIZED_KEYS FILE FORMAT")], ["22.6"]),
    C("ssh-droits", "Droits exigés par SSH", NET, "Client : clé privée en 600. Serveur : ni le dossier personnel, ni ~/.ssh, ni authorized_keys modifiables par d'autres.",
      ["chmod 600 <clé privée>", "chmod 700 ~/.ssh", "chmod 600 ~/.ssh/authorized_keys"],
      [("namei -l /home/alice/.ssh/authorized_keys", "trouver l'élément trop ouvert"), ("sudo tail /var/log/auth.log", "le refus y est expliqué")], ["22.7", "24.3", "25.7"]),
    C("sshd-users", "Qui peut se connecter en SSH", NET, "Liste noire (DenyUsers) ou liste blanche (AllowUsers, qui exclut tous les autres).",
      ["DenyUsers <u1> <u2>", "AllowUsers <u1> <u2>", "DenyGroups / AllowGroups"], [("DenyUsers invite", "dans sshd_config, puis recharger")], ["22.8"]),
    C("known-hosts", "known_hosts et empreintes", NET, "ssh mémorise la clé de chaque serveur ; si elle change, il refuse de se connecter.",
      ["ssh-keygen -lf <clé.pub>", "ssh-keygen -R <hôte>", "ssh-keygen -R '[hôte]:port'"],
      [("ssh-keygen -lf /etc/ssh/ssh_host_ed25519_key.pub", "empreinte d'une clé d'hôte"), ("ssh-keygen -R intranet", "oublier l'ancienne clé, après vérification")], ["24.9"]),

    # ── Sécurité et dépannage ──────────────────────────────────────────
    C("passwd", "passwd / chage", SEC, "Mot de passe, expiration du mot de passe et du compte.",
      ["passwd -l|-u <user>", "passwd -S <user>", "chage -l|-M <jours> <user>", "chage -E <date> <user>"],
      [("sudo passwd -l ancien", "verrouille le mot de passe seulement (pas les clés SSH)"), ("sudo usermod -s /usr/sbin/nologin ancien", "interdit le shell"),
       ("sudo chage -M 60 alice", "changement de mot de passe au moins tous les 60 jours")], ["23.4"]),
    C("desactiver", "Désactiver un compte", SEC, "L'expiration du compte bloque toutes les méthodes de connexion.",
      ["chage -E 0 <user>", "usermod -e 1 <user>", "chage -E -1 <user>   (réactiver)"],
      [("sudo chage -l ancien | grep -i expires", "vérifier"), ("ssh -N -i cle ancien@serveur", "tester aussi sans shell")], ["23.5"]),
    C("audit", "Audit rapide", SEC, "Repérer ce qui est dangereux sur une machine.",
      ["find / -perm -4000 -type f", "find <dossier> -type f -perm -o+w", "dpkg -S <fichier>"],
      [("find / -perm -4000 -type f 2>/dev/null", "exécutables SUID"), ("find /srv -type f -perm -o+w", "modifiables par tous"),
       ("awk -F: '$3 >= 1000 {print $1}' /etc/passwd", "comptes humains")], ["23.1", "23.3"]),
    C("cron-root", "Tâches root détournables", SEC, "Ce que lance root ne doit être modifiable que par root : le fichier et chacun de ses dossiers.",
      ["grep -h root /etc/cron.d/*", "namei -l <chemin>", "find <chemin> -perm /022"],
      [("namei -l /usr/local/sbin/purge", "propriétaire et droits de chaque élément"), ("sudo chmod go-w /opt/outils", "")], ["23.8", "18.2"]),
    C("cles-autorisees", "Clés SSH autorisées", SEC, "Chaque compte, root compris, peut avoir un authorized_keys : c'est la clé qui compte, pas son commentaire.",
      ["sudo find / -xdev -name authorized_keys", "awk '{print $2}' <fichier>"],
      [("sudo grep -rl 'AAAAC3Nz…' /root/.ssh /home/*/.ssh", "où cette clé est-elle autorisée ?")], ["23.9"]),
    C("crlf", "Fins de ligne Windows", SEC, "Un script écrit sous Windows contient des \\r : « bad interpreter ».",
      ["cat -A <fichier>", "file <fichier>", "sed -i 's/\\r$//' <fichier>"], [("cat -A deploy.sh", "^M en fin de ligne = CRLF")], ["24.1"]),
    C("truncate", "truncate", SEC, "Vide un fichier sans le supprimer (le programme qui l'a ouvert continue d'écrire dedans).",
      ["truncate -s 0 <fichier>", ": > <fichier>"], [("sudo truncate -s 0 /var/log/nginx/access.log", "")], ["24.2"]),
    C("namei", "namei", SEC, "Affiche les droits de chaque dossier d'un chemin.",
      ["namei -l <chemin>"], [("namei -l /var/www/site/index.html", "trouver le dossier qui bloque")], ["24.3", "24.6"]),
    C("diag-service", "Diagnostiquer un service", SEC, "Lire chaque message, corriger une cause à la fois, relancer.",
      ["sudo -u <compte> <service> --check", "ls -ld <dossier>", "chown <compte>: <dossier>"],
      [("systemctl status nginx", "sur un vrai serveur"), ("journalctl -u nginx -e", "sur un vrai serveur : son journal")], ["24.5"]),
]
