"""Mémo du parcours Jest : une fiche par notion ou API, débloquée par un exercice."""
from ..linux.memo import C

BASE, MATCH, ORGA, DOUBLES, ASYNC, QUAL = (
    "Bases", "Matchers", "Organisation", "Doublures", "Asynchrone et temps", "Qualité et CI",
)

CARDS = [
    C("test", "test / expect / describe", BASE, "Un test vérifie un comportement avec des assertions ; describe regroupe les tests.",
      ["describe('sujet', () => { ... })", "test('comportement', () => { expect(valeur).matcher(attendu); })"],
      [("test('ajoute la TVA', () => {\n  expect(calculerTTC(100)).toBe(120);\n});", "")], ["J1.1"]),
    C("toBe", "toBe", MATCH, "Égalité stricte (Object.is) : pour les nombres, chaînes, booléens.",
      ["expect(x).toBe(y)", "expect(x).not.toBe(y)"], [("expect(arrondir(1.005)).toBe(1.01);", "")], ["J1.1"]),
    C("toBeCloseTo", "toBeCloseTo", MATCH, "Égalité approchée pour les flottants (2 décimales par défaut).",
      ["expect(x).toBeCloseTo(y, chiffres)"],
      [("expect(0.1 + 0.2).toBeCloseTo(0.3);", ""), ("toBe(23.99)", "si la règle dit « arrondi au centime », préférez la valeur exacte")], ["J1.1"]),
    C("cli", "Lancer Jest", BASE, "Commandes utiles dans le terminal.",
      ["npx jest [chemin]", "npx jest -t 'nom'", "npx jest --watch"],
      [("npx jest tests/prix", "un fichier"), ("npx jest -t TVA", "les tests dont le nom contient TVA"), ("npx jest --watch", "relance à chaque sauvegarde")], ["J1.1"]),
    C("npm-scripts", "Scripts npm", BASE, "Standardiser les commandes de l'équipe dans package.json.",
      ['"scripts": { "test": "jest" }', "npm test", "npm run <script>"],
      [('"test": "jest",\n"test:watch": "jest --watch",\n"test:coverage": "jest --coverage"', "")], ["J1.2"]),
    C("valeurs-limites", "Cas limites", BASE, "Les bugs se cachent aux frontières : testez juste avant, pile sur, juste après.",
      ["règle « < 1 kg » → tester 0,99 · 1 · 1,01"], [("expect(arrondir(1.005)).toBe(1.01);", "le cas piège de l'arrondi")], ["J1.3"]),

    C("toEqual", "toEqual / toStrictEqual", MATCH, "Égalité de structure pour les objets et tableaux.",
      ["expect(obj).toEqual(attendu)", "expect(obj).toStrictEqual(attendu)"],
      [("expect(panier.lignes()).toEqual([{ ref: 'A', libelle: 'Gourde', prixHT: 12.5, quantite: 2 }]);", "")], ["J2.1"]),
    C("toHaveLength", "toHaveLength / toContainEqual", MATCH, "Longueur d'un tableau ; présence d'un élément de structure donnée.",
      ["expect(tab).toHaveLength(n)", "expect(tab).toContainEqual(objet)"], [("expect(panier.lignes()).toHaveLength(1);", "")], ["J2.1"]),
    C("toThrow", "toThrow", MATCH, "Vérifie qu'une fonction lève une erreur (type et/ou message).",
      ["expect(() => fn()).toThrow([Classe | 'message' | /regex/])"],
      [("expect(() => panier.ajouter(g, 0)).toThrow(RangeError);", "on passe une FONCTION à expect"), ("expect(() => retirer('X')).toThrow('absent');", "")], ["J2.2"]),
    C("toMatchObject", "toMatchObject", MATCH, "L'objet contient AU MOINS ces propriétés.",
      ["expect(obj).toMatchObject(partiel)"], [("expect(resultat).toMatchObject({ numero: 'TX-9' });", "")], ["J2.3"]),

    C("each", "test.each", ORGA, "Un même test, exécuté pour chaque ligne d'un tableau de cas.",
      ["test.each([[a, b, attendu], ...])('nom %s', (a, b, attendu) => { ... })"],
      [("test.each([\n  [0.5, 'FR', 4.9],\n  [1, 'FR', 8.9],\n])('%s kg vers %s : %s €', (p, pays, prix) => {\n  expect(fraisLivraison(p, pays)).toBe(prix);\n});", "")], ["J3.1"]),
    C("hooks", "beforeEach / afterEach", ORGA, "Préparer (et nettoyer) un état neuf pour chaque test : les tests restent indépendants.",
      ["beforeEach(() => { ... })", "afterEach", "beforeAll / afterAll"],
      [("let panier;\nbeforeEach(() => {\n  panier = new Panier();\n});", "")], ["J3.2"]),
    C("randomize", "--randomize", ORGA, "Exécute les tests dans un ordre aléatoire : révèle les dépendances cachées entre tests.",
      ["npx jest --randomize", "npx jest --randomize --seed=42"], [("npx jest tests/panier-thomas --randomize", "")], ["J3.2"]),
    C("tdd", "TDD", ORGA, "Red : un test qui échoue. Green : le code minimal qui le fait passer. Refactor : améliorer, tests verts.",
      ["1. Red  2. Green  3. Refactor"], [("validerCode('RANDO10', new Date('2026-06-01'))", "injecter la date rend le test reproductible")], ["J4.1"]),
    C("dates", "Maîtriser la date", ORGA, "Un test ne doit pas dépendre du jour où on le lance.",
      ["passer la date en paramètre", "jest.useFakeTimers({ now: new Date(...) })", "jest.setSystemTime(date)"],
      [("jest.useFakeTimers({ now: new Date('2026-07-14') });\n// ...\njest.useRealTimers();", "")], ["J4.1"]),

    C("fn", "jest.fn", DOUBLES, "Une fonction espionne, dont on contrôle le résultat et dont on inspecte les appels.",
      ["const f = jest.fn()", "jest.fn(implémentation)", "f.mockReturnValue(v) / mockResolvedValue(v) / mockResolvedValueOnce(v)"],
      [("const api = { quantiteDisponible: jest.fn(async (ref) => stocks[ref]) };", "")], ["J5.1"]),
    C("calls", "toHaveBeenCalled…", DOUBLES, "Vérifier comment une doublure a été appelée.",
      ["toHaveBeenCalled()", "toHaveBeenCalledTimes(n)", "toHaveBeenCalledWith(args...)", "not.toHaveBeenCalled()"],
      [("expect(paiement.debiter).toHaveBeenCalledWith('4970-1234', 120);", ""), ("expect(mailer.envoyer).not.toHaveBeenCalled();", "")], ["J5.1"]),
    C("mock", "jest.mock", DOUBLES, "Remplace un module entier : toutes ses fonctions deviennent des jest.fn().",
      ["jest.mock('../src/services/paiement')", "const paiement = require('../src/services/paiement')"],
      [("jest.mock('../src/services/paiement');\npaiement.debiter.mockResolvedValue({ accepte: true, transaction: 'TX-42' });", "")], ["J5.2"]),
    C("clear", "jest.clearAllMocks", DOUBLES, "Remet à zéro les appels enregistrés entre deux tests.",
      ["beforeEach(() => jest.clearAllMocks())", '"clearMocks": true (configuration)'], [("beforeEach(() => jest.clearAllMocks());", "")], ["J5.2"]),

    C("async", "Tests asynchrones", ASYNC, "Un test async attend les promesses ; sans await, il passe toujours.",
      ["test('...', async () => { await ... })", "await expect(p).resolves.toEqual(v)", "await expect(p).rejects.toThrow(msg)"],
      [("await expect(passerCommande(panier, client)).rejects.toThrow('Paiement refusé');", "")], ["J6.1"]),
    C("rejected", "mockRejectedValueOnce", ASYNC, "Simuler une panne (promesse rejetée), une seule fois ou à chaque appel.",
      ["f.mockRejectedValueOnce(erreur)", "f.mockRejectedValue(erreur)"],
      [("paiement.debiter\n  .mockRejectedValueOnce(new Error('Timeout'))\n  .mockResolvedValueOnce({ accepte: true });", "une panne puis un succès")], ["J6.2"]),
    C("timers", "Faux minuteurs", ASYNC, "Faire avancer le temps sans attendre.",
      ["jest.useFakeTimers()", "jest.advanceTimersByTime(ms)", "jest.runAllTimers()", "jest.useRealTimers()"],
      [("jest.advanceTimersByTime(24 * 60 * 60 * 1000 - 1);\nexpect(mailer.envoyer).not.toHaveBeenCalled();", "juste avant le délai")], ["J7.1"]),

    C("coverage", "Couverture de code", QUAL, "Mesure ce que les tests exécutent : lignes, fonctions, branches.",
      ["npx jest --coverage", "--collectCoverageFrom=src/x.js"],
      [("npx jest tests/fidelite --coverage --collectCoverageFrom=src/fidelite.js", ""), ("coverage/lcov-report/index.html", "rapport détaillé")], ["J8.2"]),
    C("threshold", "coverageThreshold", QUAL, "Faire échouer la suite si la couverture descend sous un seuil.",
      ['"jest": { "collectCoverageFrom": [...], "coverageThreshold": { "global": {...} } }'],
      [('"coverageThreshold": { "global": { "branches": 80, "lines": 90 } }', "")], ["J8.1"]),
    C("regression", "Test de non-régression", QUAL, "Reproduire un bug par un test qui échoue, corriger, et garder le test.",
      ["1. test rouge qui montre le bug  2. correction  3. le test reste dans la suite"], [("// bug #218 : le port est dû sous le seuil après remise", "")], ["J9.1"]),
    C("only-skip", ".only / .skip", QUAL, "Focaliser ou désactiver des tests… à ne jamais laisser dans le dépôt.",
      ["test.only / describe.only / fit", "test.skip / xit"], [("grep -rnE '\\.(only|skip)\\(' tests/", "les retrouver")], ["J10.1"]),
    C("ci", "GitHub Actions", QUAL, "Lancer la suite de tests à chaque push et pull request.",
      [".github/workflows/tests.yml"],
      [("on: [push, pull_request]\njobs:\n  tests:\n    runs-on: ubuntu-latest\n    steps:\n      - uses: actions/checkout@v4\n      - uses: actions/setup-node@v4\n        with:\n          node-version: 20\n      - run: npm ci\n      - run: npm test -- --coverage", "")], ["J10.2"]),
]
