"""Mémo du parcours Jest : une fiche par notion ou API, débloquée par un exercice."""
from ..linux.memo import C

BASE, MATCH, ORGA, DOUBLES, ASYNC, QUAL = (
    "Bases", "Matchers", "Organisation", "Doublures", "Asynchrone et temps", "Qualité et CI",
)

CARDS = [
    C("test", "test / expect / describe", BASE, "Un test vérifie un comportement avec des assertions ; describe regroupe les tests.",
      ["describe('sujet', () => { ... })", "test('comportement', () => { expect(valeur).matcher(attendu); })"],
      [("test('ajoute la TVA', () => {\n  expect(calculerTTC(100)).toBe(120);\n});", "")], ["J1.1"]),
    C("toBe", "toBe", MATCH, "Égalité stricte (Object.is) : pour les nombres, chaînes, booléens.",
      ["expect(x).toBe(y)", "expect(x).not.toBe(y)"], [("expect(arrondir(1.005)).toBe(1.01);", "")], ["J1.1"]),
    C("toBeCloseTo", "toBeCloseTo", MATCH, "Égalité approchée pour les flottants (2 décimales par défaut : écart < 0,005).",
      ["expect(x).toBeCloseTo(y, chiffres)"],
      [("expect(0.1 + 0.2).toBeCloseTo(0.3);", ""), ("toBe(23.99)", "si la règle dit « arrondi au centime », préférez la valeur exacte")], ["J1.1"]),
    C("cli", "Lancer Jest", BASE, "Commandes utiles dans le terminal.",
      ["npx jest [chemin]", "npx jest -t 'nom'", "npx jest --watchAll", "npx jest --ci"],
      [("npx jest tests/prix", "les fichiers dont le chemin correspond"), ("npx jest -t TVA", "les tests dont le nom contient TVA"),
       ("npx jest --watchAll", "relance tout à chaque sauvegarde"), ("npx jest --watch", "seulement ce qui a changé depuis le dernier commit : nécessite un dépôt git")], ["J1.1"]),
    C("npm-scripts", "Scripts npm", BASE, "Standardiser les commandes de l'équipe dans package.json.",
      ['"scripts": { "test": "jest" }', "npm test", "npm run <script>", "npm test -- <options de jest>"],
      [('"test": "jest",\n"test:watch": "jest --watchAll",\n"test:ci": "jest --ci"', ""), ("npm test -- -t TVA", "options transmises à jest après --")], ["J1.2"]),
    C("valeurs-limites", "Cas limites", BASE, "Les bugs se cachent aux frontières : testez juste avant, pile sur, juste après.",
      ["règle « < 1 kg » → tester 0,99 · 1 · 1,01"], [("expect(arrondir(1.005)).toBe(1.01);", "le cas piège de l'arrondi")], ["J1.3"]),
    C("test-inutile", "Un test qui peut échouer", BASE, "Un test n'échoue que si un matcher n'est pas satisfait ou si une exception s'échappe.",
      ["expect(x) seul ne vérifie rien", "expect(fn).toThrow sans () ne vérifie rien", "attendu calculé avec le code testé = tautologie"],
      [("expect(appliquerRemise(50, 10)).toBe(45);", "valeur attendue calculée à la main"), ("expect(() => f()).toThrow(RangeError);", "le matcher est appelé")], ["J1.4"]),
    C("flottants", "Nombres flottants", BASE, "Les décimaux sont stockés en binaire : la plupart ne sont qu'approchés.",
      ["(x).toPrecision(20)", "Number.EPSILON : écart entre 1 et le flottant suivant"],
      [("(1.005).toPrecision(20)", "→ '1.0049999999999998934'"), ("0.1 + 0.2", "→ 0.30000000000000004")], ["J1.5"]),

    C("toEqual", "toEqual / toStrictEqual", MATCH, "Égalité de structure pour les objets et tableaux ; toStrictEqual voit aussi les propriétés undefined et la classe.",
      ["expect(obj).toEqual(attendu)", "expect(obj).toStrictEqual(attendu)"],
      [("expect(panier.lignes()).toEqual([{ ref: 'A', libelle: 'Gourde', prixHT: 12.5, quantite: 2 }]);", ""),
       ("expect({ a: 1, b: undefined }).toEqual({ a: 1 });", "passe"), ("expect({ a: 1, b: undefined }).toStrictEqual({ a: 1 });", "échoue")], ["J2.1", "J2.4"]),
    C("toHaveLength", "toHaveLength / toContainEqual", MATCH, "Longueur d'un tableau ; présence d'un élément de structure donnée, quelle que soit sa position.",
      ["expect(tab).toHaveLength(n)", "expect(tab).toContainEqual(objet)"], [("expect(panier.lignes()).toHaveLength(1);", "")], ["J2.1", "J2.5"]),
    C("toThrow", "toThrow", MATCH, "Vérifie qu'une fonction lève une erreur (type et/ou message).",
      ["expect(() => fn()).toThrow([Classe | 'message' | /regex/])"],
      [("expect(() => panier.ajouter(g, 0)).toThrow(RangeError);", "on passe une FONCTION à expect"), ("expect(() => retirer('X')).toThrow('absent');", "")], ["J2.2"]),
    C("toMatchObject", "toMatchObject", MATCH, "L'objet contient AU MOINS ces propriétés (les autres sont ignorées).",
      ["expect(obj).toMatchObject(partiel)"], [("expect(resultat).toMatchObject({ numero: 'TX-9' });", "")], ["J2.3", "J6.2"]),
    C("trop-strict", "Ni trop, ni trop peu", MATCH, "Un test doit échouer quand la règle est violée, et seulement dans ce cas.",
      ["l'ordre n'est pas garanti → ne pas l'imposer", "le texte change → vérifier seulement ce qui compte"],
      [("expect(res).toEqual(expect.arrayContaining([a, b]));\nexpect(res).toHaveLength(2);", "mêmes éléments, dans n'importe quel ordre")], ["J2.5"]),

    C("each", "test.each / describe.each", ORGA, "Un même test (ou un même bloc de tests) exécuté pour chaque ligne d'un tableau de cas.",
      ["test.each([[a, b, attendu], ...])('nom %s', (a, b, attendu) => { ... })", "describe.each([...])('bloc $champ', ({ champ }) => { ... })"],
      [("test.each([\n  [0.5, 'FR', 4.9],\n  [1, 'FR', 8.9],\n])('%s kg vers %s : %s €', (p, pays, prix) => {\n  expect(fraisLivraison(p, pays)).toBe(prix);\n});", "")], ["J3.1"]),
    C("hooks", "beforeEach / afterEach", ORGA, "Préparer (et nettoyer) un état neuf pour chaque test : les tests restent indépendants.",
      ["beforeEach(() => { ... })", "afterEach", "beforeAll / afterAll"],
      [("let panier;\nbeforeEach(() => {\n  panier = new Panier();\n});", "")], ["J3.2"]),
    C("randomize", "--randomize", ORGA, "Exécute les tests dans un ordre aléatoire : révèle les dépendances cachées entre tests.",
      ["npx jest --randomize", "npx jest --randomize --seed=42"], [("npx jest tests/panier-thomas --randomize", ""), ("npx jest -t 'on peut retirer'", "un test seul")], ["J3.2", "J3.3", "J5.4"]),
    C("modules", "jest.resetModules", ORGA, "Repartir d'un registre de modules neuf : l'état stocké dans un module est réinitialisé.",
      ["jest.resetModules()", "jest.isolateModules(() => { ... })"],
      [("let prochainNumero;\nbeforeEach(() => {\n  jest.resetModules();\n  ({ prochainNumero } = require('../src/numerotation'));\n});", "re-require APRÈS la remise à zéro")], ["J3.3"]),
    C("tdd", "TDD", ORGA, "Red : un test qui échoue. Green : le code minimal qui le fait passer. Refactor : améliorer, tests verts.",
      ["1. Red  2. Green  3. Refactor", "spécification modifiée → d'abord les tests"],
      [("validerCode('RANDO10', new Date('2026-06-01T10:00:00'))", "injecter la date rend le test reproductible")], ["J4.1", "J4.2", "J4.3"]),
    C("dates", "Maîtriser la date", ORGA, "Un test ne doit pas dépendre du jour où on le lance.",
      ["passer la date en paramètre", "jest.useFakeTimers({ now: new Date(...) })", "jest.setSystemTime(date)"],
      [("jest.useFakeTimers({ now: new Date('2026-07-14T12:00:00') });\n// ...\njest.useRealTimers();", "")], ["J4.1"]),
    C("fuseaux", "Dates et fuseaux horaires", ORGA, "Une date seule ISO est en UTC ; avec une heure, ou via le constructeur numérique, en heure locale.",
      ["new Date('2026-08-31') → minuit UTC", "new Date('2026-08-31T00:00:00') → minuit local", "new Date(2026, 7, 31) → local, mois à partir de 0"],
      [("new Date(2026, 7, 31, 23, 59, 59, 999)", "dernière milliseconde du 31 août, heure locale"), ("TZ=America/Toronto npx jest", "tester comme sur une machine à Montréal")], ["J4.4"]),
    C("entrees", "Entrées inattendues", ORGA, "Que fait la fonction si on ne lui passe pas ce qu'elle attend ?",
      ["null, undefined, nombre, objet…", "vérifier le type avant de normaliser"],
      [("String(null)", "→ 'NULL' : une chaîne de 4 lettres parfaitement valide !"), ("test.each([null, undefined, 42])('%p est refusé', ...)", "")], ["J4.3"]),

    C("fn", "jest.fn", DOUBLES, "Une fonction espionne, dont on contrôle le résultat et dont on inspecte les appels.",
      ["const f = jest.fn()", "jest.fn(implémentation)", "f.mockReturnValue(v) / mockResolvedValue(v) / mockResolvedValueOnce(v)"],
      [("const api = { quantiteDisponible: jest.fn() };\napi.quantiteDisponible.mockResolvedValue(3);", "la vraie API renvoie une promesse : la doublure aussi")], ["J5.1"]),
    C("calls", "toHaveBeenCalled…", DOUBLES, "Vérifier comment une doublure a été appelée.",
      ["toHaveBeenCalled()", "toHaveBeenCalledTimes(n)", "toHaveBeenCalledWith(args...)", "not.toHaveBeenCalled()"],
      [("expect(paiement.debiter).toHaveBeenCalledWith('4970-1234', 120);", ""), ("expect(mailer.envoyer).not.toHaveBeenCalled();", "")], ["J5.1"]),
    C("mock", "jest.mock", DOUBLES, "Remplace un module entier : toutes ses fonctions deviennent des jest.fn() qui renvoient undefined.",
      ["jest.mock('../src/services/paiement')", "const paiement = require('../src/services/paiement')"],
      [("jest.mock('../src/services/paiement');\npaiement.debiter.mockResolvedValue({ accepte: true, transaction: 'TX-42' });", "programmer le résultat : sinon undefined, même pour une fonction async")], ["J5.2"]),
    C("clear", "clear / reset / restore", DOUBLES, "clear oublie les appels ; reset oublie aussi les valeurs programmées ; restore remet la vraie méthode (spyOn).",
      ["jest.clearAllMocks() · clearMocks", "jest.resetAllMocks() · resetMocks", "jest.restoreAllMocks() · restoreMocks"],
      [("beforeEach(() => {\n  jest.resetAllMocks();\n  paiement.debiter.mockResolvedValue({ accepte: true });\n});", "valeurs par défaut reprogrammées avant CHAQUE test")], ["J5.2", "J5.4"]),
    C("spyOn", "jest.spyOn", DOUBLES, "Espionner (et éventuellement remplacer) une méthode existante d'un objet, puis la remettre en place.",
      ["jest.spyOn(objet, 'methode')", "espion.mockReturnValue(v)", "espion.mockRestore()"],
      [("jest.spyOn(Math, 'random').mockReturnValue(0);", "le hasard devient prévisible"), ("afterEach(() => jest.restoreAllMocks());", "")], ["J5.3"]),
    C("asymetriques", "Matchers à trous", DOUBLES, "Vérifier une valeur sans figer ce qui n'a pas d'importance.",
      ["expect.any(Classe)", "expect.stringContaining(s) / stringMatching(re)", "expect.objectContaining(o) / arrayContaining(t)"],
      [("expect(mailer.envoyer).toHaveBeenCalledWith(\n  'alice@exemple.fr', 'Confirmation de commande', expect.stringContaining('120 €'));", "")], ["J5.5"]),

    C("async", "Tests asynchrones", ASYNC, "Un test async attend les promesses ; une assertion sur une promesse doit être attendue (await) ou renvoyée.",
      ["test('...', async () => { await ... })", "await expect(p).resolves.toEqual(v)", "await expect(p).rejects.toThrow(msg)"],
      [("await expect(passerCommande(panier, client)).rejects.toThrow('Paiement refusé');", "")], ["J5.1", "J6.1"]),
    C("assertions", "expect.assertions", ASYNC, "Faire échouer un test dont les assertions (dans un catch, un .then…) ne se sont pas exécutées.",
      ["expect.assertions(n)", "expect.hasAssertions()"],
      [("expect.assertions(1);\ntry {\n  await f();\n} catch (e) {\n  expect(e.message).toBe('Panier vide');\n}", "")], ["J6.3"]),
    C("rejected", "mockRejectedValueOnce", ASYNC, "Simuler une panne (promesse rejetée), une seule fois ou à chaque appel.",
      ["f.mockRejectedValueOnce(erreur)", "f.mockRejectedValue(erreur)"],
      [("paiement.debiter\n  .mockRejectedValueOnce(new Error('Timeout'))\n  .mockResolvedValueOnce({ accepte: true });", "une panne puis un succès")], ["J6.2"]),
    C("timers", "Faux minuteurs", ASYNC, "Faire avancer le temps sans attendre.",
      ["jest.useFakeTimers()", "jest.advanceTimersByTime(ms)", "jest.runOnlyPendingTimers()", "jest.getTimerCount()", "jest.useRealTimers()"],
      [("jest.advanceTimersByTime(24 * 60 * 60 * 1000 - 1);\nexpect(mailer.envoyer).not.toHaveBeenCalled();", "juste avant le délai")], ["J7.1"]),
    C("timers-async", "Minuteurs et promesses", ASYNC, "Quand le code enchaîne await et setTimeout, faire avancer le temps ET les promesses.",
      ["await jest.advanceTimersByTimeAsync(ms)", "await jest.runAllTimersAsync()"],
      [("const p = debiterPatiemment(banque, carte, 60);\nawait jest.advanceTimersByTimeAsync(1000);\nexpect(banque.debiter).toHaveBeenCalledTimes(2);", "")], ["J7.2"]),

    C("coverage", "Couverture de code", QUAL, "Mesure ce que les tests exécutent : lignes, fonctions, branches.",
      ["npx jest --coverage", "--collectCoverageFrom=src/x.js"],
      [("npx jest tests/fidelite --coverage --collectCoverageFrom=src/fidelite.js", ""), ("coverage/lcov-report/index.html", "rapport détaillé")], ["J8.2"]),
    C("threshold", "coverageThreshold", QUAL, "Faire échouer la suite si la couverture descend sous un seuil, global ou par fichier.",
      ['"coverageThreshold": { "global": {...}, "./src/fichier.js": {...} }'],
      [('"coverageThreshold": {\n  "global": { "branches": 80, "lines": 90 },\n  "./src/prix.js": { "branches": 100 }\n}', "")], ["J8.1"]),
    C("combinaisons", "Combinaisons de règles", QUAL, "100 % de branches ne dit rien de l'ordre des règles : il faut un cas concerné par plusieurs règles à la fois.",
      ["un client gold ET dans son mois d'anniversaire", "un montant proche du plafond ET un bonus"],
      [("expect(pointsFidelite(50, { statut: 'gold', anniversaire: '1990-03-22', dateAchat: '2026-03-10' })).toBe(200);", "et non 300")], ["J8.3"]),
    C("regression", "Test de non-régression", QUAL, "Reproduire un bug par un test qui échoue, corriger, et garder le test.",
      ["1. test rouge qui montre le bug  2. correction  3. le test reste dans la suite"], [("// bug #218 : le port est dû sous le seuil après remise", "")], ["J9.1", "J9.2"]),
    C("failing", "test.failing", QUAL, "Documenter un bug connu : vert tant que le test échoue, rouge dès que le bug est corrigé.",
      ["test.failing('bug #231 : ...', () => { ... })"],
      [("test.failing('bug #231 : deux décimales', () => {\n  expect(ligneComptable(l)).toBe('...;59,40');\n});", "à transformer en test normal une fois corrigé")], ["J9.3"]),
    C("only-skip", ".only / .skip", QUAL, "Focaliser ou désactiver des tests… à ne jamais laisser dans le dépôt. .only n'agit que dans son fichier.",
      ["test.only / describe.only / fit", "test.skip / describe.skip / xit / xdescribe", "combinés : test.only.each, describe.skip.each…"],
      [("grep -rnE '\\b(test|it|describe)(\\.\\w+)*\\.(only|skip)\\b|\\b(fit|xit|xtest|xdescribe|fdescribe)\\(' tests/", "les retrouver")], ["J10.1"]),
    C("config", "jest.config.js", QUAL, "La configuration de Jest dans un fichier à part (jamais en même temps qu'une clé « jest » dans package.json).",
      ["module.exports = { ... }", "resetMocks / restoreMocks / clearMocks"],
      [("module.exports = {\n  collectCoverageFrom: ['src/**/*.js'],\n  resetMocks: true,\n  restoreMocks: true,\n};", "")], ["J10.3"]),
    C("ci", "GitHub Actions", QUAL, "Lancer la suite de tests à chaque push et pull request, sur plusieurs versions de Node.",
      [".github/workflows/tests.yml", "strategy.matrix", "npm ci (exige package-lock.json)"],
      [("on: [push, pull_request]\njobs:\n  tests:\n    runs-on: ubuntu-latest\n    strategy:\n      matrix:\n        node: [22, 24]\n    steps:\n      - uses: actions/checkout@v5\n      - uses: actions/setup-node@v5\n        with:\n          node-version: ${{ matrix.node }}\n      - run: npm ci\n      - run: npm run test:coverage", "")], ["J10.2"]),
    C("snapshot", "toMatchSnapshot", QUAL, "Enregistrer une sortie complexe dans un fichier .snap, puis la comparer à chaque exécution.",
      ["expect(valeur).toMatchSnapshot()", "npx jest -u  (mettre à jour, APRÈS avoir lu le diff)", "--ci : un snapshot absent fait échouer"],
      [("expect(recapitulatif(panier, { pays: 'FR', port: 0 })).toMatchSnapshot();", ""), ("tests/__snapshots__/*.snap", "à versionner et à relire")], ["J11.1", "J11.2"]),
]
