"""QCM de fin de cours du parcours Jest : 8 questions par étape, 4 tirées au sort pour chaque étudiant."""

QUIZ = {
    # ─── Jour 1 : test, expect, toBe, toBeCloseTo, flottants, scripts npm ───
    1: [
        {"q": "Que donne <code>expect(0.1 + 0.2).toBe(0.3)</code> ?",
         "choices": ["Le test passe : Jest arrondit les nombres avant de les comparer",
                     "Le test échoue : la somme vaut en réalité 0.30000000000000004",
                     "Le test passe : <code>toBe</code> tolère un écart inférieur à 0,005",
                     "Le test échoue : <code>toBe</code> ne s'emploie pas sur des nombres"],
         "answer": 1,
         "explain": "0,1 et 0,2 n'ont pas de représentation binaire exacte : leur somme vaut 0.30000000000000004. <code>toBe</code> compare strictement (<code>Object.is</code>), sans aucune tolérance."},
        {"q": "La règle impose un prix TTC arrondi au centime. Un test écrit <code>expect(calculerTTC(p)).toBeCloseTo(23.99)</code> (2 chiffres par défaut). Quel code bogué ce test laisse-t-il passer ?",
         "choices": ["Un code qui renvoie 24, arrondi à l'euro",
                     "Un code qui renvoie 23.98, arrondi vers le bas",
                     "Un code qui renvoie 23.9, arrondi au dixième",
                     "Un code qui renvoie 23.988, pas arrondi du tout"],
         "answer": 3,
         "explain": "Avec 2 chiffres, <code>toBeCloseTo</code> accepte un écart inférieur à 0,005 : 23.988 passe (écart 0,002) alors qu'il n'est pas arrondi. Si la règle impose l'arrondi, on vérifie la valeur arrondie exacte."},
        {"q": "Pourquoi <code>expect(arrondir(x)).toBe(arrondir(x))</code> est-il un mauvais test ?",
         "choices": ["Il compare le code à lui-même : il passe même si le calcul est faux",
                     "Jest interdit d'appeler deux fois la même fonction dans un test",
                     "Il est trop lent, car la fonction est exécutée deux fois",
                     "<code>toBe</code> compare des références : deux appels donnent deux résultats distincts"],
         "answer": 0,
         "explain": "Une valeur attendue se calcule à partir de la règle métier, jamais avec le code testé : sinon, un calcul faux est comparé à lui-même et le test reste vert."},
        {"q": "Un test appelle une fonction qui renvoie un résultat faux sans lever d'exception, mais il ne contient aucun <code>expect</code>. Quel est son résultat ?",
         "choices": ["Il échoue : Jest refuse un test sans assertion",
                     "Il est compté comme « skipped » dans le résumé",
                     "Il passe : aucun matcher n'a échoué et aucune exception ne s'est échappée",
                     "Il échoue au bout de 5 secondes, faute d'assertion"],
         "answer": 2,
         "explain": "Un test n'échoue que si un matcher n'est pas satisfait ou si une exception s'échappe. Sans <code>expect</code>, il est vert quoi que renvoie le code."},
        {"q": "Dans un dossier qui n'est pas un dépôt git, <code>npx jest --watch</code> s'arrête aussitôt avec une erreur. Pourquoi ?",
         "choices": ["<code>--watch</code> ne fonctionne qu'en mode <code>--ci</code>",
                     "<code>--watch</code> demande à git quels fichiers ont changé depuis le dernier commit",
                     "<code>--watch</code> ne fonctionne qu'à l'intérieur d'un script npm",
                     "<code>--watch</code> exige un fichier <code>jest.config.js</code>"],
         "answer": 1,
         "explain": "<code>--watch</code> ne relance que les tests concernés par les fichiers modifiés, et c'est git qui les lui indique. <code>--watchAll</code>, lui, relance toute la suite et n'a pas besoin de git."},
        {"q": "Le script <code>test</code> de <code>package.json</code> vaut <code>jest</code>. Quelle commande ne lance que les tests dont le nom contient « TVA » ?",
         "choices": ["<code>npm test -t TVA</code>",
                     "<code>npm run test TVA</code>",
                     "<code>npm test --name TVA</code>",
                     "<code>npm test -- -t TVA</code>"],
         "answer": 3,
         "explain": "Tout ce qui suit <code>--</code> est transmis au script : Jest reçoit <code>-t TVA</code>. Sans <code>--</code>, les options sont destinées à npm lui-même."},
        {"q": "<code>(1.005).toPrecision(20)</code> affiche 1.00499999999999989… Que renvoie <code>Math.round(1.005 * 100) / 100</code> ?",
         "choices": ["1 : 1,005 est stocké un peu en dessous, et l'arrondi part vers le bas",
                     "1.01 : <code>Math.round</code> arrondit toujours les demi-valeurs vers le haut",
                     "1.005 : <code>Math.round</code> ne touche pas aux décimales",
                     "1.01 : la multiplication par 100 corrige l'erreur de représentation"],
         "answer": 0,
         "explain": "<code>1.005 * 100</code> vaut 100.49999999999999, que <code>Math.round</code> arrondit à 100 : le résultat est 1, et non 1,01 comme l'exige un arrondi commercial."},
        {"q": "<code>calculer()</code> renvoie un nouvel objet <code>{ ht: 10, ttc: 12 }</code>. Que donne <code>expect(calculer()).toBe({ ht: 10, ttc: 12 })</code> ?",
         "choices": ["Il passe : les deux objets ont les mêmes propriétés",
                     "Il échoue seulement si l'ordre des propriétés diffère",
                     "Il échoue : <code>toBe</code> compare l'identité, et ce sont deux objets distincts",
                     "Il passe : <code>toBe</code> et <code>toEqual</code> sont synonymes pour les objets"],
         "answer": 2,
         "explain": "<code>toBe</code> utilise <code>Object.is</code> : deux objets distincts ne sont jamais identiques, même s'ils se ressemblent. Pour comparer une structure, on utilise <code>toEqual</code> ou <code>toStrictEqual</code>."},
    ],
    # ─── Jour 2 : matchers de structure, toThrow, ni trop laxiste ni trop strict ───
    2: [
        {"q": "Que donne <code>expect({ ref: 'A', note: undefined }).toEqual({ ref: 'A' })</code> ?",
         "choices": ["Il passe : <code>toEqual</code> ignore les propriétés qui valent <code>undefined</code>",
                     "Il échoue : l'objet reçu a une propriété de plus",
                     "Il échoue : <code>undefined</code> n'est égal à rien, pas même à lui-même",
                     "Il passe seulement si <code>note</code> est la dernière propriété déclarée"],
         "answer": 0,
         "explain": "<code>toEqual</code> ignore les propriétés valant <code>undefined</code> (et la classe des objets). <code>toStrictEqual</code>, lui, en tiendrait compte."},
        {"q": "Vous voulez vérifier que l'objet renvoyé contient au moins <code>{ statut: 'payee' }</code>, sans vous soucier de ses autres propriétés (date, identifiant…). Quel matcher convient ?",
         "choices": ["<code>toStrictEqual</code>",
                     "<code>toEqual</code>",
                     "<code>toMatchObject</code>",
                     "<code>toContainEqual</code>"],
         "answer": 2,
         "explain": "<code>toMatchObject</code> vérifie la présence et la valeur des propriétés indiquées, et ignore les autres. <code>toEqual</code> et <code>toStrictEqual</code> exigent toute la structure ; <code>toContainEqual</code> cherche un élément dans un tableau."},
        {"q": "<code>panier.ajouter(gourde, 0)</code> lève bien une <code>RangeError</code>. Que donne <code>expect(panier.ajouter(gourde, 0)).toThrow(RangeError)</code> ?",
         "choices": ["Le test passe : l'exception attendue a bien été levée",
                     "Le test échoue : l'exception est levée avant même que <code>expect</code> soit appelé",
                     "Le test passe, mais Jest affiche un avertissement",
                     "Le test est ignoré, car l'exception interrompt le fichier"],
         "answer": 1,
         "explain": "L'argument de <code>expect</code> est évalué d'abord : l'exception s'échappe du test. Il faut passer une fonction : <code>expect(() =&gt; panier.ajouter(gourde, 0)).toThrow(RangeError)</code>."},
        {"q": "Un test vérifie <code>expect(() =&gt; f()).toThrow(Error)</code>. À la suite d'un bug, <code>f</code> lève une <code>TypeError</code> au lieu de la <code>RangeError</code> prévue. Le test…",
         "choices": ["échoue : le type exact de l'erreur doit être <code>Error</code>",
                     "échoue : <code>toThrow</code> n'accepte qu'un message, pas une classe",
                     "passe seulement si le message contient le mot « Error »",
                     "passe : une <code>TypeError</code> est aussi une <code>Error</code>, le bug n'est pas vu"],
         "answer": 3,
         "explain": "<code>toThrow(Classe)</code> vérifie que l'erreur est une instance de la classe : toutes les erreurs héritent d'<code>Error</code>. Pour vérifier le type, on écrit <code>toThrow(RangeError)</code>."},
        {"q": "La règle dit : « <code>lignes()</code> renvoie les lignes du panier, dans un ordre quelconque ». Un test écrit <code>expect(panier.lignes()).toEqual([ligneA, ligneB])</code>. Que lui reprocher ?",
         "choices": ["Il est trop laxiste : <code>toEqual</code> ignore l'ordre des éléments",
                     "Il est trop strict : il casse sur une implémentation correcte qui renvoie B avant A",
                     "Rien : <code>toEqual</code> vérifie à la fois le contenu et la longueur",
                     "Il ne fonctionne pas : <code>toEqual</code> n'accepte pas de tableau"],
         "answer": 1,
         "explain": "<code>toEqual</code> compare les tableaux élément par élément, donc dans l'ordre. La règle ne garantit pas l'ordre : le test fige un détail et cassera sur un code correct."},
        {"q": "Que donne <code>expect('Gourde').toHaveLength(6)</code> ?",
         "choices": ["Il échoue : <code>toHaveLength</code> ne s'applique qu'aux tableaux",
                     "Il échoue : une chaîne de caractères n'a pas de longueur",
                     "Il passe : <code>toHaveLength</code> vérifie aussi la longueur d'une chaîne",
                     "Il passe seulement avec <code>toHaveLength('6')</code>"],
         "answer": 2,
         "explain": "<code>toHaveLength</code> lit la propriété <code>length</code> : elle existe pour les tableaux comme pour les chaînes. « Gourde » compte 6 caractères."},
        {"q": "<code>total()</code> renvoie toujours un nombre, juste ou faux. Laquelle de ces assertions ne détectera jamais un total faux ?",
         "choices": ["<code>expect(total()).toBe(42)</code>",
                     "<code>expect(total()).toBeCloseTo(42)</code>",
                     "<code>expect(total()).not.toBe(0)</code>",
                     "<code>expect(typeof total()).not.toBe('string')</code>"],
         "answer": 3,
         "explain": "Si <code>total()</code> renvoie toujours un nombre, son type n'est jamais <code>'string'</code> : l'assertion est toujours satisfaite et ne vérifie aucune valeur."},
        {"q": "<code>lignes</code> vaut <code>[{ ref: 'A', quantite: 2, prixHT: 10 }]</code>. Que donne <code>expect(lignes).toContainEqual({ ref: 'A', quantite: 2 })</code> ?",
         "choices": ["Il échoue : l'élément du tableau a une propriété <code>prixHT</code> en plus",
                     "Il passe : <code>toContainEqual</code> cherche un élément qui contient au moins ces propriétés",
                     "Il passe : <code>toContainEqual</code> ne compare que la propriété <code>ref</code>",
                     "Il échoue : <code>toContainEqual</code> exige un tableau d'une seule ligne"],
         "answer": 0,
         "explain": "<code>toContainEqual</code> cherche un élément <strong>égal</strong> (au sens de <code>toEqual</code>) à celui fourni : la propriété <code>prixHT</code> en plus empêche l'égalité."},
    ],
    # ─── Jour 3 : test.each, valeurs limites, isolation, état d'un module ───
    3: [
        {"q": "Règle : « livraison offerte pour une commande de <em>plus de</em> 50 € ». Le code écrit <code>montant &gt;= 50</code>. Quel cas de test révèle ce bug ?",
         "choices": ["Une commande de 49,99 €",
                     "Une commande de 50,01 €",
                     "Une commande de 50 € pile",
                     "Une commande de 100 €"],
         "answer": 2,
         "explain": "Un <code>&gt;</code> écrit <code>&gt;=</code> ne change le résultat que sur la limite exacte : à 50 €, la règle refuse la livraison offerte, le code l'accorde."},
        {"q": "Un fichier crée le panier dans <code>beforeAll</code>, et chaque test y ajoute des articles. Quel symptôme est typique ?",
         "choices": ["Les tests passent dans l'ordre écrit, mais échouent avec <code>--randomize</code> ou lancés seuls",
                     "Jest refuse de lancer un fichier qui contient <code>beforeAll</code>",
                     "Aucun : chaque test reçoit automatiquement un panier neuf",
                     "Les tests s'exécutent en parallèle et se bloquent mutuellement"],
         "answer": 0,
         "explain": "<code>beforeAll</code> crée un seul panier partagé : chaque test hérite de ce qu'ont laissé les précédents. <code>beforeEach</code> en crée un neuf avant chaque test."},
        {"q": "Combien de tests génère <code>test.each([[0.99, 5], [1, 7], [1.01, 7]])('%s kg : %s €', (poids, prix) =&gt; { … })</code> ?",
         "choices": ["1 test, qui fait trois vérifications",
                     "2 tests : la première ligne sert d'en-tête",
                     "6 tests, un par valeur du tableau",
                     "3 tests, un par ligne du tableau"],
         "answer": 3,
         "explain": "<code>test.each</code> génère un test par ligne ; chaque ligne fournit les arguments de la fonction et remplit les <code>%s</code> du nom."},
        {"q": "Avec <code>--randomize</code>, un test échoue une fois sur trois. Comment rejouer exactement l'ordre qui a échoué ?",
         "choices": ["Relancer <code>npx jest --randomize</code> jusqu'à retomber sur l'échec",
                     "<code>npx jest --randomize --seed=</code> suivi de la graine affichée lors de l'échec",
                     "<code>npx jest --watchAll</code>, qui conserve le dernier ordre utilisé",
                     "<code>npx jest -t</code> suivi du nom du test qui a échoué"],
         "answer": 1,
         "explain": "Jest affiche la graine utilisée pour mélanger ; la même graine redonne le même ordre. Lancer le test seul avec <code>-t</code> ne reproduit pas l'ordre qui l'a fait échouer."},
        {"q": "<code>src/compteur.js</code> déclare <code>let n = 0</code> au niveau du module et exporte <code>suivant()</code>, qui renvoie <code>++n</code>. Deux tests du même fichier attendent chacun que <code>suivant()</code> renvoie 1. Résultat ?",
         "choices": ["Le second test exécuté échoue : le module, mis en cache par <code>require</code>, garde <code>n</code>",
                     "Les deux passent : Jest recharge chaque module avant chaque test",
                     "Les deux passent : <code>beforeEach</code> remet les modules à zéro automatiquement",
                     "Les deux échouent : une variable de module est interdite dans un code testé"],
         "answer": 0,
         "explain": "Un module n'est chargé qu'une fois : sa variable est partagée par tous les tests du fichier. Le premier test obtient 1, le second 2."},
        {"q": "Quelle est la différence entre <code>test.each</code> et <code>describe.each</code> ?",
         "choices": ["<code>describe.each</code> exécute les lignes en parallèle, <code>test.each</code> en série",
                     "<code>test.each</code> accepte des objets, <code>describe.each</code> seulement des tableaux",
                     "<code>describe.each</code> génère un bloc de tests par ligne, <code>test.each</code> un seul test par ligne",
                     "Aucune : ce sont deux noms du même mécanisme"],
         "answer": 2,
         "explain": "Les deux acceptent le même tableau ; <code>describe.each</code> crée un bloc <code>describe</code> par ligne, dans lequel on peut écrire plusieurs tests (par exemple un bloc par pays)."},
        {"q": "Quel est le nom du test généré par <code>test.each([{ poids: 2, pays: 'BE' }])('$poids kg vers $pays', …)</code> ?",
         "choices": ["« $poids kg vers $pays »",
                     "« %s kg vers %s »",
                     "« test.each 0 »",
                     "« 2 kg vers BE »"],
         "answer": 3,
         "explain": "Avec des lignes objets, <code>$propriété</code> dans le nom est remplacé par la valeur correspondante de la ligne."},
        {"q": "Règle : « tarif réduit pour un colis de moins de 1 kg ». D'après l'analyse des valeurs limites vue en cours, quels poids faut-il tester ? (plusieurs réponses possibles)",
         "choices": ["0,99 kg",
                     "1 kg",
                     "1,01 kg",
                     "10 kg"],
         "answer": [0, 1, 2],
         "explain": "Juste en dessous, pile sur la limite et juste au-dessus : c'est là que se cachent les erreurs de comparaison. 10 kg ne teste aucune frontière de cette règle."},
    ],
    # ─── Jour 4 : TDD, dates, fuseaux horaires, faux minuteurs ───
    4: [
        {"q": "En TDD, que fait-on juste après avoir écrit un test qui échoue ?",
         "choices": ["On refactore le code existant, tests au rouge",
                     "On écrit le code le plus simple qui le fait passer",
                     "On écrit tous les autres tests de la spécification",
                     "On mesure la couverture de code du module"],
         "answer": 1,
         "explain": "Red, Green, Refactor : après le test rouge vient le code le plus simple qui le rend vert ; on n'améliore le code qu'une fois les tests au vert."},
        {"q": "Sur une machine réglée sur l'heure de Montréal (UTC−4 en été), que renvoie <code>new Date('2026-08-31').getDate()</code> ?",
         "choices": ["31 : une date seule est toujours lue en heure locale",
                     "1 : la date est décalée au lendemain",
                     "0 : <code>getDate</code> numérote les jours à partir de 0",
                     "30 : minuit UTC correspond au 30 août à 20 h à Montréal"],
         "answer": 3,
         "explain": "Une date seule au format ISO désigne minuit UTC ; <code>getDate</code> donne le jour en heure locale, soit le 30 août à 20 h à Montréal."},
        {"q": "Quel instant représente <code>new Date(2026, 8, 31)</code> ?",
         "choices": ["Le 1er octobre 2026 : 8 désigne septembre, qui n'a que 30 jours",
                     "Le 31 août 2026 : les mois sont numérotés à partir de 1",
                     "Aucun : le 31 septembre n'existe pas, une exception est levée",
                     "Le 31 août 2026 à minuit UTC"],
         "answer": 0,
         "explain": "Les mois sont numérotés à partir de 0 : 8 est septembre. Le 31 septembre n'existant pas, JavaScript déborde sur le 1er octobre, sans erreur."},
        {"q": "Un test appelle <code>validerCode('ETE30')</code> sans lui passer de date et sans figer l'horloge ; ce code expire le 31 août 2030. Que se passera-t-il ?",
         "choices": ["Il passera toujours : Jest fige l'horloge par défaut",
                     "Il échouera dès aujourd'hui : un test sans date est refusé",
                     "Il passe aujourd'hui, et échouera à partir du 1er septembre 2030 sans que rien n'ait changé",
                     "Il échouera seulement dans la CI, réglée sur UTC"],
         "answer": 2,
         "explain": "Le code lit la date réelle : le résultat du test dépend du jour où il est lancé. On injecte la date ou on fige l'horloge."},
        {"q": "Quelle écriture désigne le même instant sur toutes les machines, quel que soit leur fuseau horaire ?",
         "choices": ["<code>new Date('2026-08-31T00:00:00')</code>",
                     "<code>new Date('2026-08-31T00:00:00Z')</code>",
                     "<code>new Date(2026, 7, 31, 0, 0)</code>",
                     "<code>new Date('2026-08-31T00:00')</code>"],
         "answer": 1,
         "explain": "Le <code>Z</code> impose l'UTC. Une date-heure ISO sans <code>Z</code>, comme les arguments numériques, est lue en heure locale : l'instant dépend du fuseau de la machine."},
        {"q": "Après <code>jest.useFakeTimers({ now: new Date('2030-06-01T10:00:00') })</code>, que renvoie <code>new Date()</code> dans le code testé ?",
         "choices": ["La date réelle : seuls <code>setTimeout</code> et <code>setInterval</code> sont simulés",
                     "Une date invalide, tant que l'horloge n'a pas avancé",
                     "Le 1er janvier 1970, point de départ des faux minuteurs",
                     "Le 1er juin 2030 à 10 h (heure locale) : l'horloge est figée"],
         "answer": 3,
         "explain": "Les faux minuteurs simulent aussi la date : <code>new Date()</code> et <code>Date.now()</code> partent de l'instant <code>now</code> fourni."},
        {"q": "Pourquoi faut-il voir un test échouer (étape Red) avant d'écrire le code ?",
         "choices": ["Pour prouver qu'il vérifie bien le comportement manquant, et qu'il peut échouer",
                     "Parce que Jest refuse d'exécuter un test qui passe du premier coup",
                     "Pour mesurer la couverture de code avant l'implémentation",
                     "Pour que Jest l'enregistre comme test de non-régression"],
         "answer": 0,
         "explain": "Un test jamais vu rouge ne prouve rien : il pourrait passer quoi que fasse le code. Le voir échouer, puis passer grâce au code, montre qu'il teste vraiment le comportement."},
        {"q": "Un code promo est à la fois expiré et utilisé sous le montant minimum. Pourquoi écrire un test pour ce cas précis ?",
         "choices": ["Pour atteindre le nombre de tests exigé par la CI",
                     "Pour vérifier que la fonction lève une exception dans ce cas",
                     "Pour vérifier quelle raison de refus l'emporte, comme la spécification l'impose",
                     "Pour tester deux règles en un seul test et gagner du temps"],
         "answer": 2,
         "explain": "Les priorités entre règles font partie de la spécification : seul un cas concerné par deux règles à la fois montre laquelle l'emporte."},
    ],
    # ─── Jour 5 : jest.fn, jest.mock, jest.spyOn, matchers asymétriques ───
    5: [
        {"q": "Après <code>jest.mock('../src/services/paiement')</code>, sans rien programmer, le code exécute <code>const r = await paiement.debiter(…); if (r.accepte) …</code>. Que se passe-t-il ?",
         "choices": ["Le vrai module est appelé, car <code>debiter</code> est <code>async</code>",
                     "<code>r</code> vaut <code>{ accepte: false }</code>, valeur par défaut des doublures",
                     "Une <code>TypeError</code> : <code>debiter</code> renvoie <code>undefined</code>, qui n'a pas de propriété <code>accepte</code>",
                     "Le test attend la promesse indéfiniment, puis échoue au bout de 5 s"],
         "answer": 2,
         "explain": "<code>jest.mock</code> remplace chaque fonction exportée par un <code>jest.fn()</code> qui renvoie <code>undefined</code>, même si l'originale était <code>async</code> : c'est au test de programmer le résultat."},
        {"q": "<code>api.lire</code> (une doublure) a été appelée avec <code>'A'</code>, puis avec <code>'B'</code>. Que donne <code>expect(api.lire).toHaveBeenCalledWith('A')</code> ?",
         "choices": ["Il passe : il suffit qu'un des appels corresponde",
                     "Il échoue : seul le dernier appel est comparé",
                     "Il échoue : la doublure a été appelée deux fois",
                     "Il passe seulement si tous les appels ont reçu <code>'A'</code>"],
         "answer": 0,
         "explain": "<code>toHaveBeenCalledWith</code> réussit si au moins un appel a reçu ces arguments. Pour compter les appels, on ajoute <code>toHaveBeenCalledTimes</code>."},
        {"q": "Après <code>api.lire.mockResolvedValue(5); api.lire.mockResolvedValueOnce(0);</code>, que renvoient les trois premiers appels à <code>api.lire</code> ?",
         "choices": ["Des promesses de 5, puis 0, puis 5",
                     "Une promesse de 0, puis <code>undefined</code> deux fois",
                     "Les nombres 0, 5 et 5, sans promesse",
                     "Des promesses de 0, puis 5, puis 5"],
         "answer": 3,
         "explain": "Une valeur « Once » est utilisée en priorité, une seule fois ; ensuite, la doublure revient à la valeur programmée par <code>mockResolvedValue</code>."},
        {"q": "La vraie <code>api.lire</code> renvoie une promesse, et le code écrit <code>api.lire(ref).then(q =&gt; …)</code>. Quelle doublure ne respecte pas ce contrat et fait planter le code ?",
         "choices": ["<code>jest.fn().mockResolvedValue(3)</code>",
                     "<code>jest.fn().mockReturnValue(3)</code>",
                     "<code>jest.fn(async () =&gt; 3)</code>",
                     "<code>jest.fn().mockImplementation(() =&gt; Promise.resolve(3))</code>"],
         "answer": 1,
         "explain": "<code>mockReturnValue(3)</code> renvoie le nombre 3, qui n'a pas de méthode <code>then</code>. Les trois autres renvoient une promesse de 3, comme la vraie fonction."},
        {"q": "<code>const espion = jest.spyOn(outils, 'formater');</code> sans autre instruction. Que se passe-t-il quand le code appelle <code>outils.formater</code> ?",
         "choices": ["La vraie méthode s'exécute, et l'appel est enregistré",
                     "L'appel renvoie <code>undefined</code>, comme avec <code>jest.mock</code>",
                     "L'appel lève une erreur tant qu'aucune valeur n'est programmée",
                     "La vraie méthode s'exécute, mais l'appel n'est pas enregistré"],
         "answer": 0,
         "explain": "Par défaut, <code>jest.spyOn</code> garde le vrai comportement tout en enregistrant les appels ; <code>mockReturnValue</code> ou <code>mockImplementation</code> le remplacent."},
        {"q": "<code>api.enregistrer</code> a été appelée avec <code>{ ref: 'A', quantite: 3, date: … }</code>. Que donne <code>expect(api.enregistrer).toHaveBeenCalledWith(expect.objectContaining({ ref: 'A' }))</code> ?",
         "choices": ["Il échoue : l'objet reçu a des propriétés en plus",
                     "Il échoue : <code>objectContaining</code> ne s'utilise que dans <code>toEqual</code>",
                     "Il passe : l'argument contient au moins <code>ref: 'A'</code>",
                     "Il passe seulement si <code>date</code> est aussi précisée"],
         "answer": 2,
         "explain": "<code>expect.objectContaining</code> est un matcher à trous : il accepte tout objet qui contient au moins ces propriétés, et s'emploie partout où une valeur est attendue."},
        {"q": "Dans un fichier de test, <code>jest.mock('../src/services/mailer')</code> est écrit après <code>const commande = require('../src/commande')</code>. <code>commande.js</code> utilise-t-il la doublure ?",
         "choices": ["Non : <code>commande.js</code> a déjà chargé le vrai mailer",
                     "Oui : Jest remonte les appels à <code>jest.mock</code> en haut du fichier, avant les <code>require</code>",
                     "Non : <code>jest.mock</code> doit être appelé dans <code>beforeEach</code>",
                     "Oui, mais seulement pour les tests écrits après la ligne <code>jest.mock</code>"],
         "answer": 1,
         "explain": "Jest remonte les appels à <code>jest.mock</code> en tête du fichier : le remplacement est en place avant tout <code>require</code>, quel que soit l'endroit où on l'écrit."},
        {"q": "Un test vérifie <code>expect(mailer.envoyer).toHaveBeenCalledWith(expect.any(String), 'Commande confirmée', expect.any(String))</code>. Quel défaut ne détecte-t-il pas ?",
         "choices": ["Un sujet différent de « Commande confirmée »",
                     "Un e-mail qui n'est jamais envoyé",
                     "Un e-mail envoyé sans corps (deux arguments seulement)",
                     "Un e-mail envoyé à la mauvaise adresse"],
         "answer": 3,
         "explain": "<code>expect.any(String)</code> accepte n'importe quelle chaîne : une mauvaise adresse passe inaperçue. Un matcher à trous ne doit laisser libre que ce qui ne fait pas partie de la règle."},
    ],
    # ─── Jour 6 : promesses rejetées, expect.assertions, pannes simulées ───
    6: [
        {"q": "<code>test('refus', () =&gt; { expect(passerCommande(p, c)).rejects.toThrow('refusé'); });</code> Suite à un bug, <code>passerCommande</code> réussit. Que risque-t-on ?",
         "choices": ["Rien : le test échoue immédiatement, avec un message clair",
                     "Le test se termine avant la promesse : il peut rester vert sans avoir rien vérifié",
                     "Rien : Jest attend automatiquement toutes les promesses créées dans le test",
                     "Le test est compté comme « skipped », faute de <code>await</code>"],
         "answer": 1,
         "explain": "Une assertion sur une promesse doit être attendue (<code>await</code>) ou renvoyée (<code>return</code>) ; sinon le test se termine avant elle et son échec passe inaperçu ou apparaît ailleurs."},
        {"q": "<pre>test('refus', async () =&gt; {<br>  try { await passerCommande(p, c); }<br>  catch (e) { expect(e.message).toBe('Paiement refusé'); }<br>});</pre>Suite à un bug, <code>passerCommande</code> ne lève plus d'erreur. Que se passe-t-il ?",
         "choices": ["Il devient rouge : Jest signale que le <code>catch</code> n'a pas été exécuté",
                     "Il devient rouge : une fonction <code>async</code> doit utiliser <code>rejects</code>",
                     "Il reste vert, et c'est normal : aucune erreur n'a eu lieu",
                     "Il reste vert sans rien vérifier ; <code>expect.assertions(1)</code> en tête l'aurait fait échouer"],
         "answer": 3,
         "explain": "Sans erreur, le <code>catch</code> n'est jamais exécuté : aucune assertion, donc test vert. <code>expect.assertions(1)</code> exige qu'une assertion ait bien été exécutée."},
        {"q": "<code>debiter</code> est un <code>jest.fn()</code> programmé par <code>.mockRejectedValueOnce(new Error('Timeout')).mockResolvedValueOnce({ accepte: true })</code>. Que renvoie son 3<sup>e</sup> appel ?",
         "choices": ["<code>undefined</code> : les deux valeurs « Once » sont consommées, rien d'autre n'est programmé",
                     "Une promesse rejetée par « Timeout » : la liste recommence au début",
                     "Une promesse de <code>{ accepte: true }</code> : la dernière valeur est répétée",
                     "Une erreur de Jest : il y a plus d'appels que de valeurs programmées"],
         "answer": 0,
         "explain": "Chaque valeur « Once » ne sert qu'une fois. Une fois épuisées, la doublure revient à son comportement par défaut : ici, renvoyer <code>undefined</code>."},
        {"q": "Dans un test de chemin d'erreur, pourquoi vérifier <code>expect(mailer.envoyer).not.toHaveBeenCalled()</code> <em>après</em> <code>await expect(…).rejects…</code>, et pas avant ?",
         "choices": ["Parce que <code>not.toHaveBeenCalled</code> ne fonctionne que dans un test déclaré <code>async</code>",
                     "Parce qu'avant, la doublure n'a pas encore été créée par <code>jest.mock</code>",
                     "Parce qu'avant la fin de l'opération, l'e-mail n'est peut-être pas encore parti",
                     "Parce que Jest exécute les assertions d'un test dans l'ordre inverse de l'écriture"],
         "answer": 2,
         "explain": "L'absence d'effet de bord ne se constate qu'une fois l'opération terminée ; vérifiée trop tôt, elle est toujours vraie."},
        {"q": "<code>expect.assertions(2)</code> est en tête d'un test qui exécute 3 assertions, toutes satisfaites. Résultat ?",
         "choices": ["Vert : au moins 2 assertions ont été exécutées",
                     "Rouge : exactement 2 assertions étaient attendues",
                     "Vert : <code>expect.assertions</code> ne compte que les assertions asynchrones",
                     "Rouge : <code>expect.assertions</code> doit être la dernière instruction du test"],
         "answer": 1,
         "explain": "<code>expect.assertions(n)</code> exige exactement <code>n</code> assertions exécutées. Pour « au moins une », on utilise <code>expect.hasAssertions()</code>."},
        {"q": "Quelle est la différence entre <code>expect.hasAssertions()</code> et <code>expect.assertions(1)</code> ?",
         "choices": ["<code>hasAssertions</code> vérifie que chaque assertion a réussi, <code>assertions(1)</code> les compte",
                     "Aucune : ce sont deux écritures du même contrôle",
                     "<code>hasAssertions</code> exige au moins une assertion exécutée, <code>assertions(1)</code> exactement une",
                     "<code>hasAssertions</code> ne s'applique qu'aux tests synchrones"],
         "answer": 2,
         "explain": "Les deux font échouer un test qui n'a exécuté aucune assertion ; <code>assertions(1)</code> échoue aussi s'il en a exécuté plus d'une."},
        {"q": "La promesse <code>p</code> est rejetée par <code>new Error('Paiement refusé : carte expirée')</code>. Que donne <code>await expect(p).rejects.toThrow('Paiement refusé')</code> ?",
         "choices": ["Il échoue : le message doit être exactement identique",
                     "Il échoue : <code>rejects</code> n'accepte que des classes d'erreur",
                     "Il passe seulement avec <code>toThrow(Error)</code>",
                     "Il passe : une chaîne passée à <code>toThrow</code> doit seulement figurer dans le message"],
         "answer": 3,
         "explain": "Avec une chaîne, <code>toThrow</code> vérifie que le message de l'erreur la contient. Le motif « carte expirée » peut donc suivre sans faire échouer le test."},
        {"q": "Lesquels de ces tests attendent correctement la promesse avant de se terminer ? (plusieurs réponses possibles)",
         "choices": ["<code>test('x', () =&gt; { return expect(p()).rejects.toThrow('refusé'); })</code>",
                     "<code>test('x', async () =&gt; { await expect(p()).rejects.toThrow('refusé'); })</code>",
                     "<code>test('x', () =&gt; { expect(p()).rejects.toThrow('refusé'); })</code>",
                     "<code>test('x', async () =&gt; { expect(p()).rejects.toThrow('refusé'); })</code>"],
         "answer": [0, 1],
         "explain": "Il faut renvoyer l'assertion (<code>return</code>) ou l'attendre (<code>await</code>). Déclarer le test <code>async</code> ne suffit pas : sans <code>await</code>, il se termine avant l'assertion."},
    ],
    # ─── Jour 7 : faux minuteurs ───
    7: [
        {"q": "Avec les faux minuteurs : <code>setTimeout(rappel, 1000)</code>, puis <code>jest.advanceTimersByTime(999)</code>. Combien de fois <code>rappel</code> a-t-il été appelé ?",
         "choices": ["0 fois : le délai n'est pas encore atteint",
                     "1 fois : Jest arrondit les délais à la seconde",
                     "1 fois : <code>advanceTimersByTime</code> exécute tous les minuteurs",
                     "1 fois : un minuteur se déclenche dès que le temps avance"],
         "answer": 0,
         "explain": "<code>advanceTimersByTime</code> n'exécute que les minuteurs arrivés à échéance : il manque 1 ms. C'est exactement ce que vérifie un test de limite « juste avant »."},
        {"q": "Avec les faux minuteurs : <code>setInterval(tic, 1000)</code>, puis <code>jest.advanceTimersByTime(3500)</code>. Combien de fois <code>tic</code> a-t-il été appelé ?",
         "choices": ["1 fois : un minuteur ne s'exécute qu'une fois",
                     "4 fois : les 3 500 ms sont arrondies à 4 000",
                     "3 fois : à 1 000, 2 000 et 3 000 ms",
                     "0 fois : <code>setInterval</code> n'est pas simulé"],
         "answer": 2,
         "explain": "Un <code>setInterval</code> se déclenche à chaque période écoulée : 3 périodes complètes tiennent dans 3 500 ms."},
        {"q": "Pourquoi <code>jest.runAllTimers()</code> pose-t-il problème avec un code qui utilise <code>setInterval</code> ?",
         "choices": ["Parce que <code>runAllTimers</code> n'exécute que les <code>setTimeout</code>",
                     "Parce qu'un <code>setInterval</code> se reprogramme sans fin : il ne reste jamais « plus rien » à exécuter",
                     "Parce que <code>runAllTimers</code> attend les vrais délais",
                     "Parce que <code>runAllTimers</code> remet l'horloge à zéro avant de commencer"],
         "answer": 1,
         "explain": "<code>runAllTimers</code> exécute tout jusqu'à ce qu'il ne reste aucun minuteur : un <code>setInterval</code> en recrée toujours un, d'où une boucle sans fin (que Jest interrompt en erreur)."},
        {"q": "Une relance programmée par <code>setTimeout</code> vient d'être annulée. Quel contrôle montre qu'aucun minuteur n'est resté en attente ?",
         "choices": ["<code>jest.runOnlyPendingTimers()</code> renvoie <code>false</code>",
                     "<code>expect(setTimeout).not.toHaveBeenCalled()</code>",
                     "<code>jest.useRealTimers()</code> ne lève pas d'erreur",
                     "<code>expect(jest.getTimerCount()).toBe(0)</code>"],
         "answer": 3,
         "explain": "<code>jest.getTimerCount()</code> donne le nombre de minuteurs en attente. Avancer ensuite le temps et vérifier que rien n'est envoyé complète utilement ce contrôle."},
        {"q": "Un minuteur, en s'exécutant, programme un nouveau <code>setTimeout</code>. Que fait <code>jest.runOnlyPendingTimers()</code> ?",
         "choices": ["Il exécute le minuteur en attente, mais pas celui qu'il vient de créer",
                     "Il exécute les deux minuteurs, l'un après l'autre",
                     "Il n'exécute rien : un minuteur qui en crée un autre est ignoré",
                     "Il boucle jusqu'à ce qu'il ne reste plus aucun minuteur"],
         "answer": 0,
         "explain": "<code>runOnlyPendingTimers</code> exécute les minuteurs déjà en attente au moment de l'appel, pas ceux qu'ils créent : pratique pour avancer d'un cran dans une chaîne de minuteurs."},
        {"q": "Pourquoi appeler <code>jest.useRealTimers()</code> dans un <code>afterEach</code> ?",
         "choices": ["Pour que Jest affiche la durée réelle de chaque test",
                     "Pour exécuter les minuteurs restés en attente",
                     "Pour que les tests suivants du fichier ne tournent pas, à leur insu, avec une fausse horloge",
                     "Parce que les faux minuteurs empêchent Jest de passer au fichier suivant"],
         "answer": 2,
         "explain": "Les faux minuteurs restent actifs jusqu'à ce qu'on les retire : un test qui ne s'y attend pas verrait le temps figé."},
        {"q": "Une relance doit partir exactement 24 h après l'abandon du panier. Quelle séquence de test est la plus probante ?",
         "choices": ["Avancer de 48 h, puis vérifier qu'un e-mail est parti",
                     "Avancer de 24 h moins 1 ms : aucun e-mail ; puis de 1 ms : un e-mail",
                     "Avancer de 24 h, puis vérifier qu'un e-mail est parti",
                     "Appeler <code>runAllTimers</code>, puis vérifier qu'un e-mail est parti"],
         "answer": 1,
         "explain": "Seul un test de part et d'autre de la limite exacte détecte un délai faux, même de peu ; les autres acceptent une relance partie trop tôt."},
        {"q": "Sans faux minuteurs ni configuration particulière, un test <code>async</code> attend (<code>await</code>) une promesse résolue par un vrai <code>setTimeout</code> de 10 s. Que se passe-t-il ?",
         "choices": ["Il passe, mais lentement",
                     "Il passe vite : Jest accélère automatiquement les minuteurs",
                     "Il est ignoré par Jest",
                     "Il échoue : Jest l'interrompt au bout de 5 s par défaut"],
         "answer": 3,
         "explain": "Par défaut, Jest arrête un test qui dure plus de 5 s. Les faux minuteurs permettent de tester des délais de plusieurs jours sans attendre."},
    ],
    # ─── Jour 8 : couverture de code ───
    8: [
        {"q": "<pre>function frais(m) {<br>  let f = 5;<br>  if (m &gt; 50) f = 0;<br>  return f;<br>}</pre>Seul test : <code>frais(100)</code>. Quelle couverture obtient-on ?",
         "choices": ["100 % des lignes et 100 % des branches",
                     "50 % des lignes et 50 % des branches",
                     "100 % des lignes, mais 50 % des branches",
                     "100 % des branches, mais 75 % des lignes"],
         "answer": 2,
         "explain": "Toutes les lignes sont exécutées, mais le <code>if</code> n'est jamais faux : une de ses deux sorties n'est pas couverte."},
        {"q": "Un fichier atteint 100 % de couverture, mais aucun de ses tests ne contient d'<code>expect</code>. Que prouve cette couverture ?",
         "choices": ["Seulement que le code a été exécuté : aucun résultat n'a été vérifié",
                     "Que le code est correct, puisque tout s'est exécuté sans erreur",
                     "Rien : Jest ne mesure pas la couverture d'un test sans <code>expect</code>",
                     "Que toutes les branches sont justes, les lignes restant à vérifier"],
         "answer": 0,
         "explain": "La couverture mesure ce qui est exécuté, pas ce qui est vérifié : elle montre ce qui n'est pas testé, jamais que le code est juste."},
        {"q": "Un projet a une clé <code>jest</code> dans <code>package.json</code> et un fichier <code>jest.config.js</code>. Que fait Jest ?",
         "choices": ["Il fusionne les deux configurations",
                     "Il utilise <code>jest.config.js</code> et ignore <code>package.json</code>",
                     "Il utilise <code>package.json</code>, prioritaire",
                     "Il refuse de démarrer : une seule configuration à la fois"],
         "answer": 3,
         "explain": "Jest détecte plusieurs configurations et s'arrête en erreur : la configuration va soit dans <code>package.json</code>, soit dans <code>jest.config.js</code>."},
        {"q": "<code>coverageThreshold.global.branches</code> vaut 80, et la suite n'atteint que 78 % de branches, tous les tests étant verts. Que fait <code>jest --coverage</code> ?",
         "choices": ["Il réussit, en affichant un simple avertissement",
                     "Il échoue : un seuil non atteint fait échouer la commande, et la CI bloque",
                     "Il réussit, car les seuils ne s'appliquent qu'aux fichiers modifiés",
                     "Il relance les tests jusqu'à atteindre le seuil"],
         "answer": 1,
         "explain": "Un seuil non atteint fait échouer <code>jest --coverage</code> même si tous les tests passent : c'est ce qui permet à la CI de refuser la fusion."},
        {"q": "Pourquoi indiquer <code>collectCoverageFrom: ['src/**/*.js']</code> dans la configuration ?",
         "choices": ["Pour que les fichiers qu'aucun test ne charge figurent aussi au rapport, à 0 %",
                     "Pour que Jest cherche les fichiers de test dans le dossier <code>src/</code>",
                     "Pour exclure les fichiers de <code>src/</code> de la mesure de couverture",
                     "Pour accélérer les tests en ne chargeant que les fichiers de <code>src/</code>"],
         "answer": 0,
         "explain": "Sans cette option, seuls les fichiers chargés par un test sont mesurés : un module sans aucun test n'apparaît pas et ne fait pas baisser la couverture."},
        {"q": "Où lire rapidement les numéros des lignes qu'aucun test n'a exécutées ?",
         "choices": ["Dans le fichier <code>.snap</code> du fichier de test",
                     "Dans <code>package.json</code>, sous <code>coverageThreshold</code>",
                     "Dans la colonne <em>Uncovered Line #s</em> du tableau affiché par <code>--coverage</code>",
                     "Dans la sortie de <code>npx jest --verbose</code>, sans couverture"],
         "answer": 2,
         "explain": "Le tableau de couverture du terminal liste, pour chaque fichier, les lignes jamais exécutées ; le rapport HTML de <code>coverage/lcov-report</code> les surligne."},
        {"q": "Deux règles de prix : une remise de 10 % s'applique à certaines commandes, <em>puis</em> 5 € de frais s'ajoutent à certaines commandes. Quel cas de test peut révéler une inversion de l'ordre de ces deux règles ?",
         "choices": ["Une commande sans remise ni frais",
                     "Une commande avec remise, mais sans frais",
                     "Une commande avec frais, mais sans remise",
                     "Une commande avec remise et frais"],
         "answer": 3,
         "explain": "L'ordre des règles ne se voit que sur un cas concerné par les deux à la fois : (x × 0,9) + 5 ≠ (x + 5) × 0,9. Chaque règle seule donne le même résultat dans les deux ordres."},
        {"q": "Dans un rapport de couverture, la colonne <em>Functions</em> vaut 80 %. Qu'est-ce que cela signifie ?",
         "choices": ["80 % des lignes situées dans des fonctions sont exécutées",
                     "20 % des fonctions ne sont appelées par aucun test",
                     "80 % des fonctions ont au moins un <code>expect</code>",
                     "80 % des fonctions renvoient le bon résultat"],
         "answer": 1,
         "explain": "<em>Functions</em> compte les fonctions appelées au moins une fois pendant les tests. Rien ne dit que leurs résultats ont été vérifiés."},
    ],
    # ─── Jour 9 : reproduire un bug, non-régression, test.failing ───
    9: [
        {"q": "Un bug est signalé. Dans quel ordre travailler ?",
         "choices": ["Corriger le code, puis écrire un test qui passe",
                     "Écrire un test qui échoue et montre le bug, corriger, puis garder le test",
                     "Corriger le code, lancer la suite, puis supprimer le test du bug",
                     "Désactiver les tests concernés, corriger, puis les réactiver"],
         "answer": 1,
         "explain": "Reproduire, corriger, garder : le test rouge prouve qu'on a compris le bug, il passe au vert avec la correction, et reste pour empêcher le bug de revenir."},
        {"q": "Bug soupçonné : le code écrit <code>poids &lt;= 2</code> au lieu de <code>poids &lt; 2</code>. Quel test de reproduction convient ?",
         "choices": ["Un colis de 1 kg",
                     "Un colis de 5 kg",
                     "Un colis de 0,5 kg",
                     "Un colis de 2 kg pile"],
         "answer": 3,
         "explain": "Les deux comparaisons ne diffèrent que pour 2 kg exactement : c'est la seule valeur qui distingue le bon comportement du mauvais."},
        {"q": "Un test marqué <code>test.failing</code> voit un jour son assertion réussir, parce que le bug a été corrigé. Que se passe-t-il ?",
         "choices": ["Il devient rouge, pour signaler qu'il faut en faire un test normal",
                     "Il reste vert, sans rien signaler",
                     "Jest le transforme automatiquement en test normal",
                     "Il est compté comme « skipped »"],
         "answer": 0,
         "explain": "Un test <code>.failing</code> est vert tant que son contenu échoue, et devient rouge dès qu'il passe : la suite prévient que le bug est corrigé."},
        {"q": "Un test censé reproduire un bug passe du premier coup, sur la version boguée. Que faut-il en conclure ?",
         "choices": ["Le bug a déjà été corrigé en production",
                     "Le test est bon : un test doit toujours passer",
                     "Il ne reproduit pas le bug : ses données ne distinguent pas le bon comportement du mauvais",
                     "Jest a gardé un ancien résultat en cache : il faut relancer"],
         "answer": 2,
         "explain": "Un test de reproduction doit échouer sur la version boguée. Sur beaucoup de valeurs, bon et mauvais code donnent le même résultat : il faut en choisir une qui les sépare."},
        {"q": "Le bug est corrigé et le test de reproduction est vert. Pourquoi le garder ?",
         "choices": ["Pour augmenter la couverture de code jusqu'au seuil",
                     "Pour que la CI signale le bug s'il revient un jour : c'est un test de non-régression",
                     "Parce que Jest refuse de supprimer un test qui a déjà échoué",
                     "Pour dater la correction dans le rapport de tests"],
         "answer": 1,
         "explain": "Un bug corrigé peut revenir lors d'une modification ultérieure ; le test de non-régression le détectera aussitôt."},
        {"q": "Pendant le débogage, comment ne lancer que le test dont le nom contient « #218 » ?",
         "choices": ["<code>npx jest -t '#218'</code>",
                     "<code>npx jest --only '#218'</code>",
                     "<code>npx jest tests/#218</code>",
                     "<code>npx jest --seed=218</code>"],
         "answer": 0,
         "explain": "<code>-t</code> filtre les tests d'après leur nom. Un chemin filtre des fichiers, et <code>--seed</code> fixe l'ordre de <code>--randomize</code>."},
        {"q": "Comment obtenir la valeur attendue d'un test de reproduction ?",
         "choices": ["En copiant ce que renvoie le code actuel",
                     "En copiant ce que renvoyait le code avant l'apparition du bug",
                     "En utilisant <code>toBeCloseTo</code> avec une large tolérance",
                     "En la calculant à la main, à partir de la règle métier"],
         "answer": 3,
         "explain": "Le code actuel est bogué, et l'ancien l'était peut-être aussi : seule la règle métier dit ce qui est juste."},
        {"q": "Que devient un <code>console.log</code> placé dans le code testé, pendant l'exécution de Jest ?",
         "choices": ["Jest le supprime pour ne pas polluer la sortie",
                     "Il fait échouer le test qui l'exécute",
                     "Il s'affiche dans la sortie de Jest, avec le fichier et la ligne d'origine",
                     "Il ne s'affiche qu'avec l'option <code>--coverage</code>"],
         "answer": 2,
         "explain": "Jest affiche les sorties de <code>console.log</code> en indiquant d'où elles viennent : un outil de débogage simple, à retirer ensuite."},
    ],
    # ─── Jour 10 : .only/.skip, configuration, intégration continue ───
    10: [
        {"q": "Dans <code>a.test.js</code>, un test est marqué <code>test.only</code> ; <code>b.test.js</code> n'a rien de particulier. Que lance <code>npx jest</code> ?",
         "choices": ["Le test <code>.only</code> de <code>a.test.js</code>, et tous les tests de <code>b.test.js</code>",
                     "Uniquement le test <code>.only</code>, dans toute la suite",
                     "Tous les tests : <code>.only</code> n'agit qu'avec <code>--watch</code>",
                     "Aucun test de <code>a.test.js</code> : <code>.only</code> désactive le fichier"],
         "answer": 0,
         "explain": "<code>.only</code> agit dans le fichier qui le contient : les autres tests de ce fichier sont ignorés (« skipped »), les autres fichiers s'exécutent normalement."},
        {"q": "Le résumé de Jest affiche <code>Tests: 3 skipped, 40 passed</code>. Qu'en conclure ?",
         "choices": ["Tout va bien : les 43 tests ont été exécutés avec succès",
                     "3 tests ont échoué, mais Jest ne les compte pas comme des échecs",
                     "3 tests n'ont pas été exécutés : à vérifier avant de fusionner",
                     "3 tests ont été exécutés trois fois chacun"],
         "answer": 2,
         "explain": "Un test « skipped » n'a pas tourné : il ne protège de rien. C'est souvent la trace d'un <code>.only</code> ou d'un <code>.skip</code> oublié."},
        {"q": "Que faut-il versionner dans git ? (plusieurs réponses possibles)",
         "choices": ["<code>package.json</code>",
                     "<code>package-lock.json</code>",
                     "<code>node_modules/</code>",
                     "<code>.github/workflows/tests.yml</code>"],
         "answer": [0, 1, 3],
         "explain": "<code>package-lock.json</code> fige les versions exactes pour tous ; <code>node_modules</code> se réinstalle à partir de lui et va dans <code>.gitignore</code>. Le workflow fait partie du code du projet."},
        {"q": "<pre>strategy:<br>  matrix:<br>    os: [ubuntu-latest, windows-latest]<br>    node: [22, 24]</pre>Combien de fois ce job est-il exécuté ?",
         "choices": ["2 fois : une par système",
                     "1 fois : la matrice ne sert qu'à l'affichage",
                     "6 fois : 2 + 2 × 2",
                     "4 fois : une par combinaison système × version"],
         "answer": 3,
         "explain": "Une matrice produit toutes les combinaisons de ses dimensions : 2 systèmes × 2 versions de Node = 4 exécutions."},
        {"q": "Une recherche de <code>.skip(</code> dans <code>tests/</code> ne trouve rien. Peut-on affirmer qu'aucun test n'est désactivé ?",
         "choices": ["Non : <code>xit</code>, <code>xdescribe</code> ou <code>describe.skip.each</code> désactivent aussi des tests",
                     "Oui : <code>.skip(</code> est la seule façon de désactiver un test",
                     "Oui, si le résumé affiche 0 test en échec",
                     "Non, mais seulement quand <code>--randomize</code> est utilisé"],
         "answer": 0,
         "explain": "Les modificateurs ont plusieurs formes (<code>xit</code>, <code>xtest</code>, <code>xdescribe</code>) et se combinent (<code>describe.skip.each</code>) : une recherche trop étroite en oublie."},
        {"q": "Dans <code>jest.config.js</code>, à quoi équivaut <code>clearMocks: true</code> ?",
         "choices": ["À appeler <code>jest.restoreAllMocks()</code> après chaque test",
                     "À appeler <code>jest.resetModules()</code> avant chaque test",
                     "À appeler <code>jest.clearAllMocks()</code> avant chaque test",
                     "À supprimer tous les <code>jest.mock</code> des fichiers de test"],
         "answer": 2,
         "explain": "<code>clearMocks</code> efface automatiquement les appels enregistrés de toutes les doublures avant chaque test, comme <code>jest.clearAllMocks()</code>."},
        {"q": "Où s'exécute un workflow GitHub Actions qui déclare <code>runs-on: ubuntu-latest</code> ?",
         "choices": ["Sur le poste du développeur qui a poussé le code",
                     "Sur un serveur de GitHub, dans une machine neuve à chaque exécution",
                     "Sur le serveur de production de l'entreprise",
                     "Dans le navigateur, à l'ouverture de la pull request"],
         "answer": 1,
         "explain": "GitHub fournit une machine vierge pour chaque exécution : rien ne dépend du poste d'un développeur, d'où l'intérêt d'une installation reproductible."},
        {"q": "Dans un workflow, que se passerait-il sans l'étape <code>uses: actions/checkout@v5</code> ?",
         "choices": ["Node ne serait pas installé",
                     "Les dépendances seraient installées globalement",
                     "Les tests seraient lancés sur la branche main",
                     "Le code du dépôt ne serait pas présent sur la machine"],
         "answer": 3,
         "explain": "La machine démarre vide : <code>actions/checkout</code> y récupère le code du dépôt. Node est installé par <code>actions/setup-node</code>."},
    ],
    # ─── Jour 11 : snapshots ───
    11: [
        {"q": "Premier lancement d'un test <code>toMatchSnapshot()</code>, hors CI, sans fichier <code>.snap</code>. Que se passe-t-il ?",
         "choices": ["Le test échoue : aucune référence n'existe encore",
                     "Jest enregistre le snapshot, et le test passe",
                     "Jest demande de confirmer le contenu à l'écran",
                     "Le test est ignoré tant que le fichier n'est pas créé à la main"],
         "answer": 1,
         "explain": "Au premier lancement, Jest écrit le snapshot dans <code>__snapshots__/</code> ; les lancements suivants comparent la sortie à ce contenu."},
        {"q": "Même situation, mais Jest est lancé avec <code>--ci</code> : aucun fichier <code>.snap</code> n'existe. Que se passe-t-il ?",
         "choices": ["Jest crée le snapshot, et le test passe",
                     "Le test est ignoré",
                     "Jest reprend le snapshot d'un autre test",
                     "Le test échoue : en mode <code>--ci</code>, un snapshot absent n'est pas créé"],
         "answer": 3,
         "explain": "En CI, créer un snapshot reviendrait à accepter sans relecture n'importe quelle sortie : Jest fait donc échouer le test."},
        {"q": "Un snapshot a été enregistré alors que le code contenait un bug. Que devient le test ?",
         "choices": ["Il passe, et continuera de passer : il protège désormais le bug",
                     "Il échoue, car Jest compare aussi au code de référence",
                     "Il passe une fois, puis échoue",
                     "Il échoue dès que le fichier <code>.snap</code> est versionné"],
         "answer": 0,
         "explain": "Un snapshot fige le comportement du moment, bugs compris : il faut le relire à l'enregistrement comme à chaque mise à jour."},
        {"q": "Une modification voulue fait échouer un snapshot. Quelle est la bonne démarche ?",
         "choices": ["Supprimer le fichier <code>.snap</code>, puis relancer toute la suite de tests",
                     "Lancer <code>npx jest -u</code> tout de suite, puis versionner le <code>.snap</code>",
                     "Lire le diff, vérifier qu'il ne montre que le changement voulu, puis lancer <code>npx jest -u</code>",
                     "Remplacer <code>toMatchSnapshot</code> par <code>toEqual</code> sur la nouvelle sortie"],
         "answer": 2,
         "explain": "<code>-u</code> réécrit les snapshots sans discernement : mettre à jour sans lire le diff, c'est risquer de valider un bug."},
        {"q": "L'objet figé par <code>toMatchSnapshot()</code> contient une propriété <code>date</code> : un objet <code>Date</code> créé au moment de la génération. Conséquence ?",
         "choices": ["Aucune : Jest ignore les objets <code>Date</code> dans les snapshots",
                     "Le test échoue aux exécutions suivantes ; <code>expect.any(Date)</code> y remédie",
                     "Jest recrée automatiquement le snapshot à chaque exécution",
                     "Le test passe le jour de l'enregistrement, puis Jest l'ignore"],
         "answer": 1,
         "explain": "La date change à chaque exécution, donc la comparaison échoue. Un matcher à trous fige le type de la valeur sans figer la valeur elle-même."},
        {"q": "Un récapitulatif de commande est figé avec un panier d'un seul article, en quantité 1. Quelle erreur ce snapshot ne verra-t-il pas ?",
         "choices": ["Un total qui oublierait de multiplier le prix par la quantité",
                     "Un changement du libellé de l'article",
                     "Un caractère ajouté dans l'en-tête",
                     "Un prix unitaire affiché avec un mauvais séparateur décimal"],
         "answer": 0,
         "explain": "Avec une quantité de 1, prix × quantité = prix : l'oubli de la multiplication ne change pas la sortie. Un snapshot ne vérifie que ce que les données rendent visible."},
        {"q": "Que faire du fichier <code>.snap</code> ?",
         "choices": ["Rien : il est régénéré à chaque exécution",
                     "L'ajouter au <code>.gitignore</code>, comme <code>node_modules</code>",
                     "Le laisser à la CI, qui est seule à le lire",
                     "Le versionner et le relire en revue de code, comme le reste du code"],
         "answer": 3,
         "explain": "Le <code>.snap</code> contient les valeurs attendues des tests : il fait partie du code, se versionne et se relit."},
        {"q": "Pourquoi préférer plusieurs petits snapshots ciblés à un seul snapshot énorme ?",
         "choices": ["Parce que Jest limite la taille d'un snapshot",
                     "Parce qu'un gros snapshot ne peut pas être mis à jour avec <code>-u</code>",
                     "Parce qu'un diff court se relit vraiment, alors qu'un énorme finit accepté sans lecture",
                     "Parce que les petits snapshots s'exécutent en parallèle"],
         "answer": 2,
         "explain": "Un snapshot n'a de valeur que s'il est relu : un par situation significative rend chaque diff lisible et chaque règle visible."},
    ],
}
