"""QCM de fin de module du parcours Réseau : 8 questions par module, 4 tirées au sort pour chaque étudiant."""

QUIZ = {
    # ─────────────────────────────────────────────────────────────────────
    1: [
        {"q": "Quelle affirmation est vraie ?",
         "choices": ["L'adresse MAC est fixée en usine sur la carte réseau ; l'adresse IP est choisie selon le réseau où la machine est branchée",
                     "L'adresse IP est fixée en usine ; l'adresse MAC est choisie par l'administrateur",
                     "Les deux sont choisies par l'administrateur",
                     "Une machine n'a qu'une seule de ces deux adresses"],
         "answer": 0,
         "explain": "La MAC identifie la carte (comme un numéro de série) ; l'IP dépend du réseau, comme une adresse postale."},
        {"q": "À quel masque correspond le préfixe <code>/24</code> ?",
         "choices": ["<code>255.0.0.0</code>", "<code>255.255.0.0</code>", "<code>255.255.255.0</code>", "<code>255.255.255.240</code>"],
         "answer": 2,
         "explain": "/24 : les 24 premiers bits, soit les trois premiers nombres, désignent le réseau."},
        {"q": "Une machine porte <code>192.168.10.30/28</code>. Pour elle, <code>192.168.10.11</code> est…",
         "choices": ["sur son réseau, puisque les trois premiers nombres sont identiques",
                     "sur un autre réseau : en /28, son réseau ne va que de .16 à .31",
                     "sa propre adresse",
                     "une adresse invalide"],
         "answer": 1,
         "explain": "En /28, un réseau compte 16 adresses ; celui de .30 va de .16 à .31. C'est le masque de la machine qui décide, pas l'habitude du /24."},
        {"q": "<code>ping 192.168.10.50</code> répond <code>Destination Host Unreachable</code>. Que peut-on en conclure ?",
         "choices": ["L'adresse n'est pas sur mon réseau",
                     "L'adresse est sur mon réseau, mais aucune machine ne répond pour elle",
                     "La machine répond, mais lentement",
                     "Le switch est en panne, forcément"],
         "answer": 1,
         "explain": "Personne n'a répondu à la requête ARP : machine éteinte, câble débranché, interface DOWN ou sans adresse… Un switch en panne n'est qu'une des causes possibles."},
        {"q": "On tape <code>ip addr add 192.168.10.12/24 dev eth0</code>, puis la machine redémarre. Que devient l'adresse ?",
         "choices": ["Elle est conservée : ip enregistre ses réglages",
                     "Elle est perdue, sauf si elle figure aussi dans la configuration de démarrage (<code>/etc/network/interfaces</code>)",
                     "Elle est remplacée par une adresse au hasard",
                     "Elle est conservée, mais l'interface redémarre éteinte"],
         "answer": 1,
         "explain": "ip ne modifie que la configuration en cours, en mémoire. Ce qui doit survivre au redémarrage s'écrit dans le fichier."},
        {"q": "Une caisse ne répond « qu'une fois sur deux » depuis qu'un portable a été branché, et <code>arping</code> montre deux MAC différentes pour l'adresse de la caisse. De quoi s'agit-il ?",
         "choices": ["D'un câble défectueux", "D'un masque trop petit sur la caisse", "D'un conflit d'adresses IP", "D'un switch saturé"],
         "answer": 2,
         "explain": "Deux machines répondent pour la même IP : les autres envoient leurs messages tantôt à l'une, tantôt à l'autre."},
        {"q": "Sur une interface qui porte <code>192.168.10.30/28</code>, on tape <code>ip addr add 192.168.10.30/24 dev eth0</code>. Que porte maintenant l'interface ?",
         "choices": ["Seulement 192.168.10.30/24 : la nouvelle adresse remplace l'ancienne",
                     "Les deux adresses",
                     "Seulement 192.168.10.30/28 : la commande est refusée",
                     "Aucune adresse : les deux s'annulent"],
         "answer": 1,
         "explain": "Une interface peut porter plusieurs adresses : il faut retirer la mauvaise avec ip addr del, puis vérifier avec ip a."},
        {"q": "Dans <code>/etc/network/interfaces</code>, à quoi sert la ligne <code>auto eth0</code> ?",
         "choices": ["À donner une adresse automatique à eth0",
                     "À activer eth0 au démarrage, avec la configuration décrite par sa ligne iface",
                     "À détecter automatiquement le masque",
                     "À rien : c'est un commentaire"],
         "answer": 1,
         "explain": "Sans auto, la configuration existe mais n'est appliquée qu'à la demande (ifup eth0). Une adresse automatique, c'est DHCP : inet dhcp."},
    ],
}
