"""QCM de fin de module du parcours Réseau : 6 à 8 questions par module, 4 tirées au sort pour chaque étudiant."""

QUIZ = {
    # ─────────────────────────────────────────────────────────────────────
    1: [
        {"q": "L'invite affiche <code>root@poste1:~#</code>. Où êtes-vous ?",
         "choices": ["Sur la console, avec le compte etudiant", "Sur poste1, avec le compte root (administrateur)",
                     "Sur poste1, avec un compte ordinaire", "Sur le switch"],
         "answer": 1,
         "explain": "Avant @ : le compte (root) ; après @ : la machine (poste1). Le # final rappelle qu'on est administrateur."},
        {"q": "Que signifie le <code>~</code> dans l'invite <code>etudiant@console:~$</code> ?",
         "choices": ["Une erreur de la commande précédente", "Le dossier personnel du compte", "La racine du disque", "Une machine inconnue"],
         "answer": 1,
         "explain": "~ est le raccourci du dossier personnel : /home/etudiant pour etudiant, /root pour root."},
        {"q": "Dans nano, comment enregistrer le fichier ?",
         "choices": ["Ctrl+S", "Ctrl+O, puis Entrée", "Échap, puis :w", "Ctrl+X directement : nano enregistre toujours tout seul"],
         "answer": 1,
         "explain": "Ctrl+O (Write Out) enregistre, Entrée confirme le nom ; Ctrl+X quitte, en demandant d'enregistrer si besoin."},
        {"q": "Un <code>ping</code> lancé sans <code>-c</code> ne s'arrête plus. Que faire ?",
         "choices": ["Fermer l'onglet du navigateur", "Ctrl+C", "Taper exit", "Attendre : il s'arrête au bout d'une heure"],
         "answer": 1,
         "explain": "Ctrl+C interrompt la commande en cours et rend la main, sans fermer le terminal."},
        {"q": "Vous tapez <code>echo \"Camille\" &gt; signature.txt</code> dans l'onglet console. Où le fichier est-il créé ?",
         "choices": ["Sur poste1", "Sur toutes les machines", "Sur la console", "Nulle part : il faut d'abord ouvrir nano"],
         "answer": 2,
         "explain": "Une commande agit sur la machine de l'invite. Pour créer le fichier sur poste1, il faut d'abord passer sur poste1."},
        {"q": "À quoi sert la touche <strong>↑</strong> (flèche du haut) dans le terminal ?",
         "choices": ["À remonter dans le fichier ouvert", "À rappeler les commandes précédentes", "À changer de machine", "À agrandir le texte"],
         "answer": 1,
         "explain": "L'historique : on rappelle une commande pour la relancer ou la corriger, sans tout retaper."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    2: [
        {"q": "Quelle affirmation est vraie ?",
         "choices": ["L'adresse MAC est fixée en usine sur la carte réseau ; l'adresse IP est choisie selon le réseau où la machine est branchée",
                     "L'adresse IP est fixée en usine ; l'adresse MAC est choisie par l'administrateur",
                     "Les deux sont choisies par l'administrateur",
                     "Une machine n'a qu'une seule de ces deux adresses"],
         "answer": 0,
         "explain": "La MAC identifie la carte (comme un numéro de série) ; l'IP dépend du réseau, comme une adresse postale."},
        {"q": "À quel masque correspond le préfixe <code>/24</code> ?",
         "choices": ["<code>255.0.0.0</code>", "<code>255.255.0.0</code>", "<code>255.255.255.0</code>", "<code>255.255.255.240</code>"],
         "answer": 2,
         "explain": "/24 : les 24 premiers bits, soit les trois premiers nombres, désignent le réseau."},
        {"q": "Une machine porte <code>192.168.10.30/28</code>. Pour elle, <code>192.168.10.11</code> est…",
         "choices": ["sur son réseau, puisque les trois premiers nombres sont identiques",
                     "sur un autre réseau : en /28, son réseau ne va que de .16 à .31",
                     "sa propre adresse",
                     "une adresse invalide"],
         "answer": 1,
         "explain": "En /28, un réseau compte 16 adresses ; celui de .30 va de .16 à .31. C'est le masque de la machine qui décide, pas l'habitude du /24."},
        {"q": "<code>ping 192.168.10.50</code> répond <code>Destination Host Unreachable</code>. Que peut-on en conclure ?",
         "choices": ["L'adresse n'est pas sur mon réseau",
                     "L'adresse est sur mon réseau, mais aucune machine ne répond pour elle",
                     "La machine répond, mais lentement",
                     "Le switch est en panne, forcément"],
         "answer": 1,
         "explain": "Personne n'a répondu à la requête ARP : machine éteinte, câble débranché, interface DOWN ou sans adresse… Un switch en panne n'est qu'une des causes possibles."},
        {"q": "On tape <code>ip addr add 192.168.10.12/24 dev eth0</code>, puis la machine redémarre. Que devient l'adresse ?",
         "choices": ["Elle est conservée : ip enregistre ses réglages",
                     "Elle est perdue, sauf si elle figure aussi dans la configuration de démarrage (<code>/etc/network/interfaces</code>)",
                     "Elle est remplacée par une adresse au hasard",
                     "Elle est conservée, mais l'interface redémarre éteinte"],
         "answer": 1,
         "explain": "ip ne modifie que la configuration en cours, en mémoire. Ce qui doit survivre au redémarrage s'écrit dans le fichier."},
        {"q": "Une caisse ne répond « qu'une fois sur deux » depuis qu'un portable a été branché, et <code>arping</code> montre deux MAC différentes pour l'adresse de la caisse. De quoi s'agit-il ?",
         "choices": ["D'un câble défectueux", "D'un masque trop petit sur la caisse", "D'un conflit d'adresses IP", "D'un switch saturé"],
         "answer": 2,
         "explain": "Deux machines répondent pour la même IP : les autres envoient leurs messages tantôt à l'une, tantôt à l'autre."},
        {"q": "Sur une interface qui porte <code>192.168.10.30/28</code>, on tape <code>ip addr add 192.168.10.30/24 dev eth0</code>. Que porte maintenant l'interface ?",
         "choices": ["Seulement 192.168.10.30/24 : la nouvelle adresse remplace l'ancienne",
                     "Les deux adresses",
                     "Seulement 192.168.10.30/28 : la commande est refusée",
                     "Aucune adresse : les deux s'annulent"],
         "answer": 1,
         "explain": "Une interface peut porter plusieurs adresses : il faut retirer la mauvaise avec ip addr del, puis vérifier avec ip a."},
        {"q": "Dans <code>/etc/network/interfaces</code>, à quoi sert la ligne <code>auto eth0</code> ?",
         "choices": ["À donner une adresse automatique à eth0",
                     "À activer eth0 au démarrage, avec la configuration décrite par sa ligne iface",
                     "À détecter automatiquement le masque",
                     "À rien : c'est un commentaire"],
         "answer": 1,
         "explain": "Sans auto, la configuration existe mais n'est appliquée qu'à la demande (ifup eth0). Une adresse automatique, c'est DHCP : inet dhcp."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    3: [
        {"q": "Que fait une machine d'un paquet destiné à une adresse qui n'est pas sur son réseau ?",
         "choices": ["Elle l'envoie à tout le réseau", "Elle l'envoie à sa passerelle (route par défaut), si elle en a une",
                     "Elle le jette toujours", "Elle le renvoie à l'expéditeur"],
         "answer": 1,
         "explain": "Hors de ses propres réseaux, une machine confie le paquet à sa passerelle. Sans route par défaut : Network is unreachable."},
        {"q": "<code>ping 10.20.0.10</code> répond aussitôt <code>Network is unreachable</code>. La cause la plus probable ?",
         "choices": ["Le serveur est éteint", "La machine n'a pas de route vers ce réseau (pas de route par défaut)",
                     "Le câble du serveur est débranché", "Le serveur refuse les pings"],
         "answer": 1,
         "explain": "Le message vient de la machine elle-même : elle ne sait pas où envoyer le paquet. Le serveur n'a même pas été contacté."},
        {"q": "Quelle commande ajoute une route par défaut vers <code>172.16.5.254</code> ?",
         "choices": ["<code>ip addr add default 172.16.5.254</code>", "<code>ip route add default via 172.16.5.254</code>",
                     "<code>route 172.16.5.254</code>", "<code>ip link set default 172.16.5.254</code>"],
         "answer": 1,
         "explain": "ip route gère la table de routage ; « via » désigne la passerelle."},
        {"q": "Une machine en <code>192.168.10.12/24</code> peut-elle avoir <code>10.20.0.254</code> comme passerelle ?",
         "choices": ["Oui, n'importe quelle adresse convient", "Non : la passerelle doit être sur son propre réseau, joignable directement",
                     "Oui, si le masque est /16", "Seulement si c'est un serveur"],
         "answer": 1,
         "explain": "La machine doit pouvoir joindre sa passerelle directement : c'est l'adresse du routeur sur SON réseau."},
        {"q": "Les postes joignent les deux adresses du routeur, mais rien ne passe au-delà. Que vérifier sur le routeur ?",
         "choices": ["Son adresse MAC", "Le routage du noyau : <code>net.ipv4.ip_forward</code>", "Son nom de machine", "Son fichier /etc/hosts"],
         "answer": 1,
         "explain": "Un routeur Linux répond pour lui-même, mais ne relaie les paquets que si net.ipv4.ip_forward vaut 1."},
        {"q": "Un ping vers un serveur d'un autre réseau reste muet, sans message d'erreur ; le serveur reçoit bien les demandes. Cause probable ?",
         "choices": ["Le poste n'a pas de passerelle", "Le serveur ne sait pas renvoyer ses réponses (pas de route de retour)",
                     "Le masque du poste est trop grand", "Le switch est en panne"],
         "answer": 1,
         "explain": "L'aller fonctionne, le retour non : chaque machine du trajet doit savoir répondre."},
        {"q": "Que montre <code>traceroute -n 10.20.0.10</code> ?",
         "choices": ["La vitesse de la connexion", "Les routeurs traversés, étape par étape, jusqu'à la destination",
                     "Les ports ouverts du serveur", "L'adresse MAC du serveur"],
         "answer": 1,
         "explain": "Une ligne par routeur traversé ; des étoiles montrent l'étape où le chemin se perd."},
        {"q": "Comment rendre permanente la passerelle d'un poste Debian ?",
         "choices": ["En relançant ip route add à chaque démarrage, à la main", "Avec une ligne <code>gateway</code> dans /etc/network/interfaces",
                     "Dans /etc/sysctl.conf", "C'est impossible sans DHCP"],
         "answer": 1,
         "explain": "ifup lit la ligne gateway et crée la route par défaut à chaque démarrage. /etc/sysctl.conf sert aux réglages du noyau, comme le routage."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    4: [
        {"q": "À quoi sert un serveur DNS ?",
         "choices": ["À donner une adresse IP aux postes qui démarrent", "À traduire un nom (comme stock.cimes.lan) en adresse IP",
                     "À relier deux réseaux entre eux", "À protéger le réseau des attaques"],
         "answer": 1,
         "explain": "Le DNS est l'annuaire du réseau : nom vers adresse IP. Donner des adresses aux postes, c'est le rôle de DHCP ; relier deux réseaux, celui d'un routeur."},
        {"q": "Dans quel fichier une machine Linux trouve-t-elle l'adresse du serveur DNS à interroger ?",
         "choices": ["/etc/hosts", "/etc/network/interfaces", "/etc/resolv.conf", "/etc/hostname"],
         "answer": 2,
         "explain": "La ligne « nameserver <adresse> » de /etc/resolv.conf désigne le serveur DNS."},
        {"q": "<code>ping stock.cimes.lan</code> répond <code>Temporary failure in name resolution</code>, mais <code>ping 10.20.0.10</code> fonctionne. Que vérifier en premier ?",
         "choices": ["La passerelle du poste", "Le serveur DNS configuré dans /etc/resolv.conf", "Le masque du poste", "Le câble du serveur"],
         "answer": 1,
         "explain": "Le réseau fonctionne (l'adresse IP répond) : c'est la traduction du nom qui échoue. Aucun serveur DNS n'a répondu."},
        {"q": "<code>dig +short stock.cimes.lan</code> répond 10.20.0.10, mais <code>getent hosts stock.cimes.lan</code> répond 10.20.0.99. Pourquoi ?",
         "choices": ["Le serveur DNS est en panne", "Une ligne de /etc/hosts, consultée avant le DNS, donne une autre adresse",
                     "getent est plus récent que dig", "Le serveur de stock a deux adresses"],
         "answer": 1,
         "explain": "dig interroge seulement le DNS ; getent suit le chemin réel de la machine : /etc/hosts d'abord, puis le DNS."},
        {"q": "Que fait <code>dig @10.20.0.53 intranet.cimes.lan</code> ?",
         "choices": ["Il se connecte à l'intranet", "Il demande l'adresse d'intranet.cimes.lan au serveur DNS 10.20.0.53",
                     "Il ajoute intranet.cimes.lan à l'annuaire", "Il teste la connexion vers 10.20.0.53"],
         "answer": 1,
         "explain": "@ désigne le serveur DNS à interroger ; sans lui, dig utilise celui de /etc/resolv.conf."},
        {"q": "Vous ajoutez une ligne à l'annuaire de dnsmasq, mais le DNS ne connaît toujours pas le nouveau nom. Qu'avez-vous oublié ?",
         "choices": ["De redémarrer tous les postes", "De redémarrer le service DNS (service dnsmasq restart)",
                     "De modifier /etc/hosts sur chaque poste", "Rien : il faut attendre 24 heures"],
         "answer": 1,
         "explain": "Un service ne relit pas sa configuration tout seul : après modification, on le redémarre, puis on vérifie avec dig."},
        {"q": "Dans la réponse de <code>dig</code>, que signifie <code>status: NXDOMAIN</code> ?",
         "choices": ["Tout s'est bien passé", "Le nom demandé n'existe pas dans l'annuaire", "Le serveur DNS ne répond pas", "Le nom existe mais n'a pas d'adresse"],
         "answer": 1,
         "explain": "NXDOMAIN : nom inexistant. NOERROR indique une réponse normale ; un serveur muet donne « connection timed out »."},
        {"q": "Pourquoi préférer le DNS au fichier /etc/hosts dans une entreprise ?",
         "choices": ["Le DNS est plus rapide", "Une seule modification dans l'annuaire suffit pour tous les postes",
                     "/etc/hosts ne fonctionne pas sous Linux", "Le DNS chiffre les communications"],
         "answer": 1,
         "explain": "/etc/hosts se tient à jour à la main, sur chaque poste ; le DNS centralise l'annuaire."},
    ],
}
