"""Mémo du parcours Git : une fiche par commande ou notion, débloquée par un exercice."""
from ..linux.memo import C

BASE, HIST, REMOTE, BRANCH, CONFLICT, REWRITE, INQUIRY, SECRET = (
    "Premiers pas", "Historique", "Dépôt distant", "Branches", "Conflits", "Réécrire son histoire",
    "Enquêtes et versions", "Secrets et garde-fous",
)

CARDS = [
    C("config", "git config", BASE, "Réglages de Git ; --global : pour tous vos dépôts (fichier ~/.gitconfig).",
      ["git config --global <clé> <valeur>", "git config --global --get <clé>", "git config --global --list"],
      [('git config --global user.name "Camille Martin"', ""), ('git config --global user.email "camille.martin@cimes-sentiers.fr"', ""),
       ("git config --global init.defaultBranch main", "branche des nouveaux dépôts")], ["G1.1"]),
    C("init", "git init", BASE, "Transforme le dossier courant en dépôt Git (crée le dossier caché .git).",
      ["git init", "git branch -m <nom>"], [("cd ~/procedures && git init", ""), ("git branch -m main", "renommer la branche courante")], ["G1.2"]),
    C("status", "git status", BASE, "État du répertoire de travail et de l'index : fichiers modifiés, indexés, non suivis.",
      ["git status", "git status -s"], [("git status", "à lancer sans modération"), ("git status -s", "format court")], ["G1.2"]),
    C("commit", "git add / git commit", BASE, "add prépare les modifications (index), commit les enregistre dans l'historique.",
      ["git add <fichier>... | .", 'git commit -m "<message>"', 'git commit -am "<message>"'],
      [("git add sauvegarde.md comptes.md", ""), ('git commit -m "Procédures d\'exploitation"', ""),
       ('git commit -am "Correction"', "-a : indexe aussi les fichiers déjà suivis modifiés")], ["G1.2"]),
    C("gitignore", ".gitignore", BASE, "Liste des fichiers que Git doit ignorer ; un fichier déjà suivi doit d'abord être retiré de l'index.",
      [".gitignore : un motif par ligne", "git rm --cached <fichier>", "git check-ignore -v <fichier>"],
      [("brouillon-perso.txt\n*.log\nnode_modules/", "contenu de .gitignore"), ("git rm --cached brouillon-perso.txt", "ne supprime pas le fichier du disque"),
       ("git check-ignore -v brouillon-perso.txt", "quelle règle l'ignore ?")], ["G1.3", "G9.1"]),
    C("diff", "git diff", BASE, "Compare le répertoire de travail, l'index et les commits, ligne par ligne.",
      ["git diff", "git diff --staged", "git diff HEAD", "git diff <commit> <commit> [--name-only]"],
      [("git diff", "ce qui n'est pas encore indexé"), ("git diff --staged", "ce qui partira au prochain commit"),
       ("git diff a1b2c3d HEAD --name-only", "les fichiers modifiés entre deux commits")], ["G1.4"]),
    C("restore", "git restore", BASE, "Jette des modifications non commitées, ou remet un fichier dans l'état d'un commit.",
      ["git restore <fichier>", "git restore --staged <fichier>", "git restore --source=<commit> <fichier>"],
      [("git restore README.md", "abandonne les modifications en cours (définitif)"), ("git restore --staged notes.txt", "désindexe sans rien perdre"),
       ("git restore --source=3f9c2a1^ data/fournisseurs.csv", "^ : le parent du commit")], ["G1.4", "G2.2"]),
    C("add-p", "git add -p", BASE, "Indexe une partie seulement des modifications d'un fichier, morceau par morceau.",
      ["git add -p [<fichier>]", "y / n / s (découper) / q / ?"],
      [("git add -p js/app.js", "y pour la correction, n pour le debug"), ("git diff --staged", "contrôler avant de commiter")], ["G1.5"]),

    C("log", "git log", HIST, "L'historique des commits, filtrable.",
      ["git log [--oneline] [--graph] [--all]", "git log -p <fichier>", 'git log -S "<texte>" [-- <chemin>]', 'git log -G "<regex>"', "git log --author=<nom>"],
      [("git log --oneline --graph --all", "vue d'ensemble"), ('git log -S "0.055" --oneline -- js/panier.js', "qui a ajouté ou retiré ce texte, dans ce fichier ?"),
       ("git log --diff-filter=D --name-only", "commits qui ont supprimé des fichiers")], ["G2.1"]),
    C("show", "git show", HIST, "Examiner un commit, ou un fichier tel qu'il était dans un commit.",
      ["git show <commit>", "git show <commit>:<fichier>"],
      [("git show 3f9c2a1", ""), ("git show HEAD~2:js/panier.js", "le fichier tel qu'il était")], ["G2.1"]),
    C("blame", "git blame / git log -L", HIST, "Pour chaque ligne, le dernier commit qui l'a modifiée ; log -L suit l'histoire de quelques lignes.",
      ["git blame [-w] [-L <début>,<fin>] <fichier>", "git log -L <début>,<fin>:<fichier>"],
      [("git blame -w js/port.js", "-w : ignore les commits qui n'ont changé que des espaces"),
       ("git log -L '/standard/,+1:js/port.js'", "toutes les versions de cette ligne")], ["G2.4"]),
    C("revert", "git revert", HIST, "Crée un nouveau commit qui annule un commit précédent, sans réécrire l'historique.",
      ["git revert [--no-edit] <commit>", "git revert --continue | --abort"],
      [("git revert 3f9c2a1", "la bonne façon d'annuler un commit partagé"),
       ("git add js/livraison.js && git revert --continue", "après avoir résolu un conflit")], ["G2.3", "G2.5"]),

    C("clone", "git clone", REMOTE, "Copie complète d'un dépôt distant ; le distant s'appelle origin.",
      ["git clone <url ou chemin> [dossier]"],
      [("git clone /srv/git/boutique.git", ""), ("git clone https://github.com/org/projet.git", "")], ["G3.1"]),
    C("remote", "git remote", REMOTE, "Les dépôts distants connus de votre dépôt, et leur adresse.",
      ["git remote -v", "git remote add <nom> <url>", "git remote set-url <nom> <url>", "git remote remove <nom>"],
      [("git remote -v", "où pointe origin ?"), ("git remote set-url origin /srv/git/vitrine.git", "corriger une adresse")], ["G3.3"]),
    C("push", "git push", REMOTE, "Publie les commits locaux sur le dépôt distant.",
      ["git push", "git push -u origin <branche>", "git push origin <branche>"],
      [("git push", "refusé si le distant a avancé : git pull d'abord"), ("git push -u origin main", "publie et mémorise le suivi (upstream)")], ["G3.2", "G3.3"]),
    C("fetch", "git fetch", REMOTE, "Télécharge les nouveautés du distant (met à jour origin/…) sans toucher à vos branches.",
      ["git fetch [--prune]", "git log main..origin/main", "git rev-list --count <a>..<b>"],
      [("git fetch && git status", "« behind by 3 commits »"), ("git log --oneline main..origin/main", "ce qui arrivera au prochain pull")], ["G4.3"]),
    C("pull", "git pull", REMOTE, "pull = fetch + intégration dans la branche courante (fusion ou rebase).",
      ["git pull [--rebase | --no-rebase]"],
      [("git pull", ""), ("git pull --rebase", "rejoue vos commits au-dessus du distant")], ["G4.2"]),
    C("pull-rebase", "pull.rebase / rebase.autoStash", REMOTE, "Réglages : git pull rebase par défaut, et met de côté vos modifications en cours le temps du rebase.",
      ["git config --global pull.rebase true", "git config --global rebase.autoStash true"],
      [("git config --global pull.rebase true", "historique linéaire"), ("git pull --autostash", "la même chose, pour une seule fois")], ["G4.1"]),
    C("rebase-conflit", "Conflit pendant un rebase", REMOTE, "Le rebase s'arrête sur le commit en conflit : résoudre, add, puis continuer (pas commit).",
      ["git status", "git add <fichier>", "git rebase --continue | --skip | --abort"],
      [("git add css/style.css && git rebase --continue", "passe au commit suivant"), ("git rebase --abort", "revient à l'état d'avant")], ["G4.4"]),

    C("branch", "git branch / git switch", BRANCH, "Une branche est un pointeur mobile vers un commit ; on développe à côté de main.",
      ["git branch [-a] [-vv]", "git branch <nouvelle> [<commit>]", "git switch -c <nouvelle>", "git switch <branche>"],
      [("git switch -c feature/promo-ete", "créer et s'y placer"), ("git switch main", ""), ("git branch -a", "y compris les branches distantes")], ["G5.1"]),
    C("push-u", "Branches de suivi", BRANCH, "Une branche locale peut suivre une branche distante (upstream) : push et pull savent alors où aller.",
      ["git push -u origin <branche>", "git switch <branche distante sans origin/>", "git branch -u origin/<branche>", "git branch -vv"],
      [("git push -u origin feature/promo-ete", "ensuite, git push suffit"), ("git switch feature/code-promo-1234", "crée la branche locale qui suit origin/…"),
       ("git branch -vv", "qui suit quoi ?")], ["G5.1", "G5.4"]),
    C("merge", "git merge", BRANCH, "Intègre une branche dans la branche courante (fast-forward ou commit de fusion).",
      ["git merge <branche>", "git merge --no-edit <branche>"],
      [("git switch main && git pull && git merge origin/feature/avis-clients", "mettre main à jour d'abord")], ["G5.2"]),
    C("branch-d", "Supprimer une branche", BRANCH, "Une branche fusionnée se supprime, localement et sur le distant.",
      ["git branch -d <branche>", "git push origin --delete <branche>", "git fetch --prune"],
      [("git branch -d feature/avis-clients", "refuse si son travail n'est pas intégré"), ("git push origin --delete feature/avis-clients", ""),
       ("git fetch --prune", "oublie les branches distantes supprimées")], ["G5.3"]),
    C("reset", "git reset", BRANCH, "Déplace la branche courante ; --soft garde les modifications indexées, --mixed non indexées, --hard les jette.",
      ["git reset --soft <commit>", "git reset [--mixed] <commit>", "git reset --hard <commit>"],
      [("git branch feature/panier-v2 && git reset --hard HEAD~2", "déplacer des commits sur une branche"),
       ("git reset HEAD~2", "défaire deux commits en gardant le travail"), ("git reset --soft HEAD~3", "fondre trois commits en un")], ["G5.5", "G7.5"]),
    C("cherry-pick", "git cherry-pick", BRANCH, "Rejoue un commit précis (et lui seul) sur la branche courante.",
      ["git cherry-pick [-x] <commit>", "git cherry-pick --continue | --abort"],
      [("git switch main && git cherry-pick -x 3f9c2a1", "-x : note l'origine dans le message")], ["G5.6"]),

    C("conflit", "Résoudre un conflit", CONFLICT, "Même ligne modifiée des deux côtés : choisir le contenu, supprimer les marqueurs, add, commit.",
      ["<<<<<<< HEAD … ======= … >>>>>>> branche", "git add <fichier>", "git commit | git merge --continue"],
      [("git status", "fichiers « both modified »"), ("git add tarifs.html && git commit --no-edit", "termine la fusion"),
       ("git config --global merge.conflictStyle zdiff3", "affiche aussi la version d'origine")], ["G6.1"]),
    C("merge-abort", "git merge --abort", CONFLICT, "Annule une fusion en cours et revient à l'état d'avant.",
      ["git merge --abort"], [("git merge --abort", "")], ["G6.2"]),
    C("ours-theirs", "--ours / --theirs", CONFLICT, "Pendant un conflit, prendre la version entière d'un côté pour un fichier.",
      ["git checkout --ours <fichier>", "git checkout --theirs <fichier>"],
      [("git checkout --theirs stock.json && git add stock.json", "la version de la branche fusionnée"),
       ("git merge -X theirs <branche>", "attention : ne tranche que les zones en conflit")], ["G6.4"]),
    C("revert-merge", "git revert -m", CONFLICT, "Annule un commit de fusion : -m indique le parent de référence (1 = la branche où l'on a fusionné).",
      ["git revert -m 1 <fusion>"],
      [("git revert -m 1 7a8b9c0", "retire tout ce que la branche a apporté"),
       ("git revert <commit d'annulation>", "pour réintégrer plus tard la branche")], ["G6.3"]),

    C("stash", "git stash", REWRITE, "Range les modifications en cours pour les reprendre plus tard.",
      ["git stash [-u]", "git stash list", "git stash show -p stash@{n}", "git stash pop [stash@{n}]", "git stash drop stash@{n}"],
      [("git stash && git switch main", "urgence sur une autre branche"), ("git stash -u", "fichiers non suivis compris"),
       ("git stash pop", "reprend le travail rangé")], ["G7.1", "G7.6"]),
    C("amend", "git commit --amend", REWRITE, "Remplace le dernier commit (message, fichiers oubliés) : uniquement s'il n'est pas encore poussé.",
      ["git commit --amend [-m \"<message>\"]", "git commit --amend --reset-author --no-edit"],
      [("git add oubli.txt && git commit --amend -m \"Bon message\"", "")], ["G7.2"]),
    C("rebase", "git rebase", REWRITE, "Rejoue les commits de la branche courante au-dessus d'une autre : historique linéaire.",
      ["git rebase <base>", "git rebase --continue | --abort"],
      [("git switch feature/filtres && git rebase main", "")], ["G7.3"]),
    C("rebase-i", "git rebase -i", REWRITE, "Réorganise des commits non publiés : réordonner, fondre (squash, fixup), renommer (reword), supprimer (drop).",
      ["git rebase -i <base>", "pick | reword | edit | squash | fixup | drop"],
      [("git rebase -i main", "une ligne par commit, du plus ancien au plus récent"),
       ("fixup 5d6e7f8 wip", "fond « wip » dans le commit de la ligne précédente")], ["G7.4"]),

    C("bisect", "git bisect", INQUIRY, "Trouve par dichotomie le premier commit qui a introduit un bug.",
      ["git bisect start | bad | good <commit> | skip | log | reset", "git bisect run <script>"],
      [("git bisect start && git bisect bad && git bisect good 1a2b3c4", ""), ("git bisect run ./tests.sh", "0 = bon, 125 = à sauter, autre = mauvais"),
       ("git bisect log > ~/bisect.log", "avant git bisect reset")], ["G8.1"]),
    C("tag", "git tag", INQUIRY, "Étiquette un commit (une version livrée) ; -a : étiquette annotée, avec auteur et message.",
      ["git tag -a <nom> -m \"<message>\"", "git tag -d <nom>", "git push origin <nom>", "git push --force origin <nom>"],
      [('git tag -a v1.0 -m "Première version en production"', ""), ("git push origin v1.0", "les étiquettes ne partent pas avec git push"),
       ("git tag -d v1.0 && git push origin --delete v1.0", "retirer une étiquette partout")], ["G8.2"]),
    C("reflog", "git reflog", INQUIRY, "Journal de toutes les positions de HEAD : retrouve des commits « perdus ».",
      ["git reflog", "git branch <nom> <commit>"],
      [("git reflog", ""), ("git branch sauvetage HEAD@{1}", "récupérer l'état d'avant la dernière commande")], ["G8.3"]),

    C("ignore-avance", "Règles de .gitignore", SECRET, "Motifs sans barre : partout ; avec barre : relatifs au .gitignore ; !motif : exception (impossible si le dossier parent est exclu).",
      ["*.log   /build/*   !/build/.gitkeep   node_modules/", "git check-ignore -v [--no-index] <chemin>", "git status --ignored"],
      [("/build/*\n!/build/.gitkeep", "exclure le contenu, pas le dossier"), ("git check-ignore -v --no-index src/local.ini", "quelle règle s'applique ?")], ["G9.2"]),
    C("purge", "Purger l'historique", SECRET, "Retire un fichier de tous les commits, puis republie de force. Le secret doit d'abord être révoqué.",
      ["git filter-repo --invert-paths --path <fichier>", "git filter-branch --index-filter '…' -- <branche>", "git push --force origin <branche>"],
      [("git filter-repo --force --invert-paths --path config/api.env", "retire aussi le distant origin"),
       ("git log --all -p | grep API_KEY=", "vérifier : plus rien")], ["G9.3"]),
    C("hooks", "Hooks Git", SECRET, "Scripts exécutables de .git/hooks, lancés par Git à certains moments ; pre-commit peut refuser un commit.",
      [".git/hooks/pre-commit | commit-msg | pre-push", "chmod +x .git/hooks/pre-commit", "git config core.hooksPath .githooks"],
      [("git diff --cached | grep -qE '^\\+.*PASSWORD=' && exit 1", "dans pre-commit : examiner l'index"),
       ("git commit --no-verify", "contourne pre-commit (à éviter)")], ["G9.4"]),
]
