"""Mémo du parcours Git : une fiche par commande ou notion, débloquée par un exercice."""
from ..linux.memo import C

BASE, HIST, REMOTE, BRANCH, CONFLICT, REWRITE, INQUIRY = (
    "Premiers pas", "Historique", "Dépôt distant", "Branches", "Conflits", "Réécrire son histoire",
    "Enquêtes et versions",
)

CARDS = [
    C("config", "git config", BASE, "Réglages de Git ; --global : pour tous vos dépôts (fichier ~/.gitconfig).",
      ["git config --global <clé> <valeur>", "git config --global --list"],
      [('git config --global user.name "Camille Martin"', ""), ('git config --global user.email "camille.martin@cimes-sentiers.fr"', ""),
       ("git config --global init.defaultBranch main", "branche des nouveaux dépôts")], ["G1.1"]),
    C("init", "git init", BASE, "Transforme le dossier courant en dépôt Git (crée le dossier caché .git).",
      ["git init", "git branch -m <nom>"], [("cd ~/procedures && git init", ""), ("git branch -m main", "renommer la branche courante")], ["G1.2"]),
    C("status", "git status", BASE, "État du répertoire de travail et de l'index : fichiers modifiés, indexés, non suivis.",
      ["git status", "git status -s"], [("git status", "à lancer sans modération"), ("git status -s", "format court")], ["G1.2"]),
    C("commit", "git add / git commit", BASE, "add prépare les modifications (index), commit les enregistre dans l'historique.",
      ["git add <fichier>... | .", 'git commit -m "<message>"', 'git commit -am "<message>"'],
      [("git add sauvegarde.md comptes.md", ""), ('git commit -m "Procédures d\'exploitation"', ""),
       ('git commit -am "Correction"', "-a : indexe aussi les fichiers déjà suivis modifiés")], ["G1.2"]),
    C("gitignore", ".gitignore", BASE, "Liste des fichiers que Git doit ignorer ; un fichier déjà suivi doit d'abord être retiré de l'index.",
      [".gitignore : un motif par ligne", "git rm --cached <fichier>", "git check-ignore -v <fichier>"],
      [("brouillon-perso.txt\n*.log\nnode_modules/", "contenu de .gitignore"), ("git rm --cached brouillon-perso.txt", "ne supprime pas le fichier du disque")], ["G1.3"]),

    C("log", "git log", HIST, "L'historique des commits, filtrable.",
      ["git log [--oneline] [--graph] [--all]", "git log -p <fichier>", 'git log -S "<texte>"', "git log --author=<nom>"],
      [("git log --oneline --graph --all", "vue d'ensemble"), ('git log -S "0.055" --oneline', "qui a ajouté ou retiré ce texte ?"),
       ("git log --diff-filter=D --name-only", "commits qui ont supprimé des fichiers")], ["G2.1"]),
    C("show", "git show / git diff / git blame", HIST, "Examiner un commit, comparer des versions, trouver l'auteur d'une ligne.",
      ["git show <commit>", "git show <commit>:<fichier>", "git diff [--staged] [<a> <b>]", "git blame <fichier>"],
      [("git show 3f9c2a1", ""), ("git show HEAD~2:js/panier.js", "le fichier tel qu'il était"), ("git diff --staged", "ce qui partira au prochain commit")], ["G2.1"]),
    C("restore", "git restore", HIST, "Remet un fichier dans l'état d'un commit (ou annule des modifications non commitées).",
      ["git restore <fichier>", "git restore --source=<commit> <fichier>", "git restore --staged <fichier>"],
      [("git restore --source=3f9c2a1^ data/fournisseurs.csv", "^ : le parent du commit"), ("git restore index.html", "abandonne les modifications en cours")], ["G2.2"]),
    C("revert", "git revert", HIST, "Crée un nouveau commit qui annule un commit précédent, sans réécrire l'historique.",
      ["git revert [--no-edit] <commit>"], [("git revert 3f9c2a1", "la bonne façon d'annuler un commit partagé")], ["G2.3"]),

    C("clone", "git clone / git remote", REMOTE, "Copie complète d'un dépôt distant ; le distant s'appelle origin.",
      ["git clone <url ou chemin> [dossier]", "git remote -v"],
      [("git clone /srv/git/boutique.git", ""), ("git clone https://github.com/org/projet.git", ""), ("git remote -v", "")], ["G3.1"]),
    C("push", "git push", REMOTE, "Publie les commits locaux sur le dépôt distant.",
      ["git push", "git push origin <branche>"], [("git push", "refusé si le distant a avancé : git pull d'abord")], ["G3.2"]),
    C("pull", "git fetch / git pull", REMOTE, "fetch télécharge les nouveautés du distant ; pull = fetch + intégration dans la branche courante.",
      ["git fetch", "git pull [--rebase | --no-rebase]"],
      [("git fetch && git log --oneline --graph --all", "voir avant d'intégrer"), ("git pull", "")], ["G4.2"]),
    C("pull-rebase", "pull.rebase", REMOTE, "git pull rejoue vos commits locaux au-dessus du distant : pas de commit de fusion inutile.",
      ["git config --global pull.rebase true", "git pull --rebase"], [("git config --global pull.rebase true", "")], ["G4.1"]),

    C("branch", "git branch / git switch", BRANCH, "Une branche est un pointeur mobile vers un commit ; on développe à côté de main.",
      ["git branch [-a]", "git switch -c <nouvelle>", "git switch <branche>"],
      [("git switch -c feature/promo-ete", "créer et s'y placer"), ("git switch main", ""), ("git branch -a", "y compris les branches distantes")], ["G5.1"]),
    C("push-u", "git push -u", BRANCH, "Publie une nouvelle branche et mémorise sa branche distante (upstream).",
      ["git push -u origin <branche>"], [("git push -u origin feature/promo-ete", "ensuite, git push suffit")], ["G5.1"]),
    C("merge", "git merge", BRANCH, "Intègre une branche dans la branche courante (fast-forward ou commit de fusion).",
      ["git merge <branche>", "git merge --no-edit <branche>"],
      [("git switch main && git merge origin/feature/avis-clients", "")], ["G5.2"]),
    C("branch-d", "Supprimer une branche", BRANCH, "Une branche fusionnée se supprime, localement et sur le distant.",
      ["git branch -d <branche>", "git push origin --delete <branche>", "git fetch --prune"],
      [("git branch -d feature/avis-clients", "refuse si elle n'est pas fusionnée"), ("git push origin --delete feature/avis-clients", "")], ["G5.3"]),

    C("conflit", "Résoudre un conflit", CONFLICT, "Même ligne modifiée des deux côtés : choisir le contenu, supprimer les marqueurs, add, commit.",
      ["<<<<<<< HEAD … ======= … >>>>>>> branche", "git add <fichier>", "git commit"],
      [("git status", "fichiers « both modified »"), ("git add tarifs.html && git commit --no-edit", "termine la fusion")], ["G6.1"]),
    C("merge-abort", "git merge --abort", CONFLICT, "Annule une fusion en cours et revient à l'état d'avant.",
      ["git merge --abort", "git rebase --abort"], [("git merge --abort", "")], ["G6.2"]),

    C("stash", "git stash", REWRITE, "Range les modifications en cours pour les reprendre plus tard.",
      ["git stash", "git stash list", "git stash pop", "git stash drop"],
      [("git stash && git switch main", "urgence sur une autre branche"), ("git stash pop", "reprend le travail rangé")], ["G7.1"]),
    C("amend", "git commit --amend", REWRITE, "Remplace le dernier commit (message, fichiers oubliés) : uniquement s'il n'est pas encore poussé.",
      ["git commit --amend [-m \"<message>\"]", "git commit --amend --reset-author"],
      [("git add oubli.txt && git commit --amend -m \"Bon message\"", "")], ["G7.2"]),
    C("rebase", "git rebase", REWRITE, "Rejoue les commits de la branche courante au-dessus d'une autre : historique linéaire.",
      ["git rebase <base>", "git rebase --continue | --abort"],
      [("git switch feature/filtres && git rebase main", ""), ("git rebase -i HEAD~3", "réorganiser ses derniers commits")], ["G7.3"]),

    C("bisect", "git bisect", INQUIRY, "Trouve par dichotomie le premier commit qui a introduit un bug.",
      ["git bisect start | bad | good <commit> | reset", "git bisect run <script>"],
      [("git bisect start && git bisect bad && git bisect good 1a2b3c4", ""), ("git bisect run ./tests.sh", "automatique"), ("git bisect reset", "")], ["G8.1"]),
    C("tag", "git tag", INQUIRY, "Étiquette un commit (une version livrée) ; -a : étiquette annotée, avec auteur et message.",
      ["git tag -a <nom> -m \"<message>\"", "git tag", "git push origin <nom>"],
      [('git tag -a v1.0 -m "Première version en production"', ""), ("git push origin v1.0", "les étiquettes ne partent pas avec git push")], ["G8.2"]),
    C("reflog", "git reflog", INQUIRY, "Journal de toutes les positions de HEAD : retrouve des commits « perdus ».",
      ["git reflog", "git branch <nom> <commit>"],
      [("git reflog", ""), ("git branch sauvetage HEAD@{1}", "récupérer l'état d'avant la dernière commande")], ["G8.3"]),
]
