"""QCM de fin de cours du parcours Git : 8 questions par étape, 4 tirées au sort pour chaque étudiant."""

QUIZ = {
    # ─────────────────────────────────────────────────────────────────────
    1: [
        {"q": "Vous faites <code>git add a.txt</code>, puis vous modifiez encore <code>a.txt</code>, puis <code>git commit -m \"Maj\"</code>. Quelle version de <code>a.txt</code> est enregistrée ?",
         "choices": ["La version actuelle du disque, car <code>commit</code> relit les fichiers",
                     "Aucune : un fichier modifié après <code>add</code> est retiré de l'index",
                     "Les deux versions, dans deux commits successifs",
                     "La version du moment du <code>git add</code>"],
         "answer": 3,
         "explain": "<code>git commit</code> enregistre l'index, c'est-à-dire l'état indexé par <code>git add</code>. La modification suivante reste dans le répertoire de travail, non indexée."},
        {"q": "Vous avez indexé toutes vos modifications avec <code>git add</code>. Qu'affiche maintenant <code>git diff</code>, sans option ?",
         "choices": ["Rien : le répertoire de travail et l'index sont identiques",
                     "Tout ce qui partira dans le prochain commit",
                     "Les différences entre vos fichiers et le dernier commit",
                     "Une erreur : il faut préciser <code>--staged</code>"],
         "answer": 0,
         "explain": "<code>git diff</code> compare le répertoire de travail à l'index. Ce qui est indexé se voit avec <code>git diff --staged</code>."},
        {"q": "Que fait <code>git restore app.js</code> sur des modifications <strong>non indexées</strong> de ce fichier ?",
         "choices": ["Il les met de côté dans un stash, récupérable plus tard",
                     "Il les jette définitivement : le fichier revient à sa version indexée",
                     "Il les retire de l'index, sans toucher au fichier",
                     "Il ramène le fichier à sa version d'il y a deux commits"],
         "answer": 1,
         "explain": "<code>git restore fichier</code> remplace le fichier par sa version indexée. Les modifications jetées ne sont enregistrées nulle part."},
        {"q": "<code>config.ini</code> est suivi par Git depuis longtemps. Vous ajoutez <code>config.ini</code> au <code>.gitignore</code>, puis vous modifiez le fichier. Que montre <code>git status</code> ?",
         "choices": ["Rien : le fichier est désormais ignoré",
                     "Le fichier comme supprimé de l'index",
                     "Le fichier comme modifié : il est toujours suivi",
                     "Le fichier comme non suivi (<em>untracked</em>)"],
         "answer": 2,
         "explain": "<code>.gitignore</code> ne concerne que les fichiers non suivis. Un fichier déjà suivi continue d'être suivi tant qu'on ne l'a pas retiré de l'index."},
        {"q": "À quoi sert l'option <code>--global</code> de <code>git config --global user.name \"Léa Martin\"</code> ?",
         "choices": ["À appliquer le réglage à tous les utilisateurs de la machine",
                     "À appliquer le réglage au dépôt courant et à tous ses clones",
                     "À publier le réglage sur le dépôt distant avec vos commits",
                     "À appliquer le réglage à tous vos dépôts, via <code>~/.gitconfig</code>"],
         "answer": 3,
         "explain": "<code>--global</code> écrit dans votre fichier personnel <code>~/.gitconfig</code> : le réglage vaut pour tous vos dépôts, sur cette machine."},
        {"q": "<code>git status</code> affiche <code>panier.js</code> à la fois sous <em>Changes to be committed</em> et sous <em>Changes not staged for commit</em>. Qu'est-ce que cela signifie ?",
         "choices": ["Le fichier est en conflit entre deux versions",
                     "Une partie de ses modifications est indexée, une autre ne l'est pas",
                     "Le fichier a été indexé deux fois de suite",
                     "Le fichier a été renommé depuis le dernier commit"],
         "answer": 1,
         "explain": "Après un <code>git add</code>, le fichier a été modifié à nouveau (ou seuls certains morceaux ont été indexés, avec <code>git add -p</code>) : l'index et le disque diffèrent."},
        {"q": "Que fait <code>git restore --staged notes.txt</code> ?",
         "choices": ["Il retire le fichier de l'index, en gardant vos modifications",
                     "Il jette vos modifications et retire le fichier de l'index",
                     "Il supprime le fichier du disque et de l'index",
                     "Il remplace le fichier du disque par sa version du dernier commit"],
         "answer": 0,
         "explain": "<code>--staged</code> agit sur l'index seulement : la modification quitte le prochain commit mais reste dans le fichier sur le disque."},
        {"q": "Quelle commande montre exactement ce qui partira dans le prochain commit ?",
         "choices": ["<code>git diff</code>",
                     "<code>git diff HEAD</code>",
                     "<code>git diff --staged</code>",
                     "<code>git log -p</code>"],
         "answer": 2,
         "explain": "<code>git diff --staged</code> compare l'index au dernier commit. <code>git diff HEAD</code> montrerait aussi les modifications non indexées."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    2: [
        {"q": "Un commit a seulement <strong>déplacé</strong> une ligne contenant <code>TVA</code> à l'intérieur du même fichier, sans rien changer d'autre. <code>git log -S \"TVA\"</code> le trouve-t-il ?",
         "choices": ["Oui : <code>-S</code> trouve tout commit dont le diff contient le texte",
                     "Non : le nombre d'occurrences de « TVA » dans le fichier ne change pas",
                     "Oui, à condition d'ajouter le chemin du fichier après <code>--</code>",
                     "Non : <code>-S</code> ne cherche que dans les messages de commit"],
         "answer": 1,
         "explain": "La « pioche » <code>-S</code> ne retient que les commits qui changent le nombre d'occurrences du texte. Elle cherche dans les modifications, pas dans les messages."},
        {"q": "Que désigne <code>HEAD~1</code> ?",
         "choices": ["Le premier commit du dépôt",
                     "La branche utilisée juste avant la branche courante",
                     "Le parent du commit courant",
                     "Le commit qui suivra le commit courant"],
         "answer": 2,
         "explain": "<code>HEAD</code> est le commit courant ; <code>HEAD~1</code> (ou <code>HEAD^</code>) est son parent, <code>HEAD~2</code> le parent de son parent."},
        {"q": "Qu'affiche <code>git show 3f9c2a1:js/app.js</code> ?",
         "choices": ["Les modifications apportées à <code>js/app.js</code> par ce commit",
                     "L'historique de <code>js/app.js</code> jusqu'à ce commit",
                     "Le message du commit, suivi de la liste de ses fichiers",
                     "Le contenu de <code>js/app.js</code> tel qu'il était dans ce commit"],
         "answer": 3,
         "explain": "La forme <code>commit:chemin</code> désigne un fichier dans un commit : <code>git show</code> affiche alors son contenu à cet instant."},
        {"q": "Pour récupérer l'ancienne version d'un fichier, Julien tape <code>git checkout 3f9c2a1</code>, sans nom de fichier. Que se passe-t-il ?",
         "choices": ["HEAD quitte la branche et se place sur ce commit (tête détachée)",
                     "Seuls les fichiers modifiés par ce commit reprennent leur version d'alors",
                     "La branche courante recule jusqu'à ce commit",
                     "Git crée une branche nommée <code>3f9c2a1</code> et s'y place"],
         "answer": 0,
         "explain": "Sans chemin, <code>checkout</code> déplace HEAD sur le commit (tête détachée). Pour un fichier : <code>git restore --source=3f9c2a1 chemin</code>."},
        {"q": "Vous tapez <code>git restore --source=3f9c2a1 data/clients.csv</code>. Que reste-t-il à faire pour que la version récupérée soit dans l'historique ?",
         "choices": ["Rien : la restauration crée un commit automatiquement",
                     "Rien : le fichier est déjà dans l'index et le commit",
                     "L'ajouter avec <code>git add</code>, puis commiter",
                     "Lancer <code>git revert 3f9c2a1</code> pour valider"],
         "answer": 2,
         "explain": "Le fichier revient seulement dans le répertoire de travail. Comme toute modification, il faut l'indexer puis le commiter."},
        {"q": "En plein conflit pendant un <code>git revert</code>, vous décidez de tout abandonner. Quelle commande ramène à l'état d'avant ?",
         "choices": ["<code>git commit --abort</code>",
                     "<code>git revert --abort</code>",
                     "<code>git reset --soft HEAD~1</code>",
                     "<code>git revert HEAD</code>"],
         "answer": 1,
         "explain": "<code>git revert --abort</code> annule l'opération en cours et restaure l'état d'avant. <code>git commit --abort</code> n'existe pas."},
        {"q": "Qu'affiche <code>git blame -L 10,20 panier.js</code> ?",
         "choices": ["Les commits n°10 à 20 de l'historique du fichier",
                     "Toute l'histoire des lignes 10 à 20, commit par commit",
                     "Les auteurs ayant modifié le fichier entre deux dates",
                     "Pour chaque ligne de 10 à 20, le dernier commit qui l'a modifiée"],
         "answer": 3,
         "explain": "<code>blame</code> indique, ligne par ligne, le dernier commit qui l'a touchée. Toute l'histoire de ces lignes, c'est <code>git log -L 10,20:panier.js</code>."},
        {"q": "Après <code>git revert 3f9c2a1</code> (sans conflit), que montre <code>git log --oneline</code> ?",
         "choices": ["Un nouveau commit « Revert … » en tête, et <code>3f9c2a1</code> toujours présent",
                     "L'historique sans <code>3f9c2a1</code>, qui a été retiré",
                     "<code>3f9c2a1</code> remplacé par une version corrigée, de même hash",
                     "Aucun changement : <code>revert</code> modifie seulement les fichiers"],
         "answer": 0,
         "explain": "<code>revert</code> ajoute un commit qui applique l'inverse du commit visé ; l'historique n'est pas réécrit, le commit d'origine reste visible."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    3: [
        {"q": "Qu'est-ce qu'un dépôt nu (<em>bare</em>), comme <code>/srv/git/boutique.git</code> ?",
         "choices": ["Un dépôt qui ne contient encore aucun commit",
                     "Un dépôt sans historique, qui ne garde que la dernière version",
                     "Un dépôt avec tout l'historique, mais sans répertoire de travail",
                     "Un dépôt accessible en lecture seule à toute l'équipe"],
         "answer": 2,
         "explain": "Un dépôt nu n'a que le contenu de <code>.git</code> : il sert de point d'échange, personne n'y travaille directement."},
        {"q": "Qu'est-ce que <code>origin/main</code> dans votre dépôt local ?",
         "choices": ["La branche <code>main</code> du serveur, modifiée en direct par vos commits",
                     "Une copie de <code>main</code> sur laquelle on peut commiter sans risque",
                     "Le nom du dossier qui contient le dépôt distant",
                     "La dernière position connue de <code>main</code> sur <code>origin</code>"],
         "answer": 3,
         "explain": "<code>origin/main</code> est une référence de suivi : la mémoire locale de l'état du distant, mise à jour lors des échanges (push, fetch, pull)."},
        {"q": "Vous venez de commiter une correction dans votre clone. Nadia consulte l'historique du dépôt partagé. Voit-elle votre commit ?",
         "choices": ["Non, tant que vous n'avez pas fait <code>git push</code>",
                     "Oui, car un clone reste synchronisé avec son distant",
                     "Oui, mais seulement après son propre <code>git fetch</code>",
                     "Non, tant qu'elle n'a pas fait <code>git pull</code>"],
         "answer": 0,
         "explain": "Un commit reste local tant qu'il n'a pas été publié par <code>git push</code> : même un <code>fetch</code> de Nadia ne peut pas le récupérer."},
        {"q": "Un <code>git push</code> répond <code>fatal: The current branch dev has no upstream branch</code>. Que signifie ce message ?",
         "choices": ["La branche <code>dev</code> n'existe pas encore en local",
                     "La branche <code>dev</code> ne suit aucune branche distante",
                     "Le dépôt distant refuse les branches autres que <code>main</code>",
                     "Le distant <code>origin</code> n'est pas joignable"],
         "answer": 1,
         "explain": "Sans lien de suivi, Git ne sait pas où publier. <code>git push -u origin dev</code> publie la branche et mémorise ce lien."},
        {"q": "Depuis votre dossier personnel, vous tapez <code>git clone /srv/git/boutique.git</code>. Qu'obtenez-vous ?",
         "choices": ["Un dépôt nu <code>~/boutique.git</code>, copie exacte du serveur",
                     "Un dossier <code>~/boutique</code> avec l'historique et le distant <code>origin</code>",
                     "Les fichiers de <code>main</code> copiés dans <code>~</code>, sans historique",
                     "Un dossier <code>~/boutique</code> sans aucun distant configuré"],
         "answer": 1,
         "explain": "<code>git clone</code> crée un dossier du nom du dépôt (sans <code>.git</code>), avec tout l'historique, et déclare la source comme distant <code>origin</code>."},
        {"q": "<code>git branch -vv</code> affiche <code>* main 3f9c2a1 [origin/main: ahead 2] Titre corrigé</code>. Qu'en déduisez-vous ?",
         "choices": ["<code>main</code> a 2 commits absents de <code>origin/main</code> : ils restent à publier",
                     "<code>origin/main</code> a 2 commits que vous n'avez pas encore récupérés",
                     "<code>main</code> est 2 commits derrière le dépôt distant",
                     "<code>main</code> suit deux branches distantes différentes"],
         "answer": 0,
         "explain": "<em>ahead 2</em> : votre branche a 2 commits de plus que sa branche suivie (selon la dernière synchronisation). Un <code>git push</code> les publierait."},
        {"q": "<code>git remote -v</code> affiche deux lignes <code>origin /srv/git/boutique.git</code>, l'une suivie de <code>(fetch)</code>, l'autre de <code>(push)</code>. Qu'est-ce que cela signifie ?",
         "choices": ["Deux distants distincts portent le même nom",
                     "Le dépôt a été cloné deux fois dans le même dossier",
                     "La branche <code>main</code> suit deux branches distantes",
                     "Un seul distant, utilisé pour récupérer et pour publier"],
         "answer": 3,
         "explain": "Chaque distant a une adresse de récupération et une adresse de publication, en général identiques : ici, un seul distant <code>origin</code>."},
        {"q": "Que fait <code>git push -u origin main</code> ?",
         "choices": ["Il publie toutes les branches locales sur <code>origin</code>",
                     "Il met à jour <code>main</code> à partir de <code>origin/main</code>",
                     "Il publie <code>main</code> et mémorise qu'elle suit <code>origin/main</code>",
                     "Il publie <code>main</code> en écrasant la branche distante"],
         "answer": 2,
         "explain": "<code>-u</code> (<code>--set-upstream</code>) enregistre le lien de suivi : ensuite, un simple <code>git push</code> ou <code>git pull</code> sait où aller."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    4: [
        {"q": "Votre <code>git push</code> est refusé avec <code>! [rejected] main -&gt; main (fetch first)</code>. Que signifie ce refus ?",
         "choices": ["Votre dépôt local est corrompu et doit être recloné",
                     "Vous n'avez pas le droit d'écrire sur le dépôt partagé",
                     "Votre branche n'a pas de branche distante suivie",
                     "Le distant a des commits que vous n'avez pas encore intégrés"],
         "answer": 3,
         "explain": "Un collègue a publié entre-temps : Git refuse d'écraser ce travail. Il faut d'abord récupérer et intégrer les commits du distant."},
        {"q": "<code>git status</code> affiche <code>Your branch is behind 'origin/main' by 3 commits, and can be fast-forwarded</code>. Que fait <code>git pull</code> ?",
         "choices": ["Il crée un commit de fusion avec les 3 commits",
                     "Il avance simplement <code>main</code> sur <code>origin/main</code>",
                     "Il rejoue vos 3 commits locaux au-dessus du distant",
                     "Il s'arrête et demande de choisir entre fusion et rebase"],
         "answer": 1,
         "explain": "Vous n'avez aucun commit local en plus : l'historique n'a pas divergé, l'étiquette <code>main</code> avance simplement (fast-forward)."},
        {"q": "Vous avez des commits locaux, et le distant a avancé de son côté. Avec Git 2.39, sans réglage particulier, que fait <code>git pull</code> ?",
         "choices": ["Il s'arrête : il faut choisir entre fusionner et rebaser",
                     "Il fusionne automatiquement, avec un commit de fusion",
                     "Il rebase automatiquement vos commits au-dessus du distant",
                     "Il écrase vos commits locaux par ceux du distant"],
         "answer": 0,
         "explain": "Face à des branches divergentes, Git 2.39 affiche <code>Need to specify how to reconcile divergent branches</code> : <code>--no-rebase</code>, <code>--rebase</code> ou le réglage <code>pull.rebase</code>."},
        {"q": "Que produit <code>git pull --rebase</code> quand vos commits locaux et ceux du distant ont divergé ?",
         "choices": ["Un commit de fusion à deux parents, en tête de <code>main</code>",
                     "Les commits du distant rejoués au-dessus des vôtres",
                     "Vos commits rejoués après ceux du distant, historique linéaire",
                     "Un seul commit qui regroupe vos commits et ceux du distant"],
         "answer": 2,
         "explain": "Le rebase recrée vos commits locaux (nouveaux hash) au-dessus des commits récupérés : pas de commit de fusion inutile."},
        {"q": "Quelle est la différence entre <code>git push --force-with-lease</code> et <code>git push --force</code> ?",
         "choices": ["<code>--force-with-lease</code> ne force que pour une durée limitée",
                     "<code>--force-with-lease</code> demande l'accord des autres développeurs",
                     "<code>--force-with-lease</code> refuse si le distant a des commits que vous n'avez pas vus",
                     "<code>--force-with-lease</code> garde une sauvegarde de l'ancienne branche distante"],
         "answer": 2,
         "explain": "Il vérifie que la branche distante est toujours là où vous l'avez vue pour la dernière fois ; sinon, il refuse au lieu d'écraser le travail d'un collègue."},
        {"q": "Que liste <code>git log --oneline main..origin/main</code> ?",
         "choices": ["Les commits de <code>origin/main</code> absents de <code>main</code>",
                     "Les commits de <code>main</code> absents de <code>origin/main</code>",
                     "Tous les commits de <code>main</code> et de <code>origin/main</code>",
                     "Les commits communs aux deux branches"],
         "answer": 0,
         "explain": "<code>A..B</code> désigne les commits accessibles depuis B mais pas depuis A : ici, ce que le distant a et que votre <code>main</code> n'a pas."},
        {"q": "<code>git pull --rebase</code> refuse de démarrer : <code>cannot pull with rebase: You have unstaged changes</code>. Comment continuer sans perdre ces modifications ?",
         "choices": ["Ajouter <code>--force</code> pour rebaser malgré les modifications",
                     "Ajouter <code>--autostash</code>, qui les met de côté le temps du rebase",
                     "Faire d'abord <code>git restore .</code> pour nettoyer le répertoire",
                     "Faire d'abord <code>git reset --hard</code> puis relancer le pull"],
         "answer": 1,
         "explain": "<code>--autostash</code> range les modifications non commitées, fait le rebase, puis les remet en place. <code>restore</code> et <code>reset --hard</code> les jetteraient."},
        {"q": "En plein rebase, un conflit vous paraît trop compliqué. Quelle commande ramène votre branche à l'état d'avant le rebase ?",
         "choices": ["<code>git rebase --skip</code>",
                     "<code>git restore .</code>",
                     "<code>git merge --abort</code>",
                     "<code>git rebase --abort</code>"],
         "answer": 3,
         "explain": "<code>git rebase --abort</code> annule toute l'opération. <code>--skip</code>, lui, abandonne seulement le commit en conflit et continue le rebase."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    5: [
        {"q": "Qu'est-ce qu'une branche, pour Git ?",
         "choices": ["Une étiquette qui désigne un commit et avance à chaque nouveau commit",
                     "Une copie complète des fichiers du projet, dans un dossier séparé",
                     "Un dépôt distinct, relié au dépôt principal",
                     "Une liste de commits figée au moment de sa création"],
         "answer": 0,
         "explain": "Une branche n'est qu'un pointeur vers un commit. Créer une branche ne copie rien : c'est instantané."},
        {"q": "Après <code>git fetch</code>, vous tapez <code>git checkout origin/promo</code>. Où êtes-vous ?",
         "choices": ["Sur une nouvelle branche locale <code>promo</code>, qui suit <code>origin/promo</code>",
                     "Sur la branche du serveur : vos commits y seront publiés directement",
                     "Sur une tête détachée, sans branche locale",
                     "Toujours sur <code>main</code> : la commande est refusée"],
         "answer": 2,
         "explain": "<code>origin/promo</code> est une référence de suivi, pas une branche de travail : <code>checkout</code> vous place dessus en tête détachée. <code>git switch promo</code> créerait la branche locale."},
        {"q": "<code>main</code> n'a pas bougé depuis la création de <code>feature</code>. Sur <code>main</code>, que fait <code>git merge feature</code> ?",
         "choices": ["Il crée un commit de fusion à deux parents",
                     "Il rejoue les commits de <code>feature</code> avec de nouveaux hash",
                     "Il supprime la branche <code>feature</code> une fois fusionnée",
                     "Il avance <code>main</code> sur le dernier commit de <code>feature</code> (fast-forward)"],
         "answer": 3,
         "explain": "Quand la branche courante est ancêtre de la branche fusionnée, il n'y a rien à combiner : l'étiquette avance simplement."},
        {"q": "Vous avez des modifications non commitées et tapez <code>git reset --hard HEAD~2</code>. Que se passe-t-il ?",
         "choices": ["La branche recule de deux commits ; les modifications non commitées sont conservées",
                     "La branche recule de deux commits ; les modifications non commitées sont perdues",
                     "Les deux derniers commits sont annulés par deux nouveaux commits",
                     "Les deux derniers commits sont définitivement effacés du dépôt"],
         "answer": 1,
         "explain": "<code>reset --hard</code> déplace la branche et aligne les fichiers : le travail non commité est jeté. Les commits retirés restent récupérables un temps par le reflog."},
        {"q": "Vous faites <code>git cherry-pick a1b2c3d</code> sur <code>main</code>. Que devient le commit ?",
         "choices": ["Il est déplacé sur <code>main</code> et disparaît de sa branche d'origine",
                     "Il est copié sur <code>main</code> avec un nouveau hash ; l'original reste en place",
                     "Il est copié sur <code>main</code> avec le même hash",
                     "Il est fusionné avec toute sa branche d'origine"],
         "answer": 1,
         "explain": "<code>cherry-pick</code> rejoue les modifications de ce seul commit sur la branche courante : c'est un nouveau commit, l'original ne bouge pas."},
        {"q": "<code>git branch -d feature/essai</code> répond <code>error: the branch 'feature/essai' is not fully merged</code>. Qu'est-ce que cela signifie ?",
         "choices": ["La branche a été supprimée, mais son travail a été perdu",
                     "La branche n'existe que sur le dépôt distant",
                     "La branche est celle sur laquelle vous vous trouvez",
                     "Son travail n'est pas intégré ; <code>-D</code> forcerait la suppression"],
         "answer": 3,
         "explain": "<code>-d</code> refuse de supprimer une branche dont les commits ne sont pas intégrés (dans sa branche suivie, sinon dans la branche courante), pour éviter de les perdre."},
        {"q": "Que fait <code>git branch correctif a1b2c3d</code> ?",
         "choices": ["Il crée la branche <code>correctif</code> sur <code>a1b2c3d</code>, sans s'y placer",
                     "Il crée la branche <code>correctif</code> sur <code>a1b2c3d</code> et s'y place",
                     "Il déplace la branche courante sur <code>a1b2c3d</code>",
                     "Il copie le commit <code>a1b2c3d</code> sur la branche <code>correctif</code>"],
         "answer": 0,
         "explain": "<code>git branch nom commit</code> pose une nouvelle étiquette ; pour s'y placer, il faut ensuite <code>git switch</code>."},
        {"q": "Avec <code>pull.rebase=true</code>, vous fusionnez localement une branche dans <code>main</code>, sans publier, puis vous faites <code>git pull</code> parce que le distant a avancé. Que devient votre fusion ?",
         "choices": ["Elle est conservée, et une seconde fusion est créée",
                     "Elle est publiée automatiquement sur le distant",
                     "Elle disparaît : ses commits sont rejoués à plat sur <code>origin/main</code>",
                     "Le pull est refusé tant que la fusion n'est pas publiée"],
         "answer": 2,
         "explain": "Le rebase rejoue les commits locaux sans conserver les commits de fusion. D'où la règle : mettre <code>main</code> à jour avant de fusionner."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    6: [
        {"q": "Dans quel cas une fusion s'arrête-t-elle sur un conflit ?",
         "choices": ["Quand le même fichier a été modifié des deux côtés",
                     "Quand la même ligne, ou des lignes voisines, a été modifiée des deux côtés",
                     "Quand deux commits des deux branches ont le même message",
                     "Quand la branche fusionnée est plus ancienne que <code>main</code>"],
         "answer": 1,
         "explain": "Git combine seul les modifications de lignes différentes, même dans un même fichier. Il ne s'arrête que s'il ne peut pas choisir entre deux versions d'une même zone."},
        {"q": "Sur <code>main</code>, vous tapez <code>git merge promo</code> et obtenez un conflit. Que contient la partie entre <code>&lt;&lt;&lt;&lt;&lt;&lt;&lt; HEAD</code> et <code>=======</code> ?",
         "choices": ["La version de <code>promo</code>, la branche fusionnée",
                     "La version d'origine, avant les deux modifications",
                     "La proposition de Git combinant les deux versions",
                     "La version de <code>main</code>, la branche courante"],
         "answer": 3,
         "explain": "<code>HEAD</code> désigne la branche courante : sa version est en haut, celle de la branche fusionnée entre <code>=======</code> et <code>&gt;&gt;&gt;&gt;&gt;&gt;&gt;</code>."},
        {"q": "Vous avez édité un fichier en conflit et supprimé les marqueurs. Qu'est-ce qui termine la fusion ?",
         "choices": ["<code>git merge --continue</code> seul, qui indexe les fichiers",
                     "<code>git merge --abort</code>, qui enregistre la résolution",
                     "<code>git add</code> du fichier, puis <code>git commit</code>",
                     "Rien : Git détecte la disparition des marqueurs"],
         "answer": 2,
         "explain": "<code>git add</code> marque le conflit comme résolu ; <code>git commit</code> (ou <code>git merge --continue</code>) crée ensuite le commit de fusion."},
        {"q": "Pendant une fusion dans <code>main</code>, <code>stock.json</code> est en conflit. Que donne <code>git checkout --ours stock.json</code> ?",
         "choices": ["La version de <code>main</code>, pour tout le fichier",
                     "La version de la branche fusionnée, pour tout le fichier",
                     "La version de <code>main</code>, seulement dans les zones en conflit",
                     "La version d'origine, avant les deux modifications"],
         "answer": 0,
         "explain": "<code>--ours</code> prend le fichier entier de la branche courante. <code>merge -X ours</code>, lui, ne tranche que les zones en conflit."},
        {"q": "Avec <code>merge.conflictStyle zdiff3</code>, que contient la section entre <code>|||||||</code> et <code>=======</code> ?",
         "choices": ["La version de la branche fusionnée",
                     "La version de la branche courante",
                     "La version d'origine, avant les deux modifications",
                     "Les numéros des lignes en conflit"],
         "answer": 2,
         "explain": "Le style <code>zdiff3</code> ajoute l'ancêtre commun : on voit ce que chaque côté a changé par rapport à lui."},
        {"q": "Une fusion publiée a été annulée par <code>git revert -m 1</code>. Des semaines plus tard, on refusionne la même branche, inchangée. Que se passe-t-il ?",
         "choices": ["Ses commits sont réappliqués normalement",
                     "Git refuse : une branche annulée ne peut plus être fusionnée",
                     "Un conflit sur chaque fichier de la branche",
                     "Rien : pour Git, ses commits sont déjà fusionnés"],
         "answer": 3,
         "explain": "L'annulation retire le contenu, pas l'historique : les commits de la branche restent « déjà fusionnés ». Pour les réintégrer, il faut annuler l'annulation."},
        {"q": "Pourquoi met-on <code>main</code> à jour (<code>git pull</code>) avant d'y fusionner une branche ?",
         "choices": ["Pour résoudre les conflits une seule fois, sur la dernière version",
                     "Parce que <code>git merge</code> refuse de fonctionner sans <code>pull</code> préalable",
                     "Pour que la fusion soit toujours un fast-forward",
                     "Pour que Git supprime ensuite la branche fusionnée"],
         "answer": 0,
         "explain": "Fusionner sur un <code>main</code> périmé oblige à résoudre des conflits, puis à les retrouver lors de la synchronisation avec le distant."},
        {"q": "Avec <code>pull.rebase=true</code>, pourquoi intégrer une branche publiée par <code>git merge origin/promo</code> plutôt que par <code>git pull origin promo</code> ?",
         "choices": ["Parce que <code>git pull</code> ne sait pas récupérer d'autres branches que <code>main</code>",
                     "Parce que <code>git pull</code> rebaserait <code>main</code> au-dessus de la branche",
                     "Parce que <code>git merge</code> publie aussi le résultat sur le distant",
                     "Parce que <code>git pull</code> supprimerait la branche distante"],
         "answer": 1,
         "explain": "Avec ce réglage, <code>pull</code> rejoue les commits locaux de <code>main</code> au-dessus de <code>promo</code> : ce n'est pas une fusion, et l'historique est réécrit."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    7: [
        {"q": "Vous avez modifié <code>index.html</code> (suivi) et créé <code>bandeau.css</code> (jamais ajouté). Que fait <code>git stash</code>, sans option ?",
         "choices": ["Il range les deux fichiers et nettoie le répertoire",
                     "Il refuse, à cause du fichier non suivi",
                     "Il range seulement <code>bandeau.css</code>",
                     "Il range <code>index.html</code> ; <code>bandeau.css</code> reste sur place"],
         "answer": 3,
         "explain": "Par défaut, <code>stash</code> ne range que les modifications des fichiers suivis. Il faut <code>-u</code> pour inclure les fichiers non suivis."},
        {"q": "Lesquelles de ces commandes réécrivent l'historique, en remplaçant ou en retirant des commits ? (plusieurs réponses possibles)",
         "choices": ["<code>git revert HEAD</code>",
                     "<code>git commit --amend</code>",
                     "<code>git stash</code>",
                     "<code>git rebase -i HEAD~3</code>"],
         "answer": [1, 3],
         "explain": "<code>--amend</code> remplace le dernier commit par un nouveau ; <code>rebase -i</code> recrée les commits rejoués. <code>revert</code> ajoute un commit, <code>stash</code> ne touche pas à la branche."},
        {"q": "Que fait <code>git reset --soft HEAD~3</code> ?",
         "choices": ["La branche recule de 3 commits ; leurs modifications restent indexées",
                     "La branche recule de 3 commits ; leurs modifications sont jetées",
                     "Trois nouveaux commits annulent les trois derniers",
                     "La branche recule de 3 commits ; leurs modifications sont non indexées"],
         "answer": 0,
         "explain": "<code>--soft</code> déplace seulement l'étiquette : tout le travail des 3 commits est dans l'index, prêt à être recommité en un seul commit."},
        {"q": "Que fait <code>git reset HEAD~1</code>, sans option ?",
         "choices": ["Il supprime le dernier commit et ses modifications",
                     "Il crée un commit qui annule le dernier",
                     "Il retire le dernier commit ; ses modifications restent dans les fichiers, non indexées",
                     "Il retire le dernier commit ; ses modifications restent indexées"],
         "answer": 2,
         "explain": "Le mode par défaut est <code>--mixed</code> : la branche recule et l'index est aligné sur elle, mais le répertoire de travail n'est pas touché."},
        {"q": "La branche <code>ma-branche</code> (commits D et E) est partie d'un ancien <code>main</code>. Sur <code>ma-branche</code>, que produit <code>git rebase main</code> ?",
         "choices": ["Un commit de fusion entre <code>main</code> et <code>ma-branche</code>",
                     "D et E recréés au-dessus de <code>main</code>, avec de nouveaux hash",
                     "D et E déplacés au-dessus de <code>main</code>, avec les mêmes hash",
                     "<code>main</code> avancé jusqu'au commit E"],
         "answer": 1,
         "explain": "Un commit dépend de son parent : rejoués sur une autre base, D et E deviennent de nouveaux commits (D', E'). <code>main</code> ne bouge pas."},
        {"q": "Dans la liste d'un <code>git rebase -i</code>, que fait le mot <code>fixup</code> devant un commit ?",
         "choices": ["Il fond le commit dans le précédent, en gardant seulement le message du précédent",
                     "Il fond le commit dans le précédent, en combinant les deux messages",
                     "Il arrête le rebase sur ce commit pour permettre de le modifier",
                     "Il corrige automatiquement les conflits de ce commit"],
         "answer": 0,
         "explain": "<code>fixup</code> est un <code>squash</code> qui jette le message du commit fondu. <code>edit</code> s'arrêterait sur le commit."},
        {"q": "Dans l'éditeur ouvert par <code>git rebase -i</code>, quel commit figure sur la première ligne ?",
         "choices": ["Le plus récent, comme dans <code>git log</code>",
                     "Le dernier commit de la branche de base",
                     "Le plus ancien des commits à rejouer",
                     "Le commit sur lequel se trouve HEAD"],
         "answer": 2,
         "explain": "La liste est dans l'ordre où les commits seront rejoués : du plus ancien au plus récent, l'inverse de <code>git log</code>."},
        {"q": "Julien a déjà poussé 3 commits sur le <code>main</code> partagé. Il veut les fondre en un seul avec <code>git reset --soft HEAD~3</code> puis un nouveau commit. Quel est le problème ?",
         "choices": ["Git refuse <code>reset --soft</code> sur des commits déjà poussés",
                     "Le nouveau commit sera publié à côté des trois anciens, en double",
                     "Aucun : le prochain <code>git push</code> remplacera simplement les trois commits",
                     "Il réécrit des commits partagés : le push sera refusé sans forcer"],
         "answer": 3,
         "explain": "Règle d'or : on ne réécrit que des commits non partagés. Sinon, le distant refuse le push, et forcer oblige chacun à réaligner son dépôt."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    8: [
        {"q": "Le code marchait il y a 100 commits. Environ combien de tests <code>git bisect</code> demande-t-il au plus pour trouver le commit fautif ?",
         "choices": ["Environ 50",
                     "Environ 10",
                     "Environ 7",
                     "Exactement 100"],
         "answer": 2,
         "explain": "Chaque test coupe l'intervalle en deux : 2<sup>7</sup> = 128 ≥ 100, donc environ 7 tests."},
        {"q": "Avec <code>git bisect run ./tests.sh</code>, le script se termine avec le code 125 sur un commit. Que fait Git ?",
         "choices": ["Il saute ce commit, considéré comme impossible à tester",
                     "Il marque ce commit comme mauvais",
                     "Il marque ce commit comme bon",
                     "Il arrête la recherche"],
         "answer": 0,
         "explain": "Code 0 : bon ; 125 : commit sauté ; de 1 à 127 (sauf 125) : mauvais ; 128 ou plus : arrêt de la recherche."},
        {"q": "Git vient d'afficher <code>a1b2c3d is the first bad commit</code>. Que fait ensuite <code>git bisect reset</code> ?",
         "choices": ["Il supprime le commit fautif de l'historique",
                     "Il recommence la recherche depuis le début",
                     "Il crée une branche sur le commit fautif",
                     "Il termine la recherche et vous ramène où vous étiez"],
         "answer": 3,
         "explain": "Pendant la recherche, Git déplace HEAD de commit en commit. <code>reset</code> termine la session et revient à la branche de départ."},
        {"q": "Quel type d'étiquette crée <code>git tag v2.0</code>, sans option ?",
         "choices": ["Une étiquette annotée, avec auteur, date et message",
                     "Une étiquette légère : un simple nom sur le commit",
                     "Une branche en lecture seule nommée <code>v2.0</code>",
                     "Une étiquette signée avec votre identité Git"],
         "answer": 1,
         "explain": "Sans <code>-a</code>, <code>-m</code> ni <code>-s</code>, l'étiquette est légère. Pour une version livrée, on préfère une étiquette annotée."},
        {"q": "Vous créez l'étiquette <code>v2.0</code> puis tapez <code>git push</code>. L'étiquette est-elle sur le dépôt partagé ?",
         "choices": ["Oui : <code>git push</code> publie les commits et leurs étiquettes",
                     "Non : il faut la pousser explicitement",
                     "Oui, si c'est une étiquette annotée",
                     "Non : une étiquette ne peut pas être publiée"],
         "answer": 1,
         "explain": "Un simple <code>git push</code> ne publie pas les étiquettes : il faut les pousser explicitement, par exemple <code>git push origin v2.0</code>."},
        {"q": "Nadia a remplacé l'étiquette <code>v1.0</code> sur le dépôt partagé. Vous aviez récupéré l'ancienne. Que fait votre <code>git fetch</code> ?",
         "choices": ["Il remplace votre <code>v1.0</code> par la nouvelle",
                     "Il garde les deux, sous les noms <code>v1.0</code> et <code>v1.0-1</code>",
                     "Il supprime votre <code>v1.0</code> sans la remplacer",
                     "Il garde votre ancienne <code>v1.0</code>, sans la remplacer"],
         "answer": 3,
         "explain": "Une étiquette est censée ne jamais bouger : <code>fetch</code> ne remplace pas celle que vous avez déjà (avec <code>--tags</code>, il le signale : <em>would clobber existing tag</em>). Il faut la supprimer ou utiliser <code>git fetch --tags --force</code>."},
        {"q": "Que garde le reflog (<code>git reflog</code>) ?",
         "choices": ["Les positions successives de HEAD dans votre dépôt local",
                     "L'historique des <code>git push</code> reçus par le serveur",
                     "Les commits supprimés par vos collègues",
                     "Les modifications non commitées jetées par <code>reset --hard</code>"],
         "answer": 0,
         "explain": "Le reflog est local : il note chaque position de HEAD (environ 90 jours). Le travail jamais commité, lui, n'y est pas."},
        {"q": "Vous tapez <code>git bisect start</code>, <code>git bisect bad</code>, puis <code>git bisect good v1.0</code>. Que fait alors Git ?",
         "choices": ["Il teste automatiquement chaque commit entre <code>v1.0</code> et HEAD",
                     "Il affiche la liste des commits suspects, sans bouger",
                     "Il se place sur un commit au milieu de l'intervalle, à tester",
                     "Il revient sur <code>v1.0</code> et attend votre verdict"],
         "answer": 2,
         "explain": "Git connaît un bon et un mauvais commit : il se place au milieu et attend <code>good</code> ou <code>bad</code> pour couper encore l'intervalle en deux."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    9: [
        {"q": "Un mot de passe de base de données a été commité et poussé sur le dépôt partagé. Quel est le premier geste ?",
         "choices": ["Réécrire l'historique pour effacer le fichier",
                     "Supprimer le fichier dans un nouveau commit",
                     "Ajouter le fichier au <code>.gitignore</code>",
                     "Révoquer le secret : changer le mot de passe"],
         "answer": 3,
         "explain": "Le secret est déjà copié dans les clones : il faut le considérer comme publié. Le nettoyage de l'historique vient ensuite et ne protège pas les copies existantes."},
        {"q": "Supprimer un fichier <code>.env</code> dans un nouveau commit suffit-il à faire disparaître la clé qu'il contenait ?",
         "choices": ["Oui, s'il est aussi ajouté au <code>.gitignore</code>",
                     "Non : la clé reste lisible dans les commits précédents",
                     "Oui, une fois le commit poussé sur le distant",
                     "Oui : Git ne garde que la dernière version de chaque fichier"],
         "answer": 1,
         "explain": "Chaque commit est un instantané complet : les commits antérieurs contiennent toujours le fichier, visible avec <code>git log -p</code>."},
        {"q": "Le <code>.gitignore</code> à la racine du dépôt contient <code>/local.ini</code>. Quels fichiers sont ignorés ?",
         "choices": ["Seulement <code>local.ini</code> à la racine du dépôt",
                     "Tous les fichiers <code>local.ini</code>, à tous les niveaux",
                     "Le fichier <code>/local.ini</code> à la racine du système",
                     "Tous les fichiers <code>.ini</code> de la racine"],
         "answer": 0,
         "explain": "Un motif qui contient une barre oblique est relatif à l'emplacement du <code>.gitignore</code>. Sans barre, <code>local.ini</code> vaudrait à tous les niveaux."},
        {"q": "Que vise la règle <code>cache/</code> dans un <code>.gitignore</code> ?",
         "choices": ["Seulement le dossier <code>cache</code> à la racine du dépôt",
                     "Tout fichier ou dossier nommé <code>cache</code>, à tous les niveaux",
                     "Les dossiers nommés <code>cache</code>, à tous les niveaux, mais pas un fichier <code>cache</code>",
                     "Le contenu de <code>cache</code>, mais pas le dossier lui-même"],
         "answer": 2,
         "explain": "La barre finale limite la règle aux dossiers ; comme il n'y a pas d'autre barre, elle s'applique à tous les niveaux."},
        {"q": "Le hook <code>.git/hooks/pre-commit</code> (exécutable) se termine avec le code 1. Que se passe-t-il ?",
         "choices": ["Le commit est créé, avec un avertissement",
                     "Le commit est créé, puis annulé au prochain push",
                     "Le hook est ignoré s'il ne produit aucun message",
                     "Le commit n'est pas créé"],
         "answer": 3,
         "explain": "Un code de retour non nul de <code>pre-commit</code> empêche le commit. Seul <code>git commit --no-verify</code> le contourne."},
        {"q": "Vous avez écrit un hook dans <code>.git/hooks/pre-commit</code> et poussé votre branche. Vos collègues l'ont-ils ?",
         "choices": ["Non : le dossier <code>.git/hooks</code> n'est pas versionné",
                     "Oui : les hooks sont publiés avec les commits",
                     "Oui, mais seulement après un <code>git pull</code>",
                     "Non, sauf s'il porte l'extension <code>.sample</code>"],
         "answer": 0,
         "explain": "Le contenu de <code>.git/</code> n'est pas versionné. Pour partager un hook, on le commite (par exemple dans <code>.githooks/</code>) et chacun active <code>git config core.hooksPath .githooks</code>."},
        {"q": "Pourquoi un hook <code>pre-commit</code> doit-il examiner <code>git diff --cached</code> plutôt que les fichiers du disque ?",
         "choices": ["Parce que les fichiers du disque sont verrouillés pendant le commit",
                     "Parce que c'est l'index qui part dans le commit, pas le disque",
                     "Parce que <code>git diff</code> n'est pas disponible dans un hook",
                     "Parce que le hook s'exécute sur le serveur, sans le disque"],
         "answer": 1,
         "explain": "Le disque peut contenir des modifications non indexées, qui ne partiront pas. Ce qui compte, c'est le contenu de l'index."},
        {"q": "Après avoir réécrit l'historique pour effacer un secret, où celui-ci peut-il encore se trouver ? (plusieurs réponses possibles)",
         "choices": ["Dans les clones faits par les collègues avant le nettoyage",
                     "Dans le fichier <code>.gitignore</code> du dépôt",
                     "Dans <code>refs/original/</code>, si vous avez utilisé <code>filter-branch</code>",
                     "Dans le réglage <code>core.hooksPath</code>"],
         "answer": [0, 2],
         "explain": "Réécrire votre dépôt ne touche pas les copies existantes, et <code>filter-branch</code> garde une sauvegarde de l'ancienne histoire. D'où la vérification avec <code>git log --all -p</code>."},
    ],
}
