"""Mémo du parcours Docker : une fiche par commande ou notion, débloquée par un exercice."""
from ..linux.memo import C

BASE, OBS, DATA, BUILD, NETW, COMPOSE, OPS = (
    "Conteneurs", "Observer et agir", "Ports et données", "Images et Dockerfile", "Réseaux",
    "docker compose", "Exploitation",
)

CARDS = [
    C("run", "docker run", BASE, "Crée ET démarre un conteneur à partir d'une image.",
      ["docker run [options] <image> [commande]"],
      [('docker run --name premier alpine echo "Bonjour"', "--name : nom du conteneur"), ("docker run -d nginx:alpine", "-d : en arrière-plan"),
       ("docker run --rm alpine ls /", "--rm : supprimé dès qu'il se termine"), ("docker run -it alpine sh", "shell interactif")], ["D1.1"]),
    C("ps", "docker ps", BASE, "Liste les conteneurs.",
      ["docker ps", "docker ps -a", "docker ps -aq --filter name=<motif>"],
      [("docker ps", "en cours"), ("docker ps -a", "tous, y compris arrêtés"), ("docker ps -aq --filter name=ancien-", "identifiants seulement, filtrés")], ["D1.1"]),
    C("images", "docker images", BASE, "Liste les images disponibles localement.",
      ["docker images", "docker pull <image>"], [("docker images", ""), ("docker pull nginx:alpine", "télécharger une image")], ["D1.1"]),
    C("processus", "Un conteneur = un processus", BASE, "Un conteneur est un processus isolé de l'hôte, pas une machine virtuelle.",
      ["docker top <conteneur>", "docker inspect -f '{{.State.Pid}}' <conteneur>"],
      [("docker top dormeur", "processus vus de l'hôte"), ("ps -p $(docker inspect -f '{{.State.Pid}}' dormeur)", "")], ["D1.2"]),
    C("rm", "docker rm", BASE, "Supprime des conteneurs.",
      ["docker rm <conteneur>...", "docker rm -f <conteneur>", "docker container prune"],
      [("docker rm $(docker ps -aq --filter name=ancien-)", "en lot"), ("docker rm -f api", "arrête puis supprime")], ["D1.3"]),

    C("logs", "docker logs", OBS, "Affiche la sortie du processus principal du conteneur.",
      ["docker logs [-f] [--tail N] <conteneur>"], [("docker logs traitement-nuit", ""), ("docker logs -f --tail 20 api", "en continu")], ["D2.1"]),
    C("stop", "docker stop / start", OBS, "Arrête (SIGTERM puis SIGKILL après 10 s) ou redémarre un conteneur ; il garde fichiers et journaux.",
      ["docker stop <conteneur>", "docker start <conteneur>", "docker restart <conteneur>"], [("docker stop traitement-nuit", "")], ["D2.2"]),
    C("exec", "docker exec", OBS, "Exécute une commande DANS un conteneur qui tourne.",
      ["docker exec <conteneur> <commande>", "docker exec -it <conteneur> sh"],
      [("docker exec coffre cat /secret/cle.txt", ""), ("docker exec -it api sh", "ouvrir un shell dedans")], ["D2.3"]),
    C("inspect", "docker inspect", OBS, "Toute la configuration d'un conteneur (ou d'une image) en JSON ; -f extrait une valeur.",
      ["docker inspect [-f '<modèle>'] <objet>"],
      [("docker inspect -f '{{.Config.Env}}' coffre", "variables d'environnement"),
       ("docker inspect -f '{{.State.Status}}' api", ""), ("docker inspect -f '{{.HostConfig.RestartPolicy.Name}}' api", "")], ["D2.4"]),

    C("ports", "-p : publier un port", DATA, "Rend un port du conteneur joignable depuis l'hôte (hôte:conteneur).",
      ["docker run -p <hôte>:<conteneur> ..."], [("docker run -d --name vitrine -p 8080:80 nginx:alpine", ""), ("docker port vitrine", "ports publiés")], ["D3.1"]),
    C("bind", "Bind mount", DATA, "Partage un dossier de l'hôte avec le conteneur (modifications visibles immédiatement).",
      ["-v /chemin/absolu:/chemin/conteneur[:ro]"],
      [("docker run -d -p 8081:80 -v ~/projet/site:/usr/share/nginx/html:ro nginx:alpine", ":ro = lecture seule")], ["D3.2"]),
    C("volume", "Volumes", DATA, "Stockage géré par Docker, indépendant du conteneur : les données survivent à docker rm.",
      ["docker volume create|ls|inspect|rm <volume>", "-v <volume>:/chemin"],
      [("docker volume create donnees-boutique", ""), ("docker run -d --name cache -v donnees-boutique:/data redis:7-alpine redis-server --appendonly yes", "")], ["D4.1"]),
    C("sauvegarde", "Sauvegarder un volume", DATA, "Un conteneur jetable monte le volume et un dossier de l'hôte, puis archive.",
      ["docker run --rm -v <volume>:/data -v <dossier>:/backup alpine tar czf /backup/x.tar.gz -C /data ."],
      [("docker run --rm -v donnees-boutique:/data -v ~/sauvegardes:/backup alpine tar czf /backup/donnees.tar.gz -C /data .", "")], ["D4.2"]),

    C("dockerfile", "Dockerfile", BUILD, "La recette d'une image : chaque instruction crée une couche.",
      ["FROM <image>", "WORKDIR /app", "COPY <src> <dest>", "RUN <commande>", "USER <utilisateur>", "EXPOSE <port>", 'CMD ["prog", "arg"]'],
      [('FROM node:20-alpine\nWORKDIR /app\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]', "image d'une API Node")], ["D5.1"]),
    C("build", "docker build", BUILD, "Construit une image à partir d'un Dockerfile et d'un contexte (dossier).",
      ["docker build -t <nom:tag> <contexte>", "docker history <image>"],
      [("docker build -t boutique-api:1.0 ~/projet/api", ""), ("docker history boutique-api:1.0", "les couches et leur taille")], ["D5.1"]),
    C("restart", "--restart", BUILD, "Politique de redémarrage automatique d'un conteneur.",
      ["--restart no | on-failure | always | unless-stopped"], [("docker run -d --restart unless-stopped --name api -p 3000:3000 boutique-api:1.0", "")], ["D5.2"]),
    C("dockerignore", ".dockerignore et USER", BUILD, "Exclure du contexte ce qui n'a rien à faire dans l'image ; ne pas exécuter en root.",
      [".dockerignore : un motif par ligne", "USER node"],
      [("node_modules\n.env\n.git", "contenu de .dockerignore"), ("docker run --rm --entrypoint whoami boutique-api:1.0", "vérifier l'utilisateur")], ["D5.3"]),

    C("network", "docker network", NETW, "Sur un réseau créé par vous, les conteneurs se joignent par leur nom.",
      ["docker network create|ls|inspect <réseau>", "docker run --network <réseau> ..."],
      [("docker network create reseau-boutique", ""), ("docker run -d --name redis --network reseau-boutique redis:7-alpine", "")], ["D6.1"]),
    C("env", "-e : variables d'environnement", NETW, "Configure l'application sans reconstruire l'image.",
      ["docker run -e NOM=valeur ...", "docker run --env-file .env ..."], [("docker run -d -e REDIS_HOST=redis --network reseau-boutique boutique-api:1.0", "")], ["D6.1"]),

    C("compose", "compose.yaml", COMPOSE, "Décrit toute l'application : services, images ou build, ports, variables, volumes.",
      ["services:  <nom>: image|build, ports, environment, volumes, depends_on", "volumes:"],
      [("services:\n  api:\n    build: ./api\n    environment:\n      REDIS_HOST: redis\n  redis:\n    image: redis:7-alpine\n    volumes:\n      - donnees:/data\nvolumes:\n  donnees:", "")], ["D7.1"]),
    C("compose-cli", "docker compose (commandes)", COMPOSE, "Piloter la pile décrite dans compose.yaml.",
      ["docker compose up -d [--build]", "docker compose ps | logs [-f] <service> | exec <service> <cmd>", "docker compose down"],
      [("docker compose up -d --build", ""), ("docker compose logs -f api", ""), ("docker compose exec api sh", ""), ("docker compose down", "sans -v : les volumes sont conservés")], ["D7.1"]),
    C("proxy", "Un seul point d'entrée", COMPOSE, "Seul le proxy publie un port ; les autres services restent internes au réseau du projet.",
      ["ports: seulement sur le proxy", "proxy_pass http://<service>:<port>/;"], [("location /api/ { proxy_pass http://api:3000/; }", "nginx")], ["D7.2"]),
    C("healthcheck", "healthcheck et depends_on", COMPOSE, "Démarrer un service seulement quand sa dépendance est prête.",
      ["healthcheck: test: [...]", "depends_on: <service>: condition: service_healthy"],
      [('healthcheck:\n  test: ["CMD", "redis-cli", "ping"]\n  interval: 5s', "sur redis"), ("depends_on:\n  redis:\n    condition: service_healthy", "sur api")], ["D7.3"]),
    C("dotenv", ".env et ${VARIABLE}", COMPOSE, "Compose remplace ${VAR} par les valeurs du fichier .env du projet.",
      ["${VARIABLE}", "docker compose config"], [("APP_VERSION: ${APP_VERSION}", "dans compose.yaml"), ("docker compose config", "voir le résultat")], ["D7.4"]),

    C("diagnostic", "Diagnostiquer une pile", OPS, "Méthode : qui tourne, que disent les logs, quelle configuration est vraiment appliquée ?",
      ["docker compose ps", "docker compose logs <service>", "docker compose config", "docker port <conteneur>"],
      [("docker compose ps", "Restarting = crash en boucle"), ("docker compose exec api env", "variables vues par l'appli")], ["D8.1"]),
    C("prune", "Faire de la place", OPS, "Supprimer ce qui ne sert plus.",
      ["docker system df", "docker image prune", "docker image prune -a", "docker container prune"],
      [("docker image prune", "images pendantes <none>"), ("docker image prune -a", "attention : toutes les images non utilisées !")], ["D8.2"]),
]
