"""Mémo du parcours Docker : une fiche par commande ou notion, débloquée par un exercice."""
from ..linux.memo import C

BASE, OBS, DATA, BUILD, NETW, COMPOSE, OPS = (
    "Conteneurs", "Observer et agir", "Ports et données", "Images et Dockerfile", "Réseaux",
    "docker compose", "Exploitation",
)

CARDS = [
    # ── Conteneurs ─────────────────────────────────────────────────────
    C("run", "docker run", BASE, "Crée ET démarre un conteneur à partir d'une image ; la commande vient après le nom de l'image.",
      ["docker run [options] <image> [commande]"],
      [('docker run --name essai alpine echo "Salut"', "--name : nom du conteneur"), ("docker run -d nginx:alpine", "-d : en arrière-plan"),
       ("docker run --rm alpine ls /", "--rm : supprimé dès qu'il se termine"), ("docker run -it alpine sh", "shell interactif"),
       ('docker run alpine echo "$(cat fichier.txt)"', "le shell remplace $(…) et $VAR AVANT Docker")], ["D1.1"]),
    C("ps", "docker ps", BASE, "Liste les conteneurs.",
      ["docker ps", "docker ps -a", "docker ps -aq"],
      [("docker ps", "en cours"), ("docker ps -a", "tous, y compris arrêtés"), ("docker ps --format '{{.Names}} {{.Status}}'", "colonnes choisies")], ["D1.1"]),
    C("images", "docker images", BASE, "Liste les images disponibles localement (pas d'accès à Internet en salle : pas de docker pull).",
      ["docker images", "docker image ls <nom>", "docker image inspect <image>"], [("docker images", ""), ("docker images nginx", "les versions d'une image")], ["D1.1"]),
    C("processus", "Un conteneur = un processus", BASE, "Un conteneur est un processus isolé de l'hôte, pas une machine virtuelle : il a un PID sur l'hôte, et un autre à l'intérieur.",
      ["docker top <conteneur>", "docker inspect -f '{{.State.Pid}}' <conteneur>"],
      [("docker top veilleur", "processus vus de l'hôte"), ("docker exec veilleur ps", "vus de l'intérieur : PID 1")], ["D1.2"]),
    C("rm", "docker rm", BASE, "Supprime des conteneurs.",
      ["docker rm <conteneur>...", "docker rm -f <conteneur>", "docker container prune"],
      [("docker rm $(docker ps -aq --filter status=exited)", "en lot"), ("docker rm -f api", "arrête puis supprime")], ["D1.3"]),
    C("filtres", "Filtres de docker ps", BASE, "Filtres différents : ET ; valeurs du même filtre : OU. Toujours vérifier la liste avant de supprimer.",
      ["--filter name=<motif>", "--filter status=created|running|exited", "--filter label=<clé>=<valeur>", "--filter publish=<port>", "--filter ancestor=<image>"],
      [("docker ps -a --filter label=projet=demo --filter status=exited --filter status=created", "projet demo ET (exited OU created)"),
       ("docker ps -a --format '{{.Names}} {{.Labels}}'", "voir les labels")], ["D1.3"]),
    C("code-sortie", "Codes de sortie", BASE, "Le code de sortie du processus principal raconte comment le conteneur s'est terminé.",
      ["0 : normal ; 1-125 : erreur du programme", "126 : non exécutable ; 127 : commande introuvable", "128 + n : tué par le signal n (137 = SIGKILL, 143 = SIGTERM)"],
      [("docker ps -a", "STATUS : Exited (137)"), ("docker inspect -f '{{.State.ExitCode}}' essai", "")], ["D1.4", "D2.2"]),
    C("diff", "docker diff", BASE, "Ce qui a changé dans la couche inscriptible d'un conteneur, même arrêté (A ajouté, C modifié, D supprimé).",
      ["docker diff <conteneur>"], [("docker diff essai", ""), ("docker diff essai | grep '^A'", "seulement les ajouts")], ["D1.5", "D2.8"]),
    C("env", "-e : variables d'environnement", BASE, "Configure l'application sans reconstruire l'image ; remplace les valeurs par défaut de l'image (ENV).",
      ["docker run -e NOM=valeur ...", "docker run --env-file fichier ..."],
      [("docker run -d -e DB_HOST=base-demo mon-app:1.0", ""), ("docker exec conteneur printenv NOM", "la valeur vue par l'application")], ["D2.4", "D9.1"]),

    # ── Observer et agir ───────────────────────────────────────────────
    C("logs", "docker logs", OBS, "La sortie du processus principal ; la sortie d'erreur est restituée sur la sortie d'erreur.",
      ["docker logs [-f] [--tail N] <conteneur>", "docker logs <conteneur> 2>&1 | grep …"],
      [("docker logs -f --tail 20 api", "en continu"), ("docker logs traitement 2>&1 | grep -c ERREUR", "compter aussi ce qui est écrit sur stderr")], ["D2.1"]),
    C("stop", "docker stop / start", OBS, "Arrête (SIGTERM puis SIGKILL après 10 s) ou redémarre un conteneur ; il garde fichiers et journaux.",
      ["docker stop [-t secondes] <conteneur>", "docker start <conteneur>", "docker restart <conteneur>"], [("docker stop web-demo", ""), ("docker start -a import", "redémarre et affiche la sortie")], ["D2.2"]),
    C("exec", "docker exec", OBS, "Lance une NOUVELLE commande dans un conteneur qui tourne, avec l'utilisateur du conteneur (ou -u).",
      ["docker exec <conteneur> <commande>", "docker exec -it <conteneur> sh", "docker exec -u root <conteneur> <commande>"],
      [("docker exec web-demo ls /tmp", ""), ("docker exec -u root coffre cat /secret/cle.txt", "autre utilisateur")], ["D2.3"]),
    C("inspect", "docker inspect", OBS, "Toute la configuration d'un conteneur (ou d'une image) en JSON ; -f extrait une valeur.",
      ["docker inspect [-f '<modèle>'] <objet>", "docker image inspect <image>"],
      [("docker inspect -f '{{.Config.Env}}' coffre", "variables du conteneur"), ("docker image inspect -f '{{.Config.Env}}' coffre:1", "valeurs par défaut de l'image"),
       ("docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' api", "adresse IP")], ["D2.4"]),
    C("stats", "docker stats", OBS, "Consommation CPU, mémoire, réseau de chaque conteneur.",
      ["docker stats [--no-stream] [conteneur...]"], [("docker stats --no-stream", "un seul relevé"), ("docker stats --no-stream --format '{{.Name}} {{.MemUsage}}'", "")], ["D2.5"]),
    C("update", "docker update", OBS, "Modifie à chaud les limites et la politique de redémarrage d'un conteneur, sans le recréer.",
      ["docker update --memory <taille> --memory-swap <taille> <conteneur>", "docker update --cpus <n> <conteneur>", "docker update --restart <politique> <conteneur>"],
      [("docker update --memory 256m --memory-swap 256m --cpus 1.5 worker", "mémoire + swap : même valeur")], ["D2.6"]),
    C("attach", "docker attach", OBS, "Branche le terminal sur le processus principal (lancé avec -it) ; Ctrl+P puis Ctrl+Q pour se détacher sans l'arrêter.",
      ["docker attach <conteneur>", "Ctrl+P Ctrl+Q : se détacher"], [("docker run -dit --name console alpine sh", ""), ("docker attach console", "")], ["D2.7"]),
    C("cp", "docker cp", OBS, "Copie des fichiers entre l'hôte et un conteneur, même arrêté, quel que soit l'utilisateur du conteneur.",
      ["docker cp <conteneur>:<chemin> <destination>", "docker cp <source> <conteneur>:<chemin>"],
      [("docker cp web-demo:/etc/nginx/nginx.conf .", ""), ("docker cp generateur:/factures/. ~/factures/", "le contenu d'un dossier")], ["D2.8"]),

    # ── Ports et données ───────────────────────────────────────────────
    C("ports", "-p : publier un port", DATA, "Rend un port du conteneur joignable depuis l'hôte (hôte:conteneur). On ne change pas les ports d'un conteneur existant : on le recrée.",
      ["docker run -p [<ip>:]<hôte>:<conteneur> ..."], [("docker run -d --name demo -p 9000:80 nginx:alpine", ""), ("docker port demo", "ports publiés")], ["D3.1"]),
    C("port-occupe", "Qui occupe ce port ?", DATA, "« port is already allocated » : un autre conteneur publie déjà ce port.",
      ["docker ps --filter publish=<port>", "docker port <conteneur>"], [("docker ps --filter publish=9000 --format '{{.Names}}'", "")], ["D3.3"]),
    C("ecoute-locale", "Publier sur une seule adresse", DATA, "-p écoute par défaut sur toutes les interfaces ; une adresse devant le port restreint l'accès.",
      ["-p 127.0.0.1:<hôte>:<conteneur>"], [("docker run -d -p 127.0.0.1:9000:80 nginx:alpine", "joignable seulement depuis la machine")], ["D3.4"]),
    C("bind", "Bind mount", DATA, "Partage un dossier de l'hôte avec le conteneur (modifications visibles immédiatement). -v nom:… sans / ni ./ monte un VOLUME nommé.",
      ["-v /chemin/absolu:/chemin/conteneur[:ro]", "--mount type=bind,src=…,dst=…,readonly"],
      [("docker run -d -p 9001:80 -v ~/documentation:/usr/share/nginx/html:ro nginx:alpine", ":ro = lecture seule")], ["D3.2"]),
    C("bind-fichier", "Monter un fichier seul", DATA, "Un bind mount de fichier suit l'inode d'origine : sed -i et la plupart des éditeurs créent un nouveau fichier, que le conteneur ne voit pas. Montez plutôt le dossier.",
      ["-v /hote/conf/:/etc/app/conf.d/:ro"], [("ls -i fichier", "l'inode change-t-il ?"), ("docker exec web nginx -s reload", "recharger la configuration")], ["D3.5"]),
    C("droits-uid", "Droits et UID", DATA, "Un bind mount garde les droits de l'hôte, en numéros : le processus du conteneur (ex. nginx, uid 101) doit y avoir accès.",
      ["docker top <conteneur>", "ls -ln <dossier>", "chmod 644 fichiers ; chmod 755 dossiers"], [("docker exec web id nginx", "")], ["D3.6"]),
    C("volume", "Volumes", DATA, "Stockage géré par Docker, indépendant du conteneur : les données survivent à docker rm.",
      ["docker volume create|ls|inspect|rm <volume>", "-v <volume>:/chemin"],
      [("docker volume create demo-data", ""), ("docker run -d --name demo-db -v demo-data:/data redis:7-alpine redis-server --appendonly yes", "")], ["D4.1"]),
    C("sauvegarde", "Sauvegarder un volume", DATA, "Un conteneur jetable monte le volume et un dossier de l'hôte, puis archive.",
      ["docker run --rm -v <volume>:/source -v <dossier>:/dest alpine tar czf /dest/x.tar.gz -C /source ."],
      [("docker run --rm -v demo-data:/source -v ~/archives:/dest alpine tar czf /dest/demo.tar.gz -C /source .", "")], ["D4.2"]),
    C("moteur-root", "Le moteur est root", DATA, "dockerd tourne en root : membre du groupe docker = droits de root. Un conteneur jetable peut rendre des fichiers à leur propriétaire.",
      ["docker run --rm -v <dossier>:/d alpine chown -R <uid>:<gid> /d"], [("docker run --rm -v ~/donnees:/d alpine chown -R $(id -u):$(id -g) /d", "")], ["D4.3"]),
    C("copie-volume", "Copier (« renommer ») un volume", DATA, "Un volume ne se renomme pas : un conteneur jetable monte l'ancien et le nouveau, et copie.",
      ["docker run --rm -v <ancien>:/de -v <nouveau>:/vers alpine cp -a /de/. /vers/"], [("docker volume rm <ancien>", "une fois la copie vérifiée")], ["D4.4"]),

    C("volume-init", "Volume pré-rempli ou bind mount", DATA, "Un volume nommé vide reçoit le contenu de l'image au premier montage ; un bind mount masque ce contenu.",
      ["-v <volume>:/dossier    # copie du contenu de l'image si le volume est vide", "-v /hote:/dossier       # masque le dossier de l'image"],
      [("docker run -d -v demo-conf:/etc/nginx/conf.d nginx:alpine", "le volume garde default.conf"),
       ("docker cp page.html demo:/usr/share/nginx/html/", "écrit dans le volume")], ["D5.1"]),
    C("volume-masque", "Nouvelle image, ancien contenu", DATA, "Un volume n'est rempli qu'une fois : monté sur un contenu livré par l'image, il masque toutes les versions suivantes.",
      ["docker inspect -f '{{range .Mounts}}{{.Name}} -> {{.Destination}}{{end}}' <conteneur>"],
      [("docker run -d --name site site:2", "contenu livré par l'image : rien de monté par-dessus")], ["D5.5"]),
    C("restauration", "Restaurer un volume", DATA, "Extraire l'archive dans le volume AVANT de démarrer le service.",
      ["docker run --rm -v <volume>:/data -v <dossier>:/backup alpine tar xzf /backup/x.tar.gz -C /data"],
      [("docker run --rm -v donnees-demo:/data -v ~/archives:/backup alpine tar xzf /backup/demo.tar.gz -C /data", "")], ["D5.2"]),
    C("volume-prune", "Volumes anonymes", DATA, "Une image qui déclare VOLUME crée un volume anonyme à chaque docker run sans -v ; il survit à docker rm.",
      ["docker volume ls -f dangling=true", "docker rm -v <conteneur>", "docker volume prune [-a]"],
      [("docker volume prune", "volumes anonymes inutilisés seulement"), ("docker volume prune -a", "aussi les volumes nommés inutilisés : danger")], ["D5.3"]),
    C("volume-filtres", "Labels et filtres de volumes", DATA, "Filtrer les volumes par état, nom ou label, y compris par négation.",
      ["docker volume create --label <clé>=<valeur> <volume>", "docker volume ls -f dangling=true -f label=<clé>", "docker volume prune -a --filter 'label!=<clé>=<valeur>'"],
      [("docker volume prune -a -f --filter 'label!=garder=oui'", "tous les volumes inutilisés, sauf les étiquetés")], ["D5.7"]),
    C("read-only", "--read-only et --tmpfs", DATA, "Système de fichiers du conteneur en lecture seule ; tmpfs (en mémoire) là où l'application doit écrire.",
      ["docker run --read-only --tmpfs <dossier> ..."],
      [("docker run -d --read-only --tmpfs /var/cache/nginx --tmpfs /run nginx:alpine", ""), ("docker logs vitrine-ro", "« Read-only file system » : quel dossier ?")], ["D5.4"]),
    C("tmpfs-options", "Options d'un tmpfs", DATA, "Docker monte les tmpfs en noexec, nosuid, nodev : on précise les options après le chemin.",
      ["--tmpfs <dossier>:<options>", "docker exec <conteneur> mount"], [("--tmpfs /cache:size=16m,mode=1777", ""), ("--tmpfs /work:exec", "autoriser l'exécution")], ["D5.6"]),

    # ── Images et Dockerfile ───────────────────────────────────────────
    C("dockerfile", "Dockerfile", BUILD, "La recette d'une image : chaque instruction crée une couche.",
      ["FROM <image>", "WORKDIR /app", "COPY <src> <dest>", "RUN <commande>", "USER <utilisateur>", "EXPOSE <port>", 'CMD ["prog", "arg"]'],
      [('FROM node:20-alpine\nWORKDIR /srv/outil\nCOPY . .\nEXPOSE 8000\nCMD ["node", "index.js"]', "image d'un outil Node")], ["D6.1"]),
    C("build", "docker build", BUILD, "Construit une image à partir d'un Dockerfile et d'un contexte (dossier).",
      ["docker build -t <nom:tag> <contexte>", "docker history <image>"],
      [("docker build -t outil:1.0 ~/outil", ""), ("docker history outil:1.0", "les couches et leur taille")], ["D6.1"]),
    C("dockerignore", ".dockerignore et USER", BUILD, "Exclure du contexte ce qui n'a rien à faire dans l'image ; ne pas exécuter en root.",
      [".dockerignore : un motif par ligne", "USER node"],
      [("node_modules\n.env\n.git", "contenu de .dockerignore"), ("docker run --rm --entrypoint whoami outil:1.0", "vérifier l'utilisateur")], ["D6.3"]),
    C("healthcheck-image", "HEALTHCHECK", BUILD, "Une commande exécutée régulièrement DANS le conteneur : code 0 = healthy. Elle doit exister dans l'image.",
      ["HEALTHCHECK [--interval=…] [--timeout=…] [--retries=…] CMD <commande>"],
      [("HEALTHCHECK --interval=30s CMD wget -q --spider http://localhost/ || exit 1", "Alpine : wget, pas curl"), ("docker inspect -f '{{json .State.Health}}' web", "")], ["D6.5"]),
    C("commit", "Dockerfile plutôt que commit", BUILD, "docker commit fige un conteneur en image : impossible à refaire. Une image se décrit dans un Dockerfile.",
      ["docker diff <conteneur>", "docker cp <conteneur>:<fichier> .", "docker build -t <image> ."],
      [("docker commit essai essai:1", "à éviter : personne ne sait refaire cette image")], ["D6.6"]),

    C("cache", "Cache de construction", BUILD, "Une couche est reprise du cache si elle et toutes les précédentes sont inchangées : ce qui change rarement en premier.",
      ["COPY package.json package-lock.json ./", "RUN npm ci --omit=dev --no-audit --no-fund", "COPY . .", "docker build --progress=plain ..."],
      [("docker build --progress=plain -t outil:1.0 .", "CACHED = couche réutilisée")], ["D7.1"]),
    C("pid1", "Forme exec et PID 1", BUILD, "docker stop envoie SIGTERM au PID 1 : ce doit être l'application, pas un shell.",
      ['CMD ["prog", "arg"]      # forme exec', "exec prog               # dernière ligne d'un script de démarrage"],
      [("docker top pointeuse", "qui est le PID 1 ?"), ("time docker stop pointeuse", "10 s = signal ignoré (code 137)")], ["D7.2"]),
    C("entrypoint", "ENTRYPOINT et CMD", BUILD, "ENTRYPOINT : le programme ; CMD : ses arguments par défaut, remplacés par ceux de docker run.",
      ['ENTRYPOINT ["prog"]', 'CMD ["--option", "défaut"]', "docker run --entrypoint <prog> ..."],
      [('ENTRYPOINT ["ping"]\nCMD ["-c", "3", "localhost"]', ""), ("docker run --rm pingeur -c 1 cimes.local", "remplace le CMD")], ["D7.3"]),
    C("script-entree", "Script d'entrée", BUILD, "Un script ENTRYPOINT prépare l'environnement, puis se fait remplacer par la commande reçue (le CMD).",
      ['#!/bin/sh\n# … préparation …\nexec "$@"', 'ENTRYPOINT ["./demarrage.sh"]\nCMD ["node", "server.js"]'],
      [("docker run --rm image cat /tmp/config.json", "déboguer : la commande remplace le CMD")], ["D7.5"]),
    C("init", "--init", BUILD, "Un PID 1 sans gestionnaire de SIGTERM ignore le signal ; --init place tini en PID 1, qui le transmet.",
      ["docker run --init ...", "init: true   # dans compose"], [("docker run -d --init --name rapports rapports:1.0", "")], ["D7.6"]),
    C("arg", "ARG, ENV et LABEL", BUILD, "ARG : variable de construction ; ENV : présente à l'exécution ; LABEL : métadonnée de l'image.",
      ["ARG NOM=défaut", "ENV NOM=$NOM", "LABEL clé=valeur", "docker build --build-arg NOM=valeur ..."],
      [("docker build --build-arg REVISION=a1b2c3 -t outil:a1b2c3 .", ""), ("docker image inspect -f '{{json .Config.Labels}}' outil:a1b2c3", "")], ["D7.4"]),
    C("tag", "docker tag", BUILD, "Un tag est une étiquette mobile sur un identifiant d'image ; latest n'est que le tag par défaut. Un conteneur garde son image.",
      ["docker tag <source> <cible>", "docker images <nom>"], [("docker tag outil:1.2 outil:latest", "latest désigne maintenant la 1.2")], ["D7.7"]),
    C("multistage", "Multi-stage", BUILD, "Construire avec les outils dans une étape, ne garder que le résultat dans l'image finale.",
      ["FROM <image> AS <étape>", "COPY --from=<étape> <src> <dest>"],
      [("FROM node:20-alpine AS outils\nRUN node compiler-doc.js\nFROM nginx:alpine\nCOPY --from=outils /build/html/ /usr/share/nginx/html/", "")], ["D8.1"]),
    C("couches", "Couches, history et save", BUILD, "Une image garde toutes ses couches : un fichier supprimé plus loin reste lisible (et pèse), les ARG restent dans l'historique.",
      ["docker history --no-trunc <image>", "docker save <image> -o image.tar"],
      [("docker history --no-trunc vieille-image:2.3", "commandes complètes et ARG"), ("tar -xf image.tar ; tar -tf blobs/sha256/<empreinte>", "contenu d'une couche")], ["D8.2", "D8.3"]),
    C("taille", "Alléger une image", BUILD, "Créer, utiliser et supprimer un fichier de travail dans le MÊME RUN, ou dans une étape séparée.",
      ["RUN créer && utiliser && supprimer", "COPY --from=<étape> <résultat> <dest>"],
      [("docker image inspect -f '{{.Size}}' image", "taille en octets"), ("docker history image", "quelle couche pèse ?")], ["D8.6"]),
    C("secret", "Secrets de construction", BUILD, "Fournir un secret à un seul RUN, sans l'écrire dans une couche ni dans l'historique… à condition de ne pas le recopier.",
      ["RUN --mount=type=secret,id=<id> <commande utilisant /run/secrets/<id>>", "docker build --secret id=<id>,src=$HOME/<fichier> ..."],
      [("docker build --secret id=jeton_api,src=$HOME/secrets/api.txt -t outil:1.0 .", ""), ("docker save outil:1.0 | grep -a <secret>", "vérifier l'absence de fuite")], ["D8.4", "D8.5"]),
    C("save-load", "Livrer une image sans registre", BUILD, "docker save : l'image complète (couches, configuration, tags) ; docker export : seulement les fichiers d'un conteneur.",
      ["docker save <image> | gzip > image.tar.gz", "docker load < image.tar.gz"], [("docker save outil:1.0 | gzip > outil.tar.gz", "")], ["D8.7"]),

    # ── Réseaux ────────────────────────────────────────────────────────
    C("network", "docker network", NETW, "Sur un réseau créé par vous, les conteneurs se joignent par leur nom (jamais par une adresse IP).",
      ["docker network create|ls|inspect <réseau>", "docker run --network <réseau> ..."],
      [("docker network create reseau-demo", ""), ("docker run -d --name base-demo --network reseau-demo redis:7-alpine", "")], ["D9.1"]),
    C("network-connect", "Brancher un conteneur à chaud", NETW, "Un conteneur peut rejoindre (ou quitter) un réseau sans être recréé ; le réseau bridge par défaut ne résout aucun nom.",
      ["docker network connect <réseau> <conteneur>", "docker network disconnect <réseau> <conteneur>"],
      [("docker network connect reseau-demo ancien-conteneur", "")], ["D9.2"]),
    C("reseau-interne", "Réseau interne", NETW, "Un réseau sans passerelle vers l'extérieur ; le conteneur qui doit être publié se branche sur deux réseaux.",
      ["docker network create --internal <réseau>"], [("docker network inspect -f '{{.Internal}}' donnees", "")], ["D9.3"]),
    C("alias", "Alias réseau", NETW, "Des noms supplémentaires sur un réseau ; plusieurs conteneurs peuvent partager un alias.",
      ["docker run --network <réseau> --network-alias <nom> ...", "docker network connect --alias <nom> <réseau> <conteneur>"],
      [("docker run -d --network reseau-demo --network-alias web nginx:alpine", "")], ["D9.4", "D9.5"]),
    C("diag-reseau", "Diagnostiquer un réseau", NETW, "Deux questions : un réseau commun ? le nom existe-t-il, vu du conteneur ?",
      ["docker exec <conteneur> nslookup <nom>", "docker inspect -f '{{json .NetworkSettings.Networks}}' <conteneur>"],
      [("docker exec app-demo nslookup base-demo", ""), ("docker exec app-demo env", "la configuration vue par l'application")], ["D9.4"]),

    # ── docker compose ─────────────────────────────────────────────────
    C("compose", "compose.yaml", COMPOSE, "Décrit toute l'application : services, images ou build, ports, variables, volumes.",
      ["services:  <nom>: image|build, ports, environment, volumes, depends_on", "volumes:"],
      [("services:\n  back:\n    build: ./back\n    environment:\n      DB_HOST: base\n  base:\n    image: redis:7-alpine\n    volumes:\n      - base-donnees:/data\nvolumes:\n  base-donnees:", "")], ["D10.1"]),
    C("compose-cli", "docker compose (commandes)", COMPOSE, "Piloter la pile décrite dans compose.yaml.",
      ["docker compose up -d [--build]", "docker compose ps | logs [-f] <service> | exec <service> <cmd>", "docker compose down"],
      [("docker compose up -d --build", ""), ("docker compose logs -f back", ""), ("docker compose exec back sh", ""), ("docker compose down", "sans -v : les volumes nommés sont conservés")], ["D10.1"]),
    C("proxy", "Un seul point d'entrée", COMPOSE, "Seul le proxy publie un port ; les autres services restent internes au réseau du projet.",
      ["ports: seulement sur le proxy", "proxy_pass http://<service>:<port>/;", "depends_on: le service visé doit exister au démarrage de nginx"],
      [("location /api/ { proxy_pass http://back:8000/; }", "nginx")], ["D10.2"]),
    C("healthcheck", "healthcheck et depends_on", COMPOSE, "Démarrer un service seulement quand sa dépendance est prête.",
      ["healthcheck: test: [...]", "depends_on: <service>: condition: service_healthy"],
      [('healthcheck:\n  test: ["CMD", "wget", "-q", "--spider", "http://localhost:8000/"]\n  interval: 5s', ""), ("depends_on:\n  back:\n    condition: service_healthy", "")], ["D10.3"]),
    C("dotenv", ".env et ${VARIABLE}", COMPOSE, "Compose remplace ${VAR} par les valeurs du fichier .env du projet.",
      ["${VARIABLE}", "env_file: <fichier>", "docker compose config"], [("APP_VERSION: ${APP_VERSION}", "dans compose.yaml"), ("docker compose config", "voir le résultat")], ["D10.4"]),
    C("profils", "Profils", COMPOSE, "Un service rattaché à un profil n'existe que si le profil est activé.",
      ["profiles: [<profil>]", "docker compose --profile <profil> run --rm <service> <cmd>"],
      [("docker compose --profile debug run --rm outils sh", "ponctuel, supprimé après usage")], ["D10.5"]),
    C("volumes-compose", "Volumes nommés et down", COMPOSE, "Un volume nommé (section volumes: de premier niveau) survit à docker compose down ; un volume anonyme est remplacé au prochain up.",
      ["volumes:\n  - donnees:/data", "volumes:\n  donnees:"], [("docker compose down -v", "supprime AUSSI les volumes nommés")], ["D10.6"]),

    # ── Exploitation ───────────────────────────────────────────────────
    C("restart", "--restart", OPS, "Politique de redémarrage automatique d'un conteneur.",
      ["--restart no | on-failure[:N] | always | unless-stopped"], [("docker run -d --restart unless-stopped --name api -p 3000:3000 boutique-api:1.0", "")], ["D6.2"]),
    C("crash-boucle", "Crash en boucle", OPS, "« Restarting (code) » : le programme plante et Docker le relance ; on lit les logs et on borne les tentatives.",
      ["docker inspect -f '{{.RestartCount}}' <conteneur>", "--restart on-failure:<N>"], [("docker logs synchro", "pourquoi plante-t-il ?")], ["D6.4"]),
    C("update-restart", "Politique de redémarrage à chaud", OPS, "La politique d'un conteneur existant se change sans le recréer ; always et unless-stopped reviennent après un redémarrage du moteur.",
      ["docker update --restart <politique> <conteneur>..."], [("docker update --restart unless-stopped web base", ""), ("docker update --restart no outil", "")], ["D11.4"]),
    C("diagnostic", "Diagnostiquer une pile", OPS, "Méthode : qui tourne, que disent les logs, quelle configuration est vraiment appliquée ?",
      ["docker compose ps -a", "docker compose logs <service>", "docker compose config", "docker port <conteneur>"],
      [("docker compose ps -a", "Restarting = crash en boucle"), ("docker compose exec api env", "variables vues par l'appli")], ["D11.1"]),
    C("oom", "Limite mémoire et OOM", OPS, "Au-delà de sa limite, le processus est tué par le noyau (code 137, sans message) : OOMKilled dans docker inspect.",
      ["docker run --memory <taille> --memory-swap <taille> ...", "docker inspect -f '{{.State.OOMKilled}}' <conteneur>"],
      [("docker update --memory 256m --memory-swap 256m import", "puis docker start")], ["D11.3"]),
    C("prune", "Faire de la place", OPS, "Supprimer ce qui ne sert plus ; prune ne supprime jamais ce qu'un conteneur, même arrêté, utilise.",
      ["docker system df", "docker image prune", "docker image prune -a", "docker container prune", "docker builder prune"],
      [("docker image prune", "images pendantes <none>"), ("docker ps -a --filter ancestor=<id>", "qui utilise cette image ?"), ("docker image prune -a", "attention : toutes les images non utilisées !")], ["D11.2"]),
]
