"""Mémo du parcours Docker : une fiche par commande ou notion, débloquée par un exercice."""
from ..linux.memo import C

BASE, OBS, DATA, BUILD, NETW, COMPOSE, OPS = (
    "Conteneurs", "Observer et agir", "Ports et données", "Images et Dockerfile", "Réseaux",
    "docker compose", "Exploitation",
)

CARDS = [
    C("run", "docker run", BASE, "Crée ET démarre un conteneur à partir d'une image.",
      ["docker run [options] <image> [commande]"],
      [('docker run --name premier alpine echo "Bonjour"', "--name : nom du conteneur"), ("docker run -d nginx:alpine", "-d : en arrière-plan"),
       ("docker run --rm alpine ls /", "--rm : supprimé dès qu'il se termine"), ("docker run -it alpine sh", "shell interactif")], ["D1.1"]),
    C("ps", "docker ps", BASE, "Liste les conteneurs.",
      ["docker ps", "docker ps -a", "docker ps -aq --filter name=<motif>"],
      [("docker ps", "en cours"), ("docker ps -a", "tous, y compris arrêtés"), ("docker ps -aq --filter name=ancien-", "identifiants seulement, filtrés")], ["D1.1"]),
    C("images", "docker images", BASE, "Liste les images disponibles localement.",
      ["docker images", "docker pull <image>"], [("docker images", ""), ("docker pull nginx:alpine", "télécharger une image")], ["D1.1"]),
    C("processus", "Un conteneur = un processus", BASE, "Un conteneur est un processus isolé de l'hôte, pas une machine virtuelle.",
      ["docker top <conteneur>", "docker inspect -f '{{.State.Pid}}' <conteneur>"],
      [("docker top dormeur", "processus vus de l'hôte"), ("ps -p $(docker inspect -f '{{.State.Pid}}' dormeur)", "")], ["D1.2"]),
    C("rm", "docker rm", BASE, "Supprime des conteneurs.",
      ["docker rm <conteneur>...", "docker rm -f <conteneur>", "docker container prune"],
      [("docker rm $(docker ps -aq --filter name=ancien-)", "en lot"), ("docker rm -f api", "arrête puis supprime")], ["D1.3"]),

    C("logs", "docker logs", OBS, "Affiche la sortie du processus principal du conteneur.",
      ["docker logs [-f] [--tail N] <conteneur>"], [("docker logs traitement-nuit", ""), ("docker logs -f --tail 20 api", "en continu")], ["D2.1"]),
    C("stop", "docker stop / start", OBS, "Arrête (SIGTERM puis SIGKILL après 10 s) ou redémarre un conteneur ; il garde fichiers et journaux.",
      ["docker stop <conteneur>", "docker start <conteneur>", "docker restart <conteneur>"], [("docker stop traitement-nuit", "")], ["D2.2"]),
    C("exec", "docker exec", OBS, "Exécute une commande DANS un conteneur qui tourne.",
      ["docker exec <conteneur> <commande>", "docker exec -it <conteneur> sh"],
      [("docker exec coffre cat /secret/cle.txt", ""), ("docker exec -it api sh", "ouvrir un shell dedans")], ["D2.3"]),
    C("inspect", "docker inspect", OBS, "Toute la configuration d'un conteneur (ou d'une image) en JSON ; -f extrait une valeur.",
      ["docker inspect [-f '<modèle>'] <objet>"],
      [("docker inspect -f '{{.Config.Env}}' coffre", "variables d'environnement"),
       ("docker inspect -f '{{.State.Status}}' api", ""), ("docker inspect -f '{{.HostConfig.RestartPolicy.Name}}' api", "")], ["D2.4"]),

    C("ports", "-p : publier un port", DATA, "Rend un port du conteneur joignable depuis l'hôte (hôte:conteneur).",
      ["docker run -p <hôte>:<conteneur> ..."], [("docker run -d --name vitrine -p 8080:80 nginx:alpine", ""), ("docker port vitrine", "ports publiés")], ["D3.1"]),
    C("bind", "Bind mount", DATA, "Partage un dossier de l'hôte avec le conteneur (modifications visibles immédiatement).",
      ["-v /chemin/absolu:/chemin/conteneur[:ro]"],
      [("docker run -d -p 8081:80 -v ~/projet/site:/usr/share/nginx/html:ro nginx:alpine", ":ro = lecture seule")], ["D3.2"]),
    C("volume", "Volumes", DATA, "Stockage géré par Docker, indépendant du conteneur : les données survivent à docker rm.",
      ["docker volume create|ls|inspect|rm <volume>", "-v <volume>:/chemin"],
      [("docker volume create donnees-boutique", ""), ("docker run -d --name cache -v donnees-boutique:/data redis:7-alpine redis-server --appendonly yes", "")], ["D4.1"]),
    C("sauvegarde", "Sauvegarder un volume", DATA, "Un conteneur jetable monte le volume et un dossier de l'hôte, puis archive.",
      ["docker run --rm -v <volume>:/data -v <dossier>:/backup alpine tar czf /backup/x.tar.gz -C /data ."],
      [("docker run --rm -v donnees-boutique:/data -v ~/sauvegardes:/backup alpine tar czf /backup/donnees.tar.gz -C /data .", "")], ["D4.2"]),

    C("volume-init", "Volume pré-rempli ou bind mount", DATA, "Un volume nommé vide reçoit le contenu de l'image au premier montage ; un bind mount masque ce contenu.",
      ["-v <volume>:/dossier    # copie du contenu de l'image si le volume est vide", "-v /hote:/dossier       # masque le dossier de l'image"],
      [("docker run -d -v html-vitrine:/usr/share/nginx/html nginx:alpine", "le volume garde la page de nginx"),
       ("docker cp promo.html vitrine-pleine:/usr/share/nginx/html/", "écrit dans le volume")], ["D5.1"]),
    C("restauration", "Restaurer un volume", DATA, "Extraire l'archive dans le volume AVANT de démarrer le service.",
      ["docker run --rm -v <volume>:/data -v <dossier>:/backup alpine tar xzf /backup/x.tar.gz -C /data"],
      [("docker run --rm -v donnees-restaurees:/data -v ~/sauvegardes:/backup alpine tar xzf /backup/cache-avant-migration.tar.gz -C /data", "")], ["D5.2"]),
    C("volume-prune", "Volumes anonymes", DATA, "Une image qui déclare VOLUME crée un volume anonyme à chaque docker run sans -v ; il survit à docker rm.",
      ["docker volume ls -f dangling=true", "docker rm -v <conteneur>", "docker volume prune [-a]"],
      [("docker volume prune", "volumes anonymes inutilisés seulement"), ("docker volume prune -a", "aussi les volumes nommés inutilisés : danger")], ["D5.3"]),
    C("read-only", "--read-only et --tmpfs", DATA, "Système de fichiers du conteneur en lecture seule ; tmpfs (en mémoire) là où l'application doit écrire.",
      ["docker run --read-only --tmpfs <dossier> ..."],
      [("docker run -d --read-only --tmpfs /var/cache/nginx --tmpfs /run -p 8083:80 nginx:alpine", ""), ("docker logs vitrine-ro", "« Read-only file system » : quel dossier ?")], ["D5.4"]),

    C("dockerfile", "Dockerfile", BUILD, "La recette d'une image : chaque instruction crée une couche.",
      ["FROM <image>", "WORKDIR /app", "COPY <src> <dest>", "RUN <commande>", "USER <utilisateur>", "EXPOSE <port>", 'CMD ["prog", "arg"]'],
      [('FROM node:20-alpine\nWORKDIR /app\nCOPY . .\nEXPOSE 3000\nCMD ["node", "server.js"]', "image d'une API Node")], ["D6.1"]),
    C("build", "docker build", BUILD, "Construit une image à partir d'un Dockerfile et d'un contexte (dossier).",
      ["docker build -t <nom:tag> <contexte>", "docker history <image>"],
      [("docker build -t boutique-api:1.0 ~/projet/api", ""), ("docker history boutique-api:1.0", "les couches et leur taille")], ["D6.1"]),
    C("restart", "--restart", BUILD, "Politique de redémarrage automatique d'un conteneur.",
      ["--restart no | on-failure | always | unless-stopped"], [("docker run -d --restart unless-stopped --name api -p 3000:3000 boutique-api:1.0", "")], ["D6.2"]),
    C("dockerignore", ".dockerignore et USER", BUILD, "Exclure du contexte ce qui n'a rien à faire dans l'image ; ne pas exécuter en root.",
      [".dockerignore : un motif par ligne", "USER node"],
      [("node_modules\n.env\n.git", "contenu de .dockerignore"), ("docker run --rm --entrypoint whoami boutique-api:1.0", "vérifier l'utilisateur")], ["D6.3"]),

    C("cache", "Cache de construction", BUILD, "Une couche est reprise du cache si elle et toutes les précédentes sont inchangées : ce qui change rarement en premier.",
      ["COPY package.json package-lock.json ./", "RUN npm ci --omit=dev", "COPY . .", "docker build --progress=plain ..."],
      [("docker build --progress=plain -t boutique-api:1.0 .", "CACHED = couche réutilisée")], ["D7.1"]),
    C("pid1", "Forme exec et PID 1", BUILD, "docker stop envoie SIGTERM au PID 1 : ce doit être l'application, pas un shell.",
      ['CMD ["prog", "arg"]      # forme exec', "exec prog               # dans un script de démarrage"],
      [("docker top pointeuse", "qui est le PID 1 ?"), ("time docker stop pointeuse", "10 s = signal ignoré (code 137)")], ["D7.2"]),
    C("entrypoint", "ENTRYPOINT et CMD", BUILD, "ENTRYPOINT : le programme ; CMD : ses arguments par défaut, remplacés par ceux de docker run.",
      ['ENTRYPOINT ["prog"]', 'CMD ["--option", "défaut"]', "docker run --entrypoint <prog> ..."],
      [('ENTRYPOINT ["node", "export.js"]\nCMD ["--format", "texte"]', ""), ("docker run --rm export-produits:1.0 --format csv", "remplace le CMD")], ["D7.3"]),
    C("arg", "ARG, ENV et LABEL", BUILD, "ARG : variable de construction ; ENV : présente à l'exécution ; LABEL : métadonnée de l'image.",
      ["ARG NOM=défaut", "ENV NOM=$NOM", "LABEL clé=valeur", "docker build --build-arg NOM=valeur ..."],
      [("docker build --build-arg APP_VERSION=1.1 -t boutique-api:1.1 .", ""), ("docker image inspect -f '{{json .Config.Labels}}' boutique-api:1.1", "")], ["D7.4"]),
    C("multistage", "Multi-stage", BUILD, "Construire avec les outils dans une étape, ne garder que le résultat dans l'image finale.",
      ["FROM <image> AS <étape>", "COPY --from=<étape> <src> <dest>"],
      [("FROM node:20-alpine AS construction\nRUN node generer.js\nFROM nginx:alpine\nCOPY --from=construction /src/dist/ /usr/share/nginx/html/", "")], ["D8.1"]),
    C("couches", "Couches, history et save", BUILD, "Une image garde toutes ses couches : un fichier supprimé plus loin reste lisible, les ARG restent dans l'historique.",
      ["docker history --no-trunc <image>", "docker save <image> -o image.tar"],
      [("docker history --no-trunc ancienne-api:0.9", "commandes complètes et ARG"), ("tar -xf image.tar ; tar -tf blobs/sha256/<empreinte>", "contenu d'une couche")], ["D8.2", "D8.3"]),
    C("secret", "Secrets de construction", BUILD, "Fournir un secret à un seul RUN, sans l'écrire dans une couche ni dans l'historique.",
      ["RUN --mount=type=secret,id=<id> <commande utilisant /run/secrets/<id>>", "docker build --secret id=<id>,src=<fichier> ..."],
      [("docker build --secret id=licence,src=$HOME/licences/reassort.txt -t outil-reassort:1.0 .", "")], ["D8.4"]),

    C("network", "docker network", NETW, "Sur un réseau créé par vous, les conteneurs se joignent par leur nom.",
      ["docker network create|ls|inspect <réseau>", "docker run --network <réseau> ..."],
      [("docker network create reseau-boutique", ""), ("docker run -d --name redis --network reseau-boutique redis:7-alpine", "")], ["D9.1"]),
    C("env", "-e : variables d'environnement", NETW, "Configure l'application sans reconstruire l'image.",
      ["docker run -e NOM=valeur ...", "docker run --env-file .env ..."], [("docker run -d -e REDIS_HOST=redis --network reseau-boutique boutique-api:1.0", "")], ["D9.1"]),

    C("network-connect", "Brancher un conteneur à chaud", NETW, "Un conteneur peut rejoindre (ou quitter) un réseau sans être recréé ; le réseau bridge par défaut ne résout aucun nom.",
      ["docker network connect <réseau> <conteneur>", "docker network disconnect <réseau> <conteneur>"],
      [("docker network connect reseau-legacy legacy-web", "")], ["D9.2"]),

    C("compose", "compose.yaml", COMPOSE, "Décrit toute l'application : services, images ou build, ports, variables, volumes.",
      ["services:  <nom>: image|build, ports, environment, volumes, depends_on", "volumes:"],
      [("services:\n  api:\n    build: ./api\n    environment:\n      REDIS_HOST: redis\n  redis:\n    image: redis:7-alpine\n    volumes:\n      - donnees:/data\nvolumes:\n  donnees:", "")], ["D10.1"]),
    C("compose-cli", "docker compose (commandes)", COMPOSE, "Piloter la pile décrite dans compose.yaml.",
      ["docker compose up -d [--build]", "docker compose ps | logs [-f] <service> | exec <service> <cmd>", "docker compose down"],
      [("docker compose up -d --build", ""), ("docker compose logs -f api", ""), ("docker compose exec api sh", ""), ("docker compose down", "sans -v : les volumes sont conservés")], ["D10.1"]),
    C("proxy", "Un seul point d'entrée", COMPOSE, "Seul le proxy publie un port ; les autres services restent internes au réseau du projet.",
      ["ports: seulement sur le proxy", "proxy_pass http://<service>:<port>/;"], [("location /api/ { proxy_pass http://api:3000/; }", "nginx")], ["D10.2"]),
    C("healthcheck", "healthcheck et depends_on", COMPOSE, "Démarrer un service seulement quand sa dépendance est prête.",
      ["healthcheck: test: [...]", "depends_on: <service>: condition: service_healthy"],
      [('healthcheck:\n  test: ["CMD", "redis-cli", "ping"]\n  interval: 5s', "sur redis"), ("depends_on:\n  redis:\n    condition: service_healthy", "sur api")], ["D10.3"]),
    C("dotenv", ".env et ${VARIABLE}", COMPOSE, "Compose remplace ${VAR} par les valeurs du fichier .env du projet.",
      ["${VARIABLE}", "docker compose config"], [("APP_VERSION: ${APP_VERSION}", "dans compose.yaml"), ("docker compose config", "voir le résultat")], ["D10.4"]),

    C("diagnostic", "Diagnostiquer une pile", OPS, "Méthode : qui tourne, que disent les logs, quelle configuration est vraiment appliquée ?",
      ["docker compose ps", "docker compose logs <service>", "docker compose config", "docker port <conteneur>"],
      [("docker compose ps", "Restarting = crash en boucle"), ("docker compose exec api env", "variables vues par l'appli")], ["D11.1"]),
    C("prune", "Faire de la place", OPS, "Supprimer ce qui ne sert plus.",
      ["docker system df", "docker image prune", "docker image prune -a", "docker container prune"],
      [("docker image prune", "images pendantes <none>"), ("docker image prune -a", "attention : toutes les images non utilisées !")], ["D11.2"]),
]
