"""QCM de fin de cours du parcours Docker : 8 questions par étape, 4 tirées au sort pour chaque étudiant."""

QUIZ = {
    # ─────────────────────────────────────────────────────────────────────
    1: [
        {"q": "Vous lancez <code>docker run alpine echo \"Salut\"</code>, puis <code>docker ps</code>. Qu'affiche <code>docker ps</code> à propos de ce conteneur ?",
         "choices": ["Rien : il est terminé, seul <code>docker ps -a</code> le montre encore",
                     "Le conteneur, à l'état <em>Up</em>, puisqu'il n'a pas été supprimé",
                     "Rien : un conteneur est supprimé dès que sa commande se termine",
                     "Le conteneur, à l'état <em>Exited (0)</em>, puisqu'il existe toujours"],
         "answer": 0,
         "explain": "<code>docker ps</code> ne liste que les conteneurs en cours d'exécution. Le conteneur, terminé, existe toujours (état Exited) jusqu'à son <code>docker rm</code> : <code>docker ps -a</code> le montre."},
        {"q": "<code>docker ps -a</code> affiche <code>Exited (143)</code> pour un conteneur. Que s'est-il passé ?",
         "choices": ["Le programme a signalé lui-même une erreur, numérotée 143",
                     "Le processus a été tué par le signal 15 (SIGTERM)",
                     "La commande demandée était introuvable dans l'image",
                     "Le processus a été tué par le signal 9 (SIGKILL)"],
         "answer": 1,
         "explain": "Au-delà de 128, le code de sortie vaut 128 + numéro du signal qui a tué le processus : 143 − 128 = 15, c'est-à-dire SIGTERM (SIGKILL donnerait 137)."},
        {"q": "Qu'est-ce qui distingue fondamentalement un conteneur d'une machine virtuelle ?",
         "choices": ["Il embarque un noyau allégé, ce qui explique son démarrage rapide",
                     "Il émule le matériel de l'hôte, mais sans disque virtuel",
                     "Il n'embarque pas de noyau : il partage celui de l'hôte",
                     "Il ne peut exécuter qu'un seul programme pendant toute sa vie"],
         "answer": 2,
         "explain": "Un conteneur est un processus de l'hôte, isolé, qui utilise le noyau de l'hôte. Il n'y a ni noyau ni matériel émulé à démarrer, d'où un lancement en une fraction de seconde."},
        {"q": "Connecté en tant que <code>etudiant</code>, vous tapez <code>docker run --rm alpine echo $HOME</code>. Qu'affiche le conteneur ?",
         "choices": ["<code>/root</code>, le dossier personnel de root dans le conteneur",
                     "<code>$HOME</code> tel quel, car <code>echo</code> n'interprète pas les variables",
                     "Une ligne vide, car la variable HOME n'existe pas dans Alpine",
                     "<code>/home/etudiant</code>, car votre shell remplace la variable avant Docker"],
         "answer": 3,
         "explain": "C'est votre shell qui lit la ligne en premier : <code>$HOME</code> est remplacé par sa valeur sur l'hôte avant que Docker ne reçoive la commande. Le conteneur reçoit donc <code>echo /home/etudiant</code>."},
        {"q": "<code>docker diff poste</code> affiche la ligne <code>D /var/cache/apk/index.tar.gz</code>. Que signifie-t-elle ?",
         "choices": ["Le fichier a été téléchargé (<em>downloaded</em>) par le conteneur",
                     "Le fichier a été retiré de l'image, pour tous ses conteneurs",
                     "Le fichier est un dossier (<em>directory</em>) créé par le conteneur",
                     "Le fichier de l'image a été supprimé dans la couche du conteneur"],
         "answer": 3,
         "explain": "<code>docker diff</code> compare la couche inscriptible du conteneur à son image : <code>A</code> ajouté, <code>C</code> modifié, <code>D</code> supprimé. L'image elle-même, en lecture seule, n'est jamais modifiée."},
        {"q": "<code>docker top veilleur</code> montre le processus <code>sleep</code> du conteneur avec le PID 48213 sur l'hôte. Le conteneur n'a pas de politique de redémarrage. Que se passe-t-il après <code>kill -9 48213</code> tapé sur l'hôte ?",
         "choices": ["Rien : ce PID appartient au noyau du conteneur, pas à celui de l'hôte",
                     "Docker relance aussitôt <code>sleep</code>, car le conteneur doit continuer",
                     "Le conteneur s'arrête, puisque son processus principal a disparu",
                     "Le processus meurt, mais le conteneur reste <em>Up</em> jusqu'au <code>docker stop</code>"],
         "answer": 2,
         "explain": "Un conteneur est un processus de l'hôte : il vit tant que son processus principal tourne. Tuer ce processus (SIGKILL) termine le conteneur, qui passe à l'état Exited (137)."},
        {"q": "Que se passe-t-il si l'on tape <code>docker rm veilleur</code> alors que ce conteneur tourne ?",
         "choices": ["Docker l'arrête proprement, puis le supprime",
                     "Docker refuse : il faut l'arrêter avant, ou ajouter <code>-f</code>",
                     "Docker supprime le conteneur, mais son processus continue",
                     "Docker supprime l'image dont le conteneur est issu"],
         "answer": 1,
         "explain": "<code>docker rm</code> ne supprime qu'un conteneur arrêté. <code>docker rm -f</code> l'arrête (brutalement) puis le supprime ; l'image n'est jamais concernée."},
        {"q": "Vous lancez deux fois de suite <code>docker run --name essai alpine ls /</code>. Que fait la seconde commande ?",
         "choices": ["Elle échoue : le nom <code>essai</code> est déjà pris par le conteneur arrêté",
                     "Elle remplace le premier conteneur, arrêté, par un nouveau du même nom",
                     "Elle réussit en nommant le nouveau conteneur <code>essai-1</code>",
                     "Elle redémarre le conteneur <code>essai</code> existant, avec la même commande"],
         "answer": 0,
         "explain": "Le premier conteneur existe toujours après sa fin : son nom reste réservé. Il faut le supprimer (<code>docker rm essai</code>) ou choisir un autre nom."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    2: [
        {"q": "Un processus écrit ses messages normaux sur la sortie standard et ses erreurs sur la sortie d'erreur. Que contient le fichier après <code>docker logs app &gt; sortie.txt</code> ?",
         "choices": ["Les deux sorties, car <code>docker logs</code> les fusionne toujours",
                     "Seulement la sortie standard ; les erreurs s'affichent encore à l'écran",
                     "Seulement la sortie d'erreur, car <code>docker logs</code> sert au diagnostic",
                     "Rien : <code>docker logs</code> écrit toujours directement sur le terminal"],
         "answer": 1,
         "explain": "<code>docker logs</code> restitue la sortie d'erreur du processus sur sa propre sortie d'erreur. <code>&gt;</code> ne redirige que la sortie standard : il faudrait ajouter <code>2&gt;&amp;1</code>."},
        {"q": "<code>docker stop tache</code> met exactement 10 secondes à rendre la main, et le code de sortie est 137. Que s'est-il passé ?",
         "choices": ["Le processus n'a pas réagi à SIGTERM ; Docker l'a tué par SIGKILL au bout du délai",
                     "Le processus s'est arrêté proprement : 137 est le code normal d'un <code>docker stop</code>",
                     "Docker attend toujours 10 secondes avant d'envoyer le premier signal",
                     "Le conteneur a dépassé sa mémoire pendant l'arrêt et le noyau l'a tué"],
         "answer": 0,
         "explain": "<code>docker stop</code> envoie SIGTERM, attend 10 s, puis envoie SIGKILL. Un code 137 (128 + 9) après 10 s d'attente signifie que SIGTERM n'a pas été entendu."},
        {"q": "Que se passe-t-il lorsque l'on tape <code>docker exec web-demo ls /tmp</code> ?",
         "choices": ["Le processus principal interrompt son travail pour exécuter <code>ls</code>",
                     "Un conteneur temporaire est créé depuis la même image pour lancer <code>ls</code>",
                     "Un processus de l'hôte lit directement le système de fichiers du conteneur",
                     "Un nouveau processus <code>ls</code> est lancé dans le conteneur, à côté du principal"],
         "answer": 3,
         "explain": "<code>docker exec</code> démarre un nouveau processus dans le conteneur existant (mêmes fichiers, même réseau), sans toucher au processus principal."},
        {"q": "<code>docker image inspect -f '{{.Config.Env}}' app:1</code> affiche <code>MODE=production</code>. Que peut-on en conclure pour un conteneur issu de cette image ?",
         "choices": ["Son processus voit forcément <code>MODE=production</code>",
                     "Que <code>MODE</code> n'existe que pendant la construction de l'image",
                     "C'est la valeur par défaut, qu'un <code>-e</code> au lancement a pu remplacer",
                     "Son processus voit <code>MODE</code> seulement s'il tourne en root"],
         "answer": 2,
         "explain": "Les variables de l'image sont des valeurs par défaut. Pour connaître la valeur réelle, on interroge le conteneur (<code>docker inspect</code> du conteneur, ou <code>printenv</code> dedans)."},
        {"q": "Que reste-t-il d'un conteneur arrêté (état Exited) qui n'a pas été supprimé ?",
         "choices": ["Ses journaux seulement : les fichiers de sa couche sont effacés à l'arrêt",
                     "Ses fichiers seulement : les journaux disparaissent avec le processus",
                     "Ses fichiers et ses journaux, consultables jusqu'au <code>docker rm</code>",
                     "Rien de consultable tant qu'on ne l'a pas redémarré"],
         "answer": 2,
         "explain": "Un conteneur arrêté garde sa couche inscriptible et ses journaux : <code>docker logs</code>, <code>docker diff</code> et <code>docker cp</code> fonctionnent encore. Tout disparaît avec <code>docker rm</code>."},
        {"q": "À quoi sert l'option <code>--no-stream</code> de <code>docker stats</code> ?",
         "choices": ["À masquer les statistiques réseau (les flux) de chaque conteneur",
                     "À inclure aussi les conteneurs arrêtés dans les mesures",
                     "À mesurer sans ralentir les conteneurs pendant le relevé",
                     "À afficher un seul relevé, puis rendre la main"],
         "answer": 3,
         "explain": "Par défaut, <code>docker stats</code> rafraîchit l'affichage en continu. <code>--no-stream</code> affiche un seul relevé et se termine, pratique dans un script."},
        {"q": "Quelle modification peut-on appliquer à un conteneur qui tourne, sans le recréer ni le redémarrer ?",
         "choices": ["Changer sa limite de CPU avec <code>docker update</code>",
                     "Publier un port supplémentaire avec <code>docker update -p</code>",
                     "Changer une variable d'environnement avec <code>docker update -e</code>",
                     "Changer son image avec <code>docker update --image</code>"],
         "answer": 0,
         "explain": "<code>docker update</code> modifie à chaud les limites de ressources (mémoire, CPU) et la politique de redémarrage. Ports, variables et image imposent de recréer le conteneur."},
        {"q": "Vous suivez les journaux avec <code>docker logs -f web</code>, puis vous appuyez sur Ctrl+C. Que se passe-t-il ?",
         "choices": ["Le conteneur s'arrête proprement, comme avec <code>docker stop</code>",
                     "Seul l'affichage s'arrête : le conteneur continue de tourner",
                     "Le signal SIGINT est transmis au processus principal du conteneur",
                     "Les journaux déjà affichés sont effacés du conteneur"],
         "answer": 1,
         "explain": "Ctrl+C interrompt la commande <code>docker logs</code>, qui ne fait que lire les journaux. Le conteneur n'est pas concerné."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    3: [
        {"q": "Après <code>docker run -d -p 9000:80 nginx:alpine</code>, quelle adresse affiche la page depuis l'hôte ?",
         "choices": ["<code>http://localhost:80</code>",
                     "<code>http://localhost:8080</code>",
                     "<code>http://localhost:9000</code>",
                     "<code>http://&lt;IP du conteneur&gt;:9000</code>"],
         "answer": 2,
         "explain": "L'ordre est toujours <code>hôte:conteneur</code> : le port 9000 de l'hôte est relié au port 80 du conteneur, sur lequel nginx écoute."},
        {"q": "Un conteneur publie déjà <code>-p 9000:80</code>. Que fait un second <code>docker run -d -p 9000:80 nginx:alpine</code> ?",
         "choices": ["Il réussit : Docker répartit les requêtes entre les deux conteneurs",
                     "Il réussit, mais publie automatiquement le port 9001 à la place",
                     "Il retire la publication du premier conteneur au profit du second",
                     "Il échoue : le port 9000 de l'hôte est déjà pris"],
         "answer": 3,
         "explain": "Un port de l'hôte ne peut être publié que par un seul conteneur à la fois (<em>port is already allocated</em>). Le second conteneur est créé mais ne démarre pas."},
        {"q": "<code>docker port demo</code> affiche <code>80/tcp -&gt; 0.0.0.0:9000</code>. Qu'en déduisez-vous ?",
         "choices": ["Le port 80 du conteneur est joignable sur le port 9000 de toutes les interfaces de l'hôte",
                     "Le port 9000 du conteneur est joignable sur le port 80 de toutes les interfaces de l'hôte",
                     "Le port 80 du conteneur n'est joignable que depuis l'hôte lui-même, par <code>localhost</code>",
                     "Le conteneur écoute sur toutes ses interfaces, mais aucun port n'est publié sur l'hôte"],
         "answer": 0,
         "explain": "<code>0.0.0.0</code> signifie « toutes les interfaces » : c'est le comportement par défaut de <code>-p</code>, sauf si l'on précise une adresse devant le port de l'hôte."},
        {"q": "Que monte <code>docker run -v documentation:/usr/share/nginx/html nginx:alpine</code>, lancé depuis votre dossier personnel qui contient <code>documentation/</code> ?",
         "choices": ["Le dossier <code>~/documentation</code>, Docker complétant le chemin relatif",
                     "Un volume nommé « documentation », et non votre dossier",
                     "Rien : Docker refuse de démarrer avec un chemin relatif",
                     "Le dossier <code>/documentation</code> à la racine de l'hôte"],
         "answer": 1,
         "explain": "Sans <code>/</code> ni <code>./</code> au début, la source de <code>-v</code> est un nom de volume. Pour un bind mount, il faut un chemin : <code>~/documentation</code> ou <code>./documentation</code>."},
        {"q": "nginx sert un dossier de l'hôte monté par bind mount. Vous modifiez <code>index.html</code> dans ce dossier. Que faut-il faire pour que nginx serve la nouvelle version ?",
         "choices": ["Reconstruire l'image nginx avec le nouveau fichier",
                     "Rien : le dossier est partagé, la modification est visible aussitôt",
                     "Redémarrer le conteneur pour qu'il recopie le dossier",
                     "Recréer le conteneur, car le dossier a été copié à sa création"],
         "answer": 1,
         "explain": "Un bind mount ne copie rien : le conteneur voit directement le dossier de l'hôte, et toute modification y est immédiatement visible."},
        {"q": "Un conteneur monte <code>-v ~/site:/usr/share/nginx/html:ro</code>. Un de ses processus tente d'écrire dans <code>/usr/share/nginx/html</code>. Que se passe-t-il ?",
         "choices": ["L'écriture échoue : le montage est en lecture seule",
                     "L'écriture réussit dans la couche du conteneur, sans toucher l'hôte",
                     "L'écriture réussit uniquement si le processus tourne en root",
                     "L'écriture réussit et modifie le fichier sur l'hôte"],
         "answer": 0,
         "explain": "<code>:ro</code> monte le dossier en lecture seule dans le conteneur : aucune écriture n'est possible, même en root, et il n'y a pas de couche inscriptible « par-dessus » un montage."},
        {"q": "Dans un bind mount, comment les propriétaires des fichiers de l'hôte apparaissent-ils dans le conteneur ?",
         "choices": ["Ils deviennent tous root, puisque le moteur Docker tourne en root",
                     "Ils prennent l'utilisateur défini par l'instruction <code>USER</code> de l'image",
                     "Ils gardent le nom <code>etudiant</code>, recréé automatiquement dans le conteneur",
                     "Avec les mêmes UID et GID que sur l'hôte, quel que soit le nom associé"],
         "answer": 3,
         "explain": "Un bind mount conserve les droits de l'hôte en numéros. Le conteneur a ses propres comptes : un même UID peut y porter un autre nom, ou aucun."},
        {"q": "Le dossier <code>/home/etudiant/sitee</code> (faute de frappe) n'existe pas. Que fait <code>docker run -d -v /home/etudiant/sitee:/usr/share/nginx/html nginx:alpine</code> ?",
         "choices": ["Il refuse de démarrer, car le chemin source n'existe pas",
                     "Il monte un volume nommé <code>sitee</code>, créé pour l'occasion",
                     "Il crée un dossier vide à ce chemin et le monte : nginx ne sert rien",
                     "Il ignore le montage et sert la page par défaut de l'image"],
         "answer": 2,
         "explain": "Avec <code>-v</code>, un dossier source absent est créé (vide) par le moteur. La syntaxe <code>--mount type=bind</code>, elle, refuserait un chemin inexistant."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    4: [
        {"q": "Un conteneur Alpine écrit <code>/notes.txt</code>, puis il est supprimé avec <code>docker rm</code>. Un nouveau conteneur est créé depuis la même image. Trouve-t-il <code>/notes.txt</code> ?",
         "choices": ["Oui : le fichier a été ajouté à l'image <code>alpine</code>",
                     "Oui, jusqu'au prochain nettoyage des images",
                     "Oui, si le nouveau conteneur porte le même nom",
                     "Non : le fichier était dans la couche du conteneur supprimé"],
         "answer": 3,
         "explain": "Ce qu'un conteneur écrit va dans sa couche inscriptible, qui disparaît avec <code>docker rm</code>. L'image reste en lecture seule et n'est jamais modifiée."},
        {"q": "Le conteneur <code>demo-db</code> monte le volume <code>demo-data</code> sur <code>/data</code>. On le supprime, puis on en crée un autre avec <code>-v demo-data:/data</code>. Et les données ?",
         "choices": ["Perdues : <code>docker rm</code> supprime les volumes montés",
                     "Perdues, sauf si le nouveau conteneur porte le même nom",
                     "Présentes : le volume est indépendant de tout conteneur",
                     "Présentes seulement si l'on a fait un <code>docker commit</code> avant"],
         "answer": 2,
         "explain": "Un volume nommé est géré par Docker, indépendamment des conteneurs : un nouveau conteneur qui le monte retrouve les données."},
        {"q": "Que fait l'option <code>--rm</code> de <code>docker run</code> ?",
         "choices": ["Elle supprime l'image une fois la commande exécutée",
                     "Elle supprime le conteneur dès que son processus se termine",
                     "Elle supprime les volumes nommés montés par le conteneur",
                     "Elle empêche le conteneur d'écrire sur le disque"],
         "answer": 1,
         "explain": "<code>--rm</code> rend le conteneur jetable : il est supprimé à la fin de son processus. Les volumes nommés qu'il montait sont conservés."},
        {"q": "Où se trouve l'archive produite par <code>docker run --rm -v demo-data:/source -v ~/archives:/dest alpine tar czf /dest/demo.tar.gz -C /source .</code> ?",
         "choices": ["Dans <code>~/archives</code> sur l'hôte, sous le nom <code>demo.tar.gz</code>",
                     "Dans le volume <code>demo-data</code>, dans un dossier <code>dest</code>",
                     "Dans la couche du conteneur alpine, supprimée avec lui",
                     "Dans un dossier <code>/dest</code> à la racine de l'hôte"],
         "answer": 0,
         "explain": "<code>/dest</code> est, dans le conteneur, le dossier <code>~/archives</code> de l'hôte monté par bind mount : l'archive y est écrite et survit au conteneur jetable."},
        {"q": "Le dossier <code>~/logs</code> n'existe pas. <code>etudiant</code> lance <code>docker run -d -v ~/logs:/var/log/app monimage</code>. À qui appartient le dossier <code>~/logs</code> ainsi créé ?",
         "choices": ["À root, car c'est le moteur Docker, qui tourne en root, qui l'a créé",
                     "À <code>etudiant</code>, qui a tapé la commande",
                     "À l'utilisateur sous lequel tourne le processus du conteneur",
                     "À personne : le dossier n'est créé que dans le conteneur"],
         "answer": 0,
         "explain": "Ce n'est pas la commande <code>docker</code> qui crée le dossier, mais le moteur <code>dockerd</code>, qui tourne en root."},
        {"q": "Pourquoi ajouter un utilisateur au groupe <code>docker</code> revient-il à lui donner les droits de root ?",
         "choices": ["Parce que le groupe <code>docker</code> a le même GID que le groupe root",
                     "Parce qu'il peut monter n'importe quel dossier de l'hôte dans un conteneur root",
                     "Parce que ce groupe autorise <code>sudo</code> sans mot de passe",
                     "Parce que les conteneurs connaissent le mot de passe root de l'hôte"],
         "answer": 1,
         "explain": "Piloter le moteur permet de lancer un conteneur root qui monte <code>/</code> ou <code>/etc</code> de l'hôte, et donc de tout lire ou modifier."},
        {"q": "Pourquoi lance-t-on Redis avec <code>redis-server --appendonly yes</code> dans le cours ?",
         "choices": ["Pour que Redis n'accepte que des ajouts, jamais de suppressions",
                     "Pour que le volume soit monté en mode « ajout seul »",
                     "Pour que Redis écrive chaque modification sur disque, pas de temps en temps",
                     "Pour que Redis sauvegarde sur l'hôte même sans volume"],
         "answer": 2,
         "explain": "Sans cette option, Redis n'écrit ses données sur disque que périodiquement : une modification récente pourrait ne pas se trouver dans le volume."},
        {"q": "Où Docker stocke-t-il les données d'un volume nommé ?",
         "choices": ["Dans le dossier courant au moment du <code>docker volume create</code>",
                     "Dans la couche inscriptible du premier conteneur qui l'utilise",
                     "Dans l'image, à côté des couches en lecture seule",
                     "Dans <code>/var/lib/docker/volumes</code>, sous le contrôle du moteur"],
         "answer": 3,
         "explain": "Un volume est géré par Docker, dans son propre répertoire de données, indépendamment des conteneurs et des images."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    5: [
        {"q": "Le volume <code>neuf</code> n'existe pas encore. Que sert <code>docker run -d -p 8000:80 -v neuf:/usr/share/nginx/html nginx:alpine</code> ?",
         "choices": ["Un dossier vide : le volume masque le dossier de l'image",
                     "La page d'accueil de nginx, recopiée de l'image dans le volume",
                     "Rien : le conteneur refuse de démarrer sans <code>docker volume create</code>",
                     "Le contenu du dossier <code>~/neuf</code> de l'hôte"],
         "answer": 1,
         "explain": "Au premier montage d'un volume nommé vide, Docker y recopie le contenu du dossier de l'image. Un bind mount, lui, masquerait ce dossier."},
        {"q": "Vous lancez cinq fois <code>docker run -d redis:7-alpine</code> sans <code>-v</code>, puis supprimez chaque conteneur avec <code>docker rm -f</code>. Que montre <code>docker volume ls</code> ?",
         "choices": ["Aucun volume : sans <code>-v</code>, Redis n'écrit que dans sa couche",
                     "Un seul volume nommé <code>redis</code>, partagé par les cinq",
                     "Aucun volume : <code>docker rm</code> supprime toujours les volumes",
                     "Cinq volumes anonymes, qui ont survécu aux <code>docker rm</code>"],
         "answer": 3,
         "explain": "L'image Redis déclare <code>VOLUME /data</code> : chaque <code>docker run</code> sans <code>-v</code> crée un volume anonyme, que <code>docker rm</code> sans <code>-v</code> ne supprime pas."},
        {"q": "Un conteneur lancé avec <code>--rm</code> monte un volume nommé et possède aussi un volume anonyme. Que deviennent-ils quand il se termine ?",
         "choices": ["Le volume anonyme est supprimé, le volume nommé conservé",
                     "Les deux volumes sont supprimés avec le conteneur",
                     "Les deux volumes sont conservés : <code>--rm</code> ne vise que le conteneur",
                     "Le volume nommé est supprimé, le volume anonyme conservé"],
         "answer": 0,
         "explain": "<code>--rm</code> supprime le conteneur et ses volumes anonymes, jamais les volumes nommés."},
        {"q": "Pourquoi faut-il restaurer une sauvegarde dans le volume <strong>avant</strong> de démarrer le service qui l'utilise ?",
         "choices": ["Parce qu'un volume monté par un conteneur en marche passe en lecture seule pour les autres",
                     "Parce que <code>tar</code> ne peut pas écrire dans un volume déjà monté par un autre conteneur",
                     "Parce que le service partirait d'un volume vide, puis écraserait ou ignorerait la restauration",
                     "Parce que le service efface le contenu de son volume à chacun de ses démarrages"],
         "answer": 2,
         "explain": "Un service démarré sur un volume vide initialise ses propres données ; les fichiers restaurés ensuite sont ignorés ou écrasés à la prochaine écriture."},
        {"q": "Que devient le contenu d'un tmpfs (<code>--tmpfs /cache</code>) quand le conteneur s'arrête ?",
         "choices": ["Il est copié dans la couche inscriptible du conteneur",
                     "Il est conservé dans un volume anonyme jusqu'au <code>docker rm</code>",
                     "Il est perdu : un tmpfs est en mémoire, vidé à l'arrêt",
                     "Il est conservé et retrouvé au prochain <code>docker start</code>"],
         "answer": 2,
         "explain": "Un tmpfs est un système de fichiers en mémoire : rien n'est écrit sur disque, et son contenu disparaît à l'arrêt du conteneur."},
        {"q": "Un conteneur est lancé avec <code>--read-only --tmpfs /tmp</code>, sans volume. Où ses processus peuvent-ils écrire des fichiers ?",
         "choices": ["Dans <code>/tmp</code>, en mémoire ; le reste est en lecture seule",
                     "Partout, sauf dans les dossiers qui viennent de l'image",
                     "Dans <code>/tmp</code> et dans sa couche inscriptible",
                     "Nulle part : <code>--read-only</code> s'applique aussi au tmpfs"],
         "answer": 0,
         "explain": "<code>--read-only</code> interdit toute écriture dans le système de fichiers du conteneur ; un tmpfs monté reste inscriptible, d'où l'intérêt de les limiter au strict nécessaire."},
        {"q": "Que liste <code>docker volume ls -f dangling=true</code> ?",
         "choices": ["Les volumes anonymes seulement, qu'ils soient utilisés ou non",
                     "Les volumes montés par des conteneurs arrêtés",
                     "Les volumes qui ne contiennent aucun fichier",
                     "Les volumes qu'aucun conteneur, même arrêté, n'utilise"],
         "answer": 3,
         "explain": "Un volume <em>dangling</em> n'est référencé par aucun conteneur, qu'il soit nommé ou anonyme. Un conteneur arrêté « utilise » encore ses volumes."},
        {"q": "Quelle option est équivalente à <code>-v /srv/site:/usr/share/nginx/html:ro</code> ?",
         "choices": ["<code>--mount type=volume,src=/srv/site,dst=/usr/share/nginx/html,readonly</code>",
                     "<code>--mount type=bind,src=/srv/site,dst=/usr/share/nginx/html,readonly</code>",
                     "<code>--mount type=bind,src=/usr/share/nginx/html,dst=/srv/site,readonly</code>",
                     "<code>--mount type=tmpfs,src=/srv/site,dst=/usr/share/nginx/html,readonly</code>"],
         "answer": 1,
         "explain": "Un chemin de l'hôte donne un bind mount : <code>type=bind</code>, la source sur l'hôte (<code>src</code>), la destination dans le conteneur (<code>dst</code>), et <code>readonly</code> pour <code>:ro</code>."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    6: [
        {"q": "Un Dockerfile se termine par <code>RUN node server.js</code> au lieu de <code>CMD [\"node\", \"server.js\"]</code>. Que se passe-t-il ?",
         "choices": ["Rien de différent : <code>RUN</code> et <code>CMD</code> sont deux syntaxes équivalentes",
                     "Le serveur démarre à chaque <code>docker run</code>, mais en root",
                     "Le serveur est lancé pendant <code>docker build</code>, qui reste bloqué",
                     "Le serveur démarre après le <code>CMD</code> hérité de l'image de base"],
         "answer": 2,
         "explain": "<code>RUN</code> s'exécute pendant la construction ; un serveur ne se termine pas, donc la construction ne se termine pas non plus. <code>CMD</code> indique la commande lancée au démarrage du conteneur."},
        {"q": "Une image contient <code>EXPOSE 3000</code>. Elle est lancée avec <code>docker run -d monimage</code>, sans <code>-p</code>. Que répond <code>curl http://localhost:3000</code> sur l'hôte ?",
         "choices": ["Rien : <code>EXPOSE</code> documente le port, seul <code>-p</code> le publie",
                     "La page de l'application : <code>EXPOSE</code> publie le port sur l'hôte",
                     "La page de l'application, mais sur un port aléatoire de l'hôte",
                     "La page de l'application, uniquement via <code>127.0.0.1</code>"],
         "answer": 0,
         "explain": "<code>EXPOSE</code> est une documentation : il ne publie rien. Pour joindre le service depuis l'hôte, il faut <code>-p 3000:3000</code>."},
        {"q": "Où faut-il placer le fichier <code>.dockerignore</code> pour qu'il soit pris en compte ?",
         "choices": ["Dans le dossier de destination du <code>COPY</code>, dans l'image",
                     "Dans <code>~/.docker</code>, pour toutes les constructions",
                     "Dans le dossier <code>.git</code> du projet",
                     "À la racine du contexte donné à <code>docker build</code>"],
         "answer": 3,
         "explain": "Le <code>.dockerignore</code> se lit à la racine du contexte de construction : il exclut des fichiers avant même qu'ils soient envoyés au moteur."},
        {"q": "Un Dockerfile fait <code>COPY . .</code> (le dossier contient <code>.env</code>), puis <code>RUN rm .env</code>. L'image contient-elle encore les secrets de <code>.env</code> ?",
         "choices": ["Non : <code>RUN rm</code> l'efface de toutes les couches de l'image",
                     "Oui : il reste dans la couche du <code>COPY</code>, lisible par qui a l'image",
                     "Non : Docker n'intègre jamais les fichiers <code>.env</code> aux images",
                     "Seulement si l'image est ensuite poussée sur un registre"],
         "answer": 1,
         "explain": "Chaque instruction ajoute une couche ; supprimer un fichier dans une couche suivante le masque sans l'effacer de la couche où il a été copié."},
        {"q": "Une image Alpine (sans <code>curl</code>) contient <code>HEALTHCHECK CMD curl -f http://localhost/ || exit 1</code>. Le site répond bien. Quel état de santé affiche <code>docker ps</code> une fois les essais prévus effectués ?",
         "choices": ["<em>(healthy)</em>, car Docker fournit sa propre commande <code>curl</code>",
                     "<em>(unhealthy)</em>, car la commande de test échoue à chaque fois",
                     "Aucun état : un HEALTHCHECK invalide est ignoré",
                     "Aucun : le conteneur refuse de démarrer"],
         "answer": 1,
         "explain": "Le test est exécuté dans le conteneur : <code>curl</code> y est introuvable, la commande échoue, et après les essais prévus le conteneur devient unhealthy. Les images Alpine ont <code>wget</code>."},
        {"q": "Un conteneur lancé avec <code>--restart always</code> a été arrêté par <code>docker stop</code>. Puis le moteur Docker redémarre. Que devient le conteneur ?",
         "choices": ["Il reste arrêté, puisqu'il avait été arrêté volontairement",
                     "Il redémarre seulement si son dernier code de sortie n'était pas 0",
                     "Il est supprimé, car <code>docker stop</code> annule sa politique",
                     "Il redémarre : <code>always</code> relance aussi au démarrage du moteur"],
         "answer": 3,
         "explain": "<code>always</code> relance le conteneur au redémarrage du moteur, même après un arrêt volontaire. C'est ce qui le distingue de <code>unless-stopped</code>."},
        {"q": "Pourquoi préfère-t-on un Dockerfile à <code>docker commit</code> pour produire une image ?",
         "choices": ["Le Dockerfile est une recette versionnée, qu'on sait relire et rejouer",
                     "<code>docker commit</code> ne conserve pas les fichiers modifiés dans le conteneur",
                     "Une image produite par <code>docker commit</code> ne peut pas être lancée par <code>docker run</code>",
                     "Un Dockerfile produit toujours une image plus petite qu'un <code>docker commit</code>"],
         "answer": 0,
         "explain": "<code>docker commit</code> fige un état obtenu à la main : personne ne sait le reproduire ni ce qu'il contient vraiment. Le Dockerfile, lui, se relit, se versionne et se reconstruit."},
        {"q": "Un Dockerfile contient <code>USER node</code> au milieu. Quel est l'effet de cette instruction ?",
         "choices": ["Seul le conteneur tourne sous <code>node</code> ; tous les <code>RUN</code> restent en root",
                     "Seuls les <code>RUN</code> suivants tournent sous <code>node</code> ; le conteneur reste en root",
                     "Les instructions suivantes et le processus du conteneur s'exécutent sous <code>node</code>",
                     "Les fichiers copiés appartiennent à <code>node</code>, mais tout s'exécute en root"],
         "answer": 2,
         "explain": "<code>USER</code> change l'utilisateur des instructions qui suivent (<code>RUN</code>…) et celui du processus lancé au démarrage du conteneur."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    7: [
        {"q": "Dockerfile : <code>FROM alpine</code>, <code>RUN apk add python3</code>, <code>COPY config.txt /etc/</code>, <code>RUN ./long-traitement.sh</code>. Vous modifiez seulement <code>config.txt</code> et reconstruisez. Qu'est-ce qui est rejoué ?",
         "choices": ["Seulement le <code>COPY config.txt</code>",
                     "Seulement le dernier <code>RUN</code>, qui utilise le fichier",
                     "Toutes les instructions, <code>FROM</code> compris",
                     "Le <code>COPY config.txt</code> et toutes les instructions suivantes"],
         "answer": 3,
         "explain": "La couche du <code>COPY</code> change car le fichier a changé ; dès qu'une couche change, toutes les suivantes sont reconstruites. Les précédentes viennent du cache."},
        {"q": "Une image a <code>ENTRYPOINT [\"/demarrer.sh\"]</code> : un script <code>#!/bin/sh</code> dont la dernière ligne est <code>node server.js</code>, sans <code>exec</code>. Quel processus est le PID 1 du conteneur ?",
         "choices": ["<code>node</code>, car Docker remplace toujours le script par sa dernière commande",
                     "<code>/bin/sh</code>, qui exécute le script ; <code>node</code> n'est que son enfant",
                     "<code>tini</code>, que Docker ajoute automatiquement en PID 1",
                     "<code>dockerd</code>, qui lance les processus de tous les conteneurs"],
         "answer": 1,
         "explain": "Le shell qui exécute le script reste PID 1 et lance <code>node</code> comme enfant ; il ne lui transmet pas SIGTERM. D'où <code>exec node server.js</code> en dernière ligne, qui remplace le shell par <code>node</code>."},
        {"q": "Un script Node sans gestionnaire <code>process.on('SIGTERM')</code> tourne en PID 1 (forme exec). Que se passe-t-il au <code>docker stop</code> ?",
         "choices": ["Il ignore SIGTERM ; Docker le tue par SIGKILL au bout de 10 s (code 137)",
                     "Il s'arrête aussitôt : l'action par défaut de SIGTERM le termine",
                     "Il s'arrête aussitôt avec le code 143, comme tout processus",
                     "Docker lui envoie SIGINT, que Node gère sans gestionnaire"],
         "answer": 0,
         "explain": "Le noyau n'applique pas l'action par défaut des signaux au PID 1 : sans gestionnaire, SIGTERM est ignoré, et Docker finit par envoyer SIGKILL."},
        {"q": "L'image <code>pingeur</code> a <code>ENTRYPOINT [\"ping\"]</code> et <code>CMD [\"-c\", \"3\", \"localhost\"]</code>. Quelle commande exécute <code>docker run --rm pingeur cimes.local</code> ?",
         "choices": ["<code>ping -c 3 localhost cimes.local</code>",
                     "<code>cimes.local</code>, qui remplace <code>ping</code>",
                     "<code>ping cimes.local</code>",
                     "<code>ping -c 3 cimes.local</code>"],
         "answer": 2,
         "explain": "Les arguments écrits après l'image remplacent tout le CMD ; l'ENTRYPOINT est conservé. Les options <code>-c 3</code> du CMD disparaissent donc aussi."},
        {"q": "Un Dockerfile déclare <code>ARG VERSION=1.0</code>, sans <code>ENV</code>. L'application lit la variable d'environnement <code>VERSION</code> au démarrage du conteneur. Que trouve-t-elle ?",
         "choices": ["<code>1.0</code>, la valeur par défaut de l'ARG",
                     "La valeur passée à <code>--build-arg</code>, sinon <code>1.0</code>",
                     "Rien : un ARG n'existe que pendant la construction",
                     "<code>1.0</code>, à condition que l'image porte un LABEL"],
         "answer": 2,
         "explain": "Un ARG est une variable de construction. Pour qu'elle existe à l'exécution, il faut la recopier dans un ENV (<code>ENV VERSION=$VERSION</code>)."},
        {"q": "<code>docker images outil</code> montre <code>outil:1.5</code> et <code>outil:latest</code> avec le même IMAGE ID. Que signifie-t-il ?",
         "choices": ["Ce sont deux étiquettes posées sur la même image",
                     "<code>latest</code> est une copie de <code>1.5</code>, reconstruite ensuite",
                     "<code>latest</code> désigne toujours la version la plus haute",
                     "<code>1.5</code> a été construite à partir de <code>latest</code>"],
         "answer": 0,
         "explain": "Un tag est une étiquette mobile posée sur un identifiant d'image. Même IMAGE ID, même image ; <code>latest</code> ne désigne que ce qu'on lui a fait désigner."},
        {"q": "Un <code>ARG REVISION</code> est déclaré en haut du Dockerfile, avant plusieurs <code>RUN</code> qui ne le citent pas. Vous reconstruisez avec une autre valeur de <code>--build-arg REVISION</code>. Que se passe-t-il ?",
         "choices": ["Seuls les <code>RUN</code> qui citent <code>$REVISION</code> sont reconstruits",
                     "Tous les <code>RUN</code> qui suivent sa déclaration sont reconstruits",
                     "Aucune couche n'est reconstruite : un ARG n'entre pas dans le cache",
                     "Seule l'instruction <code>ARG</code> elle-même est reconstruite"],
         "answer": 1,
         "explain": "Un ARG est transmis à tous les RUN qui suivent sa déclaration : s'il change, ils sont reconstruits. D'où le conseil de le déclarer le plus bas possible."},
        {"q": "Pourquoi utilise-t-on <code>npm ci</code> plutôt que <code>npm install</code> dans un Dockerfile ?",
         "choices": ["Parce que c'est la seule commande qui fonctionne sans Internet",
                     "Parce qu'elle ignore <code>package.json</code> et ne lit que le verrou",
                     "Parce qu'elle installe les outils de développement, requis par Docker",
                     "Parce qu'elle installe exactement les versions de <code>package-lock.json</code>"],
         "answer": 3,
         "explain": "<code>npm ci</code> reproduit exactement l'arbre décrit par <code>package-lock.json</code> : deux constructions donnent les mêmes dépendances."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    8: [
        {"q": "Un Dockerfile en deux étapes part de <code>node:20-alpine AS outils</code> pour générer des pages, puis de <code>nginx:alpine</code> avec <code>COPY --from=outils …</code>. L'image finale contient-elle Node ?",
         "choices": ["Non : seule la dernière étape forme l'image, avec ce qu'on y copie",
                     "Oui : les couches de toutes les étapes sont empilées dans l'image",
                     "Oui, mais Node y est désactivé par <code>COPY --from</code>",
                     "Non, car <code>COPY --from</code> supprime Node de la première étape"],
         "answer": 0,
         "explain": "L'image finale est construite à partir du dernier <code>FROM</code> ; elle ne récupère des autres étapes que ce que <code>COPY --from</code> y copie explicitement."},
        {"q": "Une archive de 80 Mo est téléchargée, décompressée puis supprimée. Quelle écriture évite qu'elle pèse dans l'image ?",
         "choices": ["Trois <code>RUN</code> séparés : téléchargement, décompression, suppression",
                     "Un <code>RUN</code> pour télécharger et décompresser, un autre pour supprimer",
                     "Un seul <code>RUN</code> qui télécharge, décompresse et supprime l'archive",
                     "Un <code>COPY</code> de l'archive suivi d'un <code>RUN rm</code>"],
         "answer": 2,
         "explain": "Une couche enregistre l'état à la fin de son instruction. Si l'archive est supprimée dans la même instruction, elle n'apparaît dans aucune couche ; sinon, elle reste dans la couche où elle a été ajoutée."},
        {"q": "Avec <code>RUN --mount=type=secret,id=jeton …</code>, où et quand le secret est-il accessible ?",
         "choices": ["Dans <code>/run/secrets/jeton</code>, pour ce RUN et tous les suivants",
                     "Dans une variable d'environnement de l'image finale",
                     "Dans le contexte de construction, copié par <code>COPY . .</code>",
                     "Dans <code>/run/secrets/jeton</code>, le temps de ce seul RUN"],
         "answer": 3,
         "explain": "BuildKit monte le secret pour une seule instruction RUN, sans l'écrire dans aucune couche ni dans l'historique… sauf si une commande le recopie ailleurs."},
        {"q": "<code>docker build --secret id=jeton,src=~/secrets/api.txt -t outil:1.0 .</code> échoue : fichier introuvable. Pourquoi ?",
         "choices": ["Les secrets doivent se trouver dans le contexte de construction",
                     "Le <code>~</code> n'est pas remplacé par le shell, car il n'est pas en début de mot",
                     "Le fichier d'un secret doit porter l'extension <code>.secret</code>",
                     "<code>src=</code> n'accepte que des chemins relatifs au Dockerfile"],
         "answer": 1,
         "explain": "Le shell ne remplace <code>~</code> qu'en début de mot ; dans <code>src=~/…</code>, Docker reçoit un <code>~</code> littéral. On écrit <code>src=$HOME/secrets/api.txt</code>."},
        {"q": "Que manque-t-il dans l'archive produite par <code>docker export conteneur &gt; systeme.tar</code> ?",
         "choices": ["La configuration (CMD, ENV…) et les tags : seuls les fichiers y sont",
                     "Les fichiers modifiés dans la couche inscriptible du conteneur",
                     "Rien : c'est l'équivalent exact de <code>docker save</code>",
                     "Les fichiers de l'image de base : seules les modifications y sont"],
         "answer": 0,
         "explain": "<code>docker export</code> produit le système de fichiers d'un conteneur, à plat. Pour livrer une image complète (couches, configuration, tags), on utilise <code>docker save</code>."},
        {"q": "Sans accès à Internet, une construction échoue dès la ligne <code># syntax=docker/dockerfile:1</code>. Pourquoi ?",
         "choices": ["Un commentaire est interdit en première ligne d'un Dockerfile",
                     "La syntaxe 1 est obsolète et refusée par Docker 27",
                     "Cette ligne active la vérification en ligne de l'image de base",
                     "Cette ligne fait télécharger l'analyseur du Dockerfile"],
         "answer": 3,
         "explain": "Cette directive demande à BuildKit d'utiliser une image d'analyseur précise, qu'il faut télécharger. Sans Internet, on la retire : l'analyseur intégré suffit."},
        {"q": "Un Dockerfile a trois étapes : <code>outils</code>, <code>tests</code> (dont rien n'est copié) et l'étape finale, qui fait <code>COPY --from=outils</code>. Que construit <code>docker build</code> avec BuildKit ?",
         "choices": ["Les trois étapes, dans l'ordre du fichier",
                     "Seulement <code>outils</code> et l'étape finale",
                     "Seulement l'étape finale ; <code>outils</code> vient toujours du cache",
                     "Les trois, puis <code>tests</code> est retirée de l'image"],
         "answer": 1,
         "explain": "BuildKit ne construit que les étapes dont l'image finale a besoin : une étape dont rien n'est copié est simplement ignorée."},
        {"q": "Parmi ces façons de fournir un mot de passe à une construction, lesquelles le laissent lisible par quiconque récupère l'image ? (plusieurs réponses possibles)",
         "choices": ["Le monter avec <code>RUN --mount=type=secret</code> sans le recopier",
                     "Le passer avec <code>--build-arg</code> et l'utiliser dans un <code>RUN</code>",
                     "Le copier avec <code>COPY</code>, puis le supprimer dans un <code>RUN</code> suivant",
                     "Le garder hors du contexte et ne jamais le transmettre au build"],
         "answer": [1, 2],
         "explain": "La valeur d'un ARG apparaît dans l'historique de l'image (<code>docker history --no-trunc</code>), et un fichier copié reste dans sa couche même supprimé ensuite. Le secret monté par BuildKit n'est écrit nulle part."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    9: [
        {"q": "Deux conteneurs, <code>app</code> et <code>base</code>, sont lancés sans option <code>--network</code>. Que donne <code>docker exec app ping -c1 base</code> ?",
         "choices": ["Il répond : Docker résout toujours les noms des conteneurs",
                     "Le nom <code>base</code> n'est pas résolu : le bridge par défaut n'a pas de DNS",
                     "Il répond seulement si <code>base</code> publie un port avec <code>-p</code>",
                     "Il répond grâce au fichier <code>/etc/hosts</code> de l'hôte"],
         "answer": 1,
         "explain": "Sur le réseau bridge par défaut, les conteneurs ont une adresse IP mais aucun nom n'est résolu. La résolution par nom n'existe que sur un réseau créé par vous."},
        {"q": "L'API et Redis tournent sur le même réseau créé par vous ; le conteneur Redis s'appelle <code>base-demo</code>. Quelle adresse l'API doit-elle utiliser ?",
         "choices": ["<code>localhost:6379</code>, car les conteneurs partagent le réseau",
                     "L'adresse IP du conteneur, relevée avec <code>docker inspect</code>",
                     "<code>base-demo:6379</code>, résolu par le DNS intégré de Docker",
                     "<code>localhost:6379</code>, à condition de publier <code>-p 6379:6379</code>"],
         "answer": 2,
         "explain": "Sur un réseau utilisateur, le DNS intégré (127.0.0.11) résout le nom des conteneurs. <code>localhost</code> désigne le conteneur lui-même, pas Redis."},
        {"q": "Redis n'est utilisé que par l'API, sur le même réseau utilisateur. Faut-il le lancer avec <code>-p 6379:6379</code> ?",
         "choices": ["Oui : sans port publié, aucun conteneur ne peut le joindre",
                     "Oui, sinon le DNS intégré ne trouve pas son nom",
                     "Oui, mais seulement si l'API tourne sur un autre réseau",
                     "Non : l'API le joint directement, et le publier l'exposerait"],
         "answer": 3,
         "explain": "Les conteneurs d'un même réseau se joignent directement. <code>-p</code> ne sert qu'à rendre un service joignable depuis l'extérieur : à éviter pour une base."},
        {"q": "Que change l'option <code>--internal</code> de <code>docker network create</code> pour les conteneurs branchés uniquement sur ce réseau ?",
         "choices": ["Ils se joignent entre eux mais n'ont aucune passerelle vers l'extérieur",
                     "Ils ne peuvent plus se joindre par leur nom, seulement par adresse IP",
                     "Ils ne sont joignables que depuis l'hôte, par les ports publiés",
                     "Ils partagent tous la même adresse IP, celle du réseau"],
         "answer": 0,
         "explain": "Un réseau interne n'a pas de passerelle : ses conteneurs se parlent entre eux (par leur nom) mais ne peuvent ni sortir ni être joints de l'extérieur."},
        {"q": "Sur un même réseau, deux conteneurs ont été lancés avec <code>--network-alias web</code>. Que renvoie <code>nslookup web</code> depuis un troisième conteneur de ce réseau ?",
         "choices": ["Les adresses des deux conteneurs",
                     "Une erreur : un alias doit être unique sur un réseau",
                     "L'adresse du premier conteneur lancé, seulement",
                     "L'adresse de la passerelle du réseau"],
         "answer": 0,
         "explain": "Plusieurs conteneurs peuvent porter le même alias : le DNS de Docker renvoie alors toutes leurs adresses."},
        {"q": "Pourquoi ne configure-t-on jamais une application avec l'adresse IP d'un autre conteneur (<code>DB_HOST=172.18.0.3</code>) ?",
         "choices": ["Parce que les conteneurs n'ont pas d'adresse IP, seulement un nom",
                     "Parce qu'une adresse IP ne passe pas dans une variable d'environnement",
                     "Parce que les adresses peuvent changer à chaque redémarrage",
                     "Parce que Docker bloque les connexions par adresse IP entre conteneurs"],
         "answer": 2,
         "explain": "Docker attribue les adresses au démarrage : elles changent. Sur un réseau utilisateur, on désigne le service par son nom, stable."},
        {"q": "L'API a été lancée avec une mauvaise valeur de <code>-e REDIS_HOST</code>. Comment corriger cette variable ?",
         "choices": ["<code>docker update -e REDIS_HOST=…</code> sur le conteneur existant",
                     "Recréer le conteneur (<code>docker rm -f</code> puis <code>docker run</code>)",
                     "<code>docker exec</code> avec <code>export REDIS_HOST=…</code> dans le conteneur",
                     "<code>docker restart</code> après avoir exporté la variable sur l'hôte"],
         "answer": 1,
         "explain": "Les variables d'un conteneur sont fixées à sa création. Un <code>export</code> dans un <code>docker exec</code> ne vaut que pour ce nouveau processus, pas pour l'application."},
        {"q": "Un conteneur est branché sur <code>front</code> et sur <code>back</code> (réseau <code>--internal</code>). Quels conteneurs peut-il joindre par leur nom ?",
         "choices": ["Seulement ceux du premier réseau auquel il a été branché",
                     "Aucun : un conteneur ne peut appartenir qu'à un seul réseau",
                     "Seulement ceux de <code>front</code>, le réseau interne bloquant tout",
                     "Ceux des deux réseaux, qu'il relie sans les fusionner"],
         "answer": 3,
         "explain": "Un conteneur peut être branché sur plusieurs réseaux et joint les conteneurs de chacun. Les autres conteneurs de <code>front</code> et de <code>back</code> ne se voient pas pour autant entre eux."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    10: [
        {"q": "Dans <code>compose.yaml</code>, <code>front</code> a <code>depends_on: [back]</code> sans condition. Que garantit Compose ?",
         "choices": ["Que <code>back</code> répond aux requêtes avant le démarrage de <code>front</code>",
                     "Que <code>front</code> redémarre automatiquement si <code>back</code> plante",
                     "Que <code>back</code> est démarré avant <code>front</code>, sans attendre qu'il soit prêt",
                     "Que <code>front</code> et <code>back</code> ont un réseau privé à eux deux"],
         "answer": 2,
         "explain": "<code>depends_on</code> fixe l'ordre de démarrage des conteneurs. Pour attendre qu'un service soit prêt, il faut un healthcheck et <code>condition: service_healthy</code>."},
        {"q": "La base écrit dans un volume nommé déclaré dans la section <code>volumes:</code> de premier niveau. Vous faites <code>docker compose down</code> puis <code>docker compose up -d</code>. Et les données ?",
         "choices": ["Perdues : <code>down</code> supprime tout ce que le projet a créé",
                     "Perdues, sauf si l'image de la base est reconstruite",
                     "Perdues, car les conteneurs recréés ont de nouveaux noms",
                     "Conservées : <code>down</code> ne supprime les volumes qu'avec <code>-v</code>"],
         "answer": 3,
         "explain": "<code>down</code> supprime les conteneurs et le réseau du projet ; les volumes nommés survivent, sauf avec <code>docker compose down -v</code>."},
        {"q": "Dans un projet Compose, le service <code>back</code> doit joindre le service <code>base</code>. Quel nom d'hôte utilise-t-il ?",
         "choices": ["<code>base</code>, le nom du service",
                     "<code>localhost</code>, car les services partagent le même conteneur",
                     "Uniquement <code>projet-base-1</code>, le nom complet du conteneur",
                     "L'adresse IP affichée par <code>docker compose ps</code>"],
         "answer": 0,
         "explain": "Compose crée un réseau pour le projet, sur lequel chaque service est joignable par son nom de service."},
        {"q": "Le fichier <code>.env</code> du projet contient <code>MODE=test</code>, et <code>compose.yaml</code> ne mentionne <code>MODE</code> nulle part. Les conteneurs ont-ils la variable <code>MODE</code> ?",
         "choices": ["Oui : Compose transmet tout le <code>.env</code> à chaque conteneur",
                     "Non : <code>.env</code> sert à remplacer les <code>${…}</code> de <code>compose.yaml</code>",
                     "Oui, mais seulement les services construits avec <code>build:</code>",
                     "Non, car <code>.env</code> n'est lu que par <code>docker run</code>"],
         "answer": 1,
         "explain": "Compose lit <code>.env</code> pour substituer les variables du fichier Compose. Pour donner des variables aux conteneurs, il faut <code>environment:</code> ou <code>env_file:</code>."},
        {"q": "Le service <code>outils</code> a <code>profiles: [debug]</code>. Que fait un simple <code>docker compose up -d</code> ?",
         "choices": ["Il démarre tous les services, <code>outils</code> compris",
                     "Il démarre les autres services, et pas <code>outils</code>",
                     "Il échoue, car le profil <code>debug</code> n'est pas précisé",
                     "Il crée le conteneur <code>outils</code> sans le démarrer"],
         "answer": 1,
         "explain": "Un service rattaché à un profil n'existe que si ce profil est activé (<code>--profile debug</code>)."},
        {"q": "Que fait <code>build: ./back</code> pour un service de <code>compose.yaml</code> ?",
         "choices": ["Il construit l'image du service à partir de <code>./back/Dockerfile</code>",
                     "Il monte le dossier <code>./back</code> dans le conteneur du service",
                     "Il exécute le script <code>./back/build.sh</code> avant le démarrage du service",
                     "Il télécharge l'image nommée <code>back</code> depuis un registre"],
         "answer": 0,
         "explain": "<code>build:</code> indique le contexte de construction (<code>./back</code>) ; Compose y cherche un Dockerfile et construit l'image du service (<code>up --build</code> force la reconstruction)."},
        {"q": "Un projet est dans le dossier <code>boutique</code> ; <code>compose.yaml</code> déclare un volume nommé <code>donnees</code>. Quel est le nom réel du volume créé ?",
         "choices": ["<code>donnees</code>",
                     "<code>boutique-donnees-1</code>",
                     "<code>redis_donnees</code>",
                     "<code>boutique_donnees</code>"],
         "answer": 3,
         "explain": "Compose préfixe les ressources par le nom du projet, qui vient du dossier : volume <code>boutique_donnees</code>, conteneurs <code>boutique-service-1</code>…"},
        {"q": "Le service nginx <code>web</code> relaie vers <code>http://api:3000</code> (<code>proxy_pass</code>) et s'arrête au démarrage avec <code>host not found in upstream \"api\"</code>. Quelle est la cause la plus probable ?",
         "choices": ["Le service <code>api</code> ne publie pas son port avec <code>ports:</code>",
                     "nginx ne sait joindre que des adresses IP, pas des noms",
                     "Le service <code>api</code> n'existait pas encore quand nginx a démarré",
                     "Le port 3000 est déjà utilisé sur l'hôte"],
         "answer": 2,
         "explain": "nginx résout les noms de ses serveurs amont à son démarrage. Si le service visé n'existe pas encore, il s'arrête : <code>depends_on</code> fixe l'ordre."},
    ],
    # ─────────────────────────────────────────────────────────────────────
    11: [
        {"q": "Un conteneur est limité à <code>--memory 256m</code>. Quelle option l'empêche en plus d'utiliser le swap ?",
         "choices": ["<code>--memory-swap 256m</code>",
                     "<code>--memory-swap 0</code>",
                     "<code>--memory-swap -1</code>",
                     "<code>--oom-kill-disable</code>"],
         "answer": 0,
         "explain": "<code>--memory-swap</code> est la limite « mémoire + swap » : égale à <code>--memory</code>, elle ne laisse aucune place au swap. <code>-1</code> autorise un swap illimité."},
        {"q": "Après deux <code>docker build -t app:latest .</code> successifs (code modifié entre les deux), <code>docker images</code> montre une ligne <code>&lt;none&gt; &lt;none&gt;</code>. Qu'est-ce ?",
         "choices": ["Une couche de cache de BuildKit",
                     "Une image corrompue par une construction interrompue",
                     "L'image de base téléchargée pour la construction",
                     "L'ancienne version, qui a perdu son tag : une image pendante"],
         "answer": 3,
         "explain": "Le tag <code>app:latest</code> a été déplacé sur la nouvelle image ; l'ancienne reste, sans tag : c'est une image pendante (<em>dangling</em>)."},
        {"q": "Que supprime <code>docker image prune -a</code> ?",
         "choices": ["Toutes les images, y compris celles des conteneurs arrêtés",
                     "Toutes les images qu'aucun conteneur, même arrêté, n'utilise",
                     "Seulement les images pendantes (<code>&lt;none&gt;</code>)",
                     "Les images créées il y a plus de 24 heures"],
         "answer": 1,
         "explain": "Avec <code>-a</code>, toute image non utilisée par un conteneur disparaît, y compris des images de base utiles. Sans <code>-a</code>, seules les images pendantes sont visées."},
        {"q": "Quelle commande indique l'espace disque occupé par les images, les conteneurs, les volumes et le cache de construction ?",
         "choices": ["<code>df -h /var/lib/docker</code>",
                     "<code>docker stats --no-stream</code>",
                     "<code>docker system df</code>",
                     "<code>docker images --size</code>"],
         "answer": 2,
         "explain": "<code>docker system df</code> détaille l'espace utilisé par catégorie, et ce qui est récupérable. <code>docker stats</code> mesure CPU et mémoire."},
        {"q": "<code>docker compose ps -a</code> montre le service <code>api</code> à l'état <em>Restarting (1)</em>. Quelle est la première chose à faire ?",
         "choices": ["<code>docker compose down -v</code>, pour repartir de zéro",
                     "<code>docker image prune</code>, pour forcer une reconstruction propre",
                     "<code>docker compose logs api</code>, pour lire le message d'erreur",
                     "<code>docker compose restart api</code>, pour relancer le service"],
         "answer": 2,
         "explain": "Le service plante en boucle avec le code 1 : son processus a signalé une erreur. Ses journaux disent laquelle ; les autres commandes détruisent des données ou ne changent rien."},
        {"q": "<code>compose.yaml</code> utilise des variables <code>${…}</code>. Comment voir la configuration réellement appliquée, variables remplacées ?",
         "choices": ["<code>docker compose ps</code>",
                     "<code>docker compose config</code>",
                     "<code>docker compose logs</code>",
                     "<code>cat compose.yaml</code>"],
         "answer": 1,
         "explain": "<code>docker compose config</code> affiche la configuration telle que Compose la comprend : fichiers fusionnés, variables substituées."},
        {"q": "Dans <code>compose.yaml</code>, un service a <code>ports: [\"8090:3000\"]</code>. Quelle affirmation est exacte ?",
         "choices": ["L'application doit écouter sur 8090 ; l'hôte relaie vers 3000",
                     "L'hôte et le conteneur écoutent tous deux sur 3000 et 8090",
                     "Le port 8090 n'est joignable que depuis les autres services",
                     "L'hôte écoute sur 8090 et relaie vers le port 3000 du conteneur"],
         "answer": 3,
         "explain": "L'ordre est toujours <code>hôte:conteneur</code>. Le port du conteneur doit être celui sur lequel l'application écoute vraiment."},
        {"q": "<code>docker system df</code> montre un cache de construction de plusieurs gigaoctets. Quelle commande le libère sans toucher aux images ni aux volumes ?",
         "choices": ["<code>docker builder prune</code>",
                     "<code>docker image prune</code>",
                     "<code>docker volume prune</code>",
                     "<code>docker container prune</code>"],
         "answer": 0,
         "explain": "<code>docker builder prune</code> vide le cache de construction. Les autres commandes visent les images, les volumes ou les conteneurs."},
    ],
}
