"""Mémo du parcours Ansible : une fiche par commande ou notion, débloquée par un exercice."""
from ..linux.memo import C

BASE, ADHOC, PLAY, VARS, HANDL, LOOPS, ROLES, PROD = (
    "Accès et inventaire", "Commandes ad hoc", "Playbooks", "Variables et modèles", "Handlers",
    "Boucles et conditions", "Rôles et vérification", "Production",
)

CARDS = [
    C("ssh-cle", "Clé SSH", BASE, "Ansible se connecte en SSH : une clé évite les mots de passe.",
      ["ssh-keygen -t ed25519", "ssh-copy-id <utilisateur>@<serveur>", "ssh-keyscan <serveur> >> ~/.ssh/known_hosts"],
      [("ssh-copy-id admin@web1", "copie la clé publique"), ("ssh admin@web1 hostname", "test : aucune question")], ["A1.1"]),
    C("inventaire", "Inventaire", BASE, "La liste des serveurs, rangés en groupes.",
      ["[groupe]", "serveur", "[parent:children]", "ansible-inventory -i <fichier> --graph"],
      [("[web]\nweb1\nweb2\n\n[production:children]\nweb\nbdd", "inventaire.ini"), ("ansible-inventory --graph", "l'arbre des groupes")], ["A1.2"]),
    C("ansible-cfg", "ansible.cfg", BASE, "Réglages du projet, lus dans le dossier courant.",
      ["[defaults]", "inventory = <fichier>", "remote_user = <utilisateur>", "ansible-config dump --only-changed"],
      [("[defaults]\ninventory = inventaire.ini\nremote_user = admin", "")], ["A1.3"]),
    C("ping", "ansible -m ping", BASE, "Vérifie qu'Ansible peut se connecter et exécuter Python (pas un ping réseau).",
      ["ansible <cible> -m ping"], [("ansible production -m ping", "pong = tout va bien"), ("ansible all -m ping -o", "une ligne par serveur")], ["A1.3"]),

    C("verbose", "-v, -vv, -vvv", ADHOC, "Affiche ce qu'Ansible fait vraiment : connexion, module envoyé, résultat.",
      ["ansible <cible> -m <module> -vvv", "ansible-playbook <playbook> -vv"],
      [("ansible web1 -m ping -vvv", "cherchez PUT … AnsiballZ_ping.py")], ["A2.1"]),
    C("facts", "Facts (module setup)", ADHOC, "Informations collectées sur chaque serveur, utilisables comme variables.",
      ["ansible <cible> -m setup [-a \"filter=<motif>\"]"],
      [("ansible db1 -m setup -a \"filter=ansible_distribution*\"", ""), ("{{ ansible_default_ipv4.address }}", "dans un modèle")], ["A2.2"]),
    C("adhoc", "Commande ad hoc", ADHOC, "Une action ponctuelle, sans playbook.",
      ["ansible <cible> -m <module> -a \"<arguments>\"", "ansible-doc <module>"],
      [("ansible web -b -m user -a \"name=deploy\"", ""), ("ansible web -b -m copy -a \"dest=/etc/motd content='Bonjour'\"", ""),
       ("ansible all -m command -a \"df -h /\"", "command : toujours « changed »")], ["A2.3"]),
    C("become", "become (-b)", ADHOC, "Exécuter en root, via sudo, sur les serveurs.",
      ["ansible ... -b", "become: true   # dans un play ou une tâche"], [("ansible web -b -m apt -a \"name=tree\"", "")], ["A2.3"]),

    C("playbook", "Playbook", PLAY, "Fichier YAML : des plays (serveurs + tâches), joués dans l'ordre.",
      ["- name: ...\n  hosts: <groupe>\n  become: true\n  tasks:\n    - name: ...\n      <module>:\n        <paramètre>: <valeur>",
       "ansible-playbook <playbook> [--syntax-check]"],
      [("ansible-playbook web.yml", ""), ("ansible-playbook web.yml --syntax-check", "vérifie le YAML")], ["A3.1"]),
    C("apt-service", "apt et service", PLAY, "Installer un paquet ; démarrer et activer un service.",
      ["ansible.builtin.apt: name, state, update_cache, cache_valid_time", "ansible.builtin.service: name, state (started|stopped|restarted|reloaded), enabled"],
      [("ansible.builtin.apt:\n  name: nginx\n  update_cache: true\n  cache_valid_time: 3600", ""), ("ansible.builtin.service:\n  name: nginx\n  state: started\n  enabled: true", "")], ["A3.1"]),
    C("copy", "copy", PLAY, "Copie un fichier du poste de contrôle vers les serveurs.",
      ["ansible.builtin.copy: src, dest, mode, owner", "ansible.builtin.copy: content, dest"],
      [("ansible.builtin.copy:\n  src: fichiers/index.html\n  dest: /var/www/html/index.html\n  mode: \"0644\"", "")], ["A3.2"]),
    C("idempotence", "Idempotence et récapitulatif", PLAY, "Rejoué, un bon playbook ne change rien : changed=0.",
      ["PLAY RECAP : ok, changed, unreachable, failed, skipped"],
      [("web1 : ok=4 changed=0 unreachable=0 failed=0", "état conforme"), ("ansible-playbook web.yml --diff", "voir ce qui change")], ["A3.3"]),

    C("vars", "group_vars et host_vars", VARS, "Variables chargées automatiquement selon le groupe ou le serveur (l'hôte l'emporte).",
      ["group_vars/<groupe>.yml", "host_vars/<serveur>.yml", "ansible-inventory --host <serveur>"],
      [("# group_vars/web.yml\nenvironnement: production", ""), ("ansible-inventory --host web2", "variables vues pour web2")], ["A4.1", "A4.2"]),
    C("template", "template (Jinja2)", VARS, "Comme copy, mais les {{ variables }} sont remplacées pour chaque serveur.",
      ["ansible.builtin.template: src, dest", "{{ variable }}", "{{ variable | filtre }}"],
      [("<p>Serveur : {{ inventory_hostname }}</p>", "dans index.html.j2"), ("{{ environnement | upper }}", "filtre")], ["A4.1"]),
    C("facts-vars", "Facts dans un modèle", VARS, "Les facts collectés s'utilisent comme n'importe quelle variable.",
      ["{{ ansible_default_ipv4.address }}", "{{ ansible_distribution }} {{ ansible_distribution_version }}", "{{ ansible_memtotal_mb }}"],
      [("<p>Adresse : {{ ansible_default_ipv4.address }}</p>", "")], ["A4.3"]),

    C("handlers", "notify et handlers", HANDL, "Une action (recharger un service) exécutée une fois, en fin de play, seulement si une tâche a changé.",
      ["notify: <nom du handler>", "handlers:\n  - name: <nom>\n    <module>: ..."],
      [("notify: Recharger nginx", "sur la tâche template"), ("handlers:\n  - name: Recharger nginx\n    ansible.builtin.service:\n      name: nginx\n      state: reloaded", "")], ["A5.1"]),
    C("extra-vars", "-e (extra vars)", HANDL, "Surcharge une variable pour une exécution (priorité la plus forte).",
      ["ansible-playbook <playbook> -e <variable>=<valeur>"], [("ansible-playbook web.yml -e http_port=8089", "")], ["A5.2"]),

    C("loop", "loop", LOOPS, "Répète une tâche pour chaque élément d'une liste ; l'élément courant est item.",
      ["loop: \"{{ liste }}\"", "{{ item }}"],
      [("ansible.builtin.user:\n  name: \"{{ item }}\"\n  groups: www-data\n  append: true\nloop: \"{{ equipe_web }}\"", "")], ["A6.1"]),
    C("when", "when", LOOPS, "N'exécute la tâche que si la condition est vraie (sinon : skipping).",
      ["when: <expression>"], [("when: environnement == \"recette\"", ""), ("when: ansible_memtotal_mb < 1024", "sur un fact")], ["A6.2"]),
    C("jinja-if", "{% if %} et {% for %}", LOOPS, "Conditions et boucles dans un modèle Jinja2.",
      ["{% if <condition> %} … {% endif %}", "{% for x in liste %} … {% endfor %}"],
      [("{% if environnement == \"recette\" %}\n<div>RECETTE</div>\n{% endif %}", "")], ["A6.2"]),

    C("roles", "Rôles", ROLES, "Tout ce qu'il faut pour un service, dans une arborescence standard.",
      ["ansible-galaxy init --init-path roles <rôle>", "roles/<rôle>/{tasks,handlers,templates,files,defaults}/", "roles:\n  - <rôle>"],
      [("ansible-galaxy init --init-path roles web", ""), ("- hosts: web\n  become: true\n  roles:\n    - web", "site.yml")], ["A7.2"]),
    C("check-diff", "--check et --diff", ROLES, "Joue « à blanc » : montre ce qui changerait, sans rien changer. Idéal contre les dérives.",
      ["ansible-playbook <playbook> --check [--diff]"], [("ansible-playbook web.yml --check --diff", "")], ["A7.1"]),

    C("vault", "ansible-vault", PROD, "Chiffre les fichiers de variables secrètes.",
      ["ansible-vault create|encrypt|view|edit <fichier>", "vault_password_file = ~/.vault_pass   # ansible.cfg"],
      [("ansible-vault encrypt group_vars/bdd/vault.yml", ""), ("ansible-vault view group_vars/bdd/vault.yml", ""), ("no_log: true", "sur une tâche qui manipule un secret")], ["A8.1"]),
    C("lineinfile", "lineinfile", PROD, "Garantit qu'une ligne est présente dans un fichier (remplace celle qui correspond à regexp).",
      ["ansible.builtin.lineinfile: path, regexp, line"],
      [("ansible.builtin.lineinfile:\n  path: /etc/redis/redis.conf\n  regexp: '^bind '\n  line: bind 0.0.0.0", "")], ["A8.1"]),
    C("limit", "--limit", PROD, "Restreint l'exécution à certains serveurs de l'inventaire.",
      ["ansible-playbook <playbook> --limit <serveur ou groupe>"], [("ansible-playbook site.yml --limit web3", "")], ["A8.2"]),
    C("site", "site.yml", PROD, "Le playbook qui décrit toute l'infrastructure : un play par groupe, des rôles.",
      ["- hosts: <groupe>\n  roles: [<rôle>]"], [("ansible-playbook site.yml", "reconstruit tout, ou vérifie que tout est conforme")], ["A8.3"]),
]
