"""Mémo du parcours Ansible : une fiche par commande ou notion, débloquée par un exercice.

Les exemples visent volontairement une autre infrastructure (vitrine1, front, cache…) : une fiche rappelle une
syntaxe, elle ne donne jamais la réponse d'un exercice.
"""
from ..linux.memo import C

BASE, ADHOC, PLAY, VARS, HANDL, LOOPS, ROLES, PROD, FIAB, DEPLOI = (
    "Accès et inventaire", "Commandes ad hoc", "Playbooks", "Variables et modèles", "Handlers",
    "Boucles, conditions et filtres", "Rôles et vérification", "Production", "Fiabiliser", "Déployer",
)

CARDS = [
    C("ssh-cle", "Clé SSH", BASE, "Ansible se connecte en SSH : une paire de clés évite les mots de passe.",
      ["ssh-keygen -t ed25519", "ssh-copy-id <utilisateur>@<serveur>", "ssh -o BatchMode=yes <utilisateur>@<serveur> true"],
      [("ssh-copy-id exploitant@vitrine1", "installe la clé publique (dernier mot de passe)"),
       ("ssh -o BatchMode=yes exploitant@vitrine1 true", "test : échoue au lieu de poser une question")], ["A1.1"]),
    C("inventaire", "Inventaire", BASE, "La liste des serveurs, rangés en groupes ; un groupe peut contenir d'autres groupes.",
      ["[groupe]", "serveur", "[parent:children]", "ansible-inventory -i <fichier> --graph"],
      [("[front]\nvitrine1\n\n[prod:children]\nfront\ncache", "serveurs.ini"), ("ansible-inventory --graph", "l'arbre des groupes")], ["A1.2"]),
    C("ansible-cfg", "ansible.cfg", BASE, "Réglages du projet, lus dans le dossier courant.",
      ["[defaults]", "inventory = <fichier>", "remote_user = <utilisateur>", "ansible-config dump --only-changed"],
      [("[defaults]\ninventory = serveurs.ini\nremote_user = exploitant", ""), ("ansible --version", "affiche aussi le fichier de configuration lu")], ["A1.3"]),
    C("ping", "ansible -m ping", BASE, "Vérifie qu'Ansible peut se connecter et exécuter Python (pas un ping réseau).",
      ["ansible <cible> -m ping"], [("ansible prod -m ping", "pong = tout va bien"), ("ansible all -m ping -o", "une ligne par serveur")], ["A1.3"]),
    C("motifs", "Motifs de cible", BASE, "Combiner des groupes pour viser exactement les bons serveurs.",
      ["a:b   (a OU b)", "a:&b  (a ET b)", "a:!b  (a SAUF b)", "a[0]  (le premier de a)", "--list-hosts"],
      [("ansible 'prod:!cache' --list-hosts", "entre guillemets simples, à cause du shell"), ("ansible 'front:&marseille' -m ping", "")], ["A1.4"]),

    C("verbose", "-v, -vv, -vvv", ADHOC, "Affiche ce qu'Ansible fait vraiment : connexion, dossier temporaire, envoi (PUT), exécution (EXEC).",
      ["ansible <cible> -m <module> -a \"…\" -vvv", "ansible-playbook <playbook> -vv"],
      [("ansible vitrine1 -m ping -vvv", "cherchez les lignes PUT et EXEC")], ["A2.1"]),
    C("modules", "Modules et collections", ADHOC, "ansible-core fournit les modules ansible.builtin ; les autres collections s'installent avec ansible-galaxy.",
      ["ansible-doc -l", "ansible-doc <module>", "ansible.builtin.<module>   # FQCN"],
      [("ansible-doc -l | grep -i user", "trouver un module"), ("ansible-doc ansible.builtin.copy", "paramètres et exemples")], ["A2.1"]),
    C("facts", "Facts (module setup)", ADHOC, "Informations collectées sur chaque serveur, y compris celles qu'il déclare lui-même (facts locaux).",
      ["ansible <cible> -m setup [-a \"filter=<motif>\"]", "/etc/ansible/facts.d/<nom>.fact  →  ansible_local.<nom>"],
      [("ansible memo1 -m setup -a \"filter=ansible_kernel*\"", ""), ("ansible memo1 -m setup -a \"filter=ansible_local\"", "les facts déclarés par le serveur")], ["A2.2"]),
    C("adhoc", "Commande ad hoc", ADHOC, "Une action ponctuelle, sans playbook.",
      ["ansible <cible> -m <module> -a \"<paramètre>=<valeur> …\""],
      [("ansible front -b -m user -a \"name=livreur uid=1500 groups=adm\"", ""), ("ansible front -b -m copy -a \"dest=/etc/issue.net content='Accès réservé\\n'\"", "")], ["A2.3"]),
    C("become", "become (-b)", ADHOC, "Exécuter en root, via sudo, sur les serveurs.",
      ["ansible ... -b", "become: true   # dans un play ou une tâche"], [("ansible front -b -m apt -a \"name=tree\"", "")], ["A2.3"]),
    C("empreintes", "Empreintes SSH", ADHOC, "Un serveur réinstallé change d'empreinte : vérifier avant de faire confiance, ne jamais désactiver la vérification.",
      ["ssh-keyscan -t ed25519 <serveur> | ssh-keygen -lf -", "ssh-keygen -R <serveur>", "ssh-keygen -F <serveur>"],
      [("ssh-keygen -R vitrine1", "oublie l'ancienne empreinte")], ["A2.4"]),
    C("find-file", "find et file", ADHOC, "Chercher des fichiers sur tous les serveurs ; décrire un fichier présent, absent, un dossier, un lien.",
      ["ansible.builtin.find: paths, patterns, recurse, contains", "ansible.builtin.file: path, state (file|directory|link|absent)"],
      [("ansible all -b -m find -a \"paths=/var/log patterns='*.gz' recurse=yes\"", ""), ("ansible memo1 -b -m file -a \"path=/tmp/vieux.log state=absent\"", "")], ["A2.5"]),

    C("playbook", "Playbook", PLAY, "Fichier YAML : des plays (serveurs + tâches), joués dans l'ordre.",
      ["- name: ...\n  hosts: <groupe>\n  become: true\n  tasks:\n    - name: ...\n      <module>:\n        <paramètre>: <valeur>",
       "ansible-playbook <playbook> [--syntax-check]"],
      [("ansible-playbook lb.yml", ""), ("ansible-playbook lb.yml --syntax-check", "YAML et structure, pas les paramètres")], ["A3.1"]),
    C("apt-service", "apt et service", PLAY, "Installer un paquet ; démarrer et activer un service.",
      ["ansible.builtin.apt: name, state, update_cache, cache_valid_time", "ansible.builtin.service: name, state (started|stopped|restarted|reloaded), enabled"],
      [("ansible.builtin.apt:\n  name: haproxy\n  update_cache: true\n  cache_valid_time: 3600", ""), ("ansible.builtin.service:\n  name: haproxy\n  state: started\n  enabled: true", "")], ["A3.1"]),
    C("copy", "copy", PLAY, "Copie un fichier du poste de contrôle vers les serveurs (src relatif au playbook).",
      ["ansible.builtin.copy: src, dest, mode, owner", "ansible.builtin.copy: content, dest"],
      [("ansible.builtin.copy:\n  src: fichiers/robots.txt\n  dest: /var/www/html/robots.txt\n  mode: \"0644\"", "")], ["A3.2"]),
    C("idempotence", "Idempotence et récapitulatif", PLAY, "Rejoué, un bon playbook ne change rien : changed=0.",
      ["PLAY RECAP : ok, changed, unreachable, failed, skipped", "command/shell : creates, removes"],
      [("lb1 : ok=4 changed=0 unreachable=0 failed=0", "état conforme"), ("ansible.builtin.command:\n  cmd: /opt/outil/installer\n  creates: /opt/outil/installé", "ne rien faire si le fichier existe")], ["A3.3"]),
    C("etat", "Décrire un état", PLAY, "Remplacer une action (mkdir, echo >>, apt-get) par le module qui décrit l'état voulu.",
      ["ansible.builtin.file: path, state: directory, owner, group, mode", "ansible.builtin.lineinfile: path, line, create: true"],
      [("ansible.builtin.lineinfile:\n  path: /etc/issue.net\n  line: Accès réservé\n  create: true", "une seule fois, quel que soit le nombre de passages")], ["A3.3"]),
    C("yaml-pieges", "Pièges du YAML et des playbooks", PLAY, "Les erreurs classiques : lire le premier message en entier.",
      ["tabulation interdite", "\"{{ variable }}\" entre guillemets", "mode: \"0644\" (pas 644)", "hosts sans correspondance : no hosts matched"],
      [("ansible-playbook lb.yml --syntax-check", ""), ("[WARNING]: Could not match supplied host pattern", "le play ne vise aucun serveur")], ["A3.4"]),

    C("vars", "group_vars et host_vars", VARS, "Variables chargées automatiquement selon le groupe ou le serveur.",
      ["group_vars/<groupe>.yml", "host_vars/<serveur>.yml", "ansible-inventory --host <serveur>"],
      [("# group_vars/front.yml\nsaison: hiver", ""), ("ansible-inventory --host vitrine2", "valeur finale, pas son origine")], ["A4.1", "A4.2"]),
    C("template", "template (Jinja2)", VARS, "Comme copy, mais les {{ variables }} sont remplacées pour chaque serveur.",
      ["ansible.builtin.template: src, dest", "{{ variable }}", "{{ variable | filtre }}", "{# commentaire #}"],
      [("<h1>{{ enseigne }}</h1>", "dans accueil.html.j2"), ("{{ saison | upper }}", "filtre")], ["A4.1"]),
    C("facts-vars", "Facts dans un modèle", VARS, "Les facts collectés s'utilisent comme n'importe quelle variable.",
      ["{{ ansible_facts['<nom>'] }}", "{{ ansible_<nom> }}   # forme historique"],
      [("{{ ansible_facts['memtotal_mb'] }} Mo", ""), ("{{ ansible_facts['distribution'] }}", "")], ["A4.3"]),
    C("magiques", "Variables magiques", VARS, "Ce qu'Ansible sait de l'inventaire : utile pour qu'un serveur connaisse les autres.",
      ["inventory_hostname", "group_names", "groups['<groupe>']", "hostvars['<serveur>']['<variable>']"],
      [("{{ groups['front'] | join(', ') }}", ""), ("{% for v in groups['front'] %}{{ hostvars[v]['saison'] }}{% endfor %}", "")], ["A4.3"]),
    C("precedence", "Précédence des variables", VARS, "Qui l'emporte quand une variable est définie à plusieurs endroits (du plus faible au plus fort).",
      ["defaults/ de rôle < [groupe:vars] < group_vars/all < group_vars/<parent> < group_vars/<enfant>",
       "< variable d'hôte de l'inventaire < host_vars < facts < vars du play < vars/ de rôle < set_fact/register < -e"],
      [("ansible vitrine2 -m debug -a \"var=saison\"", "la valeur vue pendant un jeu")], ["A4.4"]),

    C("handlers", "notify et handlers", HANDL, "Une action (recharger un service) exécutée une fois, en fin de section, seulement si une tâche a changé.",
      ["notify: <nom du handler>", "handlers:\n  - name: <nom>\n    <module>: ...", "listen: <événement>"],
      [("notify: Recharger haproxy", "sur la tâche template"), ("handlers:\n  - name: Recharger haproxy\n    ansible.builtin.service:\n      name: haproxy\n      state: reloaded", "")], ["A5.1"]),
    C("flush-uri", "flush_handlers et uri", HANDL, "Exécuter les handlers en attente tout de suite ; vérifier qu'un service HTTP répond.",
      ["- ansible.builtin.meta: flush_handlers", "ansible.builtin.uri: url, status_code, return_content"],
      [("- ansible.builtin.uri:\n    url: \"http://localhost:{{ port_admin }}/sante\"", "échoue si le code n'est pas 200")], ["A5.2"]),
    C("extra-vars", "-e (extra vars)", HANDL, "Surcharge une variable pour une exécution (priorité la plus forte ; valeur toujours de type texte).",
      ["ansible-playbook <playbook> -e <variable>=<valeur>"], [("ansible-playbook vitrine.yml -e port_vitrine=8001", "")], ["A5.2"]),
    C("validate", "validate", HANDL, "Tester le fichier candidat (%s) avant qu'il remplace le vrai : rien n'est écrit si le test échoue.",
      ["validate: <commande> %s   # template, copy, lineinfile"],
      [("validate: /usr/sbin/visudo -cf %s", "fichier sudoers"), ("validate: /usr/sbin/sshd -t -f %s", "configuration de sshd")], ["A5.3"]),
    C("force-handlers", "force_handlers", HANDL, "Sans lui, un serveur en échec perd ses handlers notifiés… et le passage suivant ne les rappelle pas.",
      ["force_handlers: true   # dans le play", "force_handlers = True   # [defaults] d'ansible.cfg"],
      [("ansible front -b -m service -a \"name=haproxy state=reloaded\"", "réparer à la main un serveur déjà touché")], ["A5.4"]),

    C("loop", "loop", LOOPS, "Répète une tâche pour chaque élément d'une liste ; l'élément courant est item.",
      ["loop: \"{{ liste }}\"", "{{ item }}  {{ item.attribut }}", "loop: \"{{ dico | dict2items }}\"  →  item.key, item.value"],
      [("ansible.builtin.user:\n  name: \"{{ item }}\"\n  groups: adm\n  append: true\nloop: \"{{ operateurs }}\"", "")], ["A6.1"]),
    C("when", "when", LOOPS, "N'exécute la tâche que si la condition est vraie (sinon : skipping) ; évaluée pour chaque élément d'une boucle.",
      ["when: <expression>", "and, or, not, in, is defined"],
      [("when: saison == \"hiver\"", "texte entre guillemets"), ("when: \"'front' in group_names\"", "")], ["A6.2"]),
    C("jinja-if", "{% if %} et {% for %}", LOOPS, "Conditions et boucles dans un modèle Jinja2.",
      ["{% if <condition> %} … {% elif … %} … {% endif %}", "{% for x in liste %} … {% endfor %}", "loop.index, loop.last"],
      [("{% if saison == \"hiver\" %}\n<p>Collection hiver</p>\n{% endif %}", "")], ["A6.2"]),
    C("filtres", "Filtres de listes", LOOPS, "Trier, extraire, filtrer une liste de fiches.",
      ["map(attribute='<clé>')", "selectattr('<clé>') / rejectattr('<clé>')", "sort, unique, join(', '), length, first, default(…)"],
      [("{{ comptes | selectattr('admin') | map(attribute='nom') | list }}", "les noms des admins"), ("{{ comptes | rejectattr('admin') | list }}", "")], ["A6.3"]),
    C("bool", "Booléens et | bool", LOOPS, "\"false\" est une chaîne non vide, donc vraie : convertir avec | bool (valeurs de -e comprises).",
      ["when: <variable> | bool", "{{ <variable> | type_debug }}"],
      [("when: sauvegarde_active | bool", ""), ("ansible vitrine1 -m debug -a \"msg={{ actif | type_debug }}\"", "")], ["A6.4"]),
    C("debug", "debug", LOOPS, "Afficher une variable ou une expression pendant un jeu, ou en ad hoc.",
      ["ansible.builtin.debug: var=<variable>", "ansible.builtin.debug: msg=\"{{ … }}\""],
      [("ansible vitrine1 -m debug -a \"msg={{ operateurs | length }}\"", "")], ["A6.4"]),

    C("check-diff", "--check et --diff", ROLES, "Joue « à blanc » : montre ce qui changerait, sans rien changer. Ne voit que ce que le code décrit.",
      ["ansible-playbook <playbook> --check [--diff]"], [("ansible-playbook vitrine.yml --check --diff", "")], ["A7.1"]),
    C("roles", "Rôles", ROLES, "Tout ce qu'il faut pour un service, dans une arborescence standard.",
      ["ansible-galaxy init --init-path roles <rôle>", "roles/<rôle>/{tasks,handlers,templates,files,defaults,vars,meta}/", "roles:\n  - <rôle>"],
      [("ansible-galaxy init --init-path roles vitrine", ""), ("- hosts: front\n  become: true\n  roles:\n    - vitrine", "site.yml")], ["A7.2"]),
    C("defaults-vars", "defaults/ ou vars/ ?", ROLES, "defaults : valeurs par défaut, surchargées par l'inventaire. vars : priorité très forte, elle écrase host_vars.",
      ["roles/<rôle>/defaults/main.yml", "roles/<rôle>/vars/main.yml"],
      [("# roles/vitrine/defaults/main.yml\nport_vitrine: 80", "surchargeable par group_vars et host_vars")], ["A7.2", "A8.4"]),
    C("absent", "Décrire une absence", ROLES, "Ce que le code ne mentionne pas n'existe pas pour Ansible : pour interdire, décrire state: absent.",
      ["ansible.builtin.user: name, state: absent, remove: true", "ansible.builtin.file: path, state: absent", "ansible.builtin.apt: name, state: absent"],
      [("ansible.builtin.user:\n  name: ancien\n  state: absent\n  remove: true", "supprime aussi le dossier personnel")], ["A7.3"]),

    C("vault", "ansible-vault", PROD, "Chiffre les fichiers de variables secrètes ; la clé reste hors du projet.",
      ["ansible-vault create|encrypt|view|edit|rekey <fichier>", "vault_password_file = <fichier>   # ansible.cfg"],
      [("ansible-vault view group_vars/cache/vault.yml", ""), ("no_log: true", "sur une tâche qui manipule un secret")], ["A8.1"]),
    C("lineinfile", "lineinfile", PROD, "Garantit une ligne dans un fichier : remplace la dernière qui correspond à regexp, sinon l'ajoute.",
      ["ansible.builtin.lineinfile: path, regexp, line"],
      [("ansible.builtin.lineinfile:\n  path: /etc/memcached.conf\n  regexp: '^-l '\n  line: -l 0.0.0.0", "")], ["A8.1"]),
    C("limit", "--limit", PROD, "Restreint un jeu à certains serveurs de l'inventaire (les autres ne sont pas contactés).",
      ["ansible-playbook <playbook> --limit <motif>"], [("ansible-playbook site.yml --limit vitrine3", "")], ["A8.2"]),
    C("site", "site.yml", PROD, "Le playbook qui décrit toute l'infrastructure : un play par groupe, des rôles. Un serveur neuf est reconstruit en un passage.",
      ["- hosts: <groupe>\n  roles: [<rôle>]"], [("ansible-playbook site.yml", "reconstruit tout, ou vérifie que tout est conforme")], ["A8.3"]),

    C("register", "register", FIAB, "Garder le résultat d'une tâche : rc, stdout, stderr, stdout_lines, changed…",
      ["register: <nom>", "<nom>.stdout  <nom>.stderr  <nom>.rc", "changed_when: false   # pour une simple lecture"],
      [("- ansible.builtin.command: uname -r\n  register: noyau\n  changed_when: false", ""), ("hostvars['vitrine1']['noyau']['stdout']", "depuis un autre serveur")], ["A9.1"]),
    C("delegate", "delegate_to et run_once", FIAB, "Exécuter une tâche ailleurs (le poste de contrôle), une seule fois pour tout le play.",
      ["delegate_to: localhost", "run_once: true", "become: false   # pas de sudo sur le poste"],
      [("dest: \"{{ playbook_dir }}/rapport.txt\"", "un fichier écrit sur le poste de contrôle")], ["A9.1"]),
    C("changed-failed", "changed_when et failed_when", FIAB, "Décider soi-même de ce que « changé » et « échoué » veulent dire pour une commande.",
      ["changed_when: <condition>", "failed_when: <condition>", "rc in [0, 2]   'texte' in resultat.stdout"],
      [("failed_when: rotation.rc not in [0, 2] or 'CRITIQUE' in rotation.stderr", "")], ["A9.2"]),
    C("assert", "assert et pre_tasks", FIAB, "Vérifier les données d'entrée avant d'agir, et s'arrêter avec un message clair.",
      ["pre_tasks:", "ansible.builtin.assert: that, fail_msg", "ansible.builtin.fail: msg"],
      [("ansible.builtin.assert:\n  that:\n    - saison in ['hiver', 'été']\n  fail_msg: Saison inconnue", "")], ["A9.3"]),
    C("block", "block, rescue, always", FIAB, "Essayer, rattraper l'échec, toujours conclure. rescue sans fail = échec rattrapé.",
      ["block: [...]", "rescue: [...]", "always: [...]", "ansible_failed_task, ansible_failed_result"],
      [("ansible.builtin.unarchive:\n  src: http://depot.exemple.lan/catalogue.tar.gz\n  dest: /srv/catalogue\n  remote_src: true", "archive téléchargée par le serveur")], ["A9.4"]),

    C("incident", "Méthode d'incident", DEPLOI, "Constater, lire, corriger dans le code, rejouer deux fois.",
      ["ansible all -m ping", "ansible-playbook site.yml --check --diff", "curl -s -o /dev/null -w '%{http_code}' http://<serveur>/"],
      [("ansible all -m getent -a \"database=group key=adm\"", "qui est dans un groupe, partout")], ["A10.1"]),
    C("serial", "serial", DEPLOI, "Déployer par lots : le play entier est joué sur un lot avant le suivant.",
      ["serial: 1 | 2 | \"30%\" | [1, \"50%\"]", "max_fail_percentage: 0", "any_errors_fatal: true"],
      [("- hosts: front\n  serial: 2\n  max_fail_percentage: 0", "")], ["A10.2"]),
    C("tags", "Tags", DEPLOI, "Étiqueter des tâches pour n'en jouer qu'une partie.",
      ["tags: [<étiquette>]", "--tags / --skip-tags <étiquette>", "--list-tags  --list-tasks", "always, never"],
      [("ansible-playbook site.yml --tags contenu", ""), ("ansible-playbook site.yml --start-at-task \"Page d'accueil\"", "reprendre à une tâche")], ["A10.3"]),
]
