"""QCM de fin de cours du parcours Ansible : 8 questions par étape, 4 tirées au sort pour chaque étudiant."""

# Inventaire utilisé par les questions de motifs du jour 1
_PARC = ("<pre>[web]<br>w1<br>w2<br>w3<br><br>[lyon]<br>w1<br>db1<br><br>[bdd]<br>db1<br>db2</pre>")

QUIZ = {
    # ─── Jour 1 : modèle d'Ansible, SSH, inventaire, motifs, ansible.cfg ───
    1: [
        {"q": "Avec cet inventaire, quels serveurs vise le motif <code>'web:&amp;lyon'</code> ?" + _PARC,
         "choices": ["w1, w2, w3 et db1",
                     "w2 et w3",
                     "w1 seulement",
                     "db1 seulement"],
         "answer": 2,
         "explain": "<code>:&amp;</code> est l'intersection : les serveurs à la fois dans web et dans lyon. Seul w1 est dans les deux groupes."},
        {"q": "Avec cet inventaire, quels serveurs vise le motif <code>'web:!lyon'</code> ?" + _PARC,
         "choices": ["w2 et w3",
                     "w1 seulement",
                     "w2, w3 et db2",
                     "w1, w2, w3 et db1"],
         "answer": 0,
         "explain": "<code>:!</code> est l'exclusion : les serveurs de web, sauf ceux de lyon. w1 est retiré ; db2 n'est pas dans web."},
        {"q": "Que faut-il installer sur un serveur pour qu'Ansible puisse le gérer ?",
         "choices": ["Un agent Ansible qui interroge régulièrement le poste de contrôle",
                     "Ansible lui-même, dans la même version que sur le poste de contrôle",
                     "Un certificat TLS délivré par le poste de contrôle",
                     "Rien de spécifique : un serveur SSH et Python suffisent"],
         "answer": 3,
         "explain": "Ansible est sans agent : il se connecte en SSH et exécute ses modules avec le Python du serveur, présent sur presque tous les Linux."},
        {"q": "Première commande Ansible vers un serveur jamais contacté : <em>Host key verification failed</em>. Quelle en est la cause ?",
         "choices": ["La clé publique du poste n'est pas dans <code>authorized_keys</code> sur le serveur",
                     "L'empreinte du serveur n'est pas encore dans <code>known_hosts</code> sur le poste",
                     "Python n'est pas installé sur le serveur, qui ne peut pas exécuter le module",
                     "Le compte distant n'a pas les droits sudo nécessaires au module"],
         "answer": 1,
         "explain": "Face à un serveur inconnu, SSH demande de confirmer son empreinte ; Ansible ne sait pas répondre, et la connexion échoue. Une clé absente donnerait <em>Permission denied</em>."},
        {"q": "<code>ansible web -m ping</code> répond <code>pong</code> pour chaque serveur. Qu'est-ce que cela prouve ?",
         "choices": ["Que les serveurs répondent au ping réseau (ICMP)",
                     "Que les droits sudo sont configurés sur les serveurs",
                     "Qu'Ansible peut s'y connecter en SSH et y exécuter Python",
                     "Que les services web tournent sur les serveurs"],
         "answer": 2,
         "explain": "Le module <code>ping</code> d'Ansible n'a rien à voir avec le ping réseau : il vérifie la connexion SSH et la présence d'un Python utilisable."},
        {"q": "Vous lancez <code>ansible</code> depuis <code>~/infra</code>, qui contient un <code>ansible.cfg</code> ; <code>~/.ansible.cfg</code> existe aussi. Quel fichier est lu ?",
         "choices": ["<code>~/infra/ansible.cfg</code> : celui du dossier courant passe en premier",
                     "<code>~/.ansible.cfg</code> : celui de l'utilisateur est prioritaire",
                     "Les deux, fusionnés ligne par ligne",
                     "<code>/etc/ansible/ansible.cfg</code>, toujours prioritaire"],
         "answer": 0,
         "explain": "Ansible lit un seul fichier : celui du dossier courant, à défaut <code>~/.ansible.cfg</code>, puis <code>/etc/ansible/ansible.cfg</code>. <code>ansible --version</code> indique lequel."},
        {"q": "Dans un inventaire, le serveur db9 n'est cité dans aucun groupe. Dans quels groupes se trouve-t-il ?",
         "choices": ["Dans aucun : Ansible l'ignore",
                     "Dans <code>all</code> seulement",
                     "Dans <code>ungrouped</code> seulement",
                     "Dans <code>all</code> et dans <code>ungrouped</code>"],
         "answer": 3,
         "explain": "Tout serveur est dans <code>all</code> ; ceux qui n'appartiennent à aucun autre groupe sont en plus dans <code>ungrouped</code>."},
        {"q": "Pourquoi <code>ssh-keyscan srv &gt;&gt; ~/.ssh/known_hosts</code> est-il risqué sur un réseau non maîtrisé ?",
         "choices": ["Il remplace la clé privée du poste de contrôle par une clé générée par le serveur",
                     "Il enregistre l'empreinte présentée sans la vérifier : celle d'un imposteur serait acceptée",
                     "Il désactive la vérification des empreintes pour tous les serveurs, y compris les connus",
                     "Il envoie la clé publique du poste à tous les serveurs SSH du réseau local"],
         "answer": 1,
         "explain": "<code>ssh-keyscan</code> récupère l'empreinte que présente le serveur, sans la comparer à une source sûre : si quelqu'un se fait passer pour lui, c'est son empreinte qui est enregistrée."},
    ],
    # ─── Jour 2 : modules, ad hoc, become, facts ───
    2: [
        {"q": "<code>ansible web -m command -a 'cat /etc/passwd | grep deploy'</code> échoue. Pourquoi ?",
         "choices": ["<code>command</code> n'utilise pas de shell : <code>cat</code> reçoit « | », « grep » et « deploy » comme noms de fichiers",
                     "<code>command</code> exige l'option <code>-b</code> pour lire <code>/etc/passwd</code>, réservé à root",
                     "Les tubes sont interdits dans une commande ad hoc, quel que soit le module utilisé",
                     "<code>grep</code> n'est pas installé par défaut sur les serveurs Debian et Ubuntu"],
         "answer": 0,
         "explain": "<code>command</code> lance le programme directement, sans <code>/bin/sh</code> : tubes et redirections ne sont pas interprétés. <code>shell</code> les comprend."},
        {"q": "<code>ansible web -b -m user -a 'name=livreur'</code> est lancée deux fois de suite. Quels résultats obtient-on ?",
         "choices": ["CHANGED puis CHANGED : chaque lancement recrée le compte",
                     "CHANGED puis FAILED : le compte existe déjà",
                     "CHANGED puis SUCCESS : le compte existe, il n'y a rien à faire",
                     "SUCCESS puis SUCCESS : <code>user</code> ne signale jamais de changement"],
         "answer": 2,
         "explain": "Le module compare l'état voulu à l'état réel : il crée le compte la première fois, puis constate qu'il existe. C'est l'idempotence."},
        {"q": "Pourquoi une tâche <code>shell</code> répond-elle <code>changed</code> à chaque exécution ?",
         "choices": ["Parce que <code>shell</code> passe toujours par sudo sur le serveur",
                     "Parce qu'Ansible ignore l'effet de la commande et suppose un changement",
                     "Parce que la commande a écrit quelque chose sur la sortie standard",
                     "Parce que <code>shell</code> recrée son dossier temporaire à chaque fois"],
         "answer": 1,
         "explain": "<code>command</code> et <code>shell</code> exécutent à l'aveugle : Ansible ne peut pas comparer d'état. D'où l'intérêt d'un module dédié, de <code>creates</code> ou de <code>changed_when</code>."},
        {"q": "Sur un serveur, <code>/etc/ansible/facts.d/reseau.fact</code> contient une section <code>[dns]</code> et la ligne <code>primaire=10.0.0.53</code>. Comment lire cette valeur ?",
         "choices": ["<code>ansible_facts.reseau.primaire</code>",
                     "<code>ansible_local.dns.primaire</code>",
                     "<code>ansible_reseau_dns_primaire</code>",
                     "<code>ansible_local.reseau.dns.primaire</code>"],
         "answer": 3,
         "explain": "Un fait local apparaît sous <code>ansible_local</code>, puis le nom du fichier (sans <code>.fact</code>), la section et la clé."},
        {"q": "Le compte distant <code>admin</code> n'est pas root. Que fait l'option <code>-b</code> d'une commande ad hoc ?",
         "choices": ["Elle exécute le module avec sudo sur le serveur",
                     "Elle se connecte directement en root par SSH",
                     "Elle lance la commande en arrière-plan",
                     "Elle rend la commande idempotente"],
         "answer": 0,
         "explain": "<code>-b</code> (<em>become</em>) fait passer l'exécution par sudo ; c'est l'équivalent de <code>become: true</code> dans un playbook."},
        {"q": "Pourquoi écrire <code>ansible.builtin.copy</code> plutôt que <code>copy</code> dans un playbook ?",
         "choices": ["Parce que le nom court est interdit depuis ansible-core 2.18",
                     "Parce que le nom complet rend la tâche plus rapide",
                     "Pour éviter toute ambiguïté si une collection installée fournit aussi un module <code>copy</code>",
                     "Parce que le nom court n'utilise pas <code>become</code>"],
         "answer": 2,
         "explain": "Le FQCN désigne sans ambiguïté le module de la collection <code>ansible.builtin</code>. Le nom court fonctionne encore, mais dépend des collections installées."},
        {"q": "<code>ansible memo1 -b -m file -a 'path=/tmp/vieux.log state=absent'</code> alors que ce fichier n'existe pas. Résultat ?",
         "choices": ["FAILED : le fichier à supprimer est introuvable",
                     "SUCCESS, sans changement : le fichier est déjà absent",
                     "CHANGED : Ansible crée le fichier puis le supprime",
                     "SKIPPED : la tâche n'a pas lieu d'être jouée"],
         "answer": 1,
         "explain": "<code>state: absent</code> décrit un état : si le fichier est déjà absent, il n'y a rien à faire, et ce n'est pas une erreur."},
        {"q": "Avec <code>-vvv</code>, que montrent les lignes <code>PUT</code> et <code>EXEC</code> ?",
         "choices": ["Les requêtes envoyées au dépôt de paquets",
                     "Les commandes tapées auparavant à la main sur le serveur",
                     "Les variables d'inventaire du serveur",
                     "L'envoi du module sur le serveur, puis son exécution"],
         "answer": 3,
         "explain": "Chaque tâche emballe son module, le copie sur le serveur (<code>PUT</code>), l'exécute (<code>EXEC</code>), récupère le JSON du résultat, puis supprime le fichier."},
    ],
    # ─── Jour 3 : YAML, premier playbook, récapitulatif, idempotence ───
    3: [
        {"q": "Une tâche <code>file</code> contient <code>mode: 644</code>, sans guillemets ni zéro initial. Quels droits obtient le fichier ?",
         "choices": ["rw-r--r-- : Ansible complète le zéro manquant",
                     "Aucun : la tâche échoue sur une erreur de syntaxe YAML",
                     "Des droits absurdes : 644 est lu comme un nombre décimal",
                     "rwxr--r-- : Ansible ajoute le droit d'exécution au propriétaire"],
         "answer": 2,
         "explain": "YAML lit 644 comme un nombre décimal, que le module interprète comme des droits (1204 en octal). On écrit <code>mode: \"0644\"</code>."},
        {"q": "<pre>web1 : ok=4  changed=0  unreachable=0  failed=0<br>web2 : ok=2  changed=1  unreachable=0  failed=1</pre>Que peut-on dire de ce récapitulatif ?",
         "choices": ["web1 était déjà conforme ; web2 s'est arrêté sur une tâche en échec",
                     "Les deux serveurs sont conformes, puisque <code>unreachable=0</code> partout",
                     "web2 a été entièrement configuré, avec une erreur sans conséquence",
                     "web1 a échoué : <code>changed=0</code> signifie qu'aucune tâche n'a fonctionné"],
         "answer": 0,
         "explain": "<code>ok</code> compte aussi les tâches qui n'avaient rien à faire. Un échec arrête le jeu pour ce serveur seulement : les autres continuent."},
        {"q": "Un play déclare <code>hosts: webs</code> alors que le groupe s'appelle <code>web</code>. Que se passe-t-il ?",
         "choices": ["Une erreur de syntaxe, détectée dès <code>--syntax-check</code>",
                     "Ansible vise tous les serveurs de l'inventaire à la place",
                     "Chaque tâche échoue, avec <code>unreachable=1</code> au récapitulatif",
                     "Un simple avertissement, puis un jeu « réussi » qui n'a rien fait"],
         "answer": 3,
         "explain": "Un motif qui ne correspond à rien ne provoque qu'un avertissement : le jeu se termine sans erreur ni récapitulatif utile. Il faut toujours le lire."},
        {"q": "Une tâche <code>shell: echo 'PROMO=1' &gt;&gt; /etc/boutique.conf</code> est jouée trois fois. Que contient le fichier ?",
         "choices": ["Une ligne PROMO=1 : Ansible détecte qu'elle existe déjà",
                     "Trois lignes PROMO=1 : la commande est rejouée à chaque passage",
                     "Aucune ligne : <code>shell</code> n'écrit pas dans <code>/etc</code>",
                     "Une ligne, puis la tâche échoue aux passages suivants"],
         "answer": 1,
         "explain": "<code>shell</code> exécute la commande à chaque fois, sans regarder l'état du fichier : une action, pas un état."},
        {"q": "Quelle tâche garantit que haproxy tourne <em>et</em> qu'il redémarrera avec le serveur ?",
         "choices": ["<code>ansible.builtin.command: systemctl start haproxy</code>",
                     "<code>ansible.builtin.apt</code> avec <code>state: started</code>",
                     "<code>ansible.builtin.service</code> avec <code>state: started</code> et <code>enabled: true</code>",
                     "<code>ansible.builtin.service</code> avec <code>state: restarted</code>"],
         "answer": 2,
         "explain": "<code>started</code> décrit un service en marche (sans le relancer s'il tourne déjà), <code>enabled</code> son lancement au démarrage. <code>restarted</code> relancerait à chaque passage."},
        {"q": "Un playbook passe <code>ansible-playbook site.yml --syntax-check</code>. Peut-il encore échouer ?",
         "choices": ["Oui : les paramètres des modules et les variables ne sont pas vérifiés",
                     "Non : <code>--syntax-check</code> garantit que le jeu réussira",
                     "Seulement en cas de coupure réseau pendant le jeu",
                     "Seulement sur une erreur d'indentation dans le YAML"],
         "answer": 0,
         "explain": "<code>--syntax-check</code> ne contrôle que le YAML et la structure du playbook. Une erreur d'indentation, justement, il la détecte."},
        {"q": "Comment vérifier qu'un playbook est idempotent ?",
         "choices": ["En le lançant avec <code>--syntax-check</code>",
                     "En vérifiant que <code>failed=0</code> au premier passage",
                     "En le lançant avec <code>-vvv</code>",
                     "En le rejouant : le second passage doit afficher <code>changed=0</code>"],
         "answer": 3,
         "explain": "Un playbook idempotent ne refait que ce qui manque : rejoué sur des serveurs conformes, il ne change plus rien."},
        {"q": "Dans une tâche <code>apt</code>, quel est le rôle de <code>cache_valid_time: 3600</code> à côté de <code>update_cache: true</code> ?",
         "choices": ["Désinstaller le paquet au bout d'une heure",
                     "Ne pas rafraîchir la liste des paquets si elle date de moins d'une heure",
                     "Limiter la durée de la tâche à une heure",
                     "Mettre à jour tous les paquets du serveur toutes les heures"],
         "answer": 1,
         "explain": "<code>update_cache</code> fait l'équivalent d'<code>apt update</code> ; <code>cache_valid_time</code> l'évite quand la liste est récente."},
    ],
    # ─── Jour 4 : variables, précédence, modèles, facts, variables magiques ───
    4: [
        {"q": "<code>saison</code> vaut <code>été</code> dans la section <code>[front:vars]</code> de l'inventaire, et <code>hiver</code> dans <code>group_vars/all.yml</code>. Quelle valeur s'applique à vitrine1, membre de front ?",
         "choices": ["été : le groupe front est plus précis que le groupe all",
                     "hiver : <code>group_vars/all</code> l'emporte sur l'inventaire",
                     "Aucune : Ansible signale un conflit entre les deux définitions",
                     "Cela dépend de l'ordre de chargement des fichiers"],
         "answer": 1,
         "explain": "C'est le piège de la précédence : les variables de groupe de l'inventaire sont plus faibles que <code>group_vars/all</code>, même pour un groupe plus précis."},
        {"q": "L'inventaire contient la ligne <code>vitrine1 saison=été</code> ; <code>group_vars/front.yml</code> contient <code>saison: hiver</code>. Quelle valeur s'applique à vitrine1 ?",
         "choices": ["hiver : un fichier <code>group_vars</code> l'emporte toujours sur l'inventaire",
                     "hiver : les variables de groupe s'appliquent après celles de l'hôte",
                     "Aucune : une variable ne peut être définie qu'une fois par serveur",
                     "été : une variable d'hôte l'emporte sur toute variable de groupe"],
         "answer": 3,
         "explain": "Les variables d'hôte, dans l'inventaire comme dans <code>host_vars</code>, sont plus fortes que toutes les variables de groupe."},
        {"q": "<code>host_vars/vitrine1.yml</code> fixe <code>port: 8080</code> ; le playbook est lancé avec <code>-e port=9000</code>. Quelle valeur s'applique à vitrine1 ?",
         "choices": ["9000 : <code>-e</code> l'emporte toujours",
                     "8080 : <code>host_vars</code> est le plus précis",
                     "8080 pour vitrine1, 9000 pour les autres serveurs",
                     "9000, seulement si <code>port</code> n'est défini nulle part ailleurs"],
         "answer": 0,
         "explain": "Les variables passées par <code>-e</code> sont les plus fortes de toutes."},
        {"q": "<code>[prod:children]</code> contient le groupe front. <code>group_vars/prod.yml</code> fixe <code>couleur: rouge</code>, <code>group_vars/front.yml</code> fixe <code>couleur: bleu</code>. Quelle valeur pour vitrine1, membre de front ?",
         "choices": ["rouge : prod englobe front",
                     "rouge : les fichiers sont lus par ordre alphabétique",
                     "bleu : un groupe enfant l'emporte sur son groupe parent",
                     "Aucune : Ansible signale un conflit entre groupes"],
         "answer": 2,
         "explain": "Entre groupes imbriqués, le plus précis (l'enfant) l'emporte sur son parent."},
        {"q": "Un modèle contient <code>{{ promo }}</code>, variable qui n'est pas définie pour web2. Que se passe-t-il ?",
         "choices": ["Le fichier est produit, avec une chaîne vide à la place",
                     "La tâche échoue sur web2 ; <code>{{ promo | default('') }}</code> éviterait l'erreur",
                     "Le fichier contient le texte <code>{{ promo }}</code> tel quel",
                     "Ansible demande la valeur à l'écran"],
         "answer": 1,
         "explain": "Une variable absente fait échouer le modèle. Le filtre <code>default</code> ou un test <code>{% if promo is defined %}</code> évitent l'erreur."},
        {"q": "Dans un modèle joué sur web1, <code>hostvars['db1']['ansible_facts']</code> est vide ou absent, alors que db1 est dans l'inventaire. Cause probable ?",
         "choices": ["db1 n'a pas de fichier <code>host_vars</code> à son nom",
                     "<code>hostvars</code> ne contient que des variables de groupe",
                     "Les facts d'un autre serveur ne sont jamais accessibles",
                     "db1 n'a pas été contacté pendant ce jeu"],
         "answer": 3,
         "explain": "Les variables d'inventaire de tous les serveurs sont toujours dans <code>hostvars</code> ; les facts d'un serveur n'y sont que s'il a été contacté pendant le jeu (ou gardé en cache)."},
        {"q": "Quelle est la différence entre les modules <code>template</code> et <code>copy</code> ?",
         "choices": ["<code>template</code> remplace d'abord les expressions Jinja2 par leur valeur, pour chaque serveur",
                     "<code>template</code> ne fonctionne que pour les fichiers HTML",
                     "<code>copy</code> remplace aussi les variables, mais seulement les plus simples",
                     "<code>template</code> copie le fichier sans vérifier s'il a changé"],
         "answer": 0,
         "explain": "<code>template</code> fonctionne comme <code>copy</code>, mais produit le fichier à partir d'un modèle Jinja2 : un contenu adapté à chaque serveur."},
        {"q": "Le groupe web contient web1 puis web2. Que produit <code>{{ groups['web'] | join(', ') }}</code> dans un modèle ?",
         "choices": ["<code>web</code>",
                     "<code>web1web2</code>",
                     "<code>web1, web2</code>",
                     "<code>['web1', 'web2']</code>"],
         "answer": 2,
         "explain": "<code>groups['web']</code> est la liste des serveurs du groupe, dans l'ordre de l'inventaire ; <code>join</code> les assemble avec le séparateur donné."},
    ],
    # ─── Jour 5 : handlers, uri, -e ───
    5: [
        {"q": "La tâche qui déploie une configuration notifie « Recharger nginx », mais elle répond <code>ok</code>. Que fait le handler ?",
         "choices": ["Il s'exécute quand même, à la fin de la section de tâches",
                     "Il s'exécute immédiatement après la tâche qui l'a notifié",
                     "Il ne s'exécute pas, puisque la tâche n'a rien changé",
                     "Il s'exécute seulement si nginx est arrêté à ce moment-là"],
         "answer": 2,
         "explain": "<code>notify</code> ne prévient le handler que si la tâche a changé quelque chose : pas de rechargement inutile quand la configuration est déjà à jour."},
        {"q": "Trois tâches <code>changed</code> notifient le même handler. Combien de fois s'exécute-t-il ?",
         "choices": ["Une seule fois, à la fin de la section de tâches",
                     "Trois fois, une après chaque tâche",
                     "Trois fois, toutes à la fin du play",
                     "Une fois, juste après la première notification"],
         "answer": 0,
         "explain": "Un handler notifié plusieurs fois ne s'exécute qu'une fois, à la fin de la section (<code>pre_tasks</code>, rôles et <code>tasks</code>, <code>post_tasks</code>)."},
        {"q": "Les handlers sont déclarés dans l'ordre A puis B ; les tâches notifient B, puis A. Dans quel ordre s'exécutent-ils ?",
         "choices": ["B puis A : l'ordre des notifications",
                     "Dans un ordre imprévisible",
                     "Seul le premier notifié s'exécute",
                     "A puis B : l'ordre de déclaration des handlers"],
         "answer": 3,
         "explain": "Les handlers s'exécutent dans l'ordre où ils sont déclarés dans <code>handlers:</code>, quel que soit l'ordre des notifications."},
        {"q": "La configuration de nginx change sur web1 (le handler est notifié), puis une tâche suivante échoue sur web1. Au passage suivant, toutes les tâches réussissent. Quel est l'état de web1 ?",
         "choices": ["Le handler s'exécute enfin, puisqu'il avait été notifié au passage précédent",
                     "nginx tourne toujours avec l'ancienne configuration : le handler n'est plus notifié",
                     "La tâche de configuration répond de nouveau <code>changed</code> et recharge nginx",
                     "Ansible détecte la notification perdue et la signale dans le récapitulatif"],
         "answer": 1,
         "explain": "C'est le handler perdu : le fichier est déjà à jour sur le disque, donc plus de <code>changed</code>, donc plus de notification, et le récapitulatif affiche <code>changed=0</code>."},
        {"q": "Quelle est la différence entre <code>state: reloaded</code> et <code>state: restarted</code> du module <code>service</code> ?",
         "choices": ["<code>reloaded</code> arrête puis relance ; <code>restarted</code> fait relire la configuration",
                     "<code>reloaded</code> agit au prochain démarrage du serveur ; <code>restarted</code> tout de suite",
                     "<code>reloaded</code> fait relire la configuration ; <code>restarted</code> arrête puis relance",
                     "Aucune pour nginx : les deux coupent les connexions en cours"],
         "answer": 2,
         "explain": "Recharger évite la coupure de service ; redémarrer arrête puis relance, ce qui coupe les connexions en cours."},
        {"q": "Deux handlers déclarent <code>listen: 'config web modifiée'</code>, et une tâche <code>changed</code> notifie « config web modifiée ». Que se passe-t-il ?",
         "choices": ["Les deux handlers s'exécutent",
                     "Seul le premier handler déclaré s'exécute",
                     "Aucun : <code>notify</code> doit citer le <code>name</code> d'un handler",
                     "Une erreur : deux handlers ne peuvent pas écouter le même événement"],
         "answer": 0,
         "explain": "<code>listen</code> permet à plusieurs handlers de réagir à une même notification : chacun s'exécute une fois."},
        {"q": "Une tâche <code>ansible.builtin.uri</code> interroge <code>http://localhost:8080/</code>, qui répond 404. Résultat ?",
         "choices": ["<code>ok</code> : <code>uri</code> vérifie seulement que le port est ouvert",
                     "<code>changed</code> : la page a été modifiée",
                     "<code>skipped</code> : <code>uri</code> ignore les erreurs HTTP",
                     "<code>failed</code> : <code>uri</code> attend par défaut le code 200"],
         "answer": 3,
         "explain": "<code>uri</code> échoue si le code de retour n'est pas celui attendu, 200 par défaut : un moyen simple de vérifier qu'un service répond vraiment."},
        {"q": "<code>group_vars/web.yml</code> fixe <code>http_port: 8080</code>. Le playbook est lancé avec <code>-e http_port=9090</code>. Quel port est utilisé pour ce lancement ?",
         "choices": ["8080 : <code>group_vars</code> l'emporte sur <code>-e</code>",
                     "9090 : <code>-e</code> l'emporte sur tout le reste",
                     "9090, mais seulement sur les serveurs sans <code>host_vars</code>",
                     "Aucun : la variable est définie deux fois"],
         "answer": 1,
         "explain": "<code>-e</code> surcharge toutes les autres définitions : pratique pour un essai, sans modifier les fichiers du projet."},
    ],
    # ─── Jour 6 : boucles, conditions, filtres, Jinja2 ───
    6: [
        {"q": "Une variable est définie par <code>actif: 'false'</code> (entre guillemets). Une tâche porte <code>when: actif</code>. Que se passe-t-il ?",
         "choices": ["La tâche s'exécute : une chaîne non vide est vraie",
                     "La tâche est sautée : le texte « false » vaut faux",
                     "Une erreur : <code>when</code> n'accepte que des booléens",
                     "La tâche est sautée sur tous les serveurs sauf le premier"],
         "answer": 0,
         "explain": "Entre guillemets, <code>'false'</code> est une chaîne, et une chaîne non vide est vraie (ansible-core 2.18 affiche seulement un avertissement de dépréciation). <code>when: actif | bool</code> la convertit correctement."},
        {"q": "Une tâche ne doit s'exécuter que si <code>promo_active</code> est vraie. Lancé avec <code>-e promo_active=false</code>, quelle condition la saute bien ?",
         "choices": ["<code>when: promo_active</code>",
                     "<code>when: promo_active != false</code>",
                     "<code>when: promo_active | bool</code>",
                     "<code>when: promo_active is defined</code>"],
         "answer": 2,
         "explain": "Une valeur passée par <code>-e clé=valeur</code> est toujours une chaîne : « false » est vrai, et différent du booléen <code>false</code>. Le filtre <code>bool</code> la convertit."},
        {"q": "Que compare la condition <code>when: saison == hiver</code> ?",
         "choices": ["La valeur de la variable <code>saison</code> au texte « hiver »",
                     "La valeur de <code>saison</code> à celle d'une variable <code>hiver</code>",
                     "Le nom de la variable (« saison ») au texte « hiver »",
                     "Rien : sans <code>{{ }}</code>, <code>when</code> provoque une erreur"],
         "answer": 1,
         "explain": "Dans une condition, un mot sans guillemets est un nom de variable. On écrit <code>saison == \"hiver\"</code> ; et jamais de <code>{{ }}</code> dans <code>when</code>."},
        {"q": "<code>comptes</code> vaut <code>[{nom: alice, admin: true}, {nom: bruno, admin: false}, {nom: chloé, admin: true}]</code>. Que donne <code>{{ comptes | selectattr('admin') | map(attribute='nom') | list }}</code> ?",
         "choices": ["<code>['bruno']</code>",
                     "<code>[true, false, true]</code>",
                     "<code>['alice', 'bruno', 'chloé']</code>",
                     "<code>['alice', 'chloé']</code>"],
         "answer": 3,
         "explain": "<code>selectattr('admin')</code> garde les fiches dont <code>admin</code> est vrai ; <code>map(attribute='nom')</code> en extrait les noms."},
        {"q": "Comment boucler sur le dictionnaire <code>limites: {cpu: 2, memoire: 512}</code> ?",
         "choices": ["<code>loop: \"{{ limites | dict2items }}\"</code>, puis <code>item.key</code> et <code>item.value</code>",
                     "<code>loop: \"{{ limites }}\"</code>, puis <code>item.key</code> et <code>item.value</code>",
                     "<code>loop: limites</code>, puis <code>item[0]</code> et <code>item[1]</code>",
                     "<code>loop: \"{{ limites | list }}\"</code>, puis <code>item.nom</code> et <code>item.valeur</code>"],
         "answer": 0,
         "explain": "<code>loop</code> n'accepte qu'une liste : <code>dict2items</code> transforme le dictionnaire en liste de paires <code>key</code> / <code>value</code>."},
        {"q": "Une tâche <code>user</code> boucle sur <code>comptes</code> avec <code>when: item.admin</code>. Que se passe-t-il pour bruno (<code>admin: false</code>) ?",
         "choices": ["La boucle entière est annulée",
                     "Le compte de bruno est créé, mais sans droits d'administration",
                     "Seule l'itération de bruno est sautée ; les autres sont traitées",
                     "La tâche échoue : <code>when</code> ne peut pas utiliser <code>item</code>"],
         "answer": 2,
         "explain": "Avec une boucle, <code>when</code> est évalué pour chaque élément : seuls les éléments pour lesquels la condition est fausse sont sautés."},
        {"q": "Dans un modèle Jinja2, que fait <code>{% set total = 3 %}</code> ?",
         "choices": ["Il écrit 3 dans le fichier produit",
                     "Il définit une variable, sans rien écrire lui-même",
                     "Il provoque une erreur : <code>set</code> est réservé aux playbooks",
                     "Il écrit « total = 3 » dans le fichier produit"],
         "answer": 1,
         "explain": "<code>{% … %}</code> est une instruction (condition, boucle, affectation) qui n'affiche rien ; seul <code>{{ … }}</code> affiche une valeur."},
        {"q": "<pre>when:<br>  - saison == 'hiver'<br>  - ansible_facts['memtotal_mb'] &lt; 1024</pre>À quoi équivaut cette liste de conditions ?",
         "choices": ["<code>saison == 'hiver' or ansible_facts['memtotal_mb'] &lt; 1024</code>",
                     "La première condition seule : la seconde est ignorée",
                     "Une erreur : <code>when</code> n'accepte qu'une expression",
                     "<code>saison == 'hiver' and ansible_facts['memtotal_mb'] &lt; 1024</code>"],
         "answer": 3,
         "explain": "Une liste de conditions sous <code>when</code> équivaut à un <code>and</code> : toutes doivent être vraies."},
    ],
    # ─── Jour 7 : --check, --diff, rôles ───
    7: [
        {"q": "Un fichier décrit par le playbook a été modifié à la main sur web1. Que fait <code>ansible-playbook site.yml --check</code> ?",
         "choices": ["Il corrige le fichier, et la tâche affiche <code>changed</code>",
                     "La tâche affiche <code>changed</code>, mais rien n'est modifié sur le serveur",
                     "La tâche affiche <code>ok</code> : <code>--check</code> ne compare rien",
                     "Le jeu échoue pour signaler la dérive"],
         "answer": 1,
         "explain": "En mode vérification, Ansible dit ce qui changerait sans rien changer : une tâche <code>changed</code> signale une dérive."},
        {"q": "Un paquet a été installé à la main sur web1, et le code n'en parle nulle part. Que montre <code>site.yml --check --diff</code> ?",
         "choices": ["Une tâche <code>changed</code> pour ce paquet, signe de dérive",
                     "Une proposition de désinstallation du paquet, en <code>--diff</code>",
                     "Une ligne <code>failed</code> au récapitulatif pour web1",
                     "Rien : ce que le code ne décrit pas lui est invisible"],
         "answer": 3,
         "explain": "Ansible ne compare que ce que le code décrit. Rejouer le playbook ne retirera pas non plus ce paquet, faute de tâche qui le décrive absent."},
        {"q": "Un play contient à la fois <code>roles:</code> et <code>tasks:</code>. Dans quel ordre s'exécutent-ils ?",
         "choices": ["Les rôles d'abord, puis les tâches",
                     "Les tâches d'abord, puis les rôles",
                     "Dans l'ordre où les sections sont écrites dans le fichier",
                     "En parallèle, sur chaque serveur"],
         "answer": 0,
         "explain": "Les rôles listés dans <code>roles:</code> passent avant les <code>tasks:</code> du play, quel que soit l'ordre d'écriture."},
        {"q": "En mode <code>--check</code>, que devient une tâche <code>command</code> ?",
         "choices": ["Elle est exécutée normalement",
                     "Elle est exécutée, puis annulée",
                     "Elle n'est pas exécutée : elle est sautée",
                     "Elle fait échouer le jeu"],
         "answer": 2,
         "explain": "Ansible ne peut pas simuler une commande quelconque : en mode vérification, il ne l'exécute pas."},
        {"q": "Où ranger, dans un rôle, le modèle <code>nginx.conf.j2</code> utilisé par une tâche <code>template</code> ?",
         "choices": ["Dans <code>files/</code> : les fichiers copiés tels quels",
                     "Dans <code>templates/</code> : <code>src: nginx.conf.j2</code> suffit alors",
                     "Dans <code>vars/</code>, avec les variables du rôle",
                     "Dans <code>meta/</code>, avec la description du rôle"],
         "answer": 1,
         "explain": "Dans un rôle, <code>template</code> cherche ses modèles dans <code>templates/</code>, et <code>copy</code> ses fichiers dans <code>files/</code>."},
        {"q": "Que contient <code>roles/web/tasks/main.yml</code> ?",
         "choices": ["Un play complet, avec <code>hosts</code> et <code>become</code>",
                     "La liste des serveurs auxquels s'applique le rôle",
                     "Les handlers du rôle",
                     "Une simple liste de tâches, sans <code>hosts</code> ni play"],
         "answer": 3,
         "explain": "Un rôle est générique : c'est le play (dans <code>site.yml</code>) qui choisit les serveurs et <code>become</code>. Les handlers vont dans <code>handlers/main.yml</code>."},
        {"q": "Quelle est la différence entre <code>import_role</code> et <code>include_role</code> ?",
         "choices": ["<code>import_role</code> est traité à la lecture du playbook, <code>include_role</code> à l'exécution",
                     "<code>include_role</code> est traité à la lecture du playbook, <code>import_role</code> à l'exécution",
                     "<code>import_role</code> copie le rôle dans le projet, <code>include_role</code> le télécharge",
                     "Aucune : ce sont deux noms du même module, gardés par compatibilité"],
         "answer": 0,
         "explain": "Les deux appellent un rôle au milieu des tâches : <code>import_*</code> est résolu à la lecture du playbook, <code>include_*</code> au moment où la tâche s'exécute."},
        {"q": "En <code>--check</code>, « Installer nginx » répond <code>changed</code>, puis « Démarrer nginx » échoue : service inconnu. Explication ?",
         "choices": ["nginx est installé, mais son paquet est cassé sur le serveur",
                     "<code>--check</code> a installé nginx, puis l'a désinstallé",
                     "Le paquet n'a pas vraiment été installé, puisque rien n'est modifié",
                     "Le module <code>service</code> échoue toujours en <code>--check</code>"],
         "answer": 2,
         "explain": "En mode vérification rien n'est modifié : le paquet n'existe toujours pas, et une tâche qui en dépend peut échouer sans que le playbook soit faux."},
    ],
    # ─── Jour 8 : Vault, lineinfile, projet complet ───
    8: [
        {"q": "Pendant un jeu, que fait Ansible d'un fichier de variables chiffré par <code>ansible-vault</code> ?",
         "choices": ["Il le déchiffre en mémoire, au moment du déploiement",
                     "Il le déchiffre sur le disque, puis le rechiffre à la fin",
                     "Il l'envoie chiffré aux serveurs, qui le déchiffrent",
                     "Il l'ignore, faute d'option particulière"],
         "answer": 0,
         "explain": "Le fichier reste chiffré (AES-256) sur le disque et dans le dépôt : Ansible ne le déchiffre qu'en mémoire, le temps du jeu."},
        {"q": "Aucun moyen de connaître la clé du coffre n'est configuré (ni <code>vault_password_file</code>, ni option). Que fait un jeu qui charge <code>group_vars/bdd/vault.yml</code>, chiffré ?",
         "choices": ["Il s'exécute en ignorant les variables chiffrées",
                     "Il demande automatiquement la clé à l'écran",
                     "Il échoue : Ansible ne peut pas déchiffrer le fichier",
                     "Il utilise les valeurs chiffrées telles quelles"],
         "answer": 2,
         "explain": "Sans la clé, Ansible ne peut pas lire le fichier chiffré et s'arrête en erreur. <code>vault_password_file</code> dans <code>ansible.cfg</code> lui indique où la trouver."},
        {"q": "Pourquoi exposer <code>memcache_mdp: \"{{ vault_memcache_mdp }}\"</code> dans un <code>vars.yml</code> en clair, à côté du coffre ?",
         "choices": ["Pour que le mot de passe soit lisible par toute l'équipe",
                     "Pour voir quelles variables existent sans ouvrir le coffre",
                     "Parce qu'une variable chiffrée ne peut pas être utilisée dans un modèle",
                     "Pour que le mot de passe soit envoyé en clair aux serveurs"],
         "answer": 1,
         "explain": "Seule la valeur reste dans le coffre : le fichier en clair documente les variables disponibles, sans révéler leur contenu."},
        {"q": "À quoi sert <code>no_log: true</code> sur une tâche ?",
         "choices": ["À chiffrer la valeur dans le fichier de variables du coffre",
                     "À empêcher la tâche de modifier le serveur (lecture seule)",
                     "À désactiver le journal sudo sur le serveur pendant la tâche",
                     "À masquer les valeurs de la tâche dans la sortie d'Ansible"],
         "answer": 3,
         "explain": "Un secret déchiffré apparaîtrait sinon en clair dans la sortie (notamment avec <code>-v</code>) : <code>no_log</code> le masque."},
        {"q": "Le fichier contient la ligne <code>-l 127.0.0.1</code>. Une tâche <code>lineinfile</code> avec <code>regexp: '^-l '</code> et <code>line: -l 0.0.0.0</code> est jouée deux fois. Résultat ?",
         "choices": ["La ligne est remplacée au premier passage (<code>changed</code>), puis <code>ok</code>",
                     "Une ligne <code>-l 0.0.0.0</code> est ajoutée à chaque passage",
                     "Les deux lignes coexistent après le premier passage",
                     "La tâche échoue : une ligne correspondante existe déjà"],
         "answer": 0,
         "explain": "La dernière ligne qui correspond à <code>regexp</code> est remplacée par <code>line</code> ; au passage suivant, elle est déjà conforme : c'est idempotent."},
        {"q": "Que fait <code>ansible-vault rekey group_vars/bdd/vault.yml</code> ?",
         "choices": ["Il déchiffre définitivement le fichier",
                     "Il génère une nouvelle clé SSH pour les serveurs du groupe",
                     "Il change la clé du coffre de ce fichier",
                     "Il chiffre une seule valeur du fichier"],
         "answer": 2,
         "explain": "<code>rekey</code> rechiffre le fichier avec une nouvelle clé : utile quand l'ancienne a pu être divulguée."},
        {"q": "À quoi sert <code>ansible-vault encrypt_string</code> ?",
         "choices": ["À chiffrer un fichier de variables entier, en place",
                     "À chiffrer une seule valeur, à coller dans un fichier en clair",
                     "À vérifier la robustesse du mot de passe du coffre",
                     "À déchiffrer une valeur du coffre pour l'afficher à l'écran"],
         "answer": 1,
         "explain": "C'est l'alternative au fichier chiffré : seule la valeur est chiffrée, le reste du fichier reste lisible."},
        {"q": "Un serveur est réinstallé à neuf, puis <code>site.yml</code> est rejoué. Qu'est-ce qui est perdu ?",
         "choices": ["Rien : Ansible sauvegarde l'état de chaque serveur",
                     "Ce qui est décrit dans les rôles",
                     "Les variables de <code>host_vars</code>",
                     "Ce qui avait été fait à la main ou en commande ad hoc"],
         "answer": 3,
         "explain": "Le playbook reconstruit tout ce qu'il décrit ; ce qui n'existe que sur l'ancien serveur disparaît avec lui."},
    ],
    # ─── Jour 9 : register, changed_when, failed_when, delegate_to, block/rescue/always ───
    9: [
        {"q": "La tâche <code>command: java -version</code> enregistre son résultat avec <code>register: v</code>. Où trouver la version ?",
         "choices": ["Dans <code>v.stdout</code>, la sortie standard",
                     "Dans <code>v.stderr</code>, la sortie d'erreur",
                     "Dans <code>v.rc</code>, le code de retour",
                     "Dans <code>v.version</code>, rempli par le module"],
         "answer": 1,
         "explain": "Certains programmes écrivent leur version sur la sortie d'erreur. <code>-v</code> affiche le résultat complet et montre où se trouve l'information."},
        {"q": "Pourquoi ajouter <code>changed_when: false</code> à une tâche <code>command: uname -r</code> ?",
         "choices": ["Pour que la tâche ne puisse pas échouer, même si la commande échoue",
                     "Pour que la commande ne soit exécutée qu'une fois par serveur",
                     "Pour masquer la sortie de la commande dans le terminal",
                     "Pour que cette simple lecture ne soit pas comptée <code>changed</code>"],
         "answer": 3,
         "explain": "<code>command</code> suppose toujours un changement ; <code>changed_when: false</code> rend le récapitulatif honnête pour une simple lecture."},
        {"q": "Une tâche d'un <code>block</code> échoue ; la section <code>rescue</code> affiche un message et se termine sans erreur. Que montre le récapitulatif ?",
         "choices": ["<code>rescued=1</code> et <code>failed=0</code> : l'échec est rattrapé",
                     "<code>failed=1</code> et <code>rescued=0</code> : un échec reste un échec",
                     "<code>failed=1</code> : <code>rescue</code> ne sert qu'à afficher un message",
                     "<code>skipped=1</code> : la tâche en échec est comptée comme sautée"],
         "answer": 0,
         "explain": "Un <code>rescue</code> qui réussit rattrape l'échec. Pour que le jeu reste en échec, on termine le <code>rescue</code> par <code>ansible.builtin.fail</code>."},
        {"q": "Quand s'exécute la section <code>always</code> ?",
         "choices": ["Seulement si toutes les tâches du <code>block</code> réussissent",
                     "Seulement si le <code>rescue</code> a été joué",
                     "Dans tous les cas, après le <code>block</code> et l'éventuel <code>rescue</code>",
                     "Avant le <code>block</code>, pour préparer le terrain"],
         "answer": 2,
         "explain": "<code>always</code> s'exécute que le bloc réussisse ou échoue : idéal pour journaliser une tentative."},
        {"q": "Dans un play qui vise 3 serveurs, une tâche <code>copy</code> vers <code>{{ playbook_dir }}/rapport.txt</code> porte <code>delegate_to: localhost</code>, mais pas <code>run_once</code>. Que se passe-t-il ?",
         "choices": ["Le fichier est écrit sur chacun des 3 serveurs",
                     "La tâche s'exécute 3 fois sur le poste de contrôle, une par serveur",
                     "La tâche s'exécute une fois, car localhost est unique",
                     "La tâche échoue : <code>delegate_to</code> exige <code>run_once</code>"],
         "answer": 1,
         "explain": "<code>delegate_to</code> change l'endroit où la tâche s'exécute, pas le nombre d'exécutions : il en faut une par serveur visé, sauf avec <code>run_once: true</code>."},
        {"q": "Pourquoi <code>ignore_errors: true</code> est-il presque toujours une mauvaise idée ?",
         "choices": ["Parce qu'il empêche la tâche de s'exécuter sur les serveurs en erreur",
                     "Parce qu'il désactive tous les handlers du play",
                     "Parce qu'il transforme l'échec en <code>changed</code> au récapitulatif",
                     "Parce que le jeu continue : les vrais problèmes passent inaperçus"],
         "answer": 3,
         "explain": "Le jeu poursuit comme si de rien n'était. Mieux vaut dire précisément ce qui est un échec avec <code>failed_when</code>."},
        {"q": "Sans <code>failed_when</code>, que devient une tâche <code>command: grep -q promo /etc/boutique.conf</code> qui ne trouve rien (code de retour 1) ?",
         "choices": ["Elle échoue, à cause du code de retour non nul",
                     "Elle réussit, sans changement, puisque rien n'a été modifié",
                     "Elle réussit, car <code>-q</code> rend <code>grep</code> silencieux",
                     "Elle est sautée, faute de résultat"],
         "answer": 0,
         "explain": "Par défaut, <code>command</code> considère tout code de retour non nul comme un échec. <code>failed_when</code> permet de dire quels codes sont normaux."},
        {"q": "Sur vitrine1, une tâche a enregistré son résultat avec <code>register: noyau</code>. Comment le lire depuis une tâche jouée pour un autre serveur ?",
         "choices": ["<code>{{ noyau['vitrine1'] }}</code>",
                     "<code>{{ groups['vitrine1'].noyau }}</code>",
                     "<code>{{ hostvars['vitrine1']['noyau'] }}</code>",
                     "<code>{{ vitrine1.noyau }}</code>"],
         "answer": 2,
         "explain": "Un résultat enregistré est une variable du serveur qui l'a produit : les autres serveurs la lisent via <code>hostvars</code>."},
    ],
    # ─── Jour 10 : diagnostic, serial, tags, reprise ───
    10: [
        {"q": "Un play porte <code>serial: 2</code>, sans <code>max_fail_percentage</code>, et vise 4 serveurs. Un des deux serveurs du premier lot échoue. Que se passe-t-il ?",
         "choices": ["Le jeu s'arrête : un seul échec suffit",
                     "Le jeu continue : les deux serveurs du lot suivant sont configurés",
                     "Le premier lot est rejoué depuis le début",
                     "Les serveurs du premier lot reviennent à l'état précédent"],
         "answer": 1,
         "explain": "Le jeu ne s'arrête que si tous les serveurs d'un lot échouent. Pour arrêter dès un échec, on ajoute <code>max_fail_percentage</code> (ou <code>any_errors_fatal</code>)."},
        {"q": "Avec <code>--tags contenu</code>, que devient une tâche non étiquetée qui crée le dossier dont a besoin la tâche étiquetée <code>contenu</code> ?",
         "choices": ["Elle est jouée, car Ansible détecte la dépendance entre les deux",
                     "Elle est jouée en premier, comme toute tâche sans étiquette",
                     "Elle fait échouer le jeu dès le lancement avec <code>--tags</code>",
                     "Elle n'est pas jouée : la tâche <code>contenu</code> risque d'échouer"],
         "answer": 3,
         "explain": "Avec <code>--tags</code>, seules les tâches portant l'une des étiquettes demandées sont jouées : un jeu partiel peut manquer de ce que préparent les autres."},
        {"q": "Une tâche porte l'étiquette spéciale <code>always</code>. Le playbook est lancé avec <code>--tags page</code>. Que devient-elle ?",
         "choices": ["Elle est jouée quand même",
                     "Elle n'est pas jouée",
                     "Elle n'est jouée qu'avec <code>--tags always</code>",
                     "Elle est jouée deux fois"],
         "answer": 0,
         "explain": "Une tâche étiquetée <code>always</code> est jouée même quand on sélectionne d'autres étiquettes (sauf si on l'exclut explicitement avec <code>--skip-tags</code>)."},
        {"q": "Un rôle est appelé dans <code>roles:</code> avec <code>tags: [web]</code>. À quoi s'applique cette étiquette ?",
         "choices": ["À la première tâche du rôle seulement",
                     "Aux handlers du rôle seulement",
                     "À toutes les tâches du rôle",
                     "À rien : un rôle ne peut pas être étiqueté"],
         "answer": 2,
         "explain": "Une étiquette posée sur un rôle ou sur un bloc est héritée par toutes ses tâches."},
        {"q": "Sans <code>serial</code>, comment un play s'exécute-t-il sur 20 serveurs ?",
         "choices": ["Un serveur à la fois, le play entier pour chacun avant de passer au suivant",
                     "Chaque tâche sur tous les serveurs (5 à la fois) avant de passer à la suivante",
                     "Toutes les tâches sur les 20 serveurs en même temps, sans ordre",
                     "Par lots de 5 serveurs, le play entier pour chaque lot (réglage <code>forks</code>)"],
         "answer": 1,
         "explain": "Par défaut, une tâche est jouée sur tout le parc avant la suivante : une erreur du playbook touche donc tous les serveurs. <code>serial</code> découpe en lots."},
        {"q": "Après avoir corrigé un incident et rejoué <code>site.yml</code>, pourquoi le rejouer une seconde fois ?",
         "choices": ["Pour vider le cache des facts, périmé après l'incident",
                     "Parce qu'Ansible ne corrige qu'un serveur par passage",
                     "Pour relancer automatiquement les handlers perdus",
                     "Parce qu'un second passage à <code>changed=0</code> prouve la conformité"],
         "answer": 3,
         "explain": "Le premier passage corrige ; le second, s'il ne change plus rien, montre que les serveurs sont conformes au code."},
        {"q": "Un jeu a échoué au milieu du playbook sur web3 ; la cause est corrigée. Comment reprendre à la tâche « Page d'accueil », sur web3 seulement ?",
         "choices": ["<code>--limit web3 --start-at-task \"Page d'accueil\"</code>",
                     "<code>--tags web3</code>",
                     "<code>--step web3</code>",
                     "<code>--limit web3 --skip-tags \"Page d'accueil\"</code>"],
         "answer": 0,
         "explain": "<code>--limit</code> restreint les serveurs, <code>--start-at-task</code> reprend à la tâche nommée. Les tags sont des étiquettes de tâches, pas des noms de serveurs."},
        {"q": "Que devient une tâche étiquetée <code>never</code> ?",
         "choices": ["Elle est toujours jouée, mais en dernier",
                     "Elle ne peut jamais être jouée, quelle que soit l'option",
                     "Elle n'est jouée que si <code>--tags</code> la demande",
                     "Elle n'est jouée qu'en mode <code>--check</code>"],
         "answer": 2,
         "explain": "<code>never</code> exclut la tâche d'un jeu normal ; on la joue en demandant l'une de ses autres étiquettes (ou <code>never</code>) avec <code>--tags</code>."},
    ],
}
