"""Exercise definitions and validation commands."""

STEPS = {
    1: {
        "title": "Premiers pas : navigation dans le système",
        "description": "Découvrez le terminal Linux, naviguez dans l'arborescence et listez les fichiers.",
        "lesson": """<h3>Bienvenue en console !</h3><p>Vous allez apprendre à utiliser l'interface en ligne de commande (CLI) de Linux. Quand vous ouvrez un terminal, vous voyez :</p><pre>user@machine:~$</pre><p>Cette ligne indique <strong>qui vous êtes</strong>, <strong>sur quelle machine</strong> et <strong>où vous êtes</strong>.</p><div class="tip">Le symbole <code>~</code> est un raccourci vers votre dossier personnel <code>/home/user</code>.</div><h3>Commandes essentielles</h3><ul><li><code>whoami</code> — votre nom d'utilisateur</li><li><code>pwd</code> — dossier courant (<em>Print Working Directory</em>)</li><li><code>cd &lt;dossier&gt;</code> — se déplacer (<em>Change Directory</em>)</li><li><code>ls</code> — lister le contenu (<em>List</em>)</li><li><code>mkdir &lt;dossier&gt;</code> — créer un dossier (<em>Make Directory</em>)</li><li><code>touch &lt;fichier&gt;</code> — créer un fichier vide</li></ul><h3>L'arborescence Linux</h3><p>Tout part de la racine <code>/</code>. Avec <code>ls /</code> on découvre :</p><ul><li><code>/home</code> — dossiers personnels</li><li><code>/etc</code> — fichiers de configuration</li><li><code>/root</code> — dossier du super-utilisateur</li><li><code>/usr</code> — programmes installés</li><li><code>/dev</code> — périphériques</li></ul>""",
        "exercises": [
            {"id": "1.1", "points": 3, "title": "Votre espace de travail",
             "desc": "Créez votre dossier de travail <code>/home/etudiant</code>.<br><span class='hint'>Quelle commande permet de créer un dossier ?</span>",
             "check": "test -d /home/etudiant"},
            {"id": "1.2", "points": 3, "title": "Explorer le système",
             "desc": "Créez un dossier <code>/home/etudiant/exploration</code> pour y stocker vos découvertes.",
             "check": "test -d /home/etudiant/exploration"},
            {"id": "1.3", "points": 3, "title": "Votre premier fichier",
             "desc": "Créez un fichier vide <code>/home/etudiant/exploration/decouverte.txt</code>.<br><span class='hint'>La commande <code>touch</code> crée un fichier vide.</span>",
             "check": "test -f /home/etudiant/exploration/decouverte.txt"},
            {"id": "1.4", "points": 3, "title": "Organiser",
             "desc": "Créez les dossiers <code>/home/etudiant/documents</code> et <code>/home/etudiant/projets</code>.",
             "check": "test -d /home/etudiant/documents && test -d /home/etudiant/projets"},
        ],
    },
    2: {
        "title": "Le manuel et les chemins",
        "description": "Apprenez à lire la documentation et à utiliser les chemins absolus et relatifs.",
        "lesson": """<h3>RTFM : Read The Manual !</h3><p>Le <strong>Manuel</strong> contient la documentation de toutes les commandes :</p><pre>man &lt;commande&gt;</pre><div class="tip"><strong>Conventions :</strong> <code>[PARAM]</code> = optionnel, <code>...</code> = plusieurs possibles</div><h3>Les options</h3><p>Les options modifient le comportement. Essayez :</p><ul><li><code>ls -l</code> — format détaillé</li><li><code>ls -a</code> — fichiers cachés</li><li><code>ls -la</code> — les deux</li></ul><h3>Chemins absolus vs relatifs</h3><table class="lesson-table"><tr><th>Absolu</th><th>Relatif</th></tr><tr><td>Commence par <code>/</code></td><td>Part de votre position</td></tr><tr><td><code>/home/user/Documents</code></td><td><code>Documents</code></td></tr><tr><td>Toujours vrai</td><td>Dépend du contexte</td></tr></table><div class="tip"><code>.</code> = dossier courant | <code>..</code> = dossier parent</div>""",
        "exercises": [
            {"id": "2.1", "points": 3, "title": "Chemin absolu",
             "desc": "En utilisant un <strong>chemin absolu</strong>, créez le dossier <code>/home/etudiant/projets/projet-alpha</code>.<br><span class='hint'>Un chemin absolu commence toujours par <code>/</code>. Pensez à l'option <code>-p</code>.</span>",
             "check": "test -d /home/etudiant/projets/projet-alpha"},
            {"id": "2.2", "points": 3, "title": "Chemin relatif",
             "desc": "Créez un dossier <code>projet-beta</code> dans <code>/home/etudiant/projets</code> en utilisant un chemin relatif.<br><span class='hint'>Placez-vous d'abord dans le bon dossier avec <code>cd</code>.</span>",
             "check": "test -d /home/etudiant/projets/projet-beta"},
            {"id": "2.3", "points": 3, "title": "Remonter avec ..",
             "desc": "Créez un fichier <code>notes.txt</code> dans <code>projet-alpha</code> en utilisant <code>..</code> depuis <code>projet-beta</code>.<br><span class='hint'><code>..</code> remonte d'un niveau dans l'arborescence.</span>",
             "check": "test -f /home/etudiant/projets/projet-alpha/notes.txt"},
            {"id": "2.4", "points": 3, "title": "Options de ls",
             "desc": "Créez un fichier <code>/home/etudiant/projets/listing.txt</code> pour prouver que vous avez exploré.<br><span class='hint'>Consultez le manuel pour découvrir les options de <code>ls</code>.</span>",
             "check": "test -f /home/etudiant/projets/listing.txt"},
        ],
    },
    3: {
        "title": "Créer, écrire, gérer fichiers et dossiers",
        "description": "Manipulez fichiers et dossiers : écriture, copie, déplacement, suppression.",
        "lesson": """<h3>Écriture dans un fichier</h3><table class="lesson-table"><tr><th>Symbole</th><th>Effet</th><th>Exemple</th></tr><tr><td><code>&gt;</code></td><td><strong>Remplace</strong> le contenu</td><td><code>echo "Bonjour" > f.txt</code></td></tr><tr><td><code>&gt;&gt;</code></td><td><strong>Ajoute</strong> à la fin</td><td><code>echo "Suite" >> f.txt</code></td></tr></table><p><code>cat fichier</code> affiche le contenu d'un fichier.</p><h3>Copier, déplacer, supprimer</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th><th>Note</th></tr><tr><td><code>cp src dest</code></td><td>Copier</td><td><code>-R</code> pour les dossiers</td></tr><tr><td><code>mv src dest</code></td><td>Déplacer / Renommer</td><td></td></tr><tr><td><code>rm fichier</code></td><td>Supprimer fichier</td><td></td></tr><tr><td><code>rm -R dossier</code></td><td>Supprimer dossier</td><td>Irréversible !</td></tr></table>""",
        "exercises": [
            {"id": "3.1", "points": 3, "title": "Arborescence",
             "desc": "Créez <code>/home/etudiant/documents/cours/</code> et <code>/home/etudiant/documents/exercices/</code>.<br><span class='hint'>Comment créer plusieurs niveaux de dossiers d'un coup ?</span>",
             "check": "test -d /home/etudiant/documents/cours && test -d /home/etudiant/documents/exercices"},
            {"id": "3.2", "points": 3, "title": "Écrire dans un fichier",
             "desc": "Écrivez <code>Bienvenue dans le cours Linux</code> dans <code>/home/etudiant/documents/cours/notes.txt</code>.<br><span class='hint'>Utilisez la redirection pour envoyer du texte dans un fichier.</span>",
             "check": "grep -qi 'bienvenue' /home/etudiant/documents/cours/notes.txt 2>/dev/null"},
            {"id": "3.3", "points": 3, "title": "Copier un fichier",
             "desc": "Copiez <code>notes.txt</code> dans <code>/home/etudiant/documents/exercices/</code>.<br><span class='hint'>Quelle commande copie un fichier d'un endroit à un autre ?</span>",
             "check": "test -f /home/etudiant/documents/exercices/notes.txt || test -f /home/etudiant/documents/exercices/notes-copie.txt"},
            {"id": "3.4", "points": 3, "title": "Renommer",
             "desc": "Renommez la copie en <code>notes-copie.txt</code> (dans <code>documents/exercices/</code>).<br><span class='hint'>Il n'y a pas de commande rename... mais déplacer permet aussi de renommer.</span>",
             "check": "test -f /home/etudiant/documents/exercices/notes-copie.txt"},
            {"id": "3.5", "points": 3, "title": "Ajouter du contenu",
             "desc": "Ajoutez une 2ème ligne <code>Ceci est un ajout</code> à <code>notes.txt</code> <strong>sans écraser</strong> la 1ère.<br><span class='hint'>Quelle différence entre <code>&gt;</code> et <code>&gt;&gt;</code> ?</span>",
             "check": "test $(wc -l < /home/etudiant/documents/cours/notes.txt 2>/dev/null) -ge 2 && grep -qi 'ajout' /home/etudiant/documents/cours/notes.txt"},
        ],
    },
    4: {
        "title": "Utilisateurs, groupes et permissions",
        "description": "Gérez les utilisateurs, les groupes et les droits d'accès aux fichiers.",
        "lesson": """<h3>Les utilisateurs</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th></tr><tr><td><code>adduser &lt;user&gt;</code></td><td>Créer un utilisateur</td></tr><tr><td><code>deluser &lt;user&gt;</code></td><td>Supprimer</td></tr></table><p>Liste : <code>/etc/passwd</code></p><h3>Les groupes</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th></tr><tr><td><code>addgroup &lt;grp&gt;</code></td><td>Créer un groupe</td></tr><tr><td><code>adduser &lt;user&gt; &lt;grp&gt;</code></td><td>Ajouter au groupe</td></tr></table><h3>Permissions</h3><p>3 triades : <strong>user</strong> | <strong>group</strong> | <strong>others</strong></p><p><code>r</code>=4, <code>w</code>=2, <code>x</code>=1 → <code>rwx</code>=7, <code>r-x</code>=5, <code>---</code>=0</p><ul><li><code>chmod 755 fichier</code></li><li><code>chown user fichier</code> / <code>chgrp group fichier</code></li></ul>""",
        "exercises": [
            {"id": "4.1", "points": 3, "title": "Créer des utilisateurs",
             "desc": "Créez deux utilisateurs : <code>alice</code> et <code>bob</code>.<br><span class='hint'>Relisez la section utilisateurs du cours.</span>",
             "check": "id alice >/dev/null 2>&1 && id bob >/dev/null 2>&1"},
            {"id": "4.2", "points": 3, "title": "Créer un groupe",
             "desc": "Créez un groupe <code>equipe</code> et ajoutez-y <code>alice</code> et <code>bob</code>.<br><span class='hint'>Deux étapes : créer le groupe, puis y ajouter chaque utilisateur.</span>",
             "check": "getent group equipe >/dev/null 2>&1 && id alice 2>/dev/null | grep -q equipe && id bob 2>/dev/null | grep -q equipe"},
            {"id": "4.3", "points": 4, "title": "Dossier de groupe",
             "desc": "Créez <code>/home/partage</code> et attribuez-le au groupe <code>equipe</code>.<br><span class='hint'>Créez le dossier, puis changez son groupe propriétaire.</span>",
             "check": "test -d /home/partage && test $(stat -c '%G' /home/partage) = equipe"},
            {"id": "4.4", "points": 4, "title": "Protéger le dossier",
             "desc": "Permissions de <code>/home/partage</code> : propriétaire et groupe = tout, autres = rien.<br><span class='hint'>En octal : rwx=7, ---=0. Quelle combinaison ?</span>",
             "check": "test $(stat -c '%a' /home/partage) = 770"},
            {"id": "4.5", "points": 3, "title": "Fichier confidentiel",
             "desc": "Créez <code>/home/partage/secret.txt</code> : propriétaire rw, groupe r, autres rien.<br><span class='hint'>Calculez : rw-=?, r--=?, ---=?</span>",
             "check": "test -f /home/partage/secret.txt && test $(stat -c '%a' /home/partage/secret.txt) = 640"},
        ],
    },
    5: {
        "title": "Super-utilisateur et processus",
        "description": "Découvrez sudo, su et la gestion des processus.",
        "lesson": """<h3>root — le super-utilisateur</h3><p>Tout-puissant. Le <code>$</code> devient <code>#</code>.</p><h3>sudo</h3><p>Exécuter en tant que root : <code>sudo &lt;commande&gt;</code>. Il faut être dans le groupe <code>sudo</code>.</p><h3>su</h3><ul><li><code>su</code> — devenir root</li><li><code>su &lt;user&gt;</code> — devenir un autre utilisateur</li></ul><h3>Processus</h3><ul><li><code>ps aux</code> — lister les processus</li><li><code>top</code> — vue en temps réel</li><li><code>kill &lt;PID&gt;</code> — arrêter un processus</li></ul><div class="tip">Le <strong>PID</strong> est l'identifiant unique de chaque processus.</div>""",
        "exercises": [
            {"id": "5.1", "points": 4, "title": "Créer un sudoer",
             "desc": "Créez <code>stagiaire</code> et faites-en un sudoer.<br><span class='hint'>Pour utiliser sudo, un utilisateur doit appartenir à un certain groupe...</span>",
             "check": "id stagiaire >/dev/null 2>&1 && id stagiaire 2>/dev/null | grep -q sudo"},
            {"id": "5.2", "points": 3, "title": "Observer les processus",
             "desc": "Lancez <code>sleep 3600 &</code> puis sauvegardez la liste des processus dans <code>/home/etudiant/processus.txt</code>.<br><span class='hint'>Quelle commande donne un instantané des processus ? Redirigez sa sortie.</span>",
             "check": "test -f /home/etudiant/processus.txt && grep -qE '(PID|pid|CPU|COMMAND|CMD)' /home/etudiant/processus.txt"},
            {"id": "5.3", "points": 4, "title": "Arrêter un processus",
             "desc": "Le processus <code>sleep</code> tourne encore. Trouvez son PID et arrêtez-le.<br><span class='hint'>Cherchez le PID avec <code>ps</code> ou <code>pgrep</code>.</span>",
             "check": "! pgrep -x sleep >/dev/null 2>&1"},
        ],
    },
    6: {
        "title": "Exercice pratique : système familial",
        "description": "Mettez tout en pratique avec un cas concret.",
        "lesson": """<h3>Cas pratique</h3><p>Vous installez Linux pour la famille : <strong>papa</strong>, <strong>maman</strong>, <strong>fils</strong>, <strong>fille</strong>.</p><p>Chacun a son compte, un dossier <code>Travail</code> et <code>Bazar</code>.</p><p>À créer :</p><ul><li>Un dossier <strong>famille</strong> partagé par tous</li><li>Un dossier <strong>parents uniquement</strong></li><li>Un <strong>compte invité</strong> sans accès familial</li></ul><div class="tip">Pensez groupes + permissions pour contrôler l'accès.</div>""",
        "exercises": [
            {"id": "6.1", "points": 4, "title": "La famille",
             "desc": "Créez <code>papa</code>, <code>maman</code>, <code>fils</code>, <code>fille</code>. Chacun avec <code>Travail</code> et <code>Bazar</code> dans son home.",
             "check": "id papa && id maman && id fils && id fille && test -d /home/papa/Travail && test -d /home/papa/Bazar && test -d /home/maman/Travail && test -d /home/maman/Bazar && test -d /home/fils/Travail && test -d /home/fils/Bazar && test -d /home/fille/Travail && test -d /home/fille/Bazar"},
            {"id": "6.2", "points": 4, "title": "Les groupes",
             "desc": "Créez <code>parents</code> (papa+maman) et <code>enfants</code> (fils+fille).",
             "check": "getent group parents && getent group enfants && id papa | grep -q parents && id maman | grep -q parents && id fils | grep -q enfants && id fille | grep -q enfants"},
            {"id": "6.3", "points": 4, "title": "Espace commun",
             "desc": "Créez <code>/home/famille</code> accessible à tous les membres (groupe <code>famille</code>, permissions <code>770</code>).<br><span class='hint'>Il faut un groupe qui rassemble tout le monde.</span>",
             "check": "test -d /home/famille && getent group famille && test $(stat -c '%G' /home/famille) = famille && test $(stat -c '%a' /home/famille) = 770"},
            {"id": "6.4", "points": 4, "title": "Espace parents",
             "desc": "Créez <code>/home/parents-only</code> réservé aux parents.",
             "check": "test -d /home/parents-only && test $(stat -c '%G' /home/parents-only) = parents && test $(stat -c '%a' /home/parents-only) = 770"},
            {"id": "6.5", "points": 4, "title": "Compte invité",
             "desc": "Créez <code>invite</code> sans accès aux dossiers familiaux.",
             "check": "id invite && ! id invite 2>/dev/null | grep -q famille && ! id invite 2>/dev/null | grep -q parents && ! id invite 2>/dev/null | grep -q enfants"},
        ],
    },
    7: {
        "title": "Installer des programmes",
        "description": "Apprenez à installer des logiciels avec apt et télécharger des fichiers.",
        "lesson": """<div class="tip">Dans Linux, <strong>tout est fichier</strong>. Installer = mettre les bons fichiers aux bons endroits.</div><h3>Gestionnaire de paquets (apt)</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th></tr><tr><td><code>apt-get update</code></td><td>Mettre à jour la liste</td></tr><tr><td><code>apt-cache search X</code></td><td>Chercher un paquet</td></tr><tr><td><code>apt-get install X</code></td><td>Installer</td></tr><tr><td><code>apt-get remove X</code></td><td>Supprimer</td></tr></table><h3>Télécharger</h3><p><code>wget &lt;url&gt;</code> télécharge un fichier depuis internet.</p>""",
        "exercises": [
            {"id": "7.1", "points": 4, "title": "Installer un programme",
             "desc": "Installez <code>tree</code> avec le gestionnaire de paquets.<br><span class='hint'>Avant d'installer, il faut mettre à jour la liste des paquets.</span>",
             "check": "command -v tree >/dev/null 2>&1"},
            {"id": "7.2", "points": 4, "title": "Télécharger un fichier",
             "desc": "Téléchargez un fichier et sauvegardez-le dans <code>/home/etudiant/download-test.txt</code>.<br><span class='hint'>Consultez le manuel de la commande de téléchargement pour choisir le nom de sortie.</span>",
             "check": "test -f /home/etudiant/download-test.txt && test -s /home/etudiant/download-test.txt"},
        ],
    },
    8: {
        "title": "Montage et systèmes de fichiers",
        "description": "Explorez les périphériques et les points de montage.",
        "lesson": """<h3>Périphériques dans /dev</h3><ul><li><code>/dev/sda</code> — premier disque</li><li><code>/dev/sda1</code> — première partition</li></ul><h3>Monter</h3><pre>mount &lt;périphérique&gt; &lt;point_de_montage&gt;</pre><div class="tip">Points de montage : généralement <code>/media</code> ou <code>/mnt</code>.</div><h3>Partitionnement</h3><p>Typiquement : <code>/</code> (système), <code>/home</code> (données), <code>swap</code> (mémoire virtuelle).</p><div class="tip">Réinstaller sur <code>/</code> sans toucher <code>/home</code> = données préservées !</div>""",
        "exercises": [
            {"id": "8.1", "points": 4, "title": "Explorer les périphériques",
             "desc": "Listez les périphériques et sauvegardez dans <code>/home/etudiant/devices.txt</code>.<br><span class='hint'>Explorez <code>/proc</code> ou cherchez une commande listant les périphériques bloc.</span>",
             "check": "test -f /home/etudiant/devices.txt && test -s /home/etudiant/devices.txt"},
            {"id": "8.2", "points": 4, "title": "Simuler un montage",
             "desc": "Créez un point de montage <code>/mnt/usb</code> avec un fichier <code>readme.txt</code> contenant <code>Point de montage prêt</code>.<br><span class='hint'>Un point de montage est un simple dossier vide.</span>",
             "check": "test -d /mnt/usb && test -f /mnt/usb/readme.txt && grep -qi 'point de montage' /mnt/usb/readme.txt"},
        ],
    },
}


def get_exercise_points(exercise_id: str) -> int:
    """Get points for an exercise ID like '1.1'."""
    step_num = int(exercise_id.split(".")[0])
    step = STEPS.get(step_num, {})
    for ex in step.get("exercises", []):
        if ex["id"] == exercise_id:
            return ex["points"]
    return 0
