"""Exercise definitions and validation commands."""

STEPS = {
    1: {
        "title": "Premiers pas : navigation dans le système",
        "description": "Découvrez le terminal Linux, naviguez dans l'arborescence et listez les fichiers.",
        "lesson": """<h3>Bienvenue en console !</h3><p>Vous allez apprendre à utiliser l'interface en ligne de commande (CLI) de Linux. Quand vous ouvrez un terminal, vous voyez :</p><pre>user@machine:~$</pre><p>Cette ligne indique <strong>qui vous êtes</strong>, <strong>sur quelle machine</strong> et <strong>où vous êtes</strong>.</p><div class="tip">Le symbole <code>~</code> est un raccourci vers votre dossier personnel <code>/home/user</code>.</div><h3>Commandes essentielles</h3><ul><li><code>whoami</code> — votre nom d'utilisateur</li><li><code>pwd</code> — dossier courant (<em>Print Working Directory</em>)</li><li><code>cd &lt;dossier&gt;</code> — se déplacer (<em>Change Directory</em>)</li><li><code>ls</code> — lister le contenu (<em>List</em>)</li><li><code>mkdir &lt;dossier&gt;</code> — créer un dossier (<em>Make Directory</em>)</li><li><code>touch &lt;fichier&gt;</code> — créer un fichier vide</li></ul><h3>L'arborescence Linux</h3><p>Tout part de la racine <code>/</code>. Avec <code>ls /</code> on découvre :</p><ul><li><code>/home</code> — dossiers personnels</li><li><code>/etc</code> — fichiers de configuration</li><li><code>/root</code> — dossier du super-utilisateur</li><li><code>/usr</code> — programmes installés</li><li><code>/dev</code> — périphériques</li></ul>""",
        "exercises": [
            {"id": "1.1", "points": 3, "title": "Votre espace de travail",
             "desc": "Créez votre dossier de travail <code>/home/etudiant</code>.<br><span class='hint'>Quelle commande permet de créer un dossier ?</span>",
             "check": "test -d /home/etudiant"},
            {"id": "1.2", "points": 3, "title": "Explorer le système",
             "desc": "Créez un dossier <code>/home/etudiant/exploration</code> pour y stocker vos découvertes.",
             "check": "test -d /home/etudiant/exploration"},
            {"id": "1.3", "points": 3, "title": "Votre premier fichier",
             "desc": "Créez un fichier vide <code>/home/etudiant/exploration/decouverte.txt</code>.<br><span class='hint'>La commande <code>touch</code> crée un fichier vide.</span>",
             "check": "test -f /home/etudiant/exploration/decouverte.txt"},
            {"id": "1.4", "points": 3, "title": "Organiser",
             "desc": "Créez les dossiers <code>/home/etudiant/documents</code> et <code>/home/etudiant/projets</code>.",
             "check": "test -d /home/etudiant/documents && test -d /home/etudiant/projets"},
        ],
    },
    2: {
        "title": "Le manuel et les chemins",
        "description": "Apprenez à lire la documentation et à utiliser les chemins absolus et relatifs.",
        "lesson": """<h3>RTFM : Read The Manual !</h3><p>Le <strong>Manuel</strong> contient la documentation de toutes les commandes :</p><pre>man &lt;commande&gt;</pre><div class="tip"><strong>Conventions :</strong> <code>[PARAM]</code> = optionnel, <code>...</code> = plusieurs possibles</div><h3>Les options</h3><p>Les options modifient le comportement. Essayez :</p><ul><li><code>ls -l</code> — format détaillé</li><li><code>ls -a</code> — fichiers cachés</li><li><code>ls -la</code> — les deux</li></ul><h3>Chemins absolus vs relatifs</h3><table class="lesson-table"><tr><th>Absolu</th><th>Relatif</th></tr><tr><td>Commence par <code>/</code></td><td>Part de votre position</td></tr><tr><td><code>/home/user/Documents</code></td><td><code>Documents</code></td></tr><tr><td>Toujours vrai</td><td>Dépend du contexte</td></tr></table><div class="tip"><code>.</code> = dossier courant | <code>..</code> = dossier parent</div>""",
        "exercises": [
            {"id": "2.1", "points": 3, "title": "Chemin absolu",
             "desc": "En utilisant un <strong>chemin absolu</strong>, créez le dossier <code>/home/etudiant/projets/projet-alpha</code>.<br><span class='hint'>Un chemin absolu commence toujours par <code>/</code>. Pensez à l'option <code>-p</code>.</span>",
             "check": "test -d /home/etudiant/projets/projet-alpha"},
            {"id": "2.2", "points": 3, "title": "Chemin relatif",
             "desc": "Créez un dossier <code>projet-beta</code> dans <code>/home/etudiant/projets</code> en utilisant un chemin relatif.<br><span class='hint'>Placez-vous d'abord dans le bon dossier avec <code>cd</code>.</span>",
             "check": "test -d /home/etudiant/projets/projet-beta"},
            {"id": "2.3", "points": 3, "title": "Remonter avec ..",
             "desc": "Créez un fichier <code>notes.txt</code> dans <code>projet-alpha</code> en utilisant <code>..</code> depuis <code>projet-beta</code>.<br><span class='hint'><code>..</code> remonte d'un niveau dans l'arborescence.</span>",
             "check": "test -f /home/etudiant/projets/projet-alpha/notes.txt"},
            {"id": "2.4", "points": 3, "title": "Options de ls",
             "desc": "Créez un fichier <code>/home/etudiant/projets/listing.txt</code> pour prouver que vous avez exploré.<br><span class='hint'>Consultez le manuel pour découvrir les options de <code>ls</code>.</span>",
             "check": "test -f /home/etudiant/projets/listing.txt"},
        ],
    },
    3: {
        "title": "Créer, écrire, gérer fichiers et dossiers",
        "description": "Manipulez fichiers et dossiers : écriture, copie, déplacement, suppression.",
        "lesson": """<h3>Écriture dans un fichier</h3><table class="lesson-table"><tr><th>Symbole</th><th>Effet</th><th>Exemple</th></tr><tr><td><code>&gt;</code></td><td><strong>Remplace</strong> le contenu</td><td><code>echo "Bonjour" > f.txt</code></td></tr><tr><td><code>&gt;&gt;</code></td><td><strong>Ajoute</strong> à la fin</td><td><code>echo "Suite" >> f.txt</code></td></tr></table><p><code>cat fichier</code> affiche le contenu d'un fichier.</p><h3>Copier, déplacer, supprimer</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th><th>Note</th></tr><tr><td><code>cp src dest</code></td><td>Copier</td><td><code>-R</code> pour les dossiers</td></tr><tr><td><code>mv src dest</code></td><td>Déplacer / Renommer</td><td></td></tr><tr><td><code>rm fichier</code></td><td>Supprimer fichier</td><td></td></tr><tr><td><code>rm -R dossier</code></td><td>Supprimer dossier</td><td>Irréversible !</td></tr></table>""",
        "exercises": [
            {"id": "3.1", "points": 3, "title": "Arborescence",
             "desc": "Créez <code>/home/etudiant/documents/cours/</code> et <code>/home/etudiant/documents/exercices/</code>.<br><span class='hint'>Comment créer plusieurs niveaux de dossiers d'un coup ?</span>",
             "check": "test -d /home/etudiant/documents/cours && test -d /home/etudiant/documents/exercices"},
            {"id": "3.2", "points": 3, "title": "Écrire dans un fichier",
             "desc": "Écrivez <code>Bienvenue dans le cours Linux</code> dans <code>/home/etudiant/documents/cours/notes.txt</code>.<br><span class='hint'>Utilisez la redirection pour envoyer du texte dans un fichier.</span>",
             "check": "grep -qi 'bienvenue' /home/etudiant/documents/cours/notes.txt 2>/dev/null"},
            {"id": "3.3", "points": 3, "title": "Copier un fichier",
             "desc": "Copiez <code>notes.txt</code> dans <code>/home/etudiant/documents/exercices/</code>.<br><span class='hint'>Quelle commande copie un fichier d'un endroit à un autre ?</span>",
             "check": "test -f /home/etudiant/documents/exercices/notes.txt || test -f /home/etudiant/documents/exercices/notes-copie.txt"},
            {"id": "3.4", "points": 3, "title": "Renommer",
             "desc": "Renommez la copie en <code>notes-copie.txt</code> (dans <code>documents/exercices/</code>).<br><span class='hint'>Il n'y a pas de commande rename... mais déplacer permet aussi de renommer.</span>",
             "check": "test -f /home/etudiant/documents/exercices/notes-copie.txt"},
            {"id": "3.5", "points": 3, "title": "Ajouter du contenu",
             "desc": "Ajoutez une 2ème ligne <code>Ceci est un ajout</code> à <code>notes.txt</code> <strong>sans écraser</strong> la 1ère.<br><span class='hint'>Quelle différence entre <code>&gt;</code> et <code>&gt;&gt;</code> ?</span>",
             "check": "test $(wc -l < /home/etudiant/documents/cours/notes.txt 2>/dev/null) -ge 2 && grep -qi 'ajout' /home/etudiant/documents/cours/notes.txt"},
        ],
    },
    4: {
        "title": "Utilisateurs, groupes et permissions",
        "description": "Gérez les utilisateurs, les groupes et les droits d'accès aux fichiers.",
        "lesson": """<h3>Les utilisateurs</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th></tr><tr><td><code>adduser &lt;user&gt;</code></td><td>Créer un utilisateur</td></tr><tr><td><code>deluser &lt;user&gt;</code></td><td>Supprimer</td></tr></table><p>Liste : <code>/etc/passwd</code></p><h3>Les groupes</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th></tr><tr><td><code>addgroup &lt;grp&gt;</code></td><td>Créer un groupe</td></tr><tr><td><code>adduser &lt;user&gt; &lt;grp&gt;</code></td><td>Ajouter au groupe</td></tr></table><h3>Permissions</h3><p>3 triades : <strong>user</strong> | <strong>group</strong> | <strong>others</strong></p><p><code>r</code>=4, <code>w</code>=2, <code>x</code>=1 → <code>rwx</code>=7, <code>r-x</code>=5, <code>---</code>=0</p><ul><li><code>chmod 755 fichier</code></li><li><code>chown user fichier</code> / <code>chgrp group fichier</code></li></ul>""",
        "exercises": [
            {"id": "4.1", "points": 3, "title": "Créer des utilisateurs",
             "desc": "Créez deux utilisateurs : <code>alice</code> et <code>bob</code>.<br><span class='hint'>Relisez la section utilisateurs du cours.</span>",
             "check": "id alice >/dev/null 2>&1 && id bob >/dev/null 2>&1"},
            {"id": "4.2", "points": 3, "title": "Créer un groupe",
             "desc": "Créez un groupe <code>equipe</code> et ajoutez-y <code>alice</code> et <code>bob</code>.<br><span class='hint'>Deux étapes : créer le groupe, puis y ajouter chaque utilisateur.</span>",
             "check": "getent group equipe >/dev/null 2>&1 && id alice 2>/dev/null | grep -q equipe && id bob 2>/dev/null | grep -q equipe"},
            {"id": "4.3", "points": 4, "title": "Dossier de groupe",
             "desc": "Créez <code>/home/partage</code> et attribuez-le au groupe <code>equipe</code>.<br><span class='hint'>Créez le dossier, puis changez son groupe propriétaire.</span>",
             "check": "test -d /home/partage && test $(stat -c '%G' /home/partage) = equipe"},
            {"id": "4.4", "points": 4, "title": "Protéger le dossier",
             "desc": "Permissions de <code>/home/partage</code> : propriétaire et groupe = tout, autres = rien.<br><span class='hint'>En octal : rwx=7, ---=0. Quelle combinaison ?</span>",
             "check": "test $(stat -c '%a' /home/partage) = 770"},
            {"id": "4.5", "points": 3, "title": "Fichier confidentiel",
             "desc": "Créez <code>/home/partage/secret.txt</code> : propriétaire rw, groupe r, autres rien.<br><span class='hint'>Calculez : rw-=?, r--=?, ---=?</span>",
             "check": "test -f /home/partage/secret.txt && test $(stat -c '%a' /home/partage/secret.txt) = 640"},
        ],
    },
    5: {
        "title": "Super-utilisateur et processus",
        "description": "Découvrez sudo, su et la gestion des processus.",
        "lesson": """<h3>root — le super-utilisateur</h3><p>Tout-puissant. Le <code>$</code> devient <code>#</code>.</p><h3>sudo</h3><p>Exécuter en tant que root : <code>sudo &lt;commande&gt;</code>. Il faut être dans le groupe <code>sudo</code>.</p><h3>su</h3><ul><li><code>su</code> — devenir root</li><li><code>su &lt;user&gt;</code> — devenir un autre utilisateur</li></ul><h3>Processus</h3><ul><li><code>ps aux</code> — lister les processus</li><li><code>top</code> — vue en temps réel</li><li><code>kill &lt;PID&gt;</code> — arrêter un processus</li></ul><div class="tip">Le <strong>PID</strong> est l'identifiant unique de chaque processus.</div>""",
        "exercises": [
            {"id": "5.1", "points": 4, "title": "Créer un sudoer",
             "desc": "Créez <code>stagiaire</code> et faites-en un sudoer.<br><span class='hint'>Pour utiliser sudo, un utilisateur doit appartenir à un certain groupe...</span>",
             "check": "id stagiaire >/dev/null 2>&1 && id stagiaire 2>/dev/null | grep -q sudo"},
            {"id": "5.2", "points": 3, "title": "Observer les processus",
             "desc": "Lancez <code>sleep 3600 &</code> puis sauvegardez la liste des processus dans <code>/home/etudiant/processus.txt</code>.<br><span class='hint'>Quelle commande donne un instantané des processus ? Redirigez sa sortie.</span>",
             "check": "test -f /home/etudiant/processus.txt && grep -qE '(PID|pid|CPU|COMMAND|CMD)' /home/etudiant/processus.txt"},
            {"id": "5.3", "points": 4, "title": "Arrêter un processus",
             "desc": "Le processus <code>sleep</code> tourne encore. Trouvez son PID et arrêtez-le.<br><span class='hint'>Cherchez le PID avec <code>ps</code> ou <code>pgrep</code>.</span>",
             "check": "! pgrep -x sleep >/dev/null 2>&1"},
        ],
    },
    6: {
        "title": "Exercice pratique : système familial",
        "description": "Mettez tout en pratique avec un cas concret.",
        "lesson": """<h3>Cas pratique</h3><p>Vous installez Linux pour la famille : <strong>papa</strong>, <strong>maman</strong>, <strong>fils</strong>, <strong>fille</strong>.</p><p>Chacun a son compte, un dossier <code>Travail</code> et <code>Bazar</code>.</p><p>À créer :</p><ul><li>Un dossier <strong>famille</strong> partagé par tous</li><li>Un dossier <strong>parents uniquement</strong></li><li>Un <strong>compte invité</strong> sans accès familial</li></ul><div class="tip">Pensez groupes + permissions pour contrôler l'accès.</div>""",
        "exercises": [
            {"id": "6.1", "points": 4, "title": "La famille",
             "desc": "Créez <code>papa</code>, <code>maman</code>, <code>fils</code>, <code>fille</code>. Chacun avec <code>Travail</code> et <code>Bazar</code> dans son home.",
             "check": "id papa && id maman && id fils && id fille && test -d /home/papa/Travail && test -d /home/papa/Bazar && test -d /home/maman/Travail && test -d /home/maman/Bazar && test -d /home/fils/Travail && test -d /home/fils/Bazar && test -d /home/fille/Travail && test -d /home/fille/Bazar"},
            {"id": "6.2", "points": 4, "title": "Les groupes",
             "desc": "Créez <code>parents</code> (papa+maman) et <code>enfants</code> (fils+fille).",
             "check": "getent group parents && getent group enfants && id papa | grep -q parents && id maman | grep -q parents && id fils | grep -q enfants && id fille | grep -q enfants"},
            {"id": "6.3", "points": 4, "title": "Espace commun",
             "desc": "Créez <code>/home/famille</code> accessible à tous les membres (groupe <code>famille</code>, permissions <code>770</code>).<br><span class='hint'>Il faut un groupe qui rassemble tout le monde.</span>",
             "check": "test -d /home/famille && getent group famille && test $(stat -c '%G' /home/famille) = famille && test $(stat -c '%a' /home/famille) = 770"},
            {"id": "6.4", "points": 4, "title": "Espace parents",
             "desc": "Créez <code>/home/parents-only</code> réservé aux parents.",
             "check": "test -d /home/parents-only && test $(stat -c '%G' /home/parents-only) = parents && test $(stat -c '%a' /home/parents-only) = 770"},
            {"id": "6.5", "points": 4, "title": "Compte invité",
             "desc": "Créez <code>invite</code> sans accès aux dossiers familiaux.",
             "check": "id invite && ! id invite 2>/dev/null | grep -q famille && ! id invite 2>/dev/null | grep -q parents && ! id invite 2>/dev/null | grep -q enfants"},
        ],
    },
    7: {
        "title": "Installer des programmes",
        "description": "Apprenez à installer des logiciels avec apt et télécharger des fichiers.",
        "lesson": """<div class="tip">Dans Linux, <strong>tout est fichier</strong>. Installer = mettre les bons fichiers aux bons endroits.</div><h3>Gestionnaire de paquets (apt)</h3><table class="lesson-table"><tr><th>Commande</th><th>Action</th></tr><tr><td><code>apt-get update</code></td><td>Mettre à jour la liste</td></tr><tr><td><code>apt-cache search X</code></td><td>Chercher un paquet</td></tr><tr><td><code>apt-get install X</code></td><td>Installer</td></tr><tr><td><code>apt-get remove X</code></td><td>Supprimer</td></tr></table><h3>Télécharger</h3><p><code>wget &lt;url&gt;</code> télécharge un fichier depuis internet.</p>""",
        "exercises": [
            {"id": "7.1", "points": 4, "title": "Installer un programme",
             "desc": "Installez <code>tree</code> avec le gestionnaire de paquets.<br><span class='hint'>Avant d'installer, il faut mettre à jour la liste des paquets.</span>",
             "check": "command -v tree >/dev/null 2>&1"},
            {"id": "7.2", "points": 4, "title": "Télécharger un fichier",
             "desc": "Téléchargez un fichier et sauvegardez-le dans <code>/home/etudiant/download-test.txt</code>.<br><span class='hint'>Consultez le manuel de la commande de téléchargement pour choisir le nom de sortie.</span>",
             "check": "test -f /home/etudiant/download-test.txt && test -s /home/etudiant/download-test.txt"},
        ],
    },
    8: {
        "title": "Montage et systèmes de fichiers",
        "description": "Explorez les périphériques et les points de montage.",
        "lesson": """<h3>Périphériques dans /dev</h3><ul><li><code>/dev/sda</code> — premier disque</li><li><code>/dev/sda1</code> — première partition</li></ul><h3>Monter</h3><pre>mount &lt;périphérique&gt; &lt;point_de_montage&gt;</pre><div class="tip">Points de montage : généralement <code>/media</code> ou <code>/mnt</code>.</div><h3>Partitionnement</h3><p>Typiquement : <code>/</code> (système), <code>/home</code> (données), <code>swap</code> (mémoire virtuelle).</p><div class="tip">Réinstaller sur <code>/</code> sans toucher <code>/home</code> = données préservées !</div>""",
        "exercises": [
            {"id": "8.1", "points": 4, "title": "Explorer les périphériques",
             "desc": "Listez les périphériques et sauvegardez dans <code>/home/etudiant/devices.txt</code>.<br><span class='hint'>Explorez <code>/proc</code> ou cherchez une commande listant les périphériques bloc.</span>",
             "check": "test -f /home/etudiant/devices.txt && test -s /home/etudiant/devices.txt"},
            {"id": "8.2", "points": 4, "title": "Simuler un montage",
             "desc": "Créez un point de montage <code>/mnt/usb</code> avec un fichier <code>readme.txt</code> contenant <code>Point de montage prêt</code>.<br><span class='hint'>Un point de montage est un simple dossier vide.</span>",
             "check": "test -d /mnt/usb && test -f /mnt/usb/readme.txt && grep -qi 'point de montage' /mnt/usb/readme.txt"},
        ],
    },
    9: {
        "title": "Recherche de fichiers et de contenu",
        "description": "Maîtrisez find, grep et wc pour retrouver fichiers et informations.",
        "lesson": """<h3>Chercher des fichiers avec find</h3><pre>find &lt;où&gt; &lt;critères&gt;</pre><ul><li><code>find /etc -name "*.conf"</code> — fichiers .conf</li><li><code>find /home -type d</code> — dossiers uniquement</li><li><code>find / -name "passwd"</code> — chercher partout</li></ul><div class="tip"><code>-name</code> sensible à la casse, <code>-iname</code> insensible.</div><h3>Chercher du contenu avec grep</h3><pre>grep &lt;motif&gt; &lt;fichier&gt;</pre><ul><li><code>grep "root" /etc/passwd</code></li><li><code>grep -r "TODO" /home/</code> — récursif</li><li><code>grep -n "config" f.txt</code> — numéros de ligne</li><li><code>grep -c "error" f.log</code> — compter</li></ul><h3>Compter avec wc</h3><ul><li><code>wc -l</code> lignes | <code>wc -w</code> mots | <code>wc -c</code> octets</li></ul>""",
        "exercises": [
            {"id": "9.1", "points": 3, "title": "Trouver des fichiers .conf",
             "desc": "Utilisez <code>find</code> pour lister les fichiers <code>.conf</code> dans <code>/etc</code>. Sauvegardez dans <code>/home/etudiant/conf-files.txt</code>.",
             "check": "test -f /home/etudiant/conf-files.txt && grep -q '\\.conf' /home/etudiant/conf-files.txt"},
            {"id": "9.2", "points": 3, "title": "Grep dans /etc/passwd",
             "desc": "Trouvez les lignes contenant <code>root</code> dans <code>/etc/passwd</code>. Sauvegardez dans <code>/home/etudiant/root-lines.txt</code>.",
             "check": "test -f /home/etudiant/root-lines.txt && grep -q root /home/etudiant/root-lines.txt"},
            {"id": "9.3", "points": 3, "title": "Compter avec wc",
             "desc": "Comptez le nombre de lignes dans <code>/etc/passwd</code>. Sauvegardez le nombre dans <code>/home/etudiant/nb-users.txt</code>.",
             "check": "test -f /home/etudiant/nb-users.txt && test -s /home/etudiant/nb-users.txt"},
            {"id": "9.4", "points": 3, "title": "Trouver des dossiers",
             "desc": "Listez tous les dossiers dans <code>/var</code> avec <code>find -type d</code>. Sauvegardez dans <code>/home/etudiant/var-dirs.txt</code>.",
             "check": "test -f /home/etudiant/var-dirs.txt && grep -q /var /home/etudiant/var-dirs.txt"},
        ],
    },
    10: {
        "title": "Redirections et pipes",
        "description": "Combinez les commandes avec les pipes et maîtrisez les redirections.",
        "lesson": """<h3>Rappel des redirections</h3><table class="lesson-table"><tr><th>Symbole</th><th>Effet</th></tr><tr><td><code>&gt;</code></td><td>Remplace le contenu</td></tr><tr><td><code>&gt;&gt;</code></td><td>Ajoute à la fin</td></tr><tr><td><code>2&gt;</code></td><td>Redirige les erreurs</td></tr><tr><td><code>2&gt;/dev/null</code></td><td>Supprime les erreurs</td></tr></table><h3>Le pipe |</h3><p>Connecte la sortie d'une commande à l'entrée de la suivante :</p><pre>commande1 | commande2 | commande3</pre><p>Exemples : <code>ls /etc | wc -l</code>, <code>cat /etc/passwd | grep bash</code></p><h3>tee</h3><p>Sauvegarde dans un fichier ET affiche : <code>ls | tee fichier.txt</code></p><h3>Outils utiles</h3><ul><li><code>sort</code> — trier</li><li><code>uniq</code> — dédupliquer</li><li><code>head</code> / <code>tail</code> — début / fin</li><li><code>cut</code> — découper</li></ul>""",
        "exercises": [
            {"id": "10.1", "points": 3, "title": "Compter avec un pipe",
             "desc": "Comptez le nombre de fichiers dans <code>/etc</code> avec un pipe. Sauvegardez dans <code>/home/etudiant/nb-etc.txt</code>.",
             "check": "test -f /home/etudiant/nb-etc.txt && test -s /home/etudiant/nb-etc.txt"},
            {"id": "10.2", "points": 3, "title": "Rediriger les erreurs",
             "desc": "Redirigez les erreurs de <code>find /root</code> dans <code>/home/etudiant/erreurs.txt</code>.",
             "check": "test -f /home/etudiant/erreurs.txt"},
            {"id": "10.3", "points": 3, "title": "Utiliser tee",
             "desc": "Sauvegardez le listing de <code>/usr/bin</code> dans <code>/home/etudiant/programmes.txt</code> avec <code>tee</code>.",
             "check": "test -f /home/etudiant/programmes.txt && test $(wc -l < /home/etudiant/programmes.txt) -gt 10"},
            {"id": "10.4", "points": 3, "title": "Trier des utilisateurs",
             "desc": "Extrayez et triez les noms d'utilisateurs de <code>/etc/passwd</code>. Sauvegardez dans <code>/home/etudiant/users-sorted.txt</code>.",
             "check": "test -f /home/etudiant/users-sorted.txt && sort -c /home/etudiant/users-sorted.txt 2>/dev/null"},
        ],
    },
    11: {
        "title": "Édition de texte en terminal",
        "description": "Modifiez des fichiers avec nano, vim et sed.",
        "lesson": """<h3>nano — l'éditeur simple</h3><p>Raccourcis : <code>Ctrl+O</code> sauvegarder, <code>Ctrl+X</code> quitter, <code>Ctrl+W</code> rechercher.</p><h3>vim — l'éditeur puissant</h3><p>Modes : <strong>normal</strong> (défaut), <strong>insertion</strong> (<code>i</code>), <strong>commande</strong> (<code>:</code>)</p><ul><li><code>i</code> → insérer | <code>Echap</code> → normal</li><li><code>:w</code> sauver | <code>:q</code> quitter | <code>:wq</code> les deux</li></ul><div class="tip">Perdu dans vim ? <code>Echap</code> puis <code>:q!</code></div><h3>sed — l'éditeur de flux</h3><pre>sed 's/ancien/nouveau/g' fichier<br>sed -i 's/ancien/nouveau/g' fichier  # modifie directement</pre>""",
        "exercises": [
            {"id": "11.1", "points": 3, "title": "Éditer avec nano",
             "desc": "Créez <code>/home/etudiant/config.txt</code> avec 3 lignes : <code>serveur=localhost</code>, <code>port=8080</code>, <code>debug=false</code>.",
             "check": "test -f /home/etudiant/config.txt && grep -q 'serveur=localhost' /home/etudiant/config.txt && grep -q 'port=8080' /home/etudiant/config.txt && grep -q 'debug=' /home/etudiant/config.txt"},
            {"id": "11.2", "points": 3, "title": "Éditer avec vim",
             "desc": "Créez <code>/home/etudiant/memo.txt</code> contenant <code>Vim est un éditeur puissant</code>.",
             "check": "test -f /home/etudiant/memo.txt && grep -qi vim /home/etudiant/memo.txt"},
            {"id": "11.3", "points": 3, "title": "Remplacer avec sed",
             "desc": "Remplacez <code>debug=false</code> par <code>debug=true</code> dans <code>config.txt</code>.",
             "check": "grep -q 'debug=true' /home/etudiant/config.txt 2>/dev/null"},
        ],
    },
    12: {
        "title": "Variables d'environnement et shell",
        "description": "Configurez votre environnement avec les variables, le PATH et les alias.",
        "lesson": """<h3>Variables d'environnement</h3><ul><li><code>echo $HOME</code>, <code>echo $PATH</code>, <code>echo $USER</code></li><li><code>env</code> ou <code>printenv</code> — lister toutes les variables</li></ul><h3>Créer / Exporter</h3><pre>MA_VAR="valeur"        # locale<br>export MA_VAR="valeur" # environnement</pre><h3>Le PATH</h3><p>Liste des dossiers où chercher les programmes :</p><pre>export PATH=$PATH:/nouveau/chemin</pre><h3>Les alias</h3><pre>alias ll='ls -la'</pre><div class="tip">Pour rendre permanent : ajouter dans <code>~/.bashrc</code> puis <code>source ~/.bashrc</code></div>""",
        "exercises": [
            {"id": "12.1", "points": 3, "title": "Lister les variables",
             "desc": "Sauvegardez toutes les variables d'environnement dans <code>/home/etudiant/env-vars.txt</code>.",
             "check": "test -f /home/etudiant/env-vars.txt && grep -qE '(PATH=|HOME=|SHELL=)' /home/etudiant/env-vars.txt"},
            {"id": "12.2", "points": 3, "title": "Créer une variable",
             "desc": "Créez <code>PROJET=linux-lab</code> et sauvegardez sa valeur dans <code>/home/etudiant/projet.txt</code>.",
             "check": "test -f /home/etudiant/projet.txt && grep -q linux-lab /home/etudiant/projet.txt"},
            {"id": "12.3", "points": 3, "title": "Afficher le PATH",
             "desc": "Sauvegardez le contenu de <code>$PATH</code> dans <code>/home/etudiant/mon-path.txt</code>.",
             "check": "test -f /home/etudiant/mon-path.txt && grep -qE '(/usr/bin|/usr/local/bin|/bin)' /home/etudiant/mon-path.txt"},
            {"id": "12.4", "points": 3, "title": "Créer un alias",
             "desc": "Ajoutez l'alias <code>ll='ls -la'</code> dans <code>/root/.bashrc</code>.",
             "check": "grep -q 'alias ll=' /root/.bashrc 2>/dev/null"},
        ],
    },
    13: {
        "title": "Réseau de base",
        "description": "Diagnostiquez le réseau : interfaces, connectivité, ports.",
        "lesson": """<h3>Informations réseau</h3><ul><li><code>ip a</code> — interfaces et adresses IP</li><li><code>hostname</code> / <code>hostname -I</code> — nom et IP de la machine</li></ul><h3>Connectivité</h3><pre>ping -c 4 google.com</pre><h3>Ports et connexions</h3><pre>ss -tuln    # ports en écoute<br>netstat -tuln  # alternative</pre><h3>/etc/hosts</h3><p>Résolution DNS locale :</p><pre>192.168.1.10 serveur-web</pre>""",
        "exercises": [
            {"id": "13.1", "points": 3, "title": "Informations réseau",
             "desc": "Sauvegardez les infos réseau dans <code>/home/etudiant/network-info.txt</code>.",
             "check": "test -f /home/etudiant/network-info.txt && test -s /home/etudiant/network-info.txt"},
            {"id": "13.2", "points": 3, "title": "Hostname",
             "desc": "Sauvegardez le hostname dans <code>/home/etudiant/hostname.txt</code>.",
             "check": "test -f /home/etudiant/hostname.txt && test -s /home/etudiant/hostname.txt"},
            {"id": "13.3", "points": 3, "title": "Ports en écoute",
             "desc": "Listez les ports en écoute dans <code>/home/etudiant/ports.txt</code>.",
             "check": "test -f /home/etudiant/ports.txt && test -s /home/etudiant/ports.txt"},
            {"id": "13.4", "points": 3, "title": "Modifier /etc/hosts",
             "desc": "Ajoutez <code>192.168.1.100 serveur-local</code> dans <code>/etc/hosts</code>.",
             "check": "grep -q '192.168.1.100' /etc/hosts && grep '192.168.1.100' /etc/hosts | grep -q 'serveur-local'"},
        ],
    },
    14: {
        "title": "Archivage et compression",
        "description": "Créez des archives tar.gz et zip, compressez avec gzip.",
        "lesson": """<h3>tar — archivage</h3><table class="lesson-table"><tr><th>Action</th><th>Commande</th></tr><tr><td>Créer (gzip)</td><td><code>tar -czf archive.tar.gz dossier/</code></td></tr><tr><td>Lister</td><td><code>tar -tzf archive.tar.gz</code></td></tr><tr><td>Extraire</td><td><code>tar -xzf archive.tar.gz -C /dest</code></td></tr></table><h3>gzip</h3><pre>gzip fichier.txt      # → fichier.txt.gz<br>gunzip fichier.txt.gz # → fichier.txt</pre><h3>zip</h3><pre>zip -r archive.zip dossier/<br>unzip archive.zip</pre><div class="tip"><code>.tar.gz</code> = standard Linux | <code>.zip</code> = compatible Windows</div>""",
        "exercises": [
            {"id": "14.1", "points": 3, "title": "Créer une archive tar.gz",
             "desc": "Créez <code>/home/etudiant/archive-test/</code> avec 3 fichiers, puis archivez en <code>archive-test.tar.gz</code>.",
             "check": "test -f /home/etudiant/archive-test.tar.gz && tar -tzf /home/etudiant/archive-test.tar.gz 2>/dev/null | grep -qE '(a\\.txt|b\\.txt|c\\.txt)'"},
            {"id": "14.2", "points": 3, "title": "Extraire une archive",
             "desc": "Extrayez <code>archive-test.tar.gz</code> dans <code>/home/etudiant/extraction/</code>.",
             "check": "test -d /home/etudiant/extraction && find /home/etudiant/extraction -name 'a.txt' 2>/dev/null | grep -q a.txt"},
            {"id": "14.3", "points": 3, "title": "Compression gzip",
             "desc": "Créez <code>compress-me.txt</code> avec du contenu puis compressez-le avec <code>gzip</code>.",
             "check": "test -f /home/etudiant/compress-me.txt.gz"},
            {"id": "14.4", "points": 3, "title": "Archive zip",
             "desc": "Créez <code>/home/etudiant/backup.zip</code> contenant le dossier <code>archive-test</code>.",
             "check": "test -f /home/etudiant/backup.zip"},
        ],
    },
    15: {
        "title": "Filtrage et traitement de texte",
        "description": "Transformez du texte avec sort, uniq, cut, awk et tr.",
        "lesson": """<h3>sort & uniq</h3><pre>sort fichier.txt          # trier<br>sort fichier.txt | uniq   # dédupliquer<br>sort fichier.txt | uniq -c # compter</pre><h3>cut</h3><pre>cut -d: -f1 /etc/passwd   # 1er champ (séparateur :)</pre><h3>awk</h3><pre>awk '{print $1}' fichier<br>awk -F: '{print $1, $3}' /etc/passwd</pre><h3>tr</h3><pre>echo "HELLO" | tr 'A-Z' 'a-z'</pre><h3>Exemple combiné</h3><pre>cut -d: -f7 /etc/passwd | sort | uniq -c | sort -rn</pre>""",
        "exercises": [
            {"id": "15.1", "points": 3, "title": "Compter les shells",
             "desc": "Comptez les shells utilisés dans <code>/etc/passwd</code>. Sauvegardez dans <code>/home/etudiant/shells-count.txt</code>.<br><span class='hint'><code>cut -d: -f7 | sort | uniq -c | sort -rn</code></span>",
             "check": "test -f /home/etudiant/shells-count.txt && grep -qE '(bash|sh|nologin|false)' /home/etudiant/shells-count.txt"},
            {"id": "15.2", "points": 3, "title": "Trier sans doublons",
             "desc": "Créez <code>data.txt</code> (10+ lignes avec doublons) puis <code>data-unique.txt</code> (trié, sans doublons).",
             "check": "test -f /home/etudiant/data.txt && test -f /home/etudiant/data-unique.txt && test $(wc -l < /home/etudiant/data.txt) -ge 10 && sort -c /home/etudiant/data-unique.txt 2>/dev/null"},
            {"id": "15.3", "points": 3, "title": "Extraire avec awk",
             "desc": "Extrayez noms et UIDs de <code>/etc/passwd</code> avec <code>awk</code>. Sauvegardez dans <code>/home/etudiant/users-uid.txt</code>.",
             "check": "test -f /home/etudiant/users-uid.txt && grep -q root /home/etudiant/users-uid.txt && grep -qE '[0-9]+' /home/etudiant/users-uid.txt"},
        ],
    },
    16: {
        "title": "Introduction au scripting Bash",
        "description": "Écrivez vos premiers scripts avec variables, conditions et boucles.",
        "lesson": """<h3>Structure d'un script</h3><pre>#!/bin/bash<br>echo "Mon script !"</pre><p>Rendre exécutable : <code>chmod +x script.sh</code></p><h3>Variables</h3><pre>NOM="Linux"<br>echo "Bonjour $NOM"<br>DATE=$(date)</pre><h3>Conditions</h3><pre>if [ -f "/etc/passwd" ]; then<br>    echo "Existe"<br>else<br>    echo "Absent"<br>fi</pre><h3>Boucles</h3><pre>for i in 1 2 3; do<br>    echo "Itération $i"<br>done</pre><div class="tip">Pas d'espaces autour du <code>=</code> ! Et espaces obligatoires dans <code>[ ]</code>.</div>""",
        "exercises": [
            {"id": "16.1", "points": 3, "title": "Premier script",
             "desc": "Créez <code>/home/etudiant/hello.sh</code> exécutable qui affiche <code>Bonjour depuis mon script !</code>.",
             "check": "test -x /home/etudiant/hello.sh && /home/etudiant/hello.sh 2>/dev/null | grep -qi bonjour"},
            {"id": "16.2", "points": 3, "title": "Script info système",
             "desc": "Créez <code>/home/etudiant/info-system.sh</code> exécutable utilisant <code>date</code>, <code>whoami</code> et <code>pwd</code>.",
             "check": "test -x /home/etudiant/info-system.sh && grep -q date /home/etudiant/info-system.sh && grep -q whoami /home/etudiant/info-system.sh && grep -q pwd /home/etudiant/info-system.sh"},
            {"id": "16.3", "points": 3, "title": "Script avec condition",
             "desc": "Créez <code>/home/etudiant/check-file.sh</code> : affiche <code>EXISTE</code> ou <code>ABSENT</code> selon que l'argument existe.",
             "check": "test -x /home/etudiant/check-file.sh && /home/etudiant/check-file.sh /etc/passwd 2>/dev/null | grep -qi EXISTE && /home/etudiant/check-file.sh /inexistant 2>/dev/null | grep -qi ABSENT"},
            {"id": "16.4", "points": 3, "title": "Script avec boucle",
             "desc": "Créez <code>/home/etudiant/create-users.sh</code> avec une boucle <code>for</code> créant <code>user1.txt</code> à <code>user5.txt</code> dans <code>/home/etudiant/users/</code>.",
             "check": "test -x /home/etudiant/create-users.sh && grep -q for /home/etudiant/create-users.sh && /home/etudiant/create-users.sh 2>/dev/null; test -f /home/etudiant/users/user1.txt && test -f /home/etudiant/users/user5.txt"},
        ],
    },
    17: {
        "title": "Tâches planifiées (cron)",
        "description": "Automatisez des tâches avec cron et crontab.",
        "lesson": """<h3>crontab</h3><pre>crontab -l    # lister<br>crontab -e    # éditer</pre><h3>Syntaxe cron</h3><pre>┌─ minute (0-59)<br>│ ┌─ heure (0-23)<br>│ │ ┌─ jour du mois (1-31)<br>│ │ │ ┌─ mois (1-12)<br>│ │ │ │ ┌─ jour semaine (0-7)<br>* * * * * commande</pre><p>Exemples :</p><ul><li><code>0 8 * * *</code> — chaque jour à 8h</li><li><code>*/15 * * * *</code> — toutes les 15 min</li><li><code>0 0 * * 0</code> — dimanche minuit</li></ul><h3>Dossiers cron</h3><p><code>/etc/cron.daily/</code>, <code>/etc/cron.hourly/</code>, etc.</p>""",
        "exercises": [
            {"id": "17.1", "points": 3, "title": "Afficher la crontab",
             "desc": "Sauvegardez la crontab actuelle dans <code>/home/etudiant/crontab-actuelle.txt</code>.",
             "check": "test -f /home/etudiant/crontab-actuelle.txt"},
            {"id": "17.2", "points": 3, "title": "Créer une tâche cron",
             "desc": "Créez <code>/etc/cron.d/backup-lab</code> pour exécuter <code>hello.sh</code> tous les jours à 2h.",
             "check": "test -f /etc/cron.d/backup-lab && grep -qE '^0\\s+2\\s+' /etc/cron.d/backup-lab"},
            {"id": "17.3", "points": 3, "title": "Script dans cron.daily",
             "desc": "Créez un script <code>cleanup.sh</code> exécutable dans <code>/etc/cron.daily/</code> qui supprime les <code>.tmp</code> de <code>/tmp</code>.",
             "check": "(test -x /etc/cron.daily/cleanup.sh || test -x /etc/cron.daily/cleanup) && (grep -qE '(rm|find).*tmp' /etc/cron.daily/cleanup.sh 2>/dev/null || grep -qE '(rm|find).*tmp' /etc/cron.daily/cleanup 2>/dev/null)"},
        ],
    },
    18: {
        "title": "Surveillance du système",
        "description": "Surveillez disque, mémoire, charge et processus.",
        "lesson": """<h3>Espace disque</h3><pre>df -h         # partitions<br>du -sh /var   # taille d'un dossier</pre><h3>Mémoire</h3><pre>free -h</pre><h3>Charge</h3><pre>uptime        # durée + load average</pre><h3>Processus</h3><pre>top           # temps réel<br>ps aux        # snapshot</pre><h3>Logs</h3><pre>dmesg | tail<br>tail -f /var/log/syslog</pre>""",
        "exercises": [
            {"id": "18.1", "points": 3, "title": "Espace disque",
             "desc": "Sauvegardez le résultat de <code>df -h</code> dans <code>/home/etudiant/disk-usage.txt</code>.",
             "check": "test -f /home/etudiant/disk-usage.txt && grep -qEi '(Filesystem|Sys|tmpfs|/dev/)' /home/etudiant/disk-usage.txt"},
            {"id": "18.2", "points": 3, "title": "Mémoire",
             "desc": "Sauvegardez le résultat de <code>free -h</code> dans <code>/home/etudiant/memory.txt</code>.",
             "check": "test -f /home/etudiant/memory.txt && grep -qEi '(Mem|Swap)' /home/etudiant/memory.txt"},
            {"id": "18.3", "points": 3, "title": "Uptime",
             "desc": "Sauvegardez le résultat de <code>uptime</code> dans <code>/home/etudiant/uptime.txt</code>.",
             "check": "test -f /home/etudiant/uptime.txt && grep -qEi '(up|load)' /home/etudiant/uptime.txt"},
            {"id": "18.4", "points": 3, "title": "Script de rapport",
             "desc": "Créez <code>/home/etudiant/rapport.sh</code> exécutable générant un rapport complet dans <code>/home/etudiant/rapport-systeme.txt</code>.",
             "check": "test -x /home/etudiant/rapport.sh && test -f /home/etudiant/rapport-systeme.txt && grep -qEi '(Mem|Swap)' /home/etudiant/rapport-systeme.txt && grep -qEi '(Filesystem|Sys|tmpfs|/dev/)' /home/etudiant/rapport-systeme.txt"},
        ],
    },
    19: {
        "title": "Intégration finale : serveur web",
        "description": "Mettez tout en pratique : utilisateurs, permissions, scripts, cron, monitoring.",
        "lesson": """<h3>Scénario</h3><p>Vous administrez un serveur web. Vous devez :</p><ol><li>Créer l'utilisateur <code>webmaster</code> et le groupe <code>www</code></li><li>Préparer l'arborescence <code>/var/www/monsite/</code></li><li>Écrire un script de sauvegarde</li><li>Planifier son exécution avec cron</li><li>Mettre en place un monitoring</li></ol><div class="tip">Cet exercice mobilise toutes les compétences du tutoriel !</div>""",
        "exercises": [
            {"id": "19.1", "points": 4, "title": "Environnement web",
             "desc": "Créez <code>webmaster</code> (groupe <code>www</code>), l'arborescence <code>/var/www/monsite/{html,logs,backup}</code> avec groupe <code>www</code> et permissions <code>775</code>.",
             "check": "id webmaster >/dev/null 2>&1 && getent group www >/dev/null 2>&1 && id webmaster 2>/dev/null | grep -q www && test -d /var/www/monsite/html && test -d /var/www/monsite/logs && test -d /var/www/monsite/backup && test $(stat -c '%G' /var/www/monsite) = www && test $(stat -c '%a' /var/www/monsite) = 775"},
            {"id": "19.2", "points": 4, "title": "Contenu web",
             "desc": "Créez <code>index.html</code> (avec Bienvenue) dans <code>html/</code> et <code>access.log</code> (5+ lignes) dans <code>logs/</code>.",
             "check": "test -f /var/www/monsite/html/index.html && grep -qi bienvenue /var/www/monsite/html/index.html && test -f /var/www/monsite/logs/access.log && test $(wc -l < /var/www/monsite/logs/access.log) -ge 5"},
            {"id": "19.3", "points": 4, "title": "Script de sauvegarde",
             "desc": "Créez <code>/home/webmaster/backup.sh</code> exécutable (tar + df). Exécutez-le.",
             "check": "test -x /home/webmaster/backup.sh && grep -q tar /home/webmaster/backup.sh && grep -q df /home/webmaster/backup.sh && ls /var/www/monsite/backup/*.tar.gz 1>/dev/null 2>&1 && test -f /var/www/monsite/backup/disk-report.txt"},
            {"id": "19.4", "points": 4, "title": "Cron de sauvegarde",
             "desc": "Créez <code>/etc/cron.d/backup-web</code> pour exécuter <code>backup.sh</code> à 3h.",
             "check": "test -f /etc/cron.d/backup-web && grep -qE '^0\\s+3\\s+.*backup\\.sh' /etc/cron.d/backup-web"},
            {"id": "19.5", "points": 4, "title": "Monitoring",
             "desc": "Créez <code>/home/webmaster/monitoring.sh</code> exécutable. Rapport dans <code>/var/www/monsite/logs/monitoring.txt</code>.",
             "check": "test -x /home/webmaster/monitoring.sh && test -f /var/www/monsite/logs/monitoring.txt && grep -qEi '(Mem|Swap)' /var/www/monsite/logs/monitoring.txt && grep -qEi '(Filesystem|Sys|tmpfs|/dev/)' /var/www/monsite/logs/monitoring.txt"},
        ],
    },
    20: {
        "title": "Liens symboliques et liens durs",
        "description": "Comprenez les inodes, créez des liens durs et symboliques.",
        "lesson": """<h3>Le concept d'inode</h3><p>Chaque fichier a un <strong>inode</strong> (numéro unique). Un nom de fichier est juste une étiquette vers un inode.</p><pre>ls -i fichier.txt   # affiche l'inode</pre><h3>Lien dur</h3><p>Seconde étiquette vers le <strong>même inode</strong>. Même contenu, mêmes permissions.</p><pre>ln fichier.txt lien-dur.txt</pre><ul><li>Ne peut pas pointer vers un dossier</li><li>Ne peut pas traverser les partitions</li><li>Données supprimées seulement quand tous les liens sont supprimés</li></ul><h3>Lien symbolique</h3><p>Raccourci vers un <strong>chemin</strong>. Fichier séparé avec son propre inode.</p><pre>ln -s /cible lien-sym</pre><ul><li>Peut pointer vers un dossier</li><li>Peut traverser les partitions</li><li>Lien cassé si la cible est supprimée</li></ul><pre>ls -l<br>lrwxrwxrwx 1 user user mon-lien -> /etc/hosts</pre>""",
        "exercises": [
            {"id": "20.1", "points": 3, "title": "Créer un lien dur",
             "desc": "Créez <code>original.txt</code> contenant <code>Fichier original</code>, puis un lien dur <code>lien-dur.txt</code>.",
             "check": "test -f /home/etudiant/original.txt && test -f /home/etudiant/lien-dur.txt && test $(stat -c '%i' /home/etudiant/original.txt) = $(stat -c '%i' /home/etudiant/lien-dur.txt)"},
            {"id": "20.2", "points": 3, "title": "Vérifier les inodes",
             "desc": "Sauvegardez le résultat de <code>ls -li</code> dans <code>/home/etudiant/inodes.txt</code>.",
             "check": "test -f /home/etudiant/inodes.txt && grep -qE '^[0-9]+' /home/etudiant/inodes.txt"},
            {"id": "20.3", "points": 3, "title": "Lien symbolique vers un dossier",
             "desc": "Créez un lien symbolique <code>/home/etudiant/lien-sym</code> pointant vers <code>/etc</code>.",
             "check": "test -L /home/etudiant/lien-sym && test $(readlink /home/etudiant/lien-sym) = /etc"},
            {"id": "20.4", "points": 3, "title": "Lien symbolique vers un fichier",
             "desc": "Créez <code>/home/etudiant/raccourci-passwd</code> pointant vers <code>/etc/passwd</code>.",
             "check": "test -L /home/etudiant/raccourci-passwd && test $(readlink /home/etudiant/raccourci-passwd) = /etc/passwd"},
        ],
    },
    21: {
        "title": "Expressions régulières",
        "description": "Maîtrisez les regex avec grep et sed pour filtrer et transformer du texte.",
        "lesson": """<h3>Syntaxe de base</h3><table class="lesson-table"><tr><th>Symbole</th><th>Signification</th></tr><tr><td><code>.</code></td><td>N'importe quel caractère</td></tr><tr><td><code>^</code></td><td>Début de ligne</td></tr><tr><td><code>$</code></td><td>Fin de ligne</td></tr><tr><td><code>*</code></td><td>0 ou plus du précédent</td></tr><tr><td><code>+</code></td><td>1 ou plus (avec <code>grep -E</code>)</td></tr><tr><td><code>[abc]</code></td><td>a, b ou c</td></tr><tr><td><code>[0-9]</code></td><td>Un chiffre</td></tr><tr><td><code>[^abc]</code></td><td>Tout sauf a, b, c</td></tr></table><h3>Exemples grep</h3><pre>grep '^#' fichier       # commentaires<br>grep -v '^$' fichier    # lignes non vides<br>grep -E '[0-9]+' f      # lignes avec nombres</pre><h3>Exemples sed</h3><pre>sed 's/[0-9]/X/g' f     # chiffres → X<br>sed '/^$/d' f           # supprimer vides</pre>""",
        "exercises": [
            {"id": "21.1", "points": 3, "title": "Grep avec regex",
             "desc": "Extrayez les lignes de <code>/etc/passwd</code> commençant par <code>r</code>. Sauvegardez dans <code>/home/etudiant/regex-r.txt</code>.",
             "check": "test -f /home/etudiant/regex-r.txt && test -s /home/etudiant/regex-r.txt && grep -q root /home/etudiant/regex-r.txt"},
            {"id": "21.2", "points": 3, "title": "Extraire des emails",
             "desc": "Créez <code>emails.txt</code> (5+ lignes, dont 3 emails). Extrayez les emails dans <code>emails-found.txt</code>.",
             "check": "test -f /home/etudiant/emails.txt && test -f /home/etudiant/emails-found.txt && test $(wc -l < /home/etudiant/emails.txt) -ge 5 && grep -q '@' /home/etudiant/emails-found.txt"},
            {"id": "21.3", "points": 3, "title": "Filtrer les commentaires",
             "desc": "Extrayez les lignes de <code>/etc/hosts</code> non vides et non commentées. Sauvegardez dans <code>hosts-clean.txt</code>.",
             "check": "test -f /home/etudiant/hosts-clean.txt && test -s /home/etudiant/hosts-clean.txt && ! grep -q '^#' /home/etudiant/hosts-clean.txt && ! grep -q '^$' /home/etudiant/hosts-clean.txt"},
            {"id": "21.4", "points": 6, "title": "Remplacer avec sed",
             "desc": "Remplacez tous les chiffres de <code>emails.txt</code> par <code>X</code>. Sauvegardez dans <code>censored.txt</code>.",
             "check": "test -f /home/etudiant/censored.txt && test -s /home/etudiant/censored.txt && grep -q X /home/etudiant/censored.txt"},
        ],
    },
    22: {
        "title": "SSH et accès distant",
        "description": "Configurez SSH : clés, permissions, config et connexion réelle.",
        "lesson": """<h3>Connexion SSH</h3><pre>ssh utilisateur@serveur</pre><p>Un serveur SSH <code>ssh-target</code> est disponible sur le réseau.<br>Utilisateur : <code>etudiant</code> / Mot de passe : <code>etudiant</code></p><h3>Clés SSH</h3><pre>ssh-keygen -t ed25519<br># → ~/.ssh/id_ed25519 (privée)<br># → ~/.ssh/id_ed25519.pub (publique)</pre><h3>Permissions critiques</h3><pre>chmod 700 ~/.ssh<br>chmod 600 ~/.ssh/id_ed25519<br>chmod 644 ~/.ssh/id_ed25519.pub<br>chmod 600 ~/.ssh/authorized_keys</pre><h3>Configuration (~/.ssh/config)</h3><pre>Host serveur-test<br>    HostName ssh-target<br>    User etudiant</pre><p>Puis : <code>ssh serveur-test</code></p><div class="tip"><code>sshpass -p 'motdepasse' ssh ...</code> permet de passer le mot de passe en ligne de commande (utile pour les scripts).</div><h3>Transfert</h3><pre>scp fichier user@serveur:/chemin/<br>scp -r dossier/ user@serveur:/chemin/</pre>""",
        "exercises": [
            {"id": "22.1", "points": 3, "title": "Générer des clés",
             "desc": "Générez une paire de clés SSH <code>ed25519</code> dans <code>/root/.ssh/</code> (sans passphrase).",
             "check": "test -f /root/.ssh/id_ed25519 && test -f /root/.ssh/id_ed25519.pub && grep -q ssh-ed25519 /root/.ssh/id_ed25519.pub"},
            {"id": "22.2", "points": 3, "title": "Permissions SSH",
             "desc": "Vérifiez/corrigez : <code>.ssh</code> = 700, clé privée = 600.",
             "check": "test $(stat -c '%a' /root/.ssh) = 700 && test $(stat -c '%a' /root/.ssh/id_ed25519) = 600"},
            {"id": "22.3", "points": 3, "title": "Configuration SSH",
             "desc": "Créez <code>/root/.ssh/config</code> avec un alias <code>serveur-test</code> pointant vers <code>ssh-target</code>, utilisateur <code>etudiant</code>.",
             "check": "test -f /root/.ssh/config && grep -qi 'Host serveur-test' /root/.ssh/config && grep -qi 'HostName.*ssh-target' /root/.ssh/config && grep -qi 'User.*etudiant' /root/.ssh/config"},
            {"id": "22.4", "points": 3, "title": "Authorized keys",
             "desc": "Ajoutez votre clé publique dans <code>/root/.ssh/authorized_keys</code> (permissions 600).",
             "check": "test -f /root/.ssh/authorized_keys && grep -q ssh-ed25519 /root/.ssh/authorized_keys && test $(stat -c '%a' /root/.ssh/authorized_keys) = 600"},
            {"id": "22.5", "points": 4, "title": "Connexion réelle",
             "desc": "Connectez-vous au serveur <code>ssh-target</code> (user: <code>etudiant</code>, mdp: <code>etudiant</code>) et sauvegardez la sortie dans <code>/root/ssh-test.txt</code>.<br><span class='hint'><code>sshpass -p 'etudiant' ssh -o StrictHostKeyChecking=no etudiant@ssh-target > /root/ssh-test.txt</code></span>",
             "check": "test -f /root/ssh-test.txt && grep -q 'CONNEXION_REUSSIE' /root/ssh-test.txt"},
        ],
    },
    23: {
        "title": "Gestion des logs",
        "description": "Lisez, filtrez et analysez les journaux système.",
        "lesson": """<h3>Où sont les logs ?</h3><pre>/var/log/syslog    — système<br>/var/log/auth.log  — authentification<br>/var/log/kern.log  — noyau<br>/var/log/dpkg.log  — paquets</pre><h3>Commandes essentielles</h3><pre>tail -20 /var/log/syslog      # dernières lignes<br>tail -f /var/log/syslog       # temps réel<br>grep "error" /var/log/syslog  # filtrer</pre><h3>dmesg</h3><pre>dmesg | tail          # messages noyau<br>dmesg -T              # avec horodatage</pre><h3>Créer ses logs</h3><pre>logger "Mon message"  # écrire dans syslog</pre><h3>logrotate</h3><p>Rotation automatique des logs (compression, suppression des anciens).</p>""",
        "exercises": [
            {"id": "23.1", "points": 3, "title": "Lister les logs",
             "desc": "Sauvegardez le listing de <code>/var/log/</code> dans <code>/home/etudiant/liste-logs.txt</code>.",
             "check": "test -f /home/etudiant/liste-logs.txt && grep -qE '(syslog|dpkg|log)' /home/etudiant/liste-logs.txt"},
            {"id": "23.2", "points": 3, "title": "Créer un fichier de log",
             "desc": "Créez <code>/var/log/app-test.log</code> : 10+ lignes horodatées, dont 2 ERROR et 2 WARNING.",
             "check": "test -f /var/log/app-test.log && test $(wc -l < /var/log/app-test.log) -ge 10 && test $(grep -c ERROR /var/log/app-test.log) -ge 2 && test $(grep -c WARNING /var/log/app-test.log) -ge 2"},
            {"id": "23.3", "points": 3, "title": "Extraire les erreurs",
             "desc": "Extrayez les ERROR dans <code>errors.txt</code> et comptez-les dans <code>error-count.txt</code>.",
             "check": "test -f /home/etudiant/errors.txt && grep -q ERROR /home/etudiant/errors.txt && test -f /home/etudiant/error-count.txt && test -s /home/etudiant/error-count.txt"},
            {"id": "23.4", "points": 3, "title": "Script d'analyse",
             "desc": "Créez <code>log-analyzer.sh</code> exécutable qui génère un résumé (INFO/WARNING/ERROR) dans <code>log-summary.txt</code>.",
             "check": "test -x /home/etudiant/log-analyzer.sh && test -f /home/etudiant/log-summary.txt && grep -qi INFO /home/etudiant/log-summary.txt && grep -qi WARNING /home/etudiant/log-summary.txt && grep -qi ERROR /home/etudiant/log-summary.txt"},
        ],
    },
    24: {
        "title": "Sécurité de base",
        "description": "Auditez et sécurisez un système Linux.",
        "lesson": """<h3>Mots de passe</h3><pre>chage -l user          # voir la politique<br>chage -M 90 user       # expiration 90 jours<br>passwd -l user         # verrouiller<br>passwd -u user         # déverrouiller</pre><h3>Fichiers sensibles</h3><pre>find / -perm -4000     # fichiers SUID<br>find /etc -perm -o+w   # world-writable</pre><h3>Pare-feu (UFW)</h3><pre>ufw enable<br>ufw default deny incoming<br>ufw allow 22           # SSH<br>ufw allow 80           # HTTP</pre><h3>Bonnes pratiques SSH</h3><pre># /etc/ssh/sshd_config<br>PermitRootLogin no<br>PasswordAuthentication no</pre><h3>Surveillance</h3><pre>last                   # connexions réussies<br>lastb                  # connexions échouées<br>ss -tulnp              # ports ouverts</pre>""",
        "exercises": [
            {"id": "24.1", "points": 3, "title": "Fichiers SUID",
             "desc": "Listez les fichiers SUID du système dans <code>/home/etudiant/suid-files.txt</code>.",
             "check": "test -f /home/etudiant/suid-files.txt"},
            {"id": "24.2", "points": 3, "title": "Fichiers world-writable",
             "desc": "Cherchez les fichiers world-writable dans <code>/etc</code>. Sauvegardez dans <code>world-writable.txt</code>.",
             "check": "test -f /home/etudiant/world-writable.txt"},
            {"id": "24.3", "points": 4, "title": "Politique de mot de passe",
             "desc": "Créez <code>securise</code>, expiration 90 jours, puis verrouillez le compte.",
             "check": "id securise >/dev/null 2>&1 && chage -l securise 2>/dev/null | grep -q 90 && passwd -S securise 2>/dev/null | grep -q L"},
            {"id": "24.4", "points": 3, "title": "Audit UID zéro",
             "desc": "Listez les comptes avec UID 0 dans <code>/home/etudiant/uid-zero.txt</code>.",
             "check": "test -f /home/etudiant/uid-zero.txt && grep -q root /home/etudiant/uid-zero.txt"},
            {"id": "24.5", "points": 4, "title": "Script d'audit",
             "desc": "Créez <code>audit-securite.sh</code> exécutable : SUID, ports, utilisateurs, fichiers modifiés. Rapport dans <code>audit.txt</code>.",
             "check": "test -x /home/etudiant/audit-securite.sh && test -f /home/etudiant/audit.txt && test -s /home/etudiant/audit.txt"},
        ],
    },
}


def get_exercise_points(exercise_id: str) -> int:
    """Get points for an exercise ID like '1.1'."""
    step_num = int(exercise_id.split(".")[0])
    step = STEPS.get(step_num, {})
    for ex in step.get("exercises", []):
        if ex["id"] == exercise_id:
            return ex["points"]
    return 0
